import { Measurement } from "@/types";

export const CHHATTISGARH_MEASUREMENTS: Measurement[] = [
  // Agriculture (Seed & Crop)
  {
    id: "ct-agri-1",
    slug: "ct-pasri-agri",
    name_english: "Pasri",
    name_hindi: "पसरी",
    local_names: ["पसरी (Pasri)"],
    meaning: "Regional grain measure.",
    category: "volume",
    sector: "agriculture",
    modern_equivalent: "≈4.66 kg",
    conversion_formula: "Usually 5 Seers = 1 Pasri",
    states: ["Chhattisgarh"],
    used_in: ["Grain storage and seed distribution"],
    references: ["Raipur, Bilaspur Gazetteers"],
  },
  {
    id: "ct-agri-2",
    slug: "ct-khandi-agri",
    name_english: "Khandi",
    name_hindi: "खंडी",
    local_names: ["खंडी (Khandi)"],
    meaning: "Largest traditional agricultural unit.",
    category: "weight",
    sector: "agriculture",
    modern_equivalent: "≈746 kg (Regional)",
    conversion_formula: "≈20 Maunds = 1 Khandi",
    states: ["Chhattisgarh"],
    used_in: ["Bulk grain storage and transport"],
    references: ["Central Provinces Revenue Manuals"],
  },

  // Trade & Commerce
  {
    id: "ct-trade-1",
    slug: "ct-adha-seer-trade",
    name_english: "Adha Seer",
    name_hindi: "आधा सेर",
    local_names: ["आधा सेर (Adha Seer)"],
    meaning: "Half Seer market weight.",
    category: "weight",
    sector: "trade-commerce",
    modern_equivalent: "≈466 g",
    conversion_formula: "2 Pav = 1 Half Seer",
    states: ["Chhattisgarh"],
    used_in: ["Grocery trade"],
    references: ["Revenue Settlement Reports"],
  },
  {
    id: "ct-trade-2",
    slug: "ct-maund-trade",
    name_english: "Maund (Man)",
    name_hindi: "मन",
    local_names: ["मन (Maund)"],
    meaning: "Principal wholesale unit.",
    category: "weight",
    sector: "trade-commerce",
    modern_equivalent: "≈37.324 kg",
    conversion_formula: "40 Seers = 1 Maund",
    states: ["Chhattisgarh"],
    used_in: ["Wholesale grain, cotton and salt"],
    references: ["Government Historical Standards"],
  },

  // Textile & Handloom
  {
    id: "ct-tex-1",
    slug: "ct-gaz-tex",
    name_english: "Gaz (Gaj)",
    name_hindi: "गज़",
    local_names: ["गज़ (Gaz)"],
    meaning: "Standard cloth measure.",
    category: "length",
    sector: "textile-handloom",
    modern_equivalent: "≈0.9144 m",
    conversion_formula: "≈2 Hasta = 1 Gaz",
    states: ["Chhattisgarh"],
    used_in: ["Cloth trade"],
    references: ["British India Standards"],
  },
  {
    id: "ct-tex-2",
    slug: "ct-danda-tex",
    name_english: "Danda",
    name_hindi: "डंडा",
    local_names: ["डंडा (Danda)"],
    meaning: "Long measuring rod.",
    category: "length",
    sector: "textile-handloom",
    modern_equivalent: "≈1.82 m",
    conversion_formula: "4 Hasta = 1 Danda",
    states: ["Chhattisgarh"],
    used_in: ["Loom measurement"],
    references: ["Arthashastra"],
  },

  // Medicine (Ayurveda)
  {
    id: "ct-med-1",
    slug: "ct-karsha-med",
    name_english: "Karsha",
    name_hindi: "कर्ष",
    local_names: ["कर्ष (Karsha)"],
    meaning: "Standard Ayurvedic dosage unit.",
    category: "weight",
    sector: "medicine",
    modern_equivalent: "≈11.66 g",
    conversion_formula: "12 Masha = 1 Karsha",
    states: ["Chhattisgarh"],
    used_in: ["Herbal formulations and decoctions"],
    references: ["Charaka Samhita"],
  },
  {
    id: "ct-med-2",
    slug: "ct-prastha-med",
    name_english: "Prastha",
    name_hindi: "प्रस्थ",
    local_names: ["प्रस्थ (Prastha)"],
    meaning: "Standard liquid measure.",
    category: "volume",
    sector: "medicine",
    modern_equivalent: "≈768 ml",
    conversion_formula: "16 Pala = 1 Prastha",
    states: ["Chhattisgarh"],
    used_in: ["Measuring medicinal liquids"],
    references: ["Charaka Samhita"],
  },

  // Construction & Architecture
  {
    id: "ct-arch-1",
    slug: "ct-vitasti-arch",
    name_english: "Vitasti",
    name_hindi: "वितस्ति",
    local_names: ["वितस्ति (Vitasti)"],
    meaning: "Span measure.",
    category: "length",
    sector: "architecture",
    modern_equivalent: "≈22.8 cm",
    conversion_formula: "12 Angula = 1 Vitasti",
    states: ["Chhattisgarh"],
    used_in: ["Measuring wooden beams and doors"],
    references: ["Manasara"],
  },
  {
    id: "ct-arch-2",
    slug: "ct-rajju-arch",
    name_english: "Rajju",
    name_hindi: "रज्जु",
    local_names: ["रज्जु (Rajju)"],
    meaning: "Measuring rope.",
    category: "length",
    sector: "architecture",
    modern_equivalent: "Variable",
    conversion_formula: "Variable rope measure",
    states: ["Chhattisgarh"],
    used_in: ["Site layout and land alignment"],
    references: ["Samarangana Sutradhara"],
  },
  {
    id: "ct-arch-3",
    slug: "ct-krosha-arch",
    name_english: "Krosha (Kos)",
    name_hindi: "कोस",
    local_names: ["कोस (Krosha)"],
    meaning: "Long-distance measure.",
    category: "length",
    sector: "architecture",
    modern_equivalent: "≈3.2 km",
    conversion_formula: "2000 Danda = 1 Krosha",
    states: ["Chhattisgarh"],
    used_in: ["Distance between settlements"],
    references: ["Arthashastra"],
  },

  // Land Measurement
  {
    id: "ct-land-1",
    slug: "ct-bigha-land",
    name_english: "Bigha",
    name_hindi: "बीघा",
    local_names: ["बीघा (Bigha)"],
    meaning: "Traditional land measure.",
    category: "area",
    sector: "land-measurement",
    modern_equivalent: "Varies",
    conversion_formula: "Regional standard",
    states: ["Chhattisgarh"],
    used_in: ["Agricultural plots"],
    references: ["Revenue Records"],
  },

  // Transportation & Distance
  {
    id: "ct-trans-1",
    slug: "ct-kos-trans",
    name_english: "Kos",
    name_hindi: "कोस",
    local_names: ["कोस (Kos)"],
    meaning: "Traditional travel distance.",
    category: "length",
    sector: "transportation-distance",
    modern_equivalent: "≈3 km",
    conversion_formula: "Regional standard",
    states: ["Chhattisgarh"],
    used_in: ["Journey distances"],
    references: ["Travel accounts"],
  },

  // Household & Daily Life
  {
    id: "ct-hh-1",
    slug: "ct-pav-hh",
    name_english: "Pav / Pao",
    name_hindi: "पाव",
    local_names: ["पाव (Pav)"],
    meaning: "Quarter seer.",
    category: "weight",
    sector: "household",
    modern_equivalent: "≈233 g",
    conversion_formula: "1/4 Seer = 1 Pav",
    states: ["Chhattisgarh"],
    used_in: ["Daily groceries"],
    references: ["Household practices"],
  },

  // Livestock & Dairy
  {
    id: "ct-dairy-1",
    slug: "ct-seer-dairy",
    name_english: "Seer",
    name_hindi: "सेर",
    local_names: ["सेर (Seer)"],
    meaning: "Standard milk measure.",
    category: "volume",
    sector: "livestock-dairy",
    modern_equivalent: "≈0.93 L",
    conversion_formula: "Standard liquid measure",
    states: ["Chhattisgarh"],
    used_in: ["Milk distribution"],
    references: ["Dairy practices"],
  },

  // Gold & Jewellery
  {
    id: "ct-gold-1",
    slug: "ct-ratti-gold",
    name_english: "Ratti",
    name_hindi: "रत्ती",
    local_names: ["रत्ती (Ratti)"],
    meaning: "Seed based weight.",
    category: "weight",
    sector: "gold-jewellery",
    modern_equivalent: "≈0.12 g",
    conversion_formula: "Base unit",
    states: ["Chhattisgarh"],
    used_in: ["Jewellery weighing"],
    references: ["Ancient weight systems"],
  },

  // Currency & Money
  {
    id: "ct-cur-1",
    slug: "ct-paisa-cur",
    name_english: "Paisa",
    name_hindi: "पैसा",
    local_names: ["पैसा (Paisa)"],
    meaning: "Small coin.",
    category: "currency",
    sector: "currency-money",
    modern_equivalent: "Historical",
    conversion_formula: "Fraction of Rupee",
    states: ["Chhattisgarh"],
    used_in: ["Daily market"],
    references: ["Colonial records"],
  },

  // Storage & Transportation
  {
    id: "ct-storage-1",
    slug: "ct-bori-storage",
    name_english: "Bori",
    name_hindi: "बोरी",
    local_names: ["बोरी (Bori)"],
    meaning: "Sack for grains.",
    category: "weight",
    sector: "storage-transport",
    modern_equivalent: "Commodity dependent",
    conversion_formula: "Sack measure",
    states: ["Chhattisgarh"],
    used_in: ["Grain transport"],
    references: ["Mandi records"],
  },

  // Religious & Cultural
  {
    id: "ct-relig-1",
    slug: "ct-ghati-relig",
    name_english: "Ghati",
    name_hindi: "घटी",
    local_names: ["घटी (Ghati)"],
    meaning: "Time measure.",
    category: "time",
    sector: "religious-cultural",
    modern_equivalent: "24 minutes",
    conversion_formula: "60 Ghati = 1 Day",
    states: ["Chhattisgarh"],
    used_in: ["Rituals"],
    references: ["Panchang"],
  },

  // Additional Authentic Land Measurement
  {
    id: "ct-land-2",
    slug: "ct-biswansi-land",
    name_english: "Biswansi",
    name_hindi: "बिस्वांसी",
    local_names: ["बिस्वांसी (Biswansi)"],
    meaning: "Small revenue subdivision.",
    category: "area",
    sector: "land-measurement",
    modern_equivalent: "Regional Variation",
    conversion_formula: "20 Biswansi = 1 Biswa",
    states: ["Chhattisgarh"],
    used_in: ["Small agricultural subdivision"],
    references: ["Settlement Reports"],
  },
  {
    id: "ct-land-3",
    slug: "ct-biswa-land",
    name_english: "Biswa",
    name_hindi: "बिस्वा",
    local_names: ["बिस्वा (Biswa)"],
    meaning: "Revenue land subdivision.",
    category: "area",
    sector: "land-measurement",
    modern_equivalent: "Regional Variation",
    conversion_formula: "20 Biswa = 1 Bigha",
    states: ["Chhattisgarh"],
    used_in: ["Agricultural land records"],
    references: ["Raipur, Durg, Bilaspur District Gazetteers"],
  },

  // Additional Authentic Gold & Jewellery
  {
    id: "ct-gold-2",
    slug: "ct-masha-gold",
    name_english: "Masha",
    name_hindi: "माशा",
    name_sanskrit: "Māṣa",
    local_names: ["माशा (Masha)"],
    meaning: "Standard small jewellery weight.",
    category: "weight",
    sector: "gold-jewellery",
    modern_equivalent: "≈0.972 g",
    conversion_formula: "8 Ratti = 1 Masha",
    states: ["Chhattisgarh"],
    used_in: ["Gold ornaments and silver articles"],
    references: ["Sushruta Samhita"],
  },
  {
    id: "ct-gold-3",
    slug: "ct-suvarna-gold",
    name_english: "Suvarna",
    name_hindi: "सुवर्ण",
    name_sanskrit: "Suvarṇa",
    local_names: ["सुवर्ण (Suvarna)"],
    meaning: "Ancient gold weight standard.",
    category: "weight",
    sector: "gold-jewellery",
    modern_equivalent: "≈15.5 g",
    conversion_formula: "≈16 Masha = 1 Suvarna",
    states: ["Chhattisgarh"],
    used_in: ["Gold coins and ornaments"],
    references: ["Arthashastra"],
  },

  // Additional Authentic Household & Daily Life
  {
    id: "ct-hh-2",
    slug: "ct-chhatak-hh",
    name_english: "Chhatak",
    name_hindi: "छटाक",
    local_names: ["छटाक (Chhatak)"],
    meaning: "Small domestic measure.",
    category: "weight",
    sector: "household",
    modern_equivalent: "≈58.3 g",
    conversion_formula: "5 Tola = 1 Chhatak",
    states: ["Chhattisgarh"],
    used_in: ["Sugar, flour, pulses"],
    references: ["Central Provinces Gazetteers"],
  },

  // Additional Authentic Livestock & Dairy
  {
    id: "ct-dairy-2",
    slug: "ct-chhatak-dairy",
    name_english: "Chhatak",
    name_hindi: "छटाक",
    local_names: ["छटाक (Chhatak)"],
    meaning: "Small dairy measure.",
    category: "weight",
    sector: "livestock-dairy",
    modern_equivalent: "≈58.3 g",
    conversion_formula: "5 Tola = 1 Chhatak",
    states: ["Chhattisgarh"],
    used_in: ["Butter, ghee, cheese"],
    references: ["Central Provinces Gazetteers"],
  },

  // Additional Authentic Currency & Money
  {
    id: "ct-cur-2",
    slug: "ct-cowrie-cur",
    name_english: "Cowrie",
    name_hindi: "कौड़ी",
    name_sanskrit: "Kapardikā",
    local_names: ["कौड़ी (Cowrie)"],
    meaning: "Shell Currency.",
    category: "currency",
    sector: "currency-money",
    modern_equivalent: "Historical",
    conversion_formula: "Base Unit",
    states: ["Chhattisgarh"],
    used_in: ["Daily village transactions"],
    references: ["Imperial Gazetteer"],
  },
  {
    id: "ct-cur-3",
    slug: "ct-anna-cur",
    name_english: "Anna",
    name_hindi: "आना",
    local_names: ["आना (Anna)"],
    meaning: "Standard fractional currency.",
    category: "currency",
    sector: "currency-money",
    modern_equivalent: "1/16 Rupee",
    conversion_formula: "16 Anna = 1 Rupee",
    states: ["Chhattisgarh"],
    used_in: ["Trade and taxation"],
    references: ["British India Monetary System"],
  },
  {
    id: "ct-cur-4",
    slug: "ct-rupee-cur",
    name_english: "Rupee",
    name_hindi: "रुपया",
    name_sanskrit: "Rūpya",
    local_names: ["रुपया (Rupee)"],
    meaning: "Standard Monetary Unit.",
    category: "currency",
    sector: "currency-money",
    modern_equivalent: "Historical",
    conversion_formula: "1 Rupee = 16 Anna",
    states: ["Chhattisgarh"],
    used_in: ["Trade, revenue and salaries"],
    references: ["British India Coinage"],
  },

  // Additional Authentic Storage & Transportation
  {
    id: "ct-storage-2",
    slug: "ct-pasri-storage",
    name_english: "Pasri",
    name_hindi: "पसरी",
    local_names: ["पसरी (Pasri)"],
    meaning: "Intermediate storage unit.",
    category: "volume",
    sector: "storage-transport",
    modern_equivalent: "≈4.66 kg",
    conversion_formula: "Usually 5 Seers = 1 Pasri",
    states: ["Chhattisgarh"],
    used_in: ["Paddy and grain storage"],
    references: ["Raipur, Bilaspur Gazetteers"],
  },
  {
    id: "ct-storage-3",
    slug: "ct-khandi-storage",
    name_english: "Khandi",
    name_hindi: "खंडी",
    local_names: ["खंडी (Khandi)"],
    meaning: "Largest traditional storage unit.",
    category: "volume",
    sector: "storage-transport",
    modern_equivalent: "≈746 kg (Regional)",
    conversion_formula: "≈20 Maunds = 1 Khandi",
    states: ["Chhattisgarh"],
    used_in: ["Bulk storage of rice, grain and forest produce"],
    references: ["Central Provinces Revenue Manuals"],
  }
];
