import { Measurement } from "@/types";

export const GOA_MEASUREMENTS: Measurement[] = [
  // Agriculture (Seed & Crop)
  {
    id: "goa-agri-1",
    slug: "goa-padi-agri",
    name_english: "Padi",
    name_hindi: "पडती", // Konkani script placeholder
    local_names: ["पडी (Padi)"],
    meaning: "Traditional grain measure.",
    category: "volume",
    sector: "agriculture",
    modern_equivalent: "≈3-4 L",
    conversion_formula: "Seed measurement",
    states: ["Goa"],
    used_in: ["Measuring paddy seed before sowing"],
    references: ["Goan Rural Traditions"],
  },
  {
    id: "goa-agri-2",
    slug: "goa-adholi-agri",
    name_english: "Adholi",
    name_hindi: "अढोली",
    local_names: ["अढोली (Adholi)"],
    meaning: "Medium-sized grain measure.",
    category: "volume",
    sector: "agriculture",
    modern_equivalent: "Regional variation",
    conversion_formula: "2 Padi = 1 Adholi",
    states: ["Goa"],
    used_in: ["Grain storage"],
    references: ["Village Revenue Records"],
  },
  {
    id: "goa-agri-3",
    slug: "goa-naral-goni",
    name_english: "Naral Goni",
    name_hindi: "नारळ गोणी",
    local_names: ["नारळ गोणी (Naral Goni)"],
    meaning: "Sack of coconuts.",
    category: "volume",
    sector: "agriculture",
    modern_equivalent: "Commodity dependent",
    conversion_formula: "Coconut Sack",
    states: ["Goa"],
    used_in: ["Transporting coconuts from plantations"],
    references: ["Portuguese Period Trade"],
  },
  {
    id: "goa-agri-4",
    slug: "goa-supari-goni",
    name_english: "Supari Goni",
    name_hindi: "सुपारी गोणी",
    local_names: ["सुपारी गोणी (Supari Goni)"],
    meaning: "Sack of arecanuts.",
    category: "volume",
    sector: "agriculture",
    modern_equivalent: "Commodity dependent",
    conversion_formula: "Arecanut Sack",
    states: ["Goa"],
    used_in: ["Arecanut trade"],
    references: ["Arecanut Trade Records"],
  },

  // Trade & Commerce
  {
    id: "goa-trade-1",
    slug: "goa-pardau-trade",
    name_english: "Pardau",
    name_hindi: "पर्दाव",
    local_names: ["पर्दाव (Pardau)"],
    meaning: "Portuguese coin.",
    category: "currency",
    sector: "trade-commerce",
    modern_equivalent: "Regional variation",
    conversion_formula: "Silver Coin",
    states: ["Goa"],
    used_in: ["Commercial transactions"],
    references: ["Portuguese Indo Coinage"],
  },
  {
    id: "goa-trade-2",
    slug: "goa-xerafim-trade",
    name_english: "Xerafim",
    name_hindi: "झेराफिम",
    local_names: ["झेराफिम (Xerafim)"],
    meaning: "Higher denomination coin.",
    category: "currency",
    sector: "trade-commerce",
    modern_equivalent: "Regional variation",
    conversion_formula: "Silver Coin",
    states: ["Goa"],
    used_in: ["Overseas trade"],
    references: ["Goa Numismatic Studies"],
  },

  // Architecture
  {
    id: "goa-arch-1",
    slug: "goa-kathi-arch",
    name_english: "Kathi",
    name_hindi: "काठी",
    local_names: ["काठी (Kathi)"],
    meaning: "Wooden measuring rod.",
    category: "length",
    sector: "architecture",
    modern_equivalent: "≈2-3 m (regional variation)",
    conversion_formula: "Measuring rod",
    states: ["Goa"],
    used_in: ["Local construction"],
    references: ["Goa Revenue Records"],
  },
  {
    id: "goa-arch-2",
    slug: "goa-sutra-arch",
    name_english: "Sutra",
    name_hindi: "सूत्र",
    local_names: ["सूत्र (Sutra)"],
    meaning: "Survey Measure.",
    category: "length",
    sector: "architecture",
    modern_equivalent: "Variable",
    conversion_formula: "Measuring cord",
    states: ["Goa"],
    used_in: ["Construction alignment"],
    references: ["Samarangana Sutradhara"],
  },

  // Medicine (Ayurveda)
  {
    id: "goa-med-1",
    slug: "goa-shana-med",
    name_english: "Shana",
    name_hindi: "शाण",
    local_names: ["शाण (Shana)"],
    meaning: "Traditional medicine unit.",
    category: "weight",
    sector: "medicine",
    modern_equivalent: "≈3-4 g",
    conversion_formula: "Herbal formulations",
    states: ["Goa"],
    used_in: ["Preparing medicinal compounds"],
    references: ["Rasashastra Texts"],
  },
  {
    id: "goa-med-2",
    slug: "goa-kalasha-med",
    name_english: "Kalasha",
    name_hindi: "कलश",
    local_names: ["कलश (Kalasha)"],
    meaning: "Large storage vessel.",
    category: "volume",
    sector: "medicine",
    modern_equivalent: "Variable",
    conversion_formula: "Storage Vessel",
    states: ["Goa"],
    used_in: ["Storing medicinal oils and decoctions"],
    references: ["Goan Vaidya Practices"],
  },

  // Textile & Handloom
  {
    id: "goa-tex-1",
    slug: "goa-sutachi-gundi",
    name_english: "Sutachi Gundi",
    name_hindi: "सुताची गुंडी",
    local_names: ["सुताची गुंडी (Sutachi Gundi)"],
    meaning: "Bundle of thread.",
    category: "length",
    sector: "textile-handloom",
    modern_equivalent: "Regional variation",
    conversion_formula: "Yarn Bundle",
    states: ["Goa"],
    used_in: ["Loom preparation"],
    references: ["Goan Handloom Traditions"],
  },
  {
    id: "goa-tex-2",
    slug: "goa-maga-rundal",
    name_english: "Maga Rundal",
    name_hindi: "मागा रुंदाल",
    local_names: ["मागा रुंदाल (Maga Rundal)"],
    meaning: "Loom Width.",
    category: "length",
    sector: "textile-handloom",
    modern_equivalent: "Variable",
    conversion_formula: "Loom width",
    states: ["Goa"],
    used_in: ["Width of cloth determined by the loom"],
    references: ["Rural Weaving Practices"],
  },
  
  // Land Measurement
  {
    id: "goa-land-1",
    slug: "goa-khajan-land",
    name_english: "Khajan",
    name_hindi: "खाजन",
    local_names: ["खाजन (Khajan)"],
    meaning: "Reclaimed coastal land measure.",
    category: "area",
    sector: "land-measurement",
    modern_equivalent: "Variable",
    conversion_formula: "Agricultural land",
    states: ["Goa"],
    used_in: ["Coastal farming"],
    references: ["Comunidade Records"],
  },

  // Transportation & Distance
  {
    id: "goa-trans-1",
    slug: "goa-kos-trans",
    name_english: "Kos",
    name_hindi: "कोस",
    local_names: ["कोस (Kos)"],
    meaning: "Traditional distance measure.",
    category: "length",
    sector: "transportation-distance",
    modern_equivalent: "≈3.2 km",
    conversion_formula: "Standard distance",
    states: ["Goa"],
    used_in: ["Travel routes"],
    references: ["Historical maps"],
  },

  // Household & Daily Life
  {
    id: "goa-hh-1",
    slug: "goa-pod-hh",
    name_english: "Pod",
    name_hindi: "पोड",
    local_names: ["पोड (Pod)"],
    meaning: "Common household measure.",
    category: "volume",
    sector: "household",
    modern_equivalent: "Regional",
    conversion_formula: "Vessel measure",
    states: ["Goa"],
    used_in: ["Daily cooking"],
    references: ["Goan Kitchens"],
  },

  // Livestock & Dairy
  {
    id: "goa-dairy-1",
    slug: "goa-sher-dairy",
    name_english: "Sher",
    name_hindi: "शेर",
    local_names: ["शेर (Sher)"],
    meaning: "Standard dairy measure.",
    category: "volume",
    sector: "livestock-dairy",
    modern_equivalent: "≈0.93 L",
    conversion_formula: "Standard volume",
    states: ["Goa"],
    used_in: ["Milk sales"],
    references: ["Local Dairy Farms"],
  },

  // Gold & Jewellery
  {
    id: "goa-gold-1",
    slug: "goa-gunja-gold",
    name_english: "Gunja",
    name_hindi: "गुंजा",
    local_names: ["गुंजा (Gunja)"],
    meaning: "Small seed weight.",
    category: "weight",
    sector: "gold-jewellery",
    modern_equivalent: "≈0.12 g",
    conversion_formula: "Seed weight",
    states: ["Goa"],
    used_in: ["Gold weighing"],
    references: ["Jewellers"],
  },

  // Currency & Money
  {
    id: "goa-cur-1",
    slug: "goa-tanga-cur",
    name_english: "Tanga",
    name_hindi: "टांगा",
    local_names: ["टांगा (Tanga)"],
    meaning: "Historical Portuguese-Goan currency.",
    category: "currency",
    sector: "currency-money",
    modern_equivalent: "Historical",
    conversion_formula: "Local trade",
    states: ["Goa"],
    used_in: ["Historical commerce"],
    references: ["Indo-Portuguese Numismatics"],
  },

  // Storage & Transportation
  {
    id: "goa-storage-1",
    slug: "goa-kothar-storage",
    name_english: "Kothar",
    name_hindi: "कोठार",
    local_names: ["कोठार (Kothar)"],
    meaning: "Large granary.",
    category: "volume",
    sector: "storage-transport",
    modern_equivalent: "Variable",
    conversion_formula: "Storage room",
    states: ["Goa"],
    used_in: ["Preserving harvest"],
    references: ["Goan Architecture"],
  },

  // Religious & Cultural
  {
    id: "goa-relig-1",
    slug: "goa-muhurta-relig",
    name_english: "Muhurta",
    name_hindi: "मुहूर्त",
    local_names: ["मुहूर्त (Muhurta)"],
    meaning: "Auspicious time unit.",
    category: "time",
    sector: "religious-cultural",
    modern_equivalent: "48 minutes",
    conversion_formula: "Ritual timing",
    states: ["Goa"],
    used_in: ["Temple rituals and weddings"],
    references: ["Hindu Panchang"],
  },

  // Additional Authentic Land Measurement
  {
    id: "goa-land-2",
    slug: "goa-vaar-land",
    name_english: "Vaar / Var",
    name_hindi: "वार",
    local_names: ["वार (Vaar)"],
    meaning: "Traditional plot measure.",
    category: "area",
    sector: "land-measurement",
    modern_equivalent: "Regional variation",
    conversion_formula: "Small plot measure",
    states: ["Goa"],
    used_in: ["Small house plots"],
    references: ["Goan land practices"],
  },
  {
    id: "goa-land-3",
    slug: "goa-guntha-land",
    name_english: "Guntha",
    name_hindi: "गुंठा",
    local_names: ["गुंठा (Guntha)"],
    meaning: "Common Deccan land unit.",
    category: "area",
    sector: "land-measurement",
    modern_equivalent: "≈1,089 sq.ft",
    conversion_formula: "40 Guntha = 1 Acre",
    states: ["Goa"],
    used_in: ["Agricultural land"],
    references: ["Revenue records"],
  },

  // Additional Authentic Household & Daily Life
  {
    id: "goa-hh-2",
    slug: "goa-ghado-hh",
    name_english: "Ghado",
    name_hindi: "घडो",
    local_names: ["घडो (Ghado)"],
    meaning: "Water Vessel.",
    category: "volume",
    sector: "household",
    modern_equivalent: "≈10–15 L",
    conversion_formula: "Water pot",
    states: ["Goa"],
    used_in: ["Storing drinking water"],
    references: ["Rural Customs"],
  },
  {
    id: "goa-hh-3",
    slug: "goa-dabba-hh",
    name_english: "Dabba",
    name_hindi: "डब्बा",
    local_names: ["डब्बा (Dabba)"],
    meaning: "Storage Container.",
    category: "volume",
    sector: "household",
    modern_equivalent: "Variable",
    conversion_formula: "Metal container",
    states: ["Goa"],
    used_in: ["Storing flour, spices, grains"],
    references: ["Household Records"],
  },

  // Additional Authentic Transportation & Distance
  {
    id: "goa-trans-2",
    slug: "goa-angul-trans",
    name_english: "Angul / Angula",
    name_hindi: "अंगुळ",
    local_names: ["अंगुळ (Angul)"],
    meaning: "Smallest traditional length unit.",
    category: "length",
    sector: "transportation-distance",
    modern_equivalent: "≈1.9 cm",
    conversion_formula: "Basic finger-width measure",
    states: ["Goa"],
    used_in: ["Small measurements in construction and crafts"],
    references: ["Indian traditional measurement system"],
  },

  // Additional Authentic Livestock & Dairy
  {
    id: "goa-dairy-2",
    slug: "goa-paili-dairy",
    name_english: "Paili",
    name_hindi: "पायली",
    local_names: ["पायली (Paili)"],
    meaning: "Traditional vessel measure.",
    category: "volume",
    sector: "livestock-dairy",
    modern_equivalent: "≈1.5–2 L (regional variation)",
    conversion_formula: "Vessel-based measure",
    states: ["Goa"],
    used_in: ["Milk, grains and household liquids"],
    references: ["Local household measures"],
  },
  {
    id: "goa-dairy-3",
    slug: "goa-kudam-dairy",
    name_english: "Kudam / Kudav",
    name_hindi: "कुडव",
    name_sanskrit: "Kuḍava",
    local_names: ["कुडव (Kudav)"],
    meaning: "Traditional pot measure.",
    category: "volume",
    sector: "livestock-dairy",
    modern_equivalent: "≈1–2 L (varies)",
    conversion_formula: "Vessel-based liquid measure",
    states: ["Goa"],
    used_in: ["Milk, curd and water storage"],
    references: ["Indian vessel measurement traditions"],
  },
  {
    id: "goa-dairy-4",
    slug: "goa-handi-dairy",
    name_english: "Handi",
    name_hindi: "हंडी",
    local_names: ["हंडी (Handi)"],
    meaning: "Large household vessel measure.",
    category: "volume",
    sector: "livestock-dairy",
    modern_equivalent: "Regional variation",
    conversion_formula: "Large vessel measure",
    states: ["Goa"],
    used_in: ["Storing large quantities of milk, curd and dairy products"],
    references: ["Local dairy traditions"],
  },

  // Additional Authentic Gold & Jewellery
  {
    id: "goa-gold-2",
    slug: "goa-dharana-gold",
    name_english: "Dharana",
    name_hindi: "धरण",
    name_sanskrit: "Dharaṇa",
    local_names: ["धरण (Dharana)"],
    meaning: "Classical Indian precious metal unit.",
    category: "weight",
    sector: "gold-jewellery",
    modern_equivalent: "≈3-4 g (varies)",
    conversion_formula: "Regional relationship with Ratti/Masha",
    states: ["Goa"],
    used_in: ["Ancient metal trade and jewellery calculations"],
    references: ["Traditional Indian weights"],
  },
  {
    id: "goa-gold-3",
    slug: "goa-bhori-gold",
    name_english: "Vori / Bhori",
    name_hindi: "वोरी",
    local_names: ["वोरी (Bhori)"],
    meaning: "Regional name for Tola.",
    category: "weight",
    sector: "gold-jewellery",
    modern_equivalent: "≈11.66 g",
    conversion_formula: "Generally equal to Tola",
    states: ["Goa"],
    used_in: ["South and West Indian jewellers"],
    references: ["Regional jeweller practices"],
  },
  {
    id: "goa-gold-4",
    slug: "goa-karsha-gold",
    name_english: "Karsha",
    name_hindi: "कर्ष",
    name_sanskrit: "Karṣa",
    local_names: ["कर्ष (Karsha)"],
    meaning: "Classical weight unit used for metals.",
    category: "weight",
    sector: "gold-jewellery",
    modern_equivalent: "≈12 g (approx.)",
    conversion_formula: "1 Karsha = 16 Masha",
    states: ["Goa"],
    used_in: ["Ancient metal measurement"],
    references: ["Classical literature"],
  }
];
