import { Measurement } from "@/types";

export const GUJARAT_MEASUREMENTS: Measurement[] = [
  // Agriculture (Seed & Crop)
  {
    id: "gj-agri-1",
    slug: "gj-paili-agri",
    name_english: "Paili",
    name_hindi: "પૈલી",
    local_names: ["પૈલી (Paili)"],
    meaning: "Grain measuring vessel.",
    category: "volume",
    sector: "agriculture",
    modern_equivalent: "≈3-4 L (regional variation)",
    conversion_formula: "Traditional grain measure",
    states: ["Gujarat"],
    used_in: ["Seed measurement"],
    references: ["Gujarat Village Traditions"],
  },
  {
    id: "gj-agri-2",
    slug: "gj-khandi-agri",
    name_english: "Khandi",
    name_hindi: "ખાંડી",
    local_names: ["ખાંડી (Khandi)"],
    meaning: "Large commercial grain storage unit.",
    category: "weight",
    sector: "agriculture",
    modern_equivalent: "≈746 kg (regional variation)",
    conversion_formula: "20 Man = 1 Khandi",
    states: ["Gujarat"],
    used_in: ["Bulk storage"],
    references: ["Revenue Administration Records"],
  },
  {
    id: "gj-agri-3",
    slug: "gj-topli-agri",
    name_english: "Topli",
    name_hindi: "ટોપલી",
    local_names: ["ટોપલી (Topli)"],
    meaning: "Bamboo basket.",
    category: "volume",
    sector: "agriculture",
    modern_equivalent: "Regional variation",
    conversion_formula: "Basket measure",
    states: ["Gujarat"],
    used_in: ["Carrying vegetables, cotton and maize"],
    references: ["Gujarat Rural Traditions"],
  },
  {
    id: "gj-agri-4",
    slug: "gj-potlu-agri",
    name_english: "Potlu",
    name_hindi: "પોટલું",
    local_names: ["પોટલું (Potlu)"],
    meaning: "Cloth bundle.",
    category: "volume",
    sector: "agriculture",
    modern_equivalent: "Commodity dependent",
    conversion_formula: "Bundle of crops",
    states: ["Gujarat"],
    used_in: ["Seeds and harvested produce"],
    references: ["Village Customs"],
  },

  // Trade & Commerce
  {
    id: "gj-trade-1",
    slug: "gj-candy-trade",
    name_english: "Candy",
    name_hindi: "કેન્ડી",
    local_names: ["કેન્ડી (Candy)"],
    meaning: "Commercial weight used for exports.",
    category: "weight",
    sector: "trade-commerce",
    modern_equivalent: "≈227 kg (regional variation)",
    conversion_formula: "Multiple Man",
    states: ["Gujarat"],
    used_in: ["Cotton, spices and silk exports"],
    references: ["East India Company Records"],
  },
  {
    id: "gj-trade-2",
    slug: "gj-mohur-trade",
    name_english: "Mohur",
    name_hindi: "મોહર",
    local_names: ["મોહર (Mohur)"],
    meaning: "High value gold coin.",
    category: "currency",
    sector: "trade-commerce",
    modern_equivalent: "≈10.9-11 g gold",
    conversion_formula: "High value coin",
    states: ["Gujarat"],
    used_in: ["Major commercial and international trade"],
    references: ["Indo-Numismatics Studies"],
  },
  {
    id: "gj-trade-3",
    slug: "gj-rupiya-trade",
    name_english: "Rupiya",
    name_hindi: "રૂપિયા",
    local_names: ["રૂપિયા (Rupiya)"],
    meaning: "Principal monetary unit.",
    category: "currency",
    sector: "trade-commerce",
    modern_equivalent: "Historical silver standard",
    conversion_formula: "16 Anna = 1 Rupiya",
    states: ["Gujarat"],
    used_in: ["General commerce"],
    references: ["Bombay Presidency Records"],
  },

  // Architecture
  {
    id: "gj-arch-1",
    slug: "gj-kathi-arch",
    name_english: "Kathi",
    name_hindi: "કાઠી",
    local_names: ["કાઠી (Kathi)"],
    meaning: "Wooden measuring pole.",
    category: "length",
    sector: "architecture",
    modern_equivalent: "≈2-3 m (regional variation)",
    conversion_formula: "Measuring pole",
    states: ["Gujarat"],
    used_in: ["Land and construction guide"],
    references: ["Gujarat Revenue Records"],
  },
  {
    id: "gj-arch-2",
    slug: "gj-sutra-arch",
    name_english: "Sutra",
    name_hindi: "સૂત્ર",
    local_names: ["સૂત્ર (Sutra)"],
    meaning: "Measuring cord.",
    category: "length",
    sector: "architecture",
    modern_equivalent: "Variable",
    conversion_formula: "Survey Measure",
    states: ["Gujarat"],
    used_in: ["Alignment in temples and public buildings"],
    references: ["Samarangana Sutradhara"],
  },

  // Medicine (Ayurveda)
  {
    id: "gj-med-1",
    slug: "gj-shana-med",
    name_english: "Shana",
    name_hindi: "શાણ",
    local_names: ["શાણ (Shana)"],
    meaning: "Traditional medicinal unit.",
    category: "weight",
    sector: "medicine",
    modern_equivalent: "≈3-4 g",
    conversion_formula: "Traditional unit",
    states: ["Gujarat"],
    used_in: ["Herbal powders"],
    references: ["Rasashastra Texts"],
  },
  {
    id: "gj-med-2",
    slug: "gj-patra-med",
    name_english: "Patra",
    name_hindi: "પાત્ર",
    local_names: ["પાત્ર (Patra)"],
    meaning: "Vessel measure.",
    category: "volume",
    sector: "medicine",
    modern_equivalent: "Variable",
    conversion_formula: "Container measure",
    states: ["Gujarat"],
    used_in: ["Preparing and storing medicines"],
    references: ["Gujarat Ayurvedic Manuscripts"],
  },

  // Textile & Handloom
  {
    id: "gj-tex-1",
    slug: "gj-sutni-gunch-tex",
    name_english: "Sutni Gunch",
    name_hindi: "સૂતની ગૂંચ",
    local_names: ["સૂતની ગૂંચ (Sutni Gunch)"],
    meaning: "Bundle of yarn.",
    category: "length",
    sector: "textile-handloom",
    modern_equivalent: "Regional variation",
    conversion_formula: "Yarn bundle",
    states: ["Gujarat"],
    used_in: ["Loom preparation before weaving"],
    references: ["Gujarati Handloom Traditions"],
  },
  {
    id: "gj-tex-2",
    slug: "gj-maggu-pakudai-tex",
    name_english: "Maggu Pakudai",
    name_hindi: "માગ્ગુ પકુડાઈ",
    local_names: ["માગ્ગુ પકુડાઈ (Maggu Pakudai)"],
    meaning: "Loom width.",
    category: "length",
    sector: "textile-handloom",
    modern_equivalent: "Variable",
    conversion_formula: "Loom width",
    states: ["Gujarat"],
    used_in: ["Width of cloth determined by the handloom"],
    references: ["Rural Weaving Practices"],
  },
  {
    id: "gj-tex-3",
    slug: "gj-patola-gathho-tex",
    name_english: "Patola Gathho",
    name_hindi: "પટોળા ગાંઠો",
    local_names: ["પટોળા ગાંઠો (Patola Gathho)"],
    meaning: "Bundle of Patola textiles.",
    category: "volume",
    sector: "textile-handloom",
    modern_equivalent: "Commodity dependent",
    conversion_formula: "Silk Bundle",
    states: ["Gujarat"],
    used_in: ["Silk trade"],
    references: ["Patan Heritage Records"],
  },

  // Land Measurement
  {
    id: "gj-land-1",
    slug: "gj-vigha-land",
    name_english: "Vigha",
    name_hindi: "વીઘા",
    local_names: ["વીઘા (Vigha)"],
    meaning: "Traditional land measure.",
    category: "area",
    sector: "land-measurement",
    modern_equivalent: "Regional variation",
    conversion_formula: "Agricultural land",
    states: ["Gujarat"],
    used_in: ["Farming plots"],
    references: ["Revenue Records"],
  },

  // Transportation & Distance
  {
    id: "gj-trans-1",
    slug: "gj-gau-trans",
    name_english: "Gau",
    name_hindi: "ગાઉ",
    local_names: ["ગાઉ (Gau)"],
    meaning: "Traditional travel distance.",
    category: "length",
    sector: "transportation-distance",
    modern_equivalent: "≈3.2 km",
    conversion_formula: "Distance measure",
    states: ["Gujarat"],
    used_in: ["Travel and routing"],
    references: ["Local Travel Logs"],
  },

  // Household & Daily Life
  {
    id: "gj-hh-1",
    slug: "gj-tola-hh",
    name_english: "Tola",
    name_hindi: "તોલા",
    local_names: ["તોલા (Tola)"],
    meaning: "Small household weight.",
    category: "weight",
    sector: "household",
    modern_equivalent: "≈11.66 g",
    conversion_formula: "Spice trade",
    states: ["Gujarat"],
    used_in: ["Kitchen ingredients"],
    references: ["Household Customs"],
  },

  // Livestock & Dairy
  {
    id: "gj-dairy-1",
    slug: "gj-sher-dairy",
    name_english: "Sher",
    name_hindi: "શેર",
    local_names: ["શેર (Sher)"],
    meaning: "Standard liquid measure.",
    category: "volume",
    sector: "livestock-dairy",
    modern_equivalent: "≈0.93 L",
    conversion_formula: "Milk measure",
    states: ["Gujarat"],
    used_in: ["Dairy sales"],
    references: ["Local Dairies"],
  },

  // Gold & Jewellery
  {
    id: "gj-gold-1",
    slug: "gj-ratti-gold",
    name_english: "Ratti",
    name_hindi: "રત્તી",
    local_names: ["રત્તી (Ratti)"],
    meaning: "Smallest gold weight.",
    category: "weight",
    sector: "gold-jewellery",
    modern_equivalent: "≈0.12 g",
    conversion_formula: "Seed unit",
    states: ["Gujarat"],
    used_in: ["Goldsmithing"],
    references: ["Jewellery traditions"],
  },

  // Currency & Money
  {
    id: "gj-cur-1",
    slug: "gj-kori-cur",
    name_english: "Kori",
    name_hindi: "કોરી",
    local_names: ["કોરી (Kori)"],
    meaning: "Kutch regional currency.",
    category: "currency",
    sector: "currency-money",
    modern_equivalent: "Historical",
    conversion_formula: "Coinage",
    states: ["Gujarat"],
    used_in: ["Kutch regional trade"],
    references: ["Numismatic Records"],
  },

  // Storage & Transportation
  {
    id: "gj-storage-1",
    slug: "gj-kothar-storage",
    name_english: "Kothar",
    name_hindi: "કોઠાર",
    local_names: ["કોઠાર (Kothar)"],
    meaning: "Granary.",
    category: "volume",
    sector: "storage-transport",
    modern_equivalent: "Variable",
    conversion_formula: "Storage room",
    states: ["Gujarat"],
    used_in: ["Grain storage"],
    references: ["Architecture studies"],
  },

  // Religious & Cultural
  {
    id: "gj-relig-1",
    slug: "gj-choghadiya-relig",
    name_english: "Choghadiya",
    name_hindi: "ચોઘડિયા",
    local_names: ["ચોઘડિયા (Choghadiya)"],
    meaning: "Astrological time unit.",
    category: "time",
    sector: "religious-cultural",
    modern_equivalent: "≈1.5 Hours",
    conversion_formula: "Time block",
    states: ["Gujarat"],
    used_in: ["Finding auspicious times"],
    references: ["Gujarati Panchang"],
  }
];
