import { Measurement } from "@/types";

export const JHARKHAND_MEASUREMENTS: Measurement[] = [
  // ─── 1. Land Measurement ──────────────────────────────────────────────────
  {
    id: "jh-land-1",
    slug: "dhurki-land-measurement-jharkhand",
    name_english: "Dhurki",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "धुरकी",
    local_names: ["धुरकी (Dhurki)"],
    meaning: "Very fine subdivision used for small residential-plot boundaries in Ranchi–Palamu–Deoghar region",
    category: "area",
    sector: "land-measurement",
    origin: "Jharkhand (Nagpuri/Sadri region)",
    historical_context: "Smallest land subdivision unit in traditional land surveying across Chota Nagpur",
    modern_equivalent: "Smallest subdivision (1/20 Dhur)",
    conversion_formula: "20 Dhurki = 1 Dhur",
    states: ["Jharkhand"],
    used_in: ["Very fine subdivision used for small residential-plot boundaries in Ranchi–Palamu–Deoghar region", "Land Measurement"],
    hierarchy: [{ name: "Dhur", relation: "larger", value: 20, unit: "20 Dhurki = 1 Dhur" }],
    references: ["https://civilsir.com/1-katha-sq-ft-in-jharkhand/"],
    tags: ["jharkhand", "land-measurement", "area", "dhurki"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-land-2",
    slug: "dhur-land-measurement-jharkhand",
    name_english: "Dhur",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "धुर",
    local_names: ["धुर (Dhur)"],
    meaning: "Smallest commonly used land unit in Jharkhand's rural land transactions and revenue records",
    category: "area",
    sector: "land-measurement",
    origin: "Jharkhand (Nagpuri/Sadri region)",
    historical_context: "Base rural land transaction unit across Jharkhand revenue divisions",
    modern_equivalent: "~13.5–68 sq ft (varies by district)",
    conversion_formula: "20 Dhur = 1 Katha",
    states: ["Jharkhand"],
    used_in: ["Smallest commonly used land unit in Jharkhand's rural land transactions and revenue records", "Land Measurement"],
    hierarchy: [{ name: "Katha", relation: "larger", value: 20, unit: "20 Dhur = 1 Katha" }],
    references: ["https://civilsir.com/1-katha-sq-ft-in-jharkhand/"],
    tags: ["jharkhand", "land-measurement", "area", "dhur"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-land-3",
    slug: "katha-kattha-land-measurement-jharkhand",
    name_english: "Katha (Kattha)",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "कट्ठा",
    local_names: ["कट्ठा (Kattha)"],
    meaning: "Primary traditional unit for buying and selling small farm and residential plots across Jharkhand",
    category: "area",
    sector: "land-measurement",
    origin: "Jharkhand (Nagpuri/Sadri region)",
    historical_context: "Primary traditional area unit for residential plot sales and farm deeds (Ranchi = 720 sq ft)",
    modern_equivalent: "~270–2,614 sq ft (varies widely: Ranchi = 720 sq ft)",
    conversion_formula: "20 Katha = 1 Bigha",
    states: ["Jharkhand"],
    used_in: ["Primary traditional unit for buying and selling small farm and residential plots across Jharkhand", "Land Measurement"],
    hierarchy: [{ name: "Bigha", relation: "larger", value: 20, unit: "20 Katha = 1 Bigha" }],
    references: ["https://civilsir.com/1-katha-sq-ft-in-jharkhand/"],
    tags: ["jharkhand", "land-measurement", "area", "katha"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-land-4",
    slug: "decimal-dismil-land-measurement-jharkhand",
    name_english: "Decimal (Dismil)",
    name_sanskrit: "(Modern colonial-era unit)",
    name_hindi: "डिसमिल",
    local_names: ["डिसमिल (Dismil)"],
    meaning: "Standard registration-office unit used alongside traditional Katha/Bigha in Jharkhand land records",
    category: "area",
    sector: "land-measurement",
    origin: "Jharkhand",
    historical_context: "Colonial land record unit widely adopted in government registry offices across Jharkhand",
    modern_equivalent: "435.6 sq ft",
    conversion_formula: "1/100 Acre",
    states: ["Jharkhand"],
    used_in: ["Standard registration-office unit used alongside traditional Katha/Bigha in Jharkhand land records", "Land Measurement"],
    hierarchy: [{ name: "Acre", relation: "larger", value: 100, unit: "100 Decimal = 1 Acre" }],
    references: ["https://civilsir.com/1-katha-sq-ft-in-jharkhand/"],
    tags: ["jharkhand", "land-measurement", "area", "decimal"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-land-5",
    slug: "bigha-land-measurement-jharkhand",
    name_english: "Bigha",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "बीघा",
    local_names: ["बीघा (Bigha)"],
    meaning: "Standard agricultural landholding unit, still widely referenced in Jharkhand revenue records",
    category: "area",
    sector: "land-measurement",
    origin: "Jharkhand (Nagpuri/Sadri region)",
    historical_context: "Standard agricultural landholding unit across Chota Nagpur and Santhal Parganas",
    modern_equivalent: "~5,412 sq ft (≈1.34 acre, state-wide reference figure)",
    conversion_formula: "20 Katha = 400 Dhur = 1 Bigha",
    states: ["Jharkhand"],
    used_in: ["Standard agricultural landholding unit, still widely referenced in Jharkhand revenue records", "Land Measurement"],
    hierarchy: [{ name: "Katha", relation: "smaller", value: 20, unit: "20 Katha = 1 Bigha" }],
    references: ["https://bhumicalculator.com/states/jharkhand/"],
    tags: ["jharkhand", "land-measurement", "area", "bigha"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-land-6",
    slug: "acre-land-measurement-jharkhand",
    name_english: "Acre",
    name_sanskrit: "(Modern imperial unit)",
    name_hindi: "एकड़",
    local_names: ["एकड़ (Ekad)"],
    meaning: "Government land records and larger agricultural holdings",
    category: "area",
    sector: "land-measurement",
    origin: "Jharkhand",
    historical_context: "Official revenue and agricultural land measurement standard",
    modern_equivalent: "43,560 sq ft (4,046.86 sq m)",
    conversion_formula: "0.7475 Bigha ≈ 1 Acre",
    states: ["Jharkhand"],
    used_in: ["Government land records and larger agricultural holdings", "Land Measurement"],
    references: ["https://en.wikipedia.org/wiki/Bigha"],
    tags: ["jharkhand", "land-measurement", "area", "acre"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-land-7",
    slug: "hectare-land-measurement-jharkhand",
    name_english: "Hectare",
    name_sanskrit: "(Modern metric unit)",
    name_hindi: "हेक्टेयर",
    local_names: ["हेक्टेयर (Hectare)"],
    meaning: "Forest, mining-lease and large agricultural-survey measurement, relevant to Jharkhand's mineral belt",
    category: "area",
    sector: "land-measurement",
    origin: "Jharkhand",
    historical_context: "Metric area unit used in forest department records, mining leases, and regional surveys",
    modern_equivalent: "10,000 sq m (2.471 Acres)",
    conversion_formula: "2.5 Bigha ≈ 1 Hectare (approx.)",
    states: ["Jharkhand"],
    used_in: ["Forest, mining-lease and large agricultural-survey measurement", "Land Measurement"],
    references: ["https://en.wikipedia.org/wiki/Hectare"],
    tags: ["jharkhand", "land-measurement", "area", "hectare"],
    created_at: "2024-01-01",
  },

  // ─── 2. Livestock & Dairy ────────────────────────────────────────────────
  {
    id: "jh-dairy-1",
    slug: "ratti-livestock-dairy-jharkhand",
    name_english: "Ratti",
    name_sanskrit: "रत्ति (Ratti)",
    name_hindi: "रत्ती",
    local_names: ["रत्ती (Ratti)"],
    meaning: "Dosing traditional veterinary herbal powders for cattle",
    category: "weight",
    sector: "livestock-dairy",
    origin: "Jharkhand",
    historical_context: "Traditional cattle medicine dosage unit used by tribal gwalas and healers",
    modern_equivalent: "~0.12 g",
    conversion_formula: "Base / smallest unit",
    states: ["Jharkhand"],
    used_in: ["Dosing traditional veterinary herbal powders for cattle", "Livestock & Dairy"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "livestock-dairy", "ratti"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-dairy-2",
    slug: "chhatank-livestock-dairy-jharkhand",
    name_english: "Chhatank",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "छटांक",
    local_names: ["छटाँक (Chhataank)"],
    meaning: "Small quantities of ghee and butter weighed in tribal households",
    category: "weight",
    sector: "livestock-dairy",
    origin: "Jharkhand",
    historical_context: "Weight unit for domestic dairy produce trade in village haats",
    modern_equivalent: "~58.3 g",
    conversion_formula: "5 Tola = 1 Chhatank",
    states: ["Jharkhand"],
    used_in: ["Small quantities of ghee and butter weighed in tribal households", "Livestock & Dairy"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "livestock-dairy", "chhatank"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-dairy-3",
    slug: "ser-livestock-dairy-jharkhand",
    name_english: "Ser",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "सेर",
    local_names: ["सेर (Ser)"],
    meaning: "Standard milk, curd and ghee measuring unit at village dairies and weekly haats",
    category: "weight",
    sector: "livestock-dairy",
    origin: "Jharkhand",
    historical_context: "Primary milk and ghee volume/weight measure across Chota Nagpur dairies",
    modern_equivalent: "~933 g / ~933 ml",
    conversion_formula: "16 Chhatank = 1 Ser",
    states: ["Jharkhand"],
    used_in: ["Standard milk, curd and ghee measuring unit at village dairies and weekly haats", "Livestock & Dairy"],
    references: ["https://en.wikipedia.org/wiki/Seer_(unit)"],
    tags: ["jharkhand", "livestock-dairy", "ser"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-dairy-4",
    slug: "paseri-livestock-dairy-jharkhand",
    name_english: "Paseri",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "पसेरी",
    local_names: ["पसेरी (Paseri)"],
    meaning: "Bulk milk and ghee trade transactions at haats",
    category: "weight",
    sector: "livestock-dairy",
    origin: "Jharkhand",
    historical_context: "5-Ser wholesale dairy measure for ghee and milk consignments",
    modern_equivalent: "~4.67 kg",
    conversion_formula: "5 Ser = 1 Paseri",
    states: ["Jharkhand"],
    used_in: ["Bulk milk and ghee trade transactions at haats", "Livestock & Dairy"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "livestock-dairy", "paseri"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-dairy-5",
    slug: "man-maund-livestock-dairy-jharkhand",
    name_english: "Man (Maund)",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "मन",
    local_names: ["मन (Man)"],
    meaning: "Large-scale fodder and oil-cake weighing for cattle and buffalo",
    category: "weight",
    sector: "livestock-dairy",
    origin: "Jharkhand",
    historical_context: "Bulk cattle feed and oil-cake weight at cattle markets",
    modern_equivalent: "~37.32 kg",
    conversion_formula: "40 Ser = 1 Man",
    states: ["Jharkhand"],
    used_in: ["Large-scale fodder and oil-cake weighing for cattle and buffalo", "Livestock & Dairy"],
    references: ["https://en.wikipedia.org/wiki/Maund"],
    tags: ["jharkhand", "livestock-dairy", "man"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-dairy-6",
    slug: "gaz-livestock-dairy-jharkhand",
    name_english: "Gaz",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "गज़",
    local_names: ["गज (Gaj)"],
    meaning: "Measuring rope/tether length for grazing cattle",
    category: "length",
    sector: "livestock-dairy",
    origin: "Jharkhand",
    historical_context: "Standard yard unit used by graziers to measure cattle tether ropes",
    modern_equivalent: "~0.914 m",
    conversion_formula: "2 Hath = 1 Gaz",
    states: ["Jharkhand"],
    used_in: ["Measuring rope/tether length for grazing cattle", "Livestock & Dairy"],
    references: ["https://handwiki.org/wiki/Indian_units_of_measurement"],
    tags: ["jharkhand", "livestock-dairy", "gaz"],
    created_at: "2024-01-01",
  },

  // ─── 3. Household & Daily Life ───────────────────────────────────────────
  {
    id: "jh-hh-1",
    slug: "chutki-pinch-household-jharkhand",
    name_english: "Chutki (pinch)",
    name_sanskrit: "(Informal, pan-Hindi-belt term)",
    name_hindi: "चुटकी",
    local_names: ["चुटकी (Chutki)"],
    meaning: "Measuring salt, spice powder while cooking",
    category: "volume",
    sector: "household",
    origin: "Jharkhand",
    historical_context: "Informal kitchen pinch measure for salt and powdered spices",
    modern_equivalent: "Small pinch (informal, no fixed weight)",
    conversion_formula: "Smallest informal unit",
    states: ["Jharkhand"],
    used_in: ["Measuring salt, spice powder while cooking", "Household & Daily Life"],
    references: ["https://handwiki.org/wiki/Indian_units_of_measurement"],
    tags: ["jharkhand", "household", "chutki"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-hh-2",
    slug: "muthi-fistful-household-jharkhand",
    name_english: "Muthi (fistful)",
    name_sanskrit: "मुष्टि (Muṣṭi) — cognate",
    name_hindi: "मुट्ठी",
    local_names: ["मुठी (Muthi)"],
    meaning: "Handling grain and lentils in the kitchen",
    category: "volume",
    sector: "household",
    origin: "Jharkhand",
    historical_context: "Fistful volumetric measure for rice and pulses in traditional daily cooking",
    modern_equivalent: "~40–60 g (varies by hand size)",
    conversion_formula: "Several Chutki = 1 Muthi",
    states: ["Jharkhand"],
    used_in: ["Handling grain and lentils in the kitchen", "Household & Daily Life"],
    references: ["https://handwiki.org/wiki/Indian_units_of_measurement"],
    tags: ["jharkhand", "household", "muthi"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-hh-3",
    slug: "chhatank-household-jharkhand",
    name_english: "Chhatank",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "छटांक",
    local_names: ["छटाँक (Chhataank)"],
    meaning: "Everyday retail purchase of spices and grain, still colloquially used",
    category: "weight",
    sector: "household",
    origin: "Jharkhand",
    historical_context: "Colloquial retail weight unit used in everyday household shopping",
    modern_equivalent: "~58.3 g",
    conversion_formula: "5 Tola = 1 Chhatank",
    states: ["Jharkhand"],
    used_in: ["Everyday retail purchase of spices and grain, still colloquially used", "Household & Daily Life"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "household", "chhatank"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-hh-4",
    slug: "pauwa-household-jharkhand",
    name_english: "Pauwa",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "पावा",
    local_names: ["पावा (Pauwa)"],
    meaning: "Common quarter-measure for household grain and flour purchase",
    category: "weight",
    sector: "household",
    origin: "Jharkhand",
    historical_context: "Quarter-Seer measure widely used in kitchen grain provisioning",
    modern_equivalent: "~233 g",
    conversion_formula: "¼ Ser = 1 Pauwa",
    states: ["Jharkhand"],
    used_in: ["Common quarter-measure for household grain and flour purchase", "Household & Daily Life"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "household", "pauwa"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-hh-5",
    slug: "adhsera-household-jharkhand",
    name_english: "Adhsera",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "अधसेरा",
    local_names: ["अधसेरा (Adhsera)"],
    meaning: "Half-measure for household grain purchase",
    category: "weight",
    sector: "household",
    origin: "Jharkhand",
    historical_context: "Half-Seer weight unit for domestic food provisioning",
    modern_equivalent: "~467 g",
    conversion_formula: "½ Ser = 1 Adhsera",
    states: ["Jharkhand"],
    used_in: ["Half-measure for household grain purchase", "Household & Daily Life"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "household", "adhsera"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-hh-6",
    slug: "ser-household-jharkhand",
    name_english: "Ser",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "सेर",
    local_names: ["सेर (Ser)"],
    meaning: "Primary household unit for buying rice, dal and flour at the local haat",
    category: "weight",
    sector: "household",
    origin: "Jharkhand",
    historical_context: "Primary domestic kitchen weight standard for staples",
    modern_equivalent: "~933 g",
    conversion_formula: "16 Chhatank = 1 Ser",
    states: ["Jharkhand"],
    used_in: ["Primary household unit for buying rice, dal and flour at the local haat", "Household & Daily Life"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "household", "ser"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-hh-7",
    slug: "paseri-household-jharkhand",
    name_english: "Paseri",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "पसेरी",
    local_names: ["पसेरी (Paseri)"],
    meaning: "Household bulk grain storage measure",
    category: "weight",
    sector: "household",
    origin: "Jharkhand",
    historical_context: "5-Seer domestic grain storage container measure",
    modern_equivalent: "~4.67 kg",
    conversion_formula: "5 Ser = 1 Paseri",
    states: ["Jharkhand"],
    used_in: ["Household bulk grain storage measure", "Household & Daily Life"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "household", "paseri"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-hh-8",
    slug: "bitta-household-jharkhand",
    name_english: "Bitta",
    name_sanskrit: "वितस्ति (Vitasti) — cognate",
    name_hindi: "बित्ता",
    local_names: ["बिस्ता (Bitta)"],
    meaning: "Measuring cloth and rope length at home",
    category: "length",
    sector: "household",
    origin: "Jharkhand",
    historical_context: "Hand-span length unit used in domestic sewing and rope cutting",
    modern_equivalent: "~22.9 cm",
    conversion_formula: "2 Bitta = 1 Hath",
    states: ["Jharkhand"],
    used_in: ["Measuring cloth and rope length at home", "Household & Daily Life"],
    references: ["https://www.indiamike.com/india/chai-and-chat-f73/weights-and-measures-t223614/"],
    tags: ["jharkhand", "household", "bitta"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-hh-9",
    slug: "hath-household-jharkhand",
    name_english: "Hath",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "हाथ",
    local_names: ["हाँथ (Hanth)"],
    meaning: "Measuring rope and firewood-bundle length at home",
    category: "length",
    sector: "household",
    origin: "Jharkhand",
    historical_context: "Cubit unit used for measuring firewood bundles and well ropes",
    modern_equivalent: "~0.457 m",
    conversion_formula: "8 Girah = 1 Hath",
    states: ["Jharkhand"],
    used_in: ["Measuring rope and firewood-bundle length at home", "Household & Daily Life"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "household", "hath"],
    created_at: "2024-01-01",
  },

  // ─── 4. Gold & Jewellery ──────────────────────────────────────────────────
  {
    id: "jh-gold-1",
    slug: "ratti-gold-jewellery-jharkhand",
    name_english: "Ratti",
    name_sanskrit: "रत्ति (Ratti)",
    name_hindi: "रत्ती",
    local_names: ["रत्ती (Ratti)"],
    meaning: "Micro-weighing of gemstones and gold in ornament-making",
    category: "weight",
    sector: "gold-jewellery",
    origin: "Jharkhand",
    historical_context: "Standard goldsmith's base weight for gemstones and gold alloys",
    modern_equivalent: "~0.12 g",
    conversion_formula: "Base / smallest unit",
    states: ["Jharkhand"],
    used_in: ["Micro-weighing of gemstones and gold in ornament-making", "Gold & Jewellery"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "gold-jewellery", "ratti"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-gold-2",
    slug: "maas-masha-gold-jewellery-jharkhand",
    name_english: "Maas (Masha)",
    name_sanskrit: "माष (Māṣa)",
    name_hindi: "मास",
    local_names: ["मास (Maas)"],
    meaning: "Fine silver-ornament weighing (Santhal 'Rajohar' necklaces, tribal earrings)",
    category: "weight",
    sector: "gold-jewellery",
    origin: "Jharkhand",
    historical_context: "Silver ornament weight standard for traditional Santhal 'Rajohar' necklaces",
    modern_equivalent: "~0.97 g",
    conversion_formula: "8 Ratti = 1 Maas",
    states: ["Jharkhand"],
    used_in: ["Fine silver-ornament weighing (Santhal 'Rajohar' necklaces, tribal earrings)", "Gold & Jewellery"],
    references: ["https://cultureandheritage.org/2024/01/traditional-tribal-jewellery-of-jharkhand.html"],
    tags: ["jharkhand", "gold-jewellery", "maas"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-gold-3",
    slug: "tola-gold-jewellery-jharkhand",
    name_english: "Tola",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "तोला",
    local_names: ["तोला (Tola)"],
    meaning: "Standard gold/silver-ornament trade weight across Jharkhand bazaars",
    category: "weight",
    sector: "gold-jewellery",
    origin: "Jharkhand",
    historical_context: "Universal bullion weight unit in Jharkhand goldsmith bazaars",
    modern_equivalent: "~11.66 g",
    conversion_formula: "12 Maas = 1 Tola",
    states: ["Jharkhand"],
    used_in: ["Standard gold/silver-ornament trade weight across Jharkhand bazaars", "Gold & Jewellery"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "gold-jewellery", "tola"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-gold-4",
    slug: "gram-gold-jewellery-jharkhand",
    name_english: "Gram",
    name_sanskrit: "(Modern metric unit)",
    name_hindi: "ग्राम",
    local_names: ["ग्राम (Gram)"],
    meaning: "BIS-hallmark jewellery billing in modern jewellery shops",
    category: "weight",
    sector: "gold-jewellery",
    origin: "Jharkhand",
    historical_context: "Modern metric gold unit used in hallmarked jewellery stores",
    modern_equivalent: "1 g",
    conversion_formula: "Modern metric base",
    states: ["Jharkhand"],
    used_in: ["BIS-hallmark jewellery billing in modern jewellery shops", "Gold & Jewellery"],
    references: ["https://en.wikipedia.org/wiki/Gram"],
    tags: ["jharkhand", "gold-jewellery", "gram"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-gold-5",
    slug: "chhatank-gold-jewellery-jharkhand",
    name_english: "Chhatank",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "छटांक",
    local_names: ["छटाँक (Chhataank)"],
    meaning: "Weighing larger batches of tribal silver ornaments (Kanjari bangles, Khopor headpieces)",
    category: "weight",
    sector: "gold-jewellery",
    origin: "Jharkhand",
    historical_context: "Bulk silver weight unit for heavy tribal anklets and head ornaments",
    modern_equivalent: "~58.3 g",
    conversion_formula: "5 Tola = 1 Chhatank",
    states: ["Jharkhand"],
    used_in: ["Weighing larger batches of tribal silver ornaments", "Gold & Jewellery"],
    references: ["https://cultureandheritage.org/2024/01/traditional-tribal-jewellery-of-jharkhand.html"],
    tags: ["jharkhand", "gold-jewellery", "chhatank"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-gold-6",
    slug: "kauri-cowrie-gold-jewellery-jharkhand",
    name_english: "Kauri (Cowrie)",
    name_sanskrit: "कपर्दिका (Kapardika) — probable cognate, unconfirmed",
    name_hindi: "कौड़ी",
    local_names: ["कौड़ी (Kaudi)"],
    meaning: "Decorative cowrie-shell stitching on Munda ornaments; historically doubled as small-denomination currency",
    category: "count",
    sector: "gold-jewellery",
    origin: "Jharkhand",
    historical_context: "Shell count unit used in traditional Munda ornament weaving",
    modern_equivalent: "Counted individually / in strings",
    conversion_formula: "N/A — counting unit",
    states: ["Jharkhand"],
    used_in: ["Decorative cowrie-shell stitching on Munda ornaments", "Gold & Jewellery"],
    references: ["https://www.wisdomlib.org/gallery/new-delhi-museum-coins/9791"],
    tags: ["jharkhand", "gold-jewellery", "kauri"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-gold-7",
    slug: "kilogram-gold-jewellery-jharkhand",
    name_english: "Kilogram",
    name_sanskrit: "(Modern metric unit)",
    name_hindi: "किलोग्राम",
    local_names: ["किलोग्राम (Kilogram)"],
    meaning: "Bullion trade and bank gold storage",
    category: "weight",
    sector: "gold-jewellery",
    origin: "Jharkhand",
    historical_context: "Bulk gold bar and bank vault weight standard",
    modern_equivalent: "1000 g",
    conversion_formula: "1000 Gram = 1 Kg",
    states: ["Jharkhand"],
    used_in: ["Bullion trade and bank gold storage", "Gold & Jewellery"],
    references: ["https://en.wikipedia.org/wiki/Kilogram"],
    tags: ["jharkhand", "gold-jewellery", "kilogram"],
    created_at: "2024-01-01",
  },

  // ─── 5. Seed & Crop Agriculture ──────────────────────────────────────
  {
    id: "jh-agri-1",
    slug: "ratti-seed-crop-agriculture-jharkhand",
    name_english: "Ratti",
    name_sanskrit: "रत्ति (Ratti)",
    name_hindi: "रत्ती",
    local_names: ["रत्ती (Ratti)"],
    meaning: "Reference weight for grading seed grain quality",
    category: "weight",
    sector: "agriculture",
    origin: "Jharkhand",
    historical_context: "Micro seed grain quality weight reference",
    modern_equivalent: "~0.12 g",
    conversion_formula: "Base / seed-grading reference",
    states: ["Jharkhand"],
    used_in: ["Reference weight for grading seed grain quality", "Seed & Crop (Agriculture)"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "agriculture", "ratti"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-agri-2",
    slug: "chhatank-seed-crop-agriculture-jharkhand",
    name_english: "Chhatank",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "छटांक",
    local_names: ["छटाँक (Chhataank)"],
    meaning: "Small seed-quantity measurement before sowing",
    category: "weight",
    sector: "agriculture",
    origin: "Jharkhand",
    historical_context: "Small seed allotment weight prior to field sowing",
    modern_equivalent: "~58.3 g",
    conversion_formula: "5 Tola = 1 Chhatank",
    states: ["Jharkhand"],
    used_in: ["Small seed-quantity measurement before sowing", "Seed & Crop (Agriculture)"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "agriculture", "chhatank"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-agri-3",
    slug: "pauwa-seed-crop-agriculture-jharkhand",
    name_english: "Pauwa",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "पावा",
    local_names: ["पावा (Pauwa)"],
    meaning: "Small seed-grain retail quantity at village haats",
    category: "weight",
    sector: "agriculture",
    origin: "Jharkhand",
    historical_context: "Quarter-Seer seed retail quantity in rural haats",
    modern_equivalent: "~233 g",
    conversion_formula: "¼ Ser = 1 Pauwa",
    states: ["Jharkhand"],
    used_in: ["Small seed-grain retail quantity at village haats", "Seed & Crop (Agriculture)"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "agriculture", "pauwa"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-agri-4",
    slug: "adhsera-seed-crop-agriculture-jharkhand",
    name_english: "Adhsera",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "अधसेरा",
    local_names: ["अधसेरा (Adhsera)"],
    meaning: "Half-measure for seed grain",
    category: "weight",
    sector: "agriculture",
    origin: "Jharkhand",
    historical_context: "Half-Seer seed grain allocation per plot",
    modern_equivalent: "~467 g",
    conversion_formula: "½ Ser = 1 Adhsera",
    states: ["Jharkhand"],
    used_in: ["Half-measure for seed grain", "Seed & Crop (Agriculture)"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "agriculture", "adhsera"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-agri-5",
    slug: "ser-seed-crop-agriculture-jharkhand",
    name_english: "Ser",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "सेर",
    local_names: ["सेर (Ser)"],
    meaning: "Standard unit for paddy, maize and millet (Marua/Gondli) seed and grain trade",
    category: "weight",
    sector: "agriculture",
    origin: "Jharkhand",
    historical_context: "Standard crop weight unit for paddy, maize, Marua and Gondli millets",
    modern_equivalent: "~933 g",
    conversion_formula: "16 Chhatank = 1 Ser",
    states: ["Jharkhand"],
    used_in: ["Standard unit for paddy, maize and millet seed trade", "Seed & Crop (Agriculture)"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "agriculture", "ser"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-agri-6",
    slug: "sawaiya-seed-crop-agriculture-jharkhand",
    name_english: "Sawaiya",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "सवेया",
    local_names: ["सवेया (Sawaiya)"],
    meaning: "Ceremonial 'new grain' offering measure during the Nawakhani harvest festival",
    category: "weight",
    sector: "agriculture",
    origin: "Jharkhand",
    historical_context: "1¼-Seer ritual offering measure of fresh paddy during Nawakhani",
    modern_equivalent: "~1.17 kg",
    conversion_formula: "5/4 Ser = 1 Sawaiya",
    states: ["Jharkhand"],
    used_in: ["Ceremonial 'new grain' offering measure during Nawakhani harvest festival", "Seed & Crop (Agriculture)"],
    references: ["https://en.wikipedia.org/wiki/Nawakhani"],
    tags: ["jharkhand", "agriculture", "sawaiya"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-agri-7",
    slug: "paseri-seed-crop-agriculture-jharkhand",
    name_english: "Paseri",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "पसेरी",
    local_names: ["पसेरी (Paseri)"],
    meaning: "Bulk grain sale at weekly haats",
    category: "weight",
    sector: "agriculture",
    origin: "Jharkhand",
    historical_context: "5-Seer wholesale grain trading unit at local haats",
    modern_equivalent: "~4.67 kg",
    conversion_formula: "5 Ser = 1 Paseri",
    states: ["Jharkhand"],
    used_in: ["Bulk grain sale at weekly haats", "Seed & Crop (Agriculture)"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "agriculture", "paseri"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-agri-8",
    slug: "dhaara-seed-crop-agriculture-jharkhand",
    name_english: "Dhaara",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "धारा",
    local_names: ["धारा (Dhaara)"],
    meaning: "Bulk paddy/maize storage before milling",
    category: "weight",
    sector: "agriculture",
    origin: "Jharkhand",
    historical_context: "10-Seer bulk grain measure prior to threshing and milling",
    modern_equivalent: "~9.33 kg",
    conversion_formula: "10 Ser = 1 Dhaara",
    states: ["Jharkhand"],
    used_in: ["Bulk paddy/maize storage before milling", "Seed & Crop (Agriculture)"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "agriculture", "dhaara"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-agri-9",
    slug: "man-maund-seed-crop-agriculture-jharkhand",
    name_english: "Man (Maund)",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "मन",
    local_names: ["मन (Man)"],
    meaning: "Primary bulk-crop trading unit at district mandis",
    category: "weight",
    sector: "agriculture",
    origin: "Jharkhand",
    historical_context: "Standard 40-Seer mandi trading unit for agricultural harvests",
    modern_equivalent: "~37.32 kg",
    conversion_formula: "40 Ser = 1 Man",
    states: ["Jharkhand"],
    used_in: ["Primary bulk-crop trading unit at district mandis", "Seed & Crop (Agriculture)"],
    references: ["https://en.wikipedia.org/wiki/Maund"],
    tags: ["jharkhand", "agriculture", "man"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-agri-10",
    slug: "quintal-seed-crop-agriculture-jharkhand",
    name_english: "Quintal",
    name_sanskrit: "(Modern metric unit)",
    name_hindi: "क्विंटल",
    local_names: ["क्विंटल (Quintal)"],
    meaning: "Government MSP (minimum support price) procurement of paddy and maize",
    category: "weight",
    sector: "agriculture",
    origin: "Jharkhand",
    historical_context: "Modern government MSP procurement standard unit",
    modern_equivalent: "100 kg",
    conversion_formula: "10 Quintal = 1 Metric Ton",
    states: ["Jharkhand"],
    used_in: ["Government MSP procurement of paddy and maize", "Seed & Crop (Agriculture)"],
    references: ["https://en.wikipedia.org/wiki/Quintal"],
    tags: ["jharkhand", "agriculture", "quintal"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-agri-11",
    slug: "metric-ton-seed-crop-agriculture-jharkhand",
    name_english: "Metric Ton",
    name_sanskrit: "(Modern metric unit)",
    name_hindi: "मीट्रिक टन",
    local_names: ["मीट्रिक टन (Metric Ton)"],
    meaning: "Large-scale grain warehousing in FCI/State godowns",
    category: "weight",
    sector: "agriculture",
    origin: "Jharkhand",
    historical_context: "Bulk warehousing and state grain stock standard",
    modern_equivalent: "1000 kg",
    conversion_formula: "10 Quintal = 1 Metric Ton",
    states: ["Jharkhand"],
    used_in: ["Large-scale grain warehousing in FCI/State godowns", "Seed & Crop (Agriculture)"],
    references: ["https://en.wikipedia.org/wiki/Tonne"],
    tags: ["jharkhand", "agriculture", "metric-ton"],
    created_at: "2024-01-01",
  },

  // ─── 6. Currency & Money ────────────────────────────────────────────────
  {
    id: "jh-curr-1",
    slug: "kauri-cowrie-currency-money-jharkhand",
    name_english: "Kauri (Cowrie)",
    name_sanskrit: "कपर्दिका (Kapardika) — probable cognate, unconfirmed",
    name_hindi: "कौड़ी",
    local_names: ["कौड़ी (Kaudi)"],
    meaning: "Petty daily transactions, colonial-era land-revenue payment, and priestly/ritual remuneration across the Chota Nagpur region",
    category: "currency",
    sector: "currency-money",
    origin: "Jharkhand (Chota Nagpur region)",
    historical_context: "Smallest traditional currency unit, counted in strings",
    modern_equivalent: "Smallest traditional currency unit, counted in strings",
    conversion_formula: "Base / smallest unit",
    states: ["Jharkhand"],
    used_in: ["Petty daily transactions, colonial-era land-revenue payment, and priestly/ritual remuneration", "Currency & Money"],
    references: ["https://www.wisdomlib.org/gallery/new-delhi-museum-coins/9791"],
    tags: ["jharkhand", "currency-money", "kauri"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-curr-2",
    slug: "damri-currency-money-jharkhand",
    name_english: "Damri",
    name_sanskrit: "(Regional/colonial-era fractional coin)",
    name_hindi: "दमड़ी",
    local_names: ["दमड़ी (Damri)"],
    meaning: "Smallest coined denomination in 19th-century Bihar–Chota Nagpur bazaars",
    category: "currency",
    sector: "currency-money",
    origin: "Jharkhand",
    historical_context: "Fractional copper-based value",
    modern_equivalent: "Fractional copper-based value",
    conversion_formula: "~10 Kauri = 1 Damri",
    states: ["Jharkhand"],
    used_in: ["Smallest coined denomination in 19th-century Bihar–Chota Nagpur bazaars", "Currency & Money"],
    references: ["https://www.indiamike.com/india/chai-and-chat-f73/weights-and-measures-t223614/"],
    tags: ["jharkhand", "currency-money", "damri"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-curr-3",
    slug: "chhadam-currency-money-jharkhand",
    name_english: "Chhadam",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "छदाम",
    local_names: ["छदाम (Chhadam)"],
    meaning: "Local retail trade at village haats",
    category: "currency",
    sector: "currency-money",
    origin: "Jharkhand",
    historical_context: "Fractional denomination",
    modern_equivalent: "Fractional denomination",
    conversion_formula: "2 Damri = 1 Chhadam",
    states: ["Jharkhand"],
    used_in: ["Local retail trade at village haats", "Currency & Money"],
    references: ["https://www.indiamike.com/india/chai-and-chat-f73/weights-and-measures-t223614/"],
    tags: ["jharkhand", "currency-money", "chhadam"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-curr-4",
    slug: "dhela-currency-money-jharkhand",
    name_english: "Dhela",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "ढेला",
    local_names: ["ढेला (Dhela)"],
    meaning: "Local retail trade",
    category: "currency",
    sector: "currency-money",
    origin: "Jharkhand",
    historical_context: "Fractional denomination",
    modern_equivalent: "Fractional denomination",
    conversion_formula: "2 Chhadam = 1 Dhela",
    states: ["Jharkhand"],
    used_in: ["Local retail trade", "Currency & Money"],
    references: ["https://www.indiamike.com/india/chai-and-chat-f73/weights-and-measures-t223614/"],
    tags: ["jharkhand", "currency-money", "dhela"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-curr-5",
    slug: "paisa-pice-currency-money-jharkhand",
    name_english: "Paisa (Pice)",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "पैसा",
    local_names: ["पैसा (Paisa)"],
    meaning: "Daily village trade and haat transactions",
    category: "currency",
    sector: "currency-money",
    origin: "Jharkhand",
    historical_context: "Colonial-era copper coin",
    modern_equivalent: "Colonial-era copper coin",
    conversion_formula: "2 Dhela = 1 Paisa",
    states: ["Jharkhand"],
    used_in: ["Daily village trade and haat transactions", "Currency & Money"],
    references: ["https://www.indiamike.com/india/chai-and-chat-f73/weights-and-measures-t223614/"],
    tags: ["jharkhand", "currency-money", "paisa"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-curr-6",
    slug: "ana-anna-currency-money-jharkhand",
    name_english: "Ana (Anna)",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "आना",
    local_names: ["आना (Ana)"],
    meaning: "Widely used sub-unit of the Rupee across Bihar–Jharkhand until decimalisation in 1957",
    category: "currency",
    sector: "currency-money",
    origin: "Jharkhand",
    historical_context: "Fractional silver-linked coin",
    modern_equivalent: "Fractional silver-linked coin",
    conversion_formula: "4 Paisa = 1 Ana; 16 Ana = 1 Rupiya",
    states: ["Jharkhand"],
    used_in: ["Widely used sub-unit of the Rupee across Bihar–Jharkhand until decimalisation in 1957", "Currency & Money"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "currency-money", "ana"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-curr-7",
    slug: "rupiya-rupee-currency-money-jharkhand",
    name_english: "Rupiya (Rupee)",
    name_sanskrit: "रूप्य (Rupya) — cognate",
    name_hindi: "रुपया",
    local_names: ["रुपैया (Rupaiya)"],
    meaning: "Became the principal currency across Chota Nagpur after British annexation, replacing cowrie/damri barter economy",
    category: "currency",
    sector: "currency-money",
    origin: "Jharkhand (Chota Nagpur region)",
    historical_context: "Standard silver coin (Mughal–British era)",
    modern_equivalent: "Standard silver coin (Mughal–British era)",
    conversion_formula: "16 Ana = 1 Rupiya",
    states: ["Jharkhand"],
    used_in: ["Became the principal currency across Chota Nagpur after British annexation", "Currency & Money"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "currency-money", "rupiya"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-curr-8",
    slug: "tola-silver-rupee-standard-currency-money-jharkhand",
    name_english: "Tola (silver-rupee standard)",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "तोला",
    local_names: ["तोला (Tola)"],
    meaning: "Basis for the standardised British-Indian Rupee circulating in the region",
    category: "currency",
    sector: "currency-money",
    origin: "Jharkhand",
    historical_context: "Currency (weight standard)",
    modern_equivalent: "1 Tola = 180 grains silver (~11.66 g)",
    conversion_formula: "Fixed 1833 British-Indian silver-rupee weight standard",
    states: ["Jharkhand"],
    used_in: ["Basis for the standardised British-Indian Rupee circulating in the region", "Currency & Money"],
    references: ["https://www.researchgate.net/publication/316599701_MEASUREMENT_UNITS_OF_LENGTH_MASS_AND_TIME_IN_INDIA_THROUGH_THE_AGES"],
    tags: ["jharkhand", "currency-money", "tola"],
    created_at: "2024-01-01",
  },

  // ─── 7. Storage & Transportation ───────────────────────────────────────
  {
    id: "jh-store-1",
    slug: "ser-storage-transportation-jharkhand",
    name_english: "Ser",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "सेर",
    local_names: ["सेर (Ser)"],
    meaning: "Household and market grain measure",
    category: "weight",
    sector: "storage-transport",
    origin: "Jharkhand",
    historical_context: "Base household and market grain measure",
    modern_equivalent: "~933 g",
    conversion_formula: "16 Chhatank = 1 Ser",
    states: ["Jharkhand"],
    used_in: ["Household and market grain measure", "Storage & Transportation"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "storage-transport", "ser"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-store-2",
    slug: "paseri-storage-transportation-jharkhand",
    name_english: "Paseri",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "पसेरी",
    local_names: ["पसेरी (Paseri)"],
    meaning: "Basket-load quantity at village haats",
    category: "weight",
    sector: "storage-transport",
    origin: "Jharkhand",
    historical_context: "5-Ser basket-load quantity",
    modern_equivalent: "~4.67 kg",
    conversion_formula: "5 Ser = 1 Paseri",
    states: ["Jharkhand"],
    used_in: ["Basket-load quantity at village haats", "Storage & Transportation"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "storage-transport", "paseri"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-store-3",
    slug: "man-maund-storage-transportation-jharkhand",
    name_english: "Man (Maund)",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "मन",
    local_names: ["मन (Man)"],
    meaning: "Traditional porter/pack-animal load unit — historically the standard weight a porter could carry over distance",
    category: "weight",
    sector: "storage-transport",
    origin: "Jharkhand",
    historical_context: "Standard porter/pack-animal load unit",
    modern_equivalent: "~37.32 kg",
    conversion_formula: "40 Ser = 1 Man",
    states: ["Jharkhand"],
    used_in: ["Traditional porter/pack-animal load unit", "Storage & Transportation"],
    references: ["https://en.wikipedia.org/wiki/Maund"],
    tags: ["jharkhand", "storage-transport", "man"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-store-4",
    slug: "bojha-headload-bundle-storage-transportation-jharkhand",
    name_english: "Bojha (headload bundle)",
    name_sanskrit: "(Informal regional term)",
    name_hindi: "बोझा",
    local_names: ["बोझा (Bojha)"],
    meaning: "Firewood and forest-produce headload carried by tribal women, central to Jharkhand's forest economy",
    category: "weight",
    sector: "storage-transport",
    origin: "Jharkhand",
    historical_context: "Informal porterage unit",
    modern_equivalent: "~20–25 kg (typical)",
    conversion_formula: "Informal porterage unit",
    states: ["Jharkhand"],
    used_in: ["Firewood and forest-produce headload carried by tribal women", "Storage & Transportation"],
    references: ["https://handwiki.org/wiki/Indian_units_of_measurement"],
    tags: ["jharkhand", "storage-transport", "bojha"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-store-5",
    slug: "bail-gaadi-load-cart-load-storage-transportation-jharkhand",
    name_english: "Bail Gaadi load (cart-load)",
    name_sanskrit: "(Informal regional term)",
    name_hindi: "बैलगाड़ी भार",
    local_names: ["बैलगाड़ी बोझ (Bail Gaadi Bojh)"],
    meaning: "Village-to-haat bullock-cart transport of grain and produce",
    category: "weight",
    sector: "storage-transport",
    origin: "Jharkhand",
    historical_context: "Informal bulk-transport unit",
    modern_equivalent: "~500–800 kg (varies by cart & terrain)",
    conversion_formula: "Informal bulk-transport unit",
    states: ["Jharkhand"],
    used_in: ["Village-to-haat bullock-cart transport of grain and produce", "Storage & Transportation"],
    references: ["https://en.wikipedia.org/wiki/Bullock_cart"],
    tags: ["jharkhand", "storage-transport", "bail-gaadi"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-store-6",
    slug: "dauri-tokri-bamboo-basket-storage-transportation-jharkhand",
    name_english: "Dauri / Tokri (bamboo basket)",
    name_sanskrit: "(Informal regional term)",
    name_hindi: "डलिया / टोकरी",
    local_names: ["ढौरी / टोकरी (Dauri/Tokri)"],
    meaning: "Collecting and carrying forest produce — mahua flowers, sal-leaf, tendu leaf, central to the tribal non-timber forest produce (NTFP) economy",
    category: "volume",
    sector: "storage-transport",
    origin: "Jharkhand",
    historical_context: "Informal carrying/storage unit",
    modern_equivalent: "~15–25 kg produce",
    conversion_formula: "Informal carrying/storage unit",
    states: ["Jharkhand"],
    used_in: ["Collecting and carrying forest produce — mahua, sal-leaf, tendu leaf", "Storage & Transportation"],
    references: ["https://handwiki.org/wiki/Indian_units_of_measurement"],
    tags: ["jharkhand", "storage-transport", "dauri"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-store-7",
    slug: "kothi-grain-bin-granary-storage-transportation-jharkhand",
    name_english: "Kothi (grain bin/granary)",
    name_sanskrit: "कोष्ठागार (Koṣṭhāgāra) — cognate",
    name_hindi: "अनाज कोठी",
    local_names: ["धान कोठी (Dhaan Kothi)"],
    meaning: "Household/village mud-and-bamboo grain-storage bin used after harvest",
    category: "volume",
    sector: "storage-transport",
    origin: "Jharkhand",
    historical_context: "Large variable capacity (several Man of grain)",
    modern_equivalent: "Large variable capacity (several Man of grain)",
    conversion_formula: "Multiple Man = 1 Kothi (variable by structure)",
    states: ["Jharkhand"],
    used_in: ["Household/village mud-and-bamboo grain-storage bin used after harvest", "Storage & Transportation"],
    references: ["https://en.wikipedia.org/wiki/Granary"],
    tags: ["jharkhand", "storage-transport", "kothi"],
    created_at: "2024-01-01",
  },

  // ─── 8. Religious & Cultural Sectors ───────────────────────────────────
  {
    id: "jh-relig-1",
    slug: "kauri-cowrie-religious-cultural-jharkhand",
    name_english: "Kauri (Cowrie)",
    name_sanskrit: "कपर्दिका (Kapardika) — probable cognate, unconfirmed",
    name_hindi: "कौड़ी",
    local_names: ["कोड़ी (Kaudi)"],
    meaning: "Traditional remuneration to priests and use in ritual offerings, documented across Hindu and Sarna practice in the region",
    category: "currency",
    sector: "religious-cultural",
    origin: "Jharkhand",
    historical_context: "Currency / Ritual object",
    modern_equivalent: "Counted individually / in strings",
    conversion_formula: "N/A — counting unit",
    states: ["Jharkhand"],
    used_in: ["Traditional remuneration to priests and use in ritual offerings", "Religious & Cultural"],
    references: ["https://www.wisdomlib.org/gallery/new-delhi-museum-coins/9791"],
    tags: ["jharkhand", "religious-cultural", "kauri"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-relig-2",
    slug: "ser-religious-cultural-jharkhand",
    name_english: "Ser",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "सेर",
    local_names: ["सेर (Ser)"],
    meaning: "Measuring rice/grain for Sarhul, Karam and Sohrai festival community offerings and feasts",
    category: "weight",
    sector: "religious-cultural",
    origin: "Jharkhand",
    historical_context: "Festival community offering and feast grain measure",
    modern_equivalent: "~933 g",
    conversion_formula: "16 Chhatank = 1 Ser",
    states: ["Jharkhand"],
    used_in: ["Measuring rice/grain for Sarhul, Karam and Sohrai festival community offerings", "Religious & Cultural"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "religious-cultural", "ser"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-relig-3",
    slug: "sawaiya-religious-cultural-jharkhand",
    name_english: "Sawaiya",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "सवेया",
    local_names: ["सवेया (Sawaiya)"],
    meaning: "Ceremonial first-grain offering during the Nawakhani harvest festival of the Chota Nagpur region",
    category: "weight",
    sector: "religious-cultural",
    origin: "Jharkhand",
    historical_context: "5/4 Ser ceremonial first-grain offering measure",
    modern_equivalent: "~1.17 kg",
    conversion_formula: "5/4 Ser = 1 Sawaiya",
    states: ["Jharkhand"],
    used_in: ["Ceremonial first-grain offering during the Nawakhani harvest festival", "Religious & Cultural"],
    references: ["https://en.wikipedia.org/wiki/Nawakhani"],
    tags: ["jharkhand", "religious-cultural", "sawaiya"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-relig-4",
    slug: "bitta-religious-cultural-jharkhand",
    name_english: "Bitta",
    name_sanskrit: "वितस्ति (Vitasti) — cognate",
    name_hindi: "बित्ता",
    local_names: ["बित्ता (Bitta)"],
    meaning: "Measuring sacred thread, garlands and ceremonial cloth length in tribal and Sadan community rituals",
    category: "length",
    sector: "religious-cultural",
    origin: "Jharkhand",
    historical_context: "Hand-span length unit for ritual items",
    modern_equivalent: "~22.9 cm",
    conversion_formula: "2 Bitta = 1 Hath",
    states: ["Jharkhand"],
    used_in: ["Measuring sacred thread, garlands and ceremonial cloth length", "Religious & Cultural"],
    references: ["https://www.indiamike.com/india/chai-and-chat-f73/weights-and-measures-t223614/"],
    tags: ["jharkhand", "religious-cultural", "bitta"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-relig-5",
    slug: "hath-religious-cultural-jharkhand",
    name_english: "Hath",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "हाथ",
    local_names: ["हाँथ (Hanth)"],
    meaning: "Marking out the boundary of a sacred grove (Sarna Sthal/Jaher) or ceremonial platform",
    category: "length",
    sector: "religious-cultural",
    origin: "Jharkhand",
    historical_context: "Cubit length for demarcating Sarna Sthal (sacred grove)",
    modern_equivalent: "~0.457 m",
    conversion_formula: "8 Girah = 1 Hath",
    states: ["Jharkhand"],
    used_in: ["Marking out the boundary of a sacred grove (Sarna Sthal/Jaher) or ceremonial platform", "Religious & Cultural"],
    references: ["https://handwiki.org/wiki/Indian_units_of_measurement"],
    tags: ["jharkhand", "religious-cultural", "hath"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-relig-6",
    slug: "tola-religious-cultural-jharkhand",
    name_english: "Tola",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "तोला",
    local_names: ["तोला (Tola)"],
    meaning: "Gold/silver donated for deity ornamentation and ancestor-worship (Bonga) offerings",
    category: "weight",
    sector: "religious-cultural",
    origin: "Jharkhand",
    historical_context: "Precious metal weight unit for deity and Bonga offerings",
    modern_equivalent: "~11.66 g",
    conversion_formula: "12 Maas = 1 Tola",
    states: ["Jharkhand"],
    used_in: ["Gold/silver donated for deity ornamentation and ancestor-worship offerings", "Religious & Cultural"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "religious-cultural", "tola"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-relig-7",
    slug: "kos-religious-cultural-jharkhand",
    name_english: "Kos",
    name_sanskrit: "क्रोश (Krosha) — cognate",
    name_hindi: "कोस",
    local_names: ["कोस (Kos)"],
    meaning: "Traditional distance measure for pilgrimage to sacred sites such as Baidyanath Dham (Deoghar) and Parasnath Hill",
    category: "length",
    sector: "religious-cultural",
    origin: "Jharkhand",
    historical_context: "Traditional distance unit for pilgrimage to Baidyanath Dham & Parasnath Hill",
    modern_equivalent: "~2.93 km",
    conversion_formula: "60 Rasari = 1 Kos",
    states: ["Jharkhand"],
    used_in: ["Traditional distance measure for pilgrimage to sacred sites such as Baidyanath Dham", "Religious & Cultural"],
    references: ["https://en.wikipedia.org/wiki/Kos_(unit)"],
    tags: ["jharkhand", "religious-cultural", "kos"],
    created_at: "2024-01-01",
  },

  // ─── 9. Trade & Commerce ──────────────────────────────────────────────────
  {
    id: "jh-tc-1",
    slug: "ratti-trade-commerce-jharkhand",
    name_english: "Ratti",
    name_sanskrit: "रत्ति (Ratti / Raktika)",
    name_hindi: "रत्ती",
    local_names: ["रत्ती (Ratti)"],
    meaning: "Smallest goldsmith's & grocer's reference weight, still used colloquially",
    category: "weight",
    sector: "trade-commerce",
    origin: "Jharkhand",
    historical_context: "Base / smallest unit",
    modern_equivalent: "~0.12 g",
    conversion_formula: "Base / smallest unit",
    states: ["Jharkhand"],
    used_in: ["Smallest goldsmith's & grocer's reference weight, still used colloquially", "Trade & Commerce"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "trade-commerce", "ratti"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-tc-2",
    slug: "maas-masha-trade-commerce-jharkhand",
    name_english: "Maas (Masha)",
    name_sanskrit: "माष (Māṣa)",
    name_hindi: "मास",
    local_names: ["मास (Maas)"],
    meaning: "Fine retail weighing of spices, grain, medicine in village shops",
    category: "weight",
    sector: "trade-commerce",
    origin: "Jharkhand",
    historical_context: "Fine retail weight",
    modern_equivalent: "~0.97 g",
    conversion_formula: "8 Ratti = 1 Maas",
    states: ["Jharkhand"],
    used_in: ["Fine retail weighing of spices, grain, medicine in village shops", "Trade & Commerce"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "trade-commerce", "maas"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-tc-3",
    slug: "tola-trade-commerce-jharkhand",
    name_english: "Tola",
    name_sanskrit: "तोला (Tola)",
    name_hindi: "तोला",
    local_names: ["तोला (Tola)"],
    meaning: "Standard shopkeeper's weight; also the fixed 1833 British-Indian silver-rupee weight standard",
    category: "weight",
    sector: "trade-commerce",
    origin: "Jharkhand",
    historical_context: "Fixed 1833 British-Indian silver-rupee weight standard",
    modern_equivalent: "~11.66 g",
    conversion_formula: "12 Maas = 1 Tola",
    states: ["Jharkhand"],
    used_in: ["Standard shopkeeper's weight; fixed 1833 British-Indian silver-rupee weight standard", "Trade & Commerce"],
    references: ["https://www.researchgate.net/publication/316599701_MEASUREMENT_UNITS_OF_LENGTH_MASS_AND_TIME_IN_INDIA_THROUGH_THE_AGES"],
    tags: ["jharkhand", "trade-commerce", "tola"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-tc-4",
    slug: "chhatank-chhaatank-trade-commerce-jharkhand",
    name_english: "Chhatank (Chhaatank)",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "छटांक",
    local_names: ["छटाँक (Chhataank)"],
    meaning: "Small retail trade of spices, grain, jaggery at village haats (weekly markets)",
    category: "weight",
    sector: "trade-commerce",
    origin: "Jharkhand",
    historical_context: "Small retail trade weight at village haats",
    modern_equivalent: "~58.3 g",
    conversion_formula: "5 Tola = 1 Chhatank",
    states: ["Jharkhand"],
    used_in: ["Small retail trade of spices, grain, jaggery at village haats (weekly markets)", "Trade & Commerce"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "trade-commerce", "chhatank"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-tc-5",
    slug: "ser-seer-trade-commerce-jharkhand",
    name_english: "Ser (Seer)",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "सेर",
    local_names: ["सेर (Ser)"],
    meaning: "Standard bazaar weight for grain, oil, and general provisions across Chota Nagpur markets",
    category: "weight",
    sector: "trade-commerce",
    origin: "Jharkhand",
    historical_context: "Standard bazaar weight across Chota Nagpur markets",
    modern_equivalent: "~933 g (~0.93 kg)",
    conversion_formula: "16 Chhatank = 1 Ser",
    states: ["Jharkhand"],
    used_in: ["Standard bazaar weight for grain, oil, and general provisions across Chota Nagpur markets", "Trade & Commerce"],
    references: ["https://en.wikipedia.org/wiki/Seer_(unit)"],
    tags: ["jharkhand", "trade-commerce", "ser"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-tc-6",
    slug: "paseri-trade-commerce-jharkhand",
    name_english: "Paseri",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "पसेरी",
    local_names: ["पसेरी (Paseri)"],
    meaning: "Wholesale trade of vegetables and grain at haats",
    category: "weight",
    sector: "trade-commerce",
    origin: "Jharkhand",
    historical_context: "5-Ser wholesale weight at haats",
    modern_equivalent: "~4.67 kg",
    conversion_formula: "5 Ser = 1 Paseri",
    states: ["Jharkhand"],
    used_in: ["Wholesale trade of vegetables and grain at haats", "Trade & Commerce"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "trade-commerce", "paseri"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-tc-7",
    slug: "dhaara-trade-commerce-jharkhand",
    name_english: "Dhaara",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "धारा",
    local_names: ["धारा (Dhaara)"],
    meaning: "Mid-scale bulk trade measure for grain and produce",
    category: "weight",
    sector: "trade-commerce",
    origin: "Jharkhand",
    historical_context: "10-Ser mid-scale bulk trade measure",
    modern_equivalent: "~9.33 kg",
    conversion_formula: "10 Ser = 1 Dhaara",
    states: ["Jharkhand"],
    used_in: ["Mid-scale bulk trade measure for grain and produce", "Trade & Commerce"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "trade-commerce", "dhaara"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-tc-8",
    slug: "man-maund-trade-commerce-jharkhand",
    name_english: "Man (Maund)",
    name_sanskrit: "मन (Maṇa) — Arabic loan 'mann', pan-Indian usage",
    name_hindi: "मन",
    local_names: ["मन (Man)"],
    meaning: "Large-scale grain, lac, and mahua trade at district mandis; historically the load a porter or pack-animal could carry",
    category: "weight",
    sector: "trade-commerce",
    origin: "Jharkhand",
    historical_context: "Standard 40-Ser mandi bulk trade unit",
    modern_equivalent: "~37.32 kg",
    conversion_formula: "40 Ser = 1 Man",
    states: ["Jharkhand"],
    used_in: ["Large-scale grain, lac, and mahua trade at district mandis", "Trade & Commerce"],
    references: ["https://en.wikipedia.org/wiki/Maund"],
    tags: ["jharkhand", "trade-commerce", "man"],
    created_at: "2024-01-01",
  },

  // ─── 10. Textile & Handloom ──────────────────────────────────────────────
  {
    id: "jh-tex-1",
    slug: "girah-textile-handloom-jharkhand",
    name_english: "Girah",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "गिरह",
    local_names: ["गिरह (Girah)"],
    meaning: "Fine cloth-measurement and loom calibration for Tussar weaving",
    category: "length",
    sector: "textile-handloom",
    origin: "Jharkhand",
    historical_context: "1/16 Gaj (width of forefinger)",
    modern_equivalent: "~5.7 cm (2¼ in)",
    conversion_formula: "1/16 Gaj = 1 Girah",
    states: ["Jharkhand"],
    used_in: ["Fine cloth-measurement and loom calibration for Tussar weaving", "Textile & Handloom"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "textile-handloom", "girah"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-tex-2",
    slug: "hath-hanth-textile-handloom-jharkhand",
    name_english: "Hath (Hanth)",
    name_sanskrit: "हस्त (Hasta) — cognate",
    name_hindi: "हाथ",
    local_names: ["हाँथ (Hanth)"],
    meaning: "Measuring woven cloth length directly on the pit-loom",
    category: "length",
    sector: "textile-handloom",
    origin: "Jharkhand",
    historical_context: "24 Angul = 1 Hath",
    modern_equivalent: "~0.406 m (16 in)",
    conversion_formula: "24 Angul = 1 Hath",
    states: ["Jharkhand"],
    used_in: ["Measuring woven cloth length directly on the pit-loom", "Textile & Handloom"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "textile-handloom", "hath"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-tex-3",
    slug: "gaj-deg-textile-handloom-jharkhand",
    name_english: "Gaj (Deg)",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "गज़",
    local_names: ["गज (Gaj)"],
    meaning: "Standard trade yard for selling Tussar and cotton handloom fabric by length",
    category: "length",
    sector: "textile-handloom",
    origin: "Jharkhand",
    historical_context: "2 Hath = 1 Gaj",
    modern_equivalent: "~0.914 m (36 in)",
    conversion_formula: "2 Hath = 1 Gaj",
    states: ["Jharkhand"],
    used_in: ["Standard trade yard for selling Tussar and cotton handloom fabric by length", "Textile & Handloom"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "textile-handloom", "gaj"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-tex-4",
    slug: "laggi-baans-textile-handloom-jharkhand",
    name_english: "Laggi (Baans)",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "लग्गी",
    local_names: ["लग्गी (Laggi)"],
    meaning: "Measuring full bolts of handloom cloth off the loom",
    category: "length",
    sector: "textile-handloom",
    origin: "Jharkhand",
    historical_context: "3 Gaj = 1 Laggi",
    modern_equivalent: "~2.74 m",
    conversion_formula: "3 Gaj = 1 Laggi",
    states: ["Jharkhand"],
    used_in: ["Measuring full bolts of handloom cloth off the loom", "Textile & Handloom"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "textile-handloom", "laggi"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-tex-5",
    slug: "ser-raw-silk-weight-textile-handloom-jharkhand",
    name_english: "Ser (raw silk weight)",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "सेर",
    local_names: ["सेर (Ser)"],
    meaning: "Weighing raw Tussar cocoons and hand-spun Ghicha yarn by Santhal/Munda/Oraon weaver families",
    category: "weight",
    sector: "textile-handloom",
    origin: "Jharkhand",
    historical_context: "16 Chhatank = 1 Ser",
    modern_equivalent: "~933 g",
    conversion_formula: "16 Chhatank = 1 Ser",
    states: ["Jharkhand"],
    used_in: ["Weighing raw Tussar cocoons and hand-spun Ghicha yarn by Santhal/Munda/Oraon weaver families", "Textile & Handloom"],
    references: ["https://www.savehandloom.org/jharkhands-gi-certified-handloom-cluster-tussar-the-tribal-silk-of-the-forests/"],
    tags: ["jharkhand", "textile-handloom", "ser", "tussar", "ghicha"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-tex-6",
    slug: "tola-textile-handloom-jharkhand",
    name_english: "Tola",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "तोला",
    local_names: ["तोला (Tola)"],
    meaning: "Weighing dye and zari thread in fine Tussar-silk saree borders",
    category: "weight",
    sector: "textile-handloom",
    origin: "Jharkhand",
    historical_context: "12 Maas = 1 Tola",
    modern_equivalent: "~11.66 g",
    conversion_formula: "12 Maas = 1 Tola",
    states: ["Jharkhand"],
    used_in: ["Weighing dye and zari thread in fine Tussar-silk saree borders", "Textile & Handloom"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "textile-handloom", "tola"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-tex-7",
    slug: "tussar-saree-traditional-length-textile-handloom-jharkhand",
    name_english: "Tussar Saree (traditional length)",
    name_sanskrit: "N/A",
    name_hindi: "तसर साड़ी",
    local_names: ["तसर साड़ी (Tasar Saree)"],
    meaning: "Traditional Tussar & Tussar-Ghicha handloom saree woven on pit/frame looms in Jharkhand's tribal belt",
    category: "length",
    sector: "textile-handloom",
    origin: "Jharkhand",
    historical_context: "Standard GI-registered Bhagaiya-cluster dimension",
    modern_equivalent: "6.5 m length × 45 in (114 cm) width",
    conversion_formula: "Standard GI-registered Bhagaiya-cluster dimension",
    states: ["Jharkhand"],
    used_in: ["Traditional Tussar & Tussar-Ghicha handloom saree woven on pit/frame looms in Jharkhand's tribal belt", "Textile & Handloom"],
    references: ["https://handlooms.nic.in/assets/img/Weavers%20Database/Jharkhand637322650354857310.pdf"],
    tags: ["jharkhand", "textile-handloom", "tussar-saree", "bhagaiya"],
    created_at: "2024-01-01",
  },

  // ─── 11. Medicine (Ayurveda) ─────────────────────────────────────────────
  {
    id: "jh-med-1",
    slug: "ratti-medicine-ayurveda-jharkhand",
    name_english: "Ratti",
    name_sanskrit: "रत्ति (Ratti)",
    name_hindi: "रत्ती",
    local_names: ["रत्ती (Ratti)"],
    meaning: "Smallest herbal seed-weight reference used by traditional Vaidyas/Kavirajas for dosing",
    category: "weight",
    sector: "medicine",
    origin: "Jharkhand",
    historical_context: "Base / smallest unit",
    modern_equivalent: "~0.12 g",
    conversion_formula: "Base / smallest unit",
    states: ["Jharkhand"],
    used_in: ["Smallest herbal seed-weight reference used by traditional Vaidyas/Kavirajas for dosing", "Medicine (Ayurveda)"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "medicine", "ratti"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-med-2",
    slug: "maas-masha-medicine-ayurveda-jharkhand",
    name_english: "Maas (Masha)",
    name_sanskrit: "माष (Māṣa)",
    name_hindi: "मास",
    local_names: ["मास (Maas)"],
    meaning: "Micro-dosage of herbal churna (powder) in tribal herbal medicine (locally termed Hodopathy)",
    category: "weight",
    sector: "medicine",
    origin: "Jharkhand",
    historical_context: "8 Ratti = 1 Maas",
    modern_equivalent: "~0.97 g",
    conversion_formula: "8 Ratti = 1 Maas",
    states: ["Jharkhand"],
    used_in: ["Micro-dosage of herbal churna in tribal herbal medicine (Hodopathy)", "Medicine (Ayurveda)"],
    references: ["https://www.researchgate.net/publication/303231067_ETHNO-MEDICINAL_PLANTS_OF_JHARKHAND_INDIA"],
    tags: ["jharkhand", "medicine", "maas", "hodopathy"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-med-3",
    slug: "tola-medicine-ayurveda-jharkhand",
    name_english: "Tola",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "तोला",
    local_names: ["तोला (Tola)"],
    meaning: "Standard dose of dried root/bark powder measured by Vaidyas and Ojhas of Munda, Oraon and Santhal communities",
    category: "weight",
    sector: "medicine",
    origin: "Jharkhand",
    historical_context: "12 Maas = 1 Tola",
    modern_equivalent: "~11.66 g",
    conversion_formula: "12 Maas = 1 Tola",
    states: ["Jharkhand"],
    used_in: ["Standard dose of dried root/bark powder measured by Vaidyas and Ojhas", "Medicine (Ayurveda)"],
    references: ["https://www.academia.edu/101382386/Medicinal_Plants_of_Jharkhand"],
    tags: ["jharkhand", "medicine", "tola"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-med-4",
    slug: "chhatank-medicine-ayurveda-jharkhand",
    name_english: "Chhatank",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "छटांक",
    local_names: ["छटाँक (Chhataank)"],
    meaning: "Weighing bundles of bark, root or leaf collected for decoctions",
    category: "weight",
    sector: "medicine",
    origin: "Jharkhand",
    historical_context: "5 Tola = 1 Chhatank",
    modern_equivalent: "~58.3 g",
    conversion_formula: "5 Tola = 1 Chhatank",
    states: ["Jharkhand"],
    used_in: ["Weighing bundles of bark, root or leaf collected for decoctions", "Medicine (Ayurveda)"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "medicine", "chhatank"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-med-5",
    slug: "ser-medicine-ayurveda-jharkhand",
    name_english: "Ser",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "सेर",
    local_names: ["सेर (Ser)"],
    meaning: "Bulk preparation of herbal decoctions (kadha) for community/village-level treatment",
    category: "weight",
    sector: "medicine",
    origin: "Jharkhand",
    historical_context: "16 Chhatank = 1 Ser",
    modern_equivalent: "~933 g",
    conversion_formula: "16 Chhatank = 1 Ser",
    states: ["Jharkhand"],
    used_in: ["Bulk preparation of herbal decoctions (kadha) for community/village-level treatment", "Medicine (Ayurveda)"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "medicine", "ser"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-med-6",
    slug: "girah-medicine-ayurveda-jharkhand",
    name_english: "Girah",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "गिरह",
    local_names: ["गिरह (Girah)"],
    meaning: "Measuring medicinal creeper and root cuttings before drying",
    category: "length",
    sector: "medicine",
    origin: "Jharkhand",
    historical_context: "1/16 Gaj",
    modern_equivalent: "~5.7 cm",
    conversion_formula: "1/16 Gaj = 1 Girah",
    states: ["Jharkhand"],
    used_in: ["Measuring medicinal creeper and root cuttings before drying", "Medicine (Ayurveda)"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "medicine", "girah"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-med-7",
    slug: "bitta-medicine-ayurveda-jharkhand",
    name_english: "Bitta",
    name_sanskrit: "वितस्ति (Vitasti) — cognate",
    name_hindi: "बिस्ता",
    local_names: ["बिस्ता (Bitta)"],
    meaning: "Traditional body-span measure referenced by regional healers when gauging dosage relative to patient size",
    category: "length",
    sector: "medicine",
    origin: "Jharkhand",
    historical_context: "2 Bitta = 1 Hath",
    modern_equivalent: "~22.9 cm (hand-span)",
    conversion_formula: "2 Bitta = 1 Hath",
    states: ["Jharkhand"],
    used_in: ["Traditional body-span measure referenced by regional healers", "Medicine (Ayurveda)"],
    references: ["https://www.indiamike.com/india/chai-and-chat-f73/weights-and-measures-t223614/"],
    tags: ["jharkhand", "medicine", "bitta"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-med-8",
    slug: "hath-medicine-ayurveda-jharkhand",
    name_english: "Hath",
    name_sanskrit: "हस्त (Hasta) — cognate",
    name_hindi: "हाथ",
    local_names: ["हाँथ (Hanth)"],
    meaning: "Reference measure for body proportion in traditional diagnosis",
    category: "length",
    sector: "medicine",
    origin: "Jharkhand",
    historical_context: "24 Angul = 1 Hath",
    modern_equivalent: "~0.406 m",
    conversion_formula: "24 Angul = 1 Hath",
    states: ["Jharkhand"],
    used_in: ["Reference measure for body proportion in traditional diagnosis", "Medicine (Ayurveda)"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "medicine", "hath"],
    created_at: "2024-01-01",
  },

  // ─── 12. Construction & Architecture ─────────────────────────────────────
  {
    id: "jh-arch-1",
    slug: "angul-anguli-construction-architecture-jharkhand",
    name_english: "Angul (Anguli)",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "अंगुल",
    local_names: ["अंगुल (Angul)"],
    meaning: "Fine masonry calibration in traditional mud (kuchcha) and brick construction",
    category: "length",
    sector: "architecture",
    origin: "Jharkhand",
    historical_context: "Width of 3 fingers (fraction of Girah); Base unit",
    modern_equivalent: "Width of 3 fingers (fraction of Girah)",
    conversion_formula: "Base unit",
    states: ["Jharkhand"],
    used_in: ["Fine masonry calibration in traditional mud (kuchcha) and brick construction", "Construction & Architecture"],
    references: ["https://handwiki.org/wiki/Indian_units_of_measurement"],
    tags: ["jharkhand", "architecture", "angul"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-arch-2",
    slug: "girah-construction-architecture-jharkhand",
    name_english: "Girah",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "गिरह",
    local_names: ["गिरह (Girah)"],
    meaning: "Door and window frame proportioning in traditional houses",
    category: "length",
    sector: "architecture",
    origin: "Jharkhand",
    historical_context: "Anguli (3-finger width) = 1 Girah",
    modern_equivalent: "~5.7 cm",
    conversion_formula: "Anguli (3-finger width) = 1 Girah",
    states: ["Jharkhand"],
    used_in: ["Door and window frame proportioning in traditional houses", "Construction & Architecture"],
    references: ["https://handwiki.org/wiki/Indian_units_of_measurement"],
    tags: ["jharkhand", "architecture", "girah"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-arch-3",
    slug: "hath-construction-architecture-jharkhand",
    name_english: "Hath",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "हाथ",
    local_names: ["हाँथ (Hanth)"],
    meaning: "Wall height and room width in traditional tribal dwellings (Munda 'Ora', Santhal 'Oda' houses)",
    category: "length",
    sector: "architecture",
    origin: "Jharkhand",
    historical_context: "8 Girah = 1 Hath",
    modern_equivalent: "~0.457 m (18 in)",
    conversion_formula: "8 Girah = 1 Hath",
    states: ["Jharkhand"],
    used_in: ["Wall height and room width in traditional tribal dwellings (Munda 'Ora', Santhal 'Oda' houses)", "Construction & Architecture"],
    references: ["https://handwiki.org/wiki/Indian_units_of_measurement"],
    tags: ["jharkhand", "architecture", "hath"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-arch-4",
    slug: "kathi-construction-architecture-jharkhand",
    name_english: "Kathi",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "काठी",
    local_names: ["काठी (Kathi)"],
    meaning: "Roof-beam and structural-span measurement",
    category: "length",
    sector: "architecture",
    origin: "Jharkhand",
    historical_context: "5½ Hath = 1 Kathi",
    modern_equivalent: "~2.67 m",
    conversion_formula: "5½ Hath = 1 Kathi",
    states: ["Jharkhand"],
    used_in: ["Roof-beam and structural-span measurement", "Construction & Architecture"],
    references: ["https://handwiki.org/wiki/Indian_units_of_measurement"],
    tags: ["jharkhand", "architecture", "kathi"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-arch-5",
    slug: "gaz-construction-architecture-jharkhand",
    name_english: "Gaz",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "गज़",
    local_names: ["गज (Gaj)"],
    meaning: "Builder's standard yard for courtyard and plinth measurement",
    category: "length",
    sector: "architecture",
    origin: "Jharkhand",
    historical_context: "2 Hath = 1 Gaz",
    modern_equivalent: "~0.914 m",
    conversion_formula: "2 Hath = 1 Gaz",
    states: ["Jharkhand"],
    used_in: ["Builder's standard yard for courtyard and plinth measurement", "Construction & Architecture"],
    references: ["https://handwiki.org/wiki/Indian_units_of_measurement"],
    tags: ["jharkhand", "architecture", "gaz"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-arch-6",
    slug: "karam-construction-architecture-jharkhand",
    name_english: "Karam",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "करम",
    local_names: ["करम (Karam)"],
    meaning: "Courtyard and plinth-boundary measurement",
    category: "length",
    sector: "architecture",
    origin: "Jharkhand",
    historical_context: "3 Gaz = 2 Karam",
    modern_equivalent: "~0.686 m (approx.)",
    conversion_formula: "3 Gaz = 2 Karam",
    states: ["Jharkhand"],
    used_in: ["Courtyard and plinth-boundary measurement", "Construction & Architecture"],
    references: ["https://handwiki.org/wiki/Indian_units_of_measurement"],
    tags: ["jharkhand", "architecture", "karam"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-arch-7",
    slug: "kan-construction-architecture-jharkhand",
    name_english: "Kan",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "कन",
    local_names: ["कन (Kan)"],
    meaning: "Foundation and boundary-pole marking; base of the Marla/Kanal area system",
    category: "length",
    sector: "architecture",
    origin: "Jharkhand",
    historical_context: "3 Karam = 1 Kan",
    modern_equivalent: "~2.06 m (approx.)",
    conversion_formula: "3 Karam = 1 Kan",
    states: ["Jharkhand"],
    used_in: ["Foundation and boundary-pole marking; base of the Marla/Kanal area system", "Construction & Architecture"],
    references: ["https://handwiki.org/wiki/Indian_units_of_measurement"],
    tags: ["jharkhand", "architecture", "kan"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-arch-8",
    slug: "laggi-baans-construction-architecture-jharkhand",
    name_english: "Laggi (Baans)",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "लग्गी",
    local_names: ["तग्गी (Laggi)"],
    meaning: "Bamboo measuring pole used in traditional Adivasi mud-and-bamboo house construction",
    category: "length",
    sector: "architecture",
    origin: "Jharkhand",
    historical_context: "3 Gaj = 1 Laggi",
    modern_equivalent: "~2.74 m",
    conversion_formula: "3 Gaj = 1 Laggi",
    states: ["Jharkhand"],
    used_in: ["Bamboo measuring pole used in traditional Adivasi mud-and-bamboo house construction", "Construction & Architecture"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "architecture", "laggi"],
    created_at: "2024-01-01",
  },

  // ─── 13. Transportation & Distance ──────────────────────────────────────
  {
    id: "jh-dist-1",
    slug: "girah-transportation-distance-jharkhand",
    name_english: "Girah",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "गिरह",
    local_names: ["गिरह (Girah)"],
    meaning: "Short-range path and field-boundary reference",
    category: "length",
    sector: "transportation-distance",
    origin: "Jharkhand",
    historical_context: "Base unit",
    modern_equivalent: "~5.7 cm",
    conversion_formula: "Base unit",
    states: ["Jharkhand"],
    used_in: ["Short-range path and field-boundary reference", "Transportation & Distance"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "transportation-distance", "girah"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-dist-2",
    slug: "hath-transportation-distance-jharkhand",
    name_english: "Hath",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "हाथ",
    local_names: ["हाँथ (Hanth)"],
    meaning: "Footpath width measurement in villages",
    category: "length",
    sector: "transportation-distance",
    origin: "Jharkhand",
    historical_context: "8 Girah = 1 Hath",
    modern_equivalent: "~0.457 m",
    conversion_formula: "8 Girah = 1 Hath",
    states: ["Jharkhand"],
    used_in: ["Footpath width measurement in villages", "Transportation & Distance"],
    references: ["https://handwiki.org/wiki/Indian_units_of_measurement"],
    tags: ["jharkhand", "transportation-distance", "hath"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-dist-3",
    slug: "gaz-transportation-distance-jharkhand",
    name_english: "Gaz",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "गज़",
    local_names: ["गज (Gaj)"],
    meaning: "Road and cart-track width measurement",
    category: "length",
    sector: "transportation-distance",
    origin: "Jharkhand",
    historical_context: "2 Hath = 1 Gaz",
    modern_equivalent: "~0.914 m",
    conversion_formula: "2 Hath = 1 Gaz",
    states: ["Jharkhand"],
    used_in: ["Road and cart-track width measurement", "Transportation & Distance"],
    references: ["https://handwiki.org/wiki/Indian_units_of_measurement"],
    tags: ["jharkhand", "transportation-distance", "gaz"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-dist-4",
    slug: "laggi-transportation-distance-jharkhand",
    name_english: "Laggi",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "लग्गी",
    local_names: ["तग्गी (Laggi)"],
    meaning: "Forest-trail and field-path distance marking",
    category: "length",
    sector: "transportation-distance",
    origin: "Jharkhand",
    historical_context: "3 Gaj = 1 Laggi",
    modern_equivalent: "~2.74 m",
    conversion_formula: "3 Gaj = 1 Laggi",
    states: ["Jharkhand"],
    used_in: ["Forest-trail and field-path distance marking", "Transportation & Distance"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "transportation-distance", "laggi"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-dist-5",
    slug: "rasari-transportation-distance-jharkhand",
    name_english: "Rasari",
    name_sanskrit: "— (Persian/Arabic/regional origin, no Sanskrit equivalent)",
    name_hindi: "रस्सी / रसरी",
    local_names: ["रस्सड़ी (Rasari)"],
    meaning: "Long rope-measure for forest and agricultural-field paths, documented in South-West Shahabad usage bordering the Jharkhand region",
    category: "length",
    sector: "transportation-distance",
    origin: "Jharkhand",
    historical_context: "20 Laggi = 1 Rasari",
    modern_equivalent: "~48.77 m",
    conversion_formula: "20 Laggi = 1 Rasari",
    states: ["Jharkhand"],
    used_in: ["Long rope-measure for forest and agricultural-field paths", "Transportation & Distance"],
    references: ["https://en.wikipedia.org/wiki/Bhojpuri_units_of_measurement"],
    tags: ["jharkhand", "transportation-distance", "rasari"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-dist-6",
    slug: "kos-transportation-distance-jharkhand",
    name_english: "Kos",
    name_sanskrit: "क्रोश (Krosha) — cognate",
    name_hindi: "कोस",
    local_names: ["कोस (Kos)"],
    meaning: "Classical Indian travel-distance unit; historically marked by Kos Minars along the Grand Trunk Road through the Chota Nagpur region",
    category: "length",
    sector: "transportation-distance",
    origin: "Jharkhand",
    historical_context: "60 Rasari = 1 Kos",
    modern_equivalent: "~2.93 km (varies ~2.9–3.2 km by region)",
    conversion_formula: "60 Rasari = 1 Kos",
    states: ["Jharkhand"],
    used_in: ["Classical Indian travel-distance unit; historically marked by Kos Minars", "Transportation & Distance"],
    references: ["https://en.wikipedia.org/wiki/Kos_(unit)"],
    tags: ["jharkhand", "transportation-distance", "kos"],
    created_at: "2024-01-01",
  },
  {
    id: "jh-dist-7",
    slug: "yojana-transportation-distance-jharkhand",
    name_english: "Yojana",
    name_sanskrit: "योजन (Yojana)",
    name_hindi: "योजन",
    local_names: ["योजन (Yojan)"],
    meaning: "Pilgrimage and army-march distance referenced in classical Sanskrit/Puranic texts across the wider Magadha–Jharkhand cultural belt",
    category: "length",
    sector: "transportation-distance",
    origin: "Jharkhand",
    historical_context: "4 Kos (classical ratio, varies by era)",
    modern_equivalent: "~12–14.5 km",
    conversion_formula: "4 Kos = 1 Yojana",
    states: ["Jharkhand"],
    used_in: ["Pilgrimage and army-march distance referenced in classical texts", "Transportation & Distance"],
    references: ["https://en.wikipedia.org/wiki/Yojana"],
    tags: ["jharkhand", "transportation-distance", "yojana"],
    created_at: "2024-01-01",
  },
];
