import { Measurement } from "@/types";

export const KARNATAKA_MEASUREMENTS: Measurement[] = [
  // Land Measurement
  {
    id: "ka-land-1",
    slug: "ka-ankanam",
    name_english: "Ankanam",
    name_hindi: "ಅಂಕಣ", // Kannada script used as per local language concept
    local_names: ["ಅಂಕಣ (Ankanam)"],
    meaning: "Traditional plot measurement.",
    category: "area",
    sector: "land-measurement",
    modern_equivalent: "≈72 sq.ft (varies)",
    conversion_formula: "Regional multiples vary",
    states: ["Karnataka"],
    used_in: ["House construction plots"],
    references: ["South Indian measurement traditions"],
  },
  {
    id: "ka-land-2",
    slug: "ka-gunta",
    name_english: "Guntha / Gunta",
    name_hindi: "ಗುಂಟೆ",
    local_names: ["ಗುಂಟೆ (Gunta)"],
    meaning: "Main agricultural land unit.",
    category: "area",
    sector: "land-measurement",
    modern_equivalent: "1,089 sq.ft",
    conversion_formula: "40 Guntha = 1 Acre",
    states: ["Karnataka"],
    used_in: ["Agricultural land unit"],
    references: ["Karnataka Revenue records"],
  },
  {
    id: "ka-land-3",
    slug: "ka-kani",
    name_english: "Kani (Regional)",
    name_hindi: "ಕಾಣಿ",
    local_names: ["ಕಾಣಿ (Kani)"],
    meaning: "Traditional South Indian agricultural land unit.",
    category: "area",
    sector: "land-measurement",
    modern_equivalent: "Approx. 1-1.3 acres",
    conversion_formula: "Regional conversion varies",
    states: ["Karnataka"],
    used_in: ["Agricultural holdings"],
    references: ["South Indian land traditions"],
  },
  {
    id: "ka-land-4",
    slug: "ka-cent",
    name_english: "Cent",
    name_hindi: "ಸೆಂಟ್",
    local_names: ["ಸೆಂಟ್ (Cent)"],
    meaning: "Colonial-era unit adopted into South India.",
    category: "area",
    sector: "land-measurement",
    modern_equivalent: "435.6 sq.ft",
    conversion_formula: "100 Cent = 1 Acre",
    states: ["Karnataka"],
    used_in: ["Small land transactions"],
    references: ["Land conversion records"],
  },

  // Transportation & Distance
  {
    id: "ka-trans-1",
    slug: "ka-aratni",
    name_english: "Hasta / Aratni",
    name_hindi: "ಮೊಳ",
    name_sanskrit: "Hasta",
    local_names: ["ಮೊಳ (Mola)"],
    meaning: "Length from elbow to fingertip.",
    category: "length",
    sector: "transportation-distance",
    modern_equivalent: "≈45–48 cm",
    conversion_formula: "2 Vitasti = 1 Hasta",
    states: ["Karnataka"],
    used_in: ["Architecture, construction and surveying"],
    references: ["Vastu and traditional texts"],
  },
  {
    id: "ka-trans-2",
    slug: "ka-danda",
    name_english: "Danda",
    name_hindi: "ದಂಡ",
    name_sanskrit: "Daṇḍa",
    local_names: ["ದಂಡ (Danda)"],
    meaning: "Rod-based distance measure unit.",
    category: "length",
    sector: "transportation-distance",
    modern_equivalent: "≈1.8–2 m",
    conversion_formula: "1 Danda = 4 Hasta",
    states: ["Karnataka"],
    used_in: ["Surveying and measuring fields/routes"],
    references: ["Arthashastra reference"],
  },
  {
    id: "ka-trans-3",
    slug: "ka-rajju",
    name_english: "Rajju",
    name_hindi: "ರಜ್ಜು",
    name_sanskrit: "Rajju",
    local_names: ["ರಜ್ಜು (Rajju)"],
    meaning: "Rope-based surveying measure.",
    category: "length",
    sector: "transportation-distance",
    modern_equivalent: "Variable",
    conversion_formula: "Made using multiple Danda lengths",
    states: ["Karnataka"],
    used_in: ["Measuring larger fields and roads"],
    references: ["Ancient Indian surveying methods"],
  },
  {
    id: "ka-trans-4",
    slug: "ka-yojana",
    name_english: "Yojana",
    name_hindi: "ಯೋಜನ",
    name_sanskrit: "Yojanā",
    local_names: ["ಯೋಜನ (Yojana)"],
    meaning: "Largest classical Indian distance unit.",
    category: "length",
    sector: "transportation-distance",
    modern_equivalent: "≈12–15 km (varies)",
    conversion_formula: "1 Yojana = 4 Krosa",
    states: ["Karnataka"],
    used_in: ["Large travel distances and geographical descriptions"],
    references: ["Puranic and classical literature"],
  },

  // Seed & Crop (Agriculture)
  {
    id: "ka-agri-1",
    slug: "ka-mana",
    name_english: "Mana",
    name_hindi: "ಮಾನ",
    local_names: ["ಮಾನ (Mana)"],
    meaning: "Traditional unit of volume used for measuring grain.",
    category: "volume",
    sector: "agriculture",
    modern_equivalent: "≈2 to 4 kg (varies)",
    conversion_formula: "8 Mana = 1 Kula",
    states: ["Karnataka"],
    used_in: ["Grain measurement"],
    references: ["Deccan records"],
  },

  // Trade & Commerce
  {
    id: "ka-trade-1",
    slug: "ka-seer",
    name_english: "Seeru",
    name_hindi: "ಸೇರು",
    local_names: ["ಸೇರು (Seeru)"],
    meaning: "Standard market measure.",
    category: "weight",
    sector: "trade-commerce",
    modern_equivalent: "≈0.933 kg",
    conversion_formula: "Base unit",
    states: ["Karnataka"],
    used_in: ["Market trade"],
    references: ["Karnataka Gazetteers"],
  },

  // Livestock & Dairy
  {
    id: "ka-dairy-1",
    slug: "ka-padi-dairy",
    name_english: "Padi",
    name_hindi: "ಪಡಿ",
    name_sanskrit: "Pāṭī / Pātra",
    local_names: ["ಪಡಿ (Padi)"],
    meaning: "Traditional vessel measure used in households and dairy.",
    category: "volume",
    sector: "livestock-dairy",
    modern_equivalent: "≈1.5–2 litres (regional variation)",
    conversion_formula: "Multiple small vessel measures make 1 Padi",
    states: ["Karnataka", "Tamil Nadu"],
    used_in: ["Measuring milk and grains"],
    references: ["Local measurement practices"],
  },
  {
    id: "ka-dairy-2",
    slug: "ka-marakkal-dairy",
    name_english: "Marakkal",
    name_hindi: "ಮರಕ್ಕಾಲ್",
    local_names: ["ಮರಕ್ಕಾಲ್ (Marakkal)"],
    meaning: "Traditional South Indian volume measure.",
    category: "volume",
    sector: "livestock-dairy",
    modern_equivalent: "≈10–11 litres (varies)",
    conversion_formula: "Multiple Padi form 1 Marakkal",
    states: ["Karnataka"],
    used_in: ["Larger quantities of milk and agricultural products"],
    references: ["South Indian measurement traditions"],
  },
  {
    id: "ka-dairy-3",
    slug: "ka-kudam-dairy",
    name_english: "Kudam",
    name_hindi: "ಕುಡಂ",
    name_sanskrit: "Kuḍava",
    local_names: ["ಕುಡಂ (Kudam)"],
    meaning: "Traditional pot/container measure.",
    category: "volume",
    sector: "livestock-dairy",
    modern_equivalent: "≈10–15 litres (varies)",
    conversion_formula: "Vessel-based larger measure",
    states: ["Karnataka"],
    used_in: ["Storing and transporting milk, curd and water"],
    references: ["Household traditions"],
  },
  {
    id: "ka-dairy-4",
    slug: "ka-hande-dairy",
    name_english: "Hande",
    name_hindi: "ಹಂಡೆ",
    local_names: ["ಹಂಡೆ (Hande)"],
    meaning: "Large metal/clay vessel used in rural households.",
    category: "volume",
    sector: "livestock-dairy",
    modern_equivalent: "Regionally varies",
    conversion_formula: "Larger vessel than Kudam",
    states: ["Karnataka"],
    used_in: ["Bulk milk storage during dairy activities"],
    references: ["Local dairy practices"],
  },

  // Medicine (Ayurveda)
  {
    id: "ka-med-1",
    slug: "ka-bindu-med",
    name_english: "Bindu",
    name_hindi: "ಬಿಂದು",
    name_sanskrit: "Bindu",
    local_names: ["ಬಿಂದು (Bindu)"],
    meaning: "Single drop.",
    category: "volume",
    sector: "medicine",
    modern_equivalent: "≈0.05 ml",
    conversion_formula: "Eye and nasal medicines",
    states: ["Karnataka"],
    used_in: ["Ayurvedic Pharmacopoeia"],
    references: ["Charaka Samhita"],
  },

  // Construction & Architecture
  {
    id: "ka-arch-1",
    slug: "ka-kishku-hasta",
    name_english: "Kishku Hasta",
    name_hindi: "ಕಿಷ್ಕು ಹಸ್ತ",
    name_sanskrit: "Kiṣku Hasta",
    local_names: ["ಕಿಷ್ಕು ಹಸ್ತ (Kishku Hasta)"],
    meaning: "Variant of Hasta used in architecture.",
    category: "length",
    sector: "architecture",
    modern_equivalent: "≈45-48 cm",
    conversion_formula: "Traditional cubit",
    states: ["Karnataka"],
    used_in: ["Residential buildings"],
    references: ["Manasara"],
  },

  // Household & Daily Life
  {
    id: "ka-hh-1",
    slug: "ka-kolaga-hh",
    name_english: "Kolaga",
    name_hindi: "ಕೊಳಗ",
    local_names: ["ಕೊಳಗ (Kolaga)"],
    meaning: "Traditional vessel measure.",
    category: "volume",
    sector: "household",
    modern_equivalent: "Regional variation",
    conversion_formula: "Wooden measuring vessel",
    states: ["Karnataka"],
    used_in: ["Rice measurement in kitchens"],
    references: ["Karnataka State Gazetteers"],
  },

  // Storage & Transportation
  {
    id: "ka-storage-1",
    slug: "ka-khanduga-storage",
    name_english: "Khanduga",
    name_hindi: "ಖಂಡುಗ",
    local_names: ["ಖಂಡುಗ (Khanduga)"],
    meaning: "Large granary measurement.",
    category: "volume",
    sector: "storage-transport",
    modern_equivalent: "≈74.6 L",
    conversion_formula: "About 20 Mana",
    states: ["Karnataka"],
    used_in: ["Bulk grain storage"],
    references: ["Karnataka Revenue Records"],
  },

  // Gold & Jewellery
  {
    id: "ka-gold-1",
    slug: "ka-gadyana-gold",
    name_english: "Gadyana",
    name_hindi: "ಗದ್ಯಾಣ",
    name_sanskrit: "Gadyāṇa",
    local_names: ["ಗದ್ಯಾಣ (Gadyana)"],
    meaning: "Prominent gold coin used by Chalukyas and Hoysalas.",
    category: "weight",
    sector: "gold-jewellery",
    modern_equivalent: "Regional standard",
    conversion_formula: "Gold coin standard",
    states: ["Karnataka"],
    used_in: ["High-value trade and jewellery"],
    references: ["Epigraphica Carnatica"],
  },

  // Currency & Money
  {
    id: "ka-cur-1",
    slug: "ka-hana-cur",
    name_english: "Hana",
    name_hindi: "ಹಣ",
    local_names: ["ಹಣ (Hana)"],
    meaning: "Standard monetary unit.",
    category: "currency",
    sector: "currency-money",
    modern_equivalent: "Historical",
    conversion_formula: "Local commerce",
    states: ["Karnataka"],
    used_in: ["Common monetary unit across Karnataka"],
    references: ["Epigraphica Carnatica"],
  },

  // Textile & Handloom
  {
    id: "ka-tex-1",
    slug: "ka-kolu-tex",
    name_english: "Kolu",
    name_hindi: "ಕೋಲು",
    local_names: ["ಕೋಲು (Kolu)"],
    meaning: "Measuring rod used in loom preparation.",
    category: "length",
    sector: "textile-handloom",
    modern_equivalent: "Regional variation",
    conversion_formula: "Wooden rod",
    states: ["Karnataka"],
    used_in: ["Warp preparation in handlooms"],
    references: ["Karnataka Handloom Traditions"],
  },

  // Religious & Cultural
  {
    id: "ka-relig-1",
    slug: "ka-dakshina-relig",
    name_english: "Dakshina",
    name_hindi: "ದಕ್ಷಿಣೆ",
    name_sanskrit: "Dakṣiṇā",
    local_names: ["ದಕ್ಷಿಣೆ (Dakshina)"],
    meaning: "Payment Unit / Honorarium.",
    category: "currency",
    sector: "religious-cultural",
    modern_equivalent: "Variable",
    conversion_formula: "Religious payments",
    states: ["Karnataka"],
    used_in: ["Traditional payment made to priests and scholars"],
    references: ["Dharmashastra"],
  }
];
