import { Measurement } from "@/types";

export const MAHARASHTRA_MEASUREMENTS: Measurement[] = [
  // Trade & Commerce
  {
    id: "mh-trade-1",
    slug: "mh-gunja",
    name_english: "Gunja",
    name_sanskrit: "Guñjā (Raktikā)",
    name_hindi: "गूंज",
    local_names: ["गूंज (Gunja)"],
    meaning: "Gunja seed used as a standard for weighing precious commodities.",
    category: "weight",
    sector: "trade-commerce",
    modern_equivalent: "≈0.1215 g",
    conversion_formula: "Seed weight",
    states: ["Maharashtra"],
    used_in: ["Gold and gem trade"],
    references: ["Charaka Samhita"],
  },
  {
    id: "mh-trade-2",
    slug: "mh-masha-trade",
    name_english: "Masha",
    name_sanskrit: "Māṣa",
    name_hindi: "माष",
    local_names: ["माष (Masha)"],
    meaning: "Used for weighing medicines, spices and valuable goods.",
    category: "weight",
    sector: "trade-commerce",
    modern_equivalent: "≈0.97 g",
    conversion_formula: "8 Gunja = 1 Masha",
    states: ["Maharashtra"],
    used_in: ["Spice trade"],
    references: ["Arthashastra"],
  },
  {
    id: "mh-trade-3",
    slug: "mh-karsha-trade",
    name_english: "Karsha",
    name_sanskrit: "Karṣa",
    name_hindi: "कर्ष",
    local_names: ["कर्ष (Karsha)"],
    meaning: "Standard commercial weight in ancient markets.",
    category: "weight",
    sector: "trade-commerce",
    modern_equivalent: "≈12 g",
    conversion_formula: "12 Masha = 1 Karsha",
    states: ["Maharashtra"],
    used_in: ["Merchant weighing"],
    references: ["Charaka Samhita"],
  },
  {
    id: "mh-trade-4",
    slug: "mh-tola-trade",
    name_english: "Tola",
    name_sanskrit: "Tulā",
    name_hindi: "तोला",
    local_names: ["तोळा (Tola)"],
    meaning: "Standard unit used by jewellers and merchants.",
    category: "weight",
    sector: "trade-commerce",
    modern_equivalent: "≈11.66 g",
    conversion_formula: "Traditional weight unit",
    states: ["Maharashtra"],
    used_in: ["Gold and silver trade"],
    references: ["Bombay Presidency Records"],
  },
  {
    id: "mh-trade-5",
    slug: "mh-chhatak",
    name_english: "Chhatak",
    name_sanskrit: "",
    name_hindi: "छटाक",
    local_names: ["छटाक (Chhatak)"],
    meaning: "Used for grains, jaggery and spices.",
    category: "weight",
    sector: "trade-commerce",
    modern_equivalent: "≈58 g",
    conversion_formula: "16 Chhatak = 1 Sher",
    states: ["Maharashtra"],
    used_in: ["Grocery trade"],
    references: ["Bombay Presidency Manual"],
  },

  // Architecture
  {
    id: "mh-arch-1",
    slug: "mh-paramanu",
    name_english: "Paramanu",
    name_sanskrit: "Paramāṇu",
    name_hindi: "परमाणु",
    local_names: ["परमाणु (Paramanu)"],
    meaning: "Smallest conceptual unit mentioned in ancient architectural treatises.",
    category: "length",
    sector: "architecture",
    modern_equivalent: "Theoretical",
    conversion_formula: "Smallest theoretical unit",
    states: ["Maharashtra"],
    used_in: ["Temple planning"],
    references: ["Manasara"],
  },
  {
    id: "mh-arch-2",
    slug: "mh-raji",
    name_english: "Raji",
    name_sanskrit: "Raji",
    name_hindi: "रजी",
    local_names: ["रजी (Raji)"],
    meaning: "Minute unit used in proportional calculations.",
    category: "length",
    sector: "architecture",
    modern_equivalent: "Theoretical",
    conversion_formula: "Larger than Paramanu",
    states: ["Maharashtra"],
    used_in: ["Architectural calculations"],
    references: ["Mayamata"],
  },
  {
    id: "mh-arch-3",
    slug: "mh-yava-arch",
    name_english: "Yava",
    name_sanskrit: "Yava",
    name_hindi: "यव",
    local_names: ["यव (Yava)"],
    meaning: "Barley grain used as a base measurement.",
    category: "length",
    sector: "architecture",
    modern_equivalent: "≈2.4 mm",
    conversion_formula: "8 Yava = 1 Angula",
    states: ["Maharashtra"],
    used_in: ["Stone carving"],
    references: ["Manasara"],
  },
  {
    id: "mh-arch-4",
    slug: "mh-angula-arch",
    name_english: "Angula",
    name_sanskrit: "Aṅgula",
    name_hindi: "अंगुल",
    local_names: ["अंगूळ (Angula)"],
    meaning: "Finger-width measurement used in architecture and sculpture.",
    category: "length",
    sector: "architecture",
    modern_equivalent: "≈1.9 cm",
    conversion_formula: "8 Yava = 1 Angula",
    states: ["Maharashtra"],
    used_in: ["Building construction"],
    references: ["Mayamata"],
  },
  {
    id: "mh-arch-5",
    slug: "mh-vitasti",
    name_english: "Vitasti",
    name_sanskrit: "Vitasti",
    name_hindi: "वितस्ती",
    local_names: ["वितस्ती (Vitasti)"],
    meaning: "Palm-span measurement used in planning walls and rooms.",
    category: "length",
    sector: "architecture",
    modern_equivalent: "≈22.8 cm",
    conversion_formula: "12 Angula = 1 Vitasti",
    states: ["Maharashtra"],
    used_in: ["Building layout"],
    references: ["Manasara"],
  },

  // Medicine (Ayurveda)
  {
    id: "mh-med-1",
    slug: "mh-masha-med",
    name_english: "Masha",
    name_sanskrit: "Māṣa",
    name_hindi: "माष",
    local_names: ["माष (Masha)"],
    meaning: "Standard Ayurvedic unit for powders and pills.",
    category: "weight",
    sector: "medicine",
    modern_equivalent: "≈0.97 g",
    conversion_formula: "8 Gunja = 1 Masha",
    states: ["Maharashtra"],
    used_in: ["Herbal powders"],
    references: ["Charaka Samhita"],
  },
  {
    id: "mh-med-2",
    slug: "mh-karsha-med",
    name_english: "Karsha",
    name_sanskrit: "Karṣa",
    name_hindi: "कर्ष",
    local_names: ["कर्ष (Karsha)"],
    meaning: "Used for herbs, minerals and medicinal mixtures.",
    category: "weight",
    sector: "medicine",
    modern_equivalent: "≈12 g",
    conversion_formula: "12 Masha = 1 Karsha",
    states: ["Maharashtra"],
    used_in: ["Medicinal preparations"],
    references: ["Sushruta Samhita"],
  },
  {
    id: "mh-med-3",
    slug: "mh-tola-med",
    name_english: "Tola",
    name_sanskrit: "Tulā",
    name_hindi: "तोला",
    local_names: ["तोळा (Tola)"],
    meaning: "Used for costly herbs and metallic preparations.",
    category: "weight",
    sector: "medicine",
    modern_equivalent: "≈11.66 g",
    conversion_formula: "Traditional weight unit",
    states: ["Maharashtra"],
    used_in: ["Precious medicinal ingredients"],
    references: ["Bombay Presidency Records"],
  },
  {
    id: "mh-med-4",
    slug: "mh-pala-med",
    name_english: "Pala",
    name_sanskrit: "Pala",
    name_hindi: "पल",
    local_names: ["पल (Pala)"],
    meaning: "Standard weight for roots, bark and herbal powders.",
    category: "weight",
    sector: "medicine",
    modern_equivalent: "≈48 g",
    conversion_formula: "4 Karsha = 1 Pala",
    states: ["Maharashtra"],
    used_in: ["Herbal ingredients"],
    references: ["Ashtanga Hridaya"],
  },
  {
    id: "mh-med-5",
    slug: "mh-prasriti",
    name_english: "Prasriti",
    name_sanskrit: "Prasṛti",
    name_hindi: "प्रसृती",
    local_names: ["प्रसृती (Prasriti)"],
    meaning: "Used for medicated oils, ghee and decoctions.",
    category: "volume",
    sector: "medicine",
    modern_equivalent: "≈96 ml",
    conversion_formula: "2 Pala = 1 Prasriti",
    states: ["Maharashtra"],
    used_in: ["Herbal decoctions"],
    references: ["Charaka Samhita"],
  },

  // Textile & Handloom
  {
    id: "mh-tex-1",
    slug: "mh-yava-tex",
    name_english: "Yava",
    name_sanskrit: "Yava",
    name_hindi: "यव",
    local_names: ["यव (Yava)"],
    meaning: "Barley grain used as the smallest linear reference for intricate textile work.",
    category: "length",
    sector: "textile-handloom",
    modern_equivalent: "≈2.4 mm",
    conversion_formula: "8 Yava = 1 Angula",
    states: ["Maharashtra"],
    used_in: ["Fine weaving"],
    references: ["Manasara"],
  },
  {
    id: "mh-tex-2",
    slug: "mh-angula-tex",
    name_english: "Angula",
    name_sanskrit: "Aṅgula",
    name_hindi: "अंगुल",
    local_names: ["अंगूळ (Angula)"],
    meaning: "Finger-width measure used by traditional weavers.",
    category: "length",
    sector: "textile-handloom",
    modern_equivalent: "≈1.9 cm",
    conversion_formula: "8 Yava = 1 Angula",
    states: ["Maharashtra"],
    used_in: ["Cloth measurement"],
    references: ["Mayamata"],
  },
  {
    id: "mh-tex-3",
    slug: "mh-vitasti-tex",
    name_english: "Vitasti",
    name_sanskrit: "Vitasti",
    name_hindi: "वितस्ती",
    local_names: ["वितस्ती (Vitasti)"],
    meaning: "Palm-span measure for warp and loom alignment.",
    category: "length",
    sector: "textile-handloom",
    modern_equivalent: "≈22.8 cm",
    conversion_formula: "12 Angula = 1 Vitasti",
    states: ["Maharashtra"],
    used_in: ["Loom setup"],
    references: ["Manasara"],
  },
  {
    id: "mh-tex-4",
    slug: "mh-hasta-tex",
    name_english: "Hasta",
    name_sanskrit: "Hasta",
    name_hindi: "हस्त",
    local_names: ["हस्त (Hasta)"],
    meaning: "Cubit used for measuring woven fabric.",
    category: "length",
    sector: "textile-handloom",
    modern_equivalent: "≈45.7 cm",
    conversion_formula: "24 Angula = 1 Hasta",
    states: ["Maharashtra"],
    used_in: ["Cloth weaving"],
    references: ["Silpa Sastra"],
  },
  {
    id: "mh-tex-5",
    slug: "mh-gaz-tex",
    name_english: "Gaz",
    name_sanskrit: "Gaja",
    name_hindi: "गज",
    local_names: ["गज (Gaz)"],
    meaning: "Standard yard used for measuring cloth in markets.",
    category: "length",
    sector: "textile-handloom",
    modern_equivalent: "≈0.9144 m",
    conversion_formula: "Traditional yard",
    states: ["Maharashtra"],
    used_in: ["Textile trade"],
    references: ["Bombay Presidency Manual"],
  },

  // Currency & Money
  {
    id: "mh-cur-1",
    slug: "mh-gunja-cur",
    name_english: "Gunja",
    name_sanskrit: "Guñjā (Raktikā)",
    name_hindi: "गूंज",
    local_names: ["गूंज (Gunja)"],
    meaning: "Gunja seed used by goldsmiths for weighing gold and gemstones.",
    category: "weight",
    sector: "currency-money",
    modern_equivalent: "≈0.1215 g",
    conversion_formula: "Seed weight",
    states: ["Maharashtra"],
    used_in: ["Gold weighing"],
    references: ["Charaka Samhita"],
  },
  {
    id: "mh-cur-2",
    slug: "mh-ratti-cur",
    name_english: "Ratti",
    name_sanskrit: "Raktikā",
    name_hindi: "रत्ती",
    local_names: ["रत्ती (Ratti)"],
    meaning: "Standard jeweler's weight for gold and gems.",
    category: "weight",
    sector: "currency-money",
    modern_equivalent: "≈0.1215 g",
    conversion_formula: "Equivalent to Gunja seed",
    states: ["Maharashtra"],
    used_in: ["Precious metals"],
    references: ["Arthashastra"],
  },
  {
    id: "mh-cur-3",
    slug: "mh-masha-cur",
    name_english: "Masha",
    name_sanskrit: "Māṣa",
    name_hindi: "माष",
    local_names: ["माष (Masha)"],
    meaning: "Used for weighing bullion and precious metals.",
    category: "weight",
    sector: "currency-money",
    modern_equivalent: "≈0.97 g",
    conversion_formula: "8 Ratti = 1 Masha",
    states: ["Maharashtra"],
    used_in: ["Gold and silver"],
    references: ["Sushruta Samhita"],
  },
  {
    id: "mh-cur-4",
    slug: "mh-karsha-cur",
    name_english: "Karsha",
    name_sanskrit: "Karṣa",
    name_hindi: "कर्ष",
    local_names: ["कर्ष (Karsha)"],
    meaning: "Commercial weight for valuable commodities.",
    category: "weight",
    sector: "currency-money",
    modern_equivalent: "≈12 g",
    conversion_formula: "12 Masha = 1 Karsha",
    states: ["Maharashtra"],
    used_in: ["Bullion trade"],
    references: ["Charaka Samhita"],
  },
  {
    id: "mh-cur-5",
    slug: "mh-tola-cur",
    name_english: "Tola",
    name_sanskrit: "Tulā",
    name_hindi: "तोला",
    local_names: ["तोळा (Tola)"],
    meaning: "Standard unit used by jewellers and merchants.",
    category: "weight",
    sector: "currency-money",
    modern_equivalent: "≈11.66 g",
    conversion_formula: "Traditional weight unit",
    states: ["Maharashtra"],
    used_in: ["Jewellery trade"],
    references: ["Bombay Presidency Records"],
  },

  // Household & Daily Life
  {
    id: "mh-hh-1",
    slug: "mh-drop-hh",
    name_english: "Drop",
    name_hindi: "बूंद",
    local_names: ["Single drop"],
    meaning: "Smallest liquid measure used in homes for oils, medicines and rituals.",
    category: "volume",
    sector: "household",
    modern_equivalent: "≈0.05 ml",
    conversion_formula: "Single drop",
    states: ["Maharashtra"],
    used_in: ["Oils and medicines"],
    references: ["Charaka Samhita"],
  },
  {
    id: "mh-hh-2",
    slug: "mh-sher-hh",
    name_english: "Sher",
    name_hindi: "शेर",
    local_names: ["शेर (Sher)"],
    meaning: "Common household measure for cereals and pulses.",
    category: "weight",
    sector: "household",
    modern_equivalent: "≈0.93 kg",
    conversion_formula: "Standard measure",
    states: ["Maharashtra"],
    used_in: ["Grain storage"],
    references: ["Bombay Gazetteer"],
  },
  {
    id: "mh-hh-3",
    slug: "mh-man-hh",
    name_english: "Man",
    name_hindi: "मन",
    local_names: ["मण (Man)"],
    meaning: "Used for storing harvested grain in households.",
    category: "weight",
    sector: "household",
    modern_equivalent: "≈37.3 kg",
    conversion_formula: "40 Sher = 1 Man",
    states: ["Maharashtra"],
    used_in: ["Bulk grain storage"],
    references: ["Bombay Presidency Gazetteer"],
  },

  // Storage & Transportation
  {
    id: "mh-st-1",
    slug: "mh-prastha-st",
    name_english: "Prastha",
    name_hindi: "प्रस्थ",
    local_names: ["प्रस्थ (Prastha)"],
    meaning: "Small vessel used for measuring grain before storage or transport.",
    category: "volume",
    sector: "storage-transport",
    modern_equivalent: "≈3-4 L",
    conversion_formula: "Basic grain measure",
    states: ["Maharashtra"],
    used_in: ["Grain storage"],
    references: ["Bombay Presidency Gazetteer"],
  },
  {
    id: "mh-st-2",
    slug: "mh-khandi-st",
    name_english: "Khandi",
    name_hindi: "खंडी",
    local_names: ["खंडी (Khandi)"],
    meaning: "Large bulk unit for grain, cotton and sugar storage.",
    category: "weight",
    sector: "storage-transport",
    modern_equivalent: "≈746 kg",
    conversion_formula: "20 Man = 1 Khandi",
    states: ["Maharashtra"],
    used_in: ["Wholesale grain trade"],
    references: ["Maratha Revenue Records"],
  },
  {
    id: "mh-st-3",
    slug: "mh-godown",
    name_english: "Godown",
    name_hindi: "गोदाम",
    local_names: ["गोदाम (Godown)"],
    meaning: "Warehouse used for storing grain, cotton and other commodities before trade and export.",
    category: "volume",
    sector: "storage-transport",
    modern_equivalent: "Variable",
    conversion_formula: "Warehouse Capacity",
    states: ["Maharashtra"],
    used_in: ["Commercial warehousing"],
    references: ["Bombay Presidency Gazetteer"],
  },

  // Seed & Crop (Agriculture)
  {
    id: "mh-agri-1",
    slug: "mh-yava-agri",
    name_english: "Yava",
    name_hindi: "यव",
    local_names: ["यव (Yava)"],
    meaning: "Barley grain used as the smallest traditional measurement.",
    category: "length",
    sector: "agriculture",
    modern_equivalent: "≈2.4 mm",
    conversion_formula: "Grain-based unit",
    states: ["Maharashtra"],
    used_in: ["Seed reference"],
    references: ["Arthashastra"],
  },
  {
    id: "mh-agri-2",
    slug: "mh-khale",
    name_english: "Khale",
    name_hindi: "खळे",
    local_names: ["खळे (Khale)"],
    meaning: "Open threshing floor where grain was separated and measured before storage.",
    category: "area",
    sector: "agriculture",
    modern_equivalent: "Variable",
    conversion_formula: "Harvest processing area",
    states: ["Maharashtra"],
    used_in: ["Post-harvest operations"],
    references: ["Maharashtra Agricultural Traditions"],
  },

  // Land Measurement
  {
    id: "mh-land-1",
    slug: "mh-square-kathi",
    name_english: "Square Kathi",
    name_hindi: "चौ. काठी",
    local_names: ["चौ. काठी (Square Kathi)"],
    meaning: "Smallest traditional land unit.",
    category: "area",
    sector: "land-measurement",
    modern_equivalent: "≈8.36 m²",
    conversion_formula: "Base Unit",
    states: ["Maharashtra"],
    used_in: ["Measuring house sites and small plots"],
    references: ["Bombay Presidency Revenue Records"],
  },
  {
    id: "mh-land-2",
    slug: "mh-guntha",
    name_english: "Guntha",
    name_hindi: "गुंठा",
    local_names: ["गुंठा (Guntha)"],
    meaning: "Most common traditional land unit.",
    category: "area",
    sector: "land-measurement",
    modern_equivalent: "≈101.17 m²",
    conversion_formula: "40 Square Kathis = 1 Guntha",
    states: ["Maharashtra"],
    used_in: ["Agricultural fields and land records"],
    references: ["Maharashtra Land Revenue Manual"],
  },
  {
    id: "mh-land-3",
    slug: "mh-bigha",
    name_english: "Bigha",
    name_hindi: "बिघा",
    local_names: ["बिघा (Bigha)"],
    meaning: "Traditional revenue unit.",
    category: "area",
    sector: "land-measurement",
    modern_equivalent: "≈0.25–0.67 hectare",
    conversion_formula: "Regional variation",
    states: ["Maharashtra"],
    used_in: ["Agricultural land measurement"],
    references: ["Bombay Gazetteers"],
  },
  {
    id: "mh-land-4",
    slug: "mh-acre",
    name_english: "Acre",
    name_hindi: "एकर",
    local_names: ["एकर (Acre)"],
    meaning: "British standard land unit.",
    category: "area",
    sector: "land-measurement",
    modern_equivalent: "4046.86 m²",
    conversion_formula: "40 Gunthas = 1 Acre",
    states: ["Maharashtra"],
    used_in: ["Land survey and revenue"],
    references: ["British India Survey Records"],
  },
  {
    id: "mh-land-5",
    slug: "mh-chavar",
    name_english: "Chavar",
    name_hindi: "चाहूर",
    local_names: ["चाहूर (Chavar)"],
    meaning: "Large traditional estate unit.",
    category: "area",
    sector: "land-measurement",
    modern_equivalent: "Variable",
    conversion_formula: "120 Bighas = 1 Chavar",
    states: ["Maharashtra"],
    used_in: ["Large agricultural estates and revenue records"],
    references: ["Maharashtra State Gazetteers"],
  },
  {
    id: "mh-land-6",
    slug: "mh-hectare",
    name_english: "Hectare",
    name_hindi: "हेक्टर",
    local_names: ["हेक्टर (Hectare)"],
    meaning: "Official metric land unit.",
    category: "area",
    sector: "land-measurement",
    modern_equivalent: "10,000 m²",
    conversion_formula: "1 Hectare = 2.471 Acres",
    states: ["Maharashtra"],
    used_in: ["Modern government land records"],
    references: ["Government of Maharashtra"],
  },

  // Livestock & Dairy
  {
    id: "mh-dairy-1",
    slug: "mh-pav-dairy",
    name_english: "Pav",
    name_hindi: "पाव",
    local_names: ["पाव (Pav)"],
    meaning: "Quarter Seer used for milk and curd.",
    category: "volume",
    sector: "livestock-dairy",
    modern_equivalent: "≈233 g (≈250 ml)",
    conversion_formula: "4 Chhatak = 1 Pav",
    states: ["Maharashtra"],
    used_in: ["Milk and curd"],
    references: ["Mughal-1958"],
  },
  {
    id: "mh-dairy-2",
    slug: "mh-adha-seer-dairy",
    name_english: "Adha Seer",
    name_hindi: "अर्धा शेर",
    local_names: ["अर्धा शेर (Adha Seer)"],
    meaning: "Half Seer used for milk and buttermilk.",
    category: "volume",
    sector: "livestock-dairy",
    modern_equivalent: "≈466 g (≈500 ml)",
    conversion_formula: "2 Pav = 1 Half Seer",
    states: ["Maharashtra"],
    used_in: ["Milk and buttermilk"],
    references: ["Mughal-1958"],
  },
  {
    id: "mh-dairy-3",
    slug: "mh-seer-dairy",
    name_english: "Seer (Sher)",
    name_hindi: "शेर",
    local_names: ["शेर (Sher)"],
    meaning: "Standard unit for milk, curd and ghee.",
    category: "volume",
    sector: "livestock-dairy",
    modern_equivalent: "≈0.933 kg / ≈0.93 L",
    conversion_formula: "2 Half Seer = 1 Seer",
    states: ["Maharashtra"],
    used_in: ["Standard unit for milk, curd and ghee"],
    references: ["Mughal-1958"],
  },
  {
    id: "mh-dairy-4",
    slug: "mh-maund-dairy",
    name_english: "Maund (Man)",
    name_hindi: "मण",
    local_names: ["मण (Man)"],
    meaning: "Principal bulk unit for fodder and cattle feed.",
    category: "weight",
    sector: "livestock-dairy",
    modern_equivalent: "≈37.324 kg",
    conversion_formula: "40 Seers = 1 Maund",
    states: ["Maharashtra"],
    used_in: ["Bulk fodder, cattle feed and dairy products"],
    references: ["Mughal-1958"],
  },

  // Gold & Jewellery
  {
    id: "mh-gold-1",
    slug: "mh-ratti-gold",
    name_english: "Ratti",
    name_sanskrit: "Raktikā",
    name_hindi: "रत्ती",
    local_names: ["रत्ती (Ratti)"],
    meaning: "Smallest traditional jewellery weight.",
    category: "weight",
    sector: "gold-jewellery",
    modern_equivalent: "≈121.5 mg",
    conversion_formula: "Base Unit",
    states: ["Maharashtra"],
    used_in: ["Measuring gemstones, pearls and small gold quantities"],
    references: ["Arthashastra; Ratna Pariksha texts"],
  },
  {
    id: "mh-gold-2",
    slug: "mh-masha-gold",
    name_english: "Masha",
    name_sanskrit: "Māṣa",
    name_hindi: "माषा",
    local_names: ["माषा (Masha)"],
    meaning: "Small goldsmith unit.",
    category: "weight",
    sector: "gold-jewellery",
    modern_equivalent: "≈0.972 g",
    conversion_formula: "8 Ratti = 1 Masha",
    states: ["Maharashtra"],
    used_in: ["Measuring small ornaments and gold pieces"],
    references: ["Sanskrit weight systems"],
  },
  {
    id: "mh-gold-3",
    slug: "mh-tola-gold",
    name_english: "Tola",
    name_sanskrit: "Tulā",
    name_hindi: "तोला",
    local_names: ["तोळा (Tola)"],
    meaning: "Most common jewellery unit.",
    category: "weight",
    sector: "gold-jewellery",
    modern_equivalent: "≈11.66 g",
    conversion_formula: "12 Masha = 1 Tola",
    states: ["Maharashtra"],
    used_in: ["Main unit for gold and silver trade"],
    references: ["British India Standards"],
  },
  {
    id: "mh-gold-4",
    slug: "mh-suvarna-gold",
    name_english: "Suvarna",
    name_sanskrit: "Suvarṇa",
    name_hindi: "सुवर्ण",
    local_names: ["सुवर्ण (Suvarna)"],
    meaning: "Classical gold unit.",
    category: "weight",
    sector: "gold-jewellery",
    modern_equivalent: "≈15.5 g",
    conversion_formula: "16 Masha = 1 Suvarna",
    states: ["Maharashtra"],
    used_in: ["Gold coins, ornaments and donations"],
    references: ["Arthashastra"],
  }
];
