import { Measurement } from "@/types";

export const MANIPUR_MEASUREMENTS: Measurement[] = [
  // ─── 1. Transportation & Distance (3 units) ─────────────────────────────────
  {
    id: "manipur-trans-1",
    slug: "sana-lamjel-fathom-distance-manipur",
    name_english: "Sana Lamjel (fathom, distance use)",
    name_sanskrit: "N/A (Meitei royal-decree unit)",
    local_names: ["সানা লামজেল"],
    name_hindi: "साना लामजेल",
    category: "length",
    measurement_type: "Length/Distance",
    sector: "transportation-distance",
    origin: "Manipur (Imphal Valley)",
    modern_equivalent: "A fathom plus 4 finger-widths",
    conversion_formula:
      "Base reference for short-to-medium distance reckoning within the valley",
    meaning:
      "Used historically for measuring roads, canal banks and field-boundary distances within the Meitei kingdom's administrative reach",
    historical_period:
      "Ningthouja/Meitei kingdom period (Nongda Lairen Pakhangba, traditionally dated 33 CE, through to the 1891 British takeover)",
    region_applicable: "Imphal Valley — the historic Meitei kingdom heartland",
    states: ["Manipur"],
    used_in: [
      "Used historically for measuring roads, canal banks and field-boundary distances within the Meitei kingdom's administrative reach",
      "Transportation & Distance",
    ],
    references: [
      "https://en.wikipedia.org/wiki/Sana_lamjel",
      "https://en.wikipedia.org/wiki/Pari_(unit)",
    ],
    tags: [
      "manipur",
      "traditional-units",
      "transportation-distance",
      "sana-lamjel",
      "fathom",
      "meitei",
      "imphal-valley",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "manipur-trans-2",
    slug: "krosha-kos-distance-manipur",
    name_english: "Krosha (Kos)",
    name_sanskrit: "क्रोश (Krosa)",
    local_names: [],
    name_hindi: "कोस",
    category: "length",
    measurement_type: "Distance",
    sector: "transportation-distance",
    origin: "Manipur (Imphal Valley)",
    modern_equivalent: "~3.2 km",
    conversion_formula: "1 Krosha = traditional travel sub-unit",
    meaning:
      "Longer travel distance reckoning adopted alongside Hindu Vaishnavite religious influence from the 18th century",
    historical_period:
      "Ancient Puranic/Sanskritic period, still ritually observed today",
    region_applicable: "Imphal Valley — the historic Meitei kingdom heartland",
    states: ["Manipur"],
    used_in: [
      "Longer travel distance reckoning adopted alongside Hindu Vaishnavite religious influence from the 18th century",
      "Transportation & Distance",
    ],
    references: ["https://en.wikipedia.org/wiki/Kos_(unit)"],
    tags: [
      "manipur",
      "traditional-units",
      "transportation-distance",
      "krosha",
      "kos",
      "distance",
      "vaishnavite",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "manipur-trans-3",
    slug: "days-walk-hill-reckoning-distance-manipur",
    name_english: "(Day's-walk hill reckoning)",
    name_sanskrit:
      "N/A — informal, terrain-based measurement, no fixed named unit documented",
    local_names: [],
    name_hindi: "दिन भर की यात्रा (अनौपचारिक)",
    category: "length",
    measurement_type: "Distance (informal, time-based)",
    sector: "transportation-distance",
    origin: "Manipur (Hill Districts)",
    modern_equivalent:
      "Distance expressed as the number of days' walk required through hill terrain",
    conversion_formula: "No standardised hierarchy",
    meaning:
      "In Manipur's Naga and Kuki-Zo hill districts, travel between villages was traditionally reckoned by days' walk rather than by a fixed-length unit",
    historical_period:
      "Customary/traditional practice of Manipur's Naga and Kuki-Zo hill communities, predating and continuing alongside Meitei valley administration",
    region_applicable:
      "Hill districts — Naga (Tangkhul, Mao, Poumai) and Kuki-Zo (Thadou, Zomi, Hmar) homelands",
    states: ["Manipur"],
    used_in: [
      "In Manipur's Naga and Kuki-Zo hill districts, travel between villages was traditionally reckoned by days' walk rather than by a fixed-length unit",
      "Transportation & Distance",
    ],
    references: [
      "No standardised metrological reference documented for this practice",
    ],
    tags: [
      "manipur",
      "traditional-units",
      "transportation-distance",
      "days-walk",
      "hill-districts",
      "naga",
      "kuki-zo",
    ],
    created_at: "2024-01-01",
  },

  // ─── 2. Land Measurement (8 units) ──────────────────────────────────────────
  {
    id: "manipur-land-1",
    slug: "tong-land-manipur",
    name_english: "Tong",
    name_sanskrit: "N/A (Meitei vernacular revenue term)",
    local_names: ["টং"],
    name_hindi: "टोंग",
    category: "area",
    measurement_type: "Area",
    sector: "land-measurement",
    origin: "Manipur (Imphal Valley)",
    modern_equivalent:
      "Smallest unit in the chain (exact sq ft varies slightly by source)",
    conversion_formula: "2 Tong = 1 Loushal",
    meaning:
      "Smallest unit in Manipur's own royally-defined land-area chain, all ultimately derived from the Sana Lamjel body-measure",
    historical_period:
      "Ningthouja/Meitei kingdom period (Nongda Lairen Pakhangba, traditionally dated 33 CE, through to the 1891 British takeover)",
    region_applicable: "Imphal Valley — the historic Meitei kingdom heartland",
    states: ["Manipur"],
    used_in: [
      "Smallest unit in Manipur's own royally-defined land-area chain, all ultimately derived from the Sana Lamjel body-measure",
      "Land Measurement",
    ],
    references: [
      "https://en.wikipedia.org/wiki/Sana_lamjel",
      "https://en.wikipedia.org/wiki/Pari_(unit)",
    ],
    tags: [
      "manipur",
      "traditional-units",
      "land-measurement",
      "tong",
      "meitei",
      "area",
      "imphal-valley",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "manipur-land-2",
    slug: "loushal-land-manipur",
    name_english: "Loushal",
    name_sanskrit: "N/A (Meitei vernacular revenue term)",
    local_names: ["লৌশাল"],
    name_hindi: "लौशाल",
    category: "area",
    measurement_type: "Area",
    sector: "land-measurement",
    origin: "Manipur (Imphal Valley)",
    modern_equivalent: "Approx. double the Tong",
    conversion_formula: "2 Tong = 1 Loushal, 2 Loushal = 1 Loukhai",
    meaning:
      "Intermediate rung in the traditional Meitei land-measurement ladder",
    historical_period:
      "Ningthouja/Meitei kingdom period (Nongda Lairen Pakhangba, traditionally dated 33 CE, through to the 1891 British takeover)",
    region_applicable: "Imphal Valley — the historic Meitei kingdom heartland",
    states: ["Manipur"],
    used_in: [
      "Intermediate rung in the traditional Meitei land-measurement ladder",
      "Land Measurement",
    ],
    references: [
      "https://en.wikipedia.org/wiki/Sana_lamjel",
      "https://en.wikipedia.org/wiki/Pari_(unit)",
    ],
    tags: [
      "manipur",
      "traditional-units",
      "land-measurement",
      "loushal",
      "meitei",
      "area",
      "imphal-valley",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "manipur-land-3",
    slug: "loukhai-land-manipur",
    name_english: "Loukhai",
    name_sanskrit: "N/A (Meitei vernacular revenue term)",
    local_names: ["লৌখাই"],
    name_hindi: "लौखाई",
    category: "area",
    measurement_type: "Area",
    sector: "land-measurement",
    origin: "Manipur (Imphal Valley)",
    modern_equivalent:
      "~13,612.5 sq ft (~1,265 sq m) per the commonly cited conversion figure",
    conversion_formula: "2 Loushal = 1 Loukhai, 2 Loukhai = 1 Sangam",
    meaning:
      "Mid-sized traditional field plot unit in Meitei valley land records",
    historical_period:
      "Ningthouja/Meitei kingdom period (Nongda Lairen Pakhangba, traditionally dated 33 CE, through to the 1891 British takeover)",
    region_applicable: "Imphal Valley — the historic Meitei kingdom heartland",
    states: ["Manipur"],
    used_in: [
      "Mid-sized traditional field plot unit in Meitei valley land records",
      "Land Measurement",
    ],
    references: [
      "https://kanglaonline.in/area-converter/",
      "https://ingkhol.com/tools/manipur-area-converter",
    ],
    tags: [
      "manipur",
      "traditional-units",
      "land-measurement",
      "loukhai",
      "meitei",
      "area",
      "imphal-valley",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "manipur-land-4",
    slug: "sangam-land-manipur",
    name_english: "Sangam",
    name_sanskrit: "N/A (Meitei vernacular revenue term)",
    local_names: ["সংগম"],
    name_hindi: "संगम",
    category: "area",
    measurement_type: "Area",
    sector: "land-measurement",
    origin: "Manipur (Imphal Valley)",
    modern_equivalent: "~27,225 sq ft (~2,530 sq m)",
    conversion_formula: "2 Loukhai = 1 Sangam, 2 Sangam = 1 Lourak",
    meaning:
      "Standard everyday land-holding unit still quoted in Manipur property transactions and online land-converter tools",
    historical_period:
      "Ningthouja/Meitei kingdom period (Nongda Lairen Pakhangba, traditionally dated 33 CE, through to the 1891 British takeover)",
    region_applicable: "Imphal Valley — the historic Meitei kingdom heartland",
    states: ["Manipur"],
    used_in: [
      "Standard everyday land-holding unit still quoted in Manipur property transactions and online land-converter tools",
      "Land Measurement",
    ],
    references: [
      "https://kanglaonline.in/area-converter/",
      "https://ingkhol.com/tools/manipur-area-converter",
    ],
    tags: [
      "manipur",
      "traditional-units",
      "land-measurement",
      "sangam",
      "meitei",
      "area",
      "imphal-valley",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "manipur-land-5",
    slug: "lourak-land-manipur",
    name_english: "Lourak",
    name_sanskrit: "N/A (Meitei vernacular revenue term)",
    local_names: ["লৌরাক"],
    name_hindi: "लौरक",
    category: "area",
    measurement_type: "Area",
    sector: "land-measurement",
    origin: "Manipur (Imphal Valley)",
    modern_equivalent: "~54,450 sq ft (~5,059 sq m)",
    conversion_formula: "2 Sangam = 1 Lourak, 2 Lourak = 1 Pari",
    meaning: "Larger agricultural landholding unit, roughly 1¼ acres",
    historical_period:
      "Ningthouja/Meitei kingdom period (Nongda Lairen Pakhangba, traditionally dated 33 CE, through to the 1891 British takeover)",
    region_applicable: "Imphal Valley — the historic Meitei kingdom heartland",
    states: ["Manipur"],
    used_in: [
      "Larger agricultural landholding unit, roughly 1¼ acres",
      "Land Measurement",
    ],
    references: [
      "https://kanglaonline.in/area-converter/",
      "https://ingkhol.com/tools/manipur-area-converter",
    ],
    tags: [
      "manipur",
      "traditional-units",
      "land-measurement",
      "lourak",
      "meitei",
      "area",
      "imphal-valley",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "manipur-land-6",
    slug: "pari-land-manipur",
    name_english: "Pari",
    name_sanskrit: "N/A (Meitei vernacular revenue term)",
    local_names: ["পারি"],
    name_hindi: "पारी",
    category: "area",
    measurement_type: "Area",
    sector: "land-measurement",
    origin: "Manipur (Imphal Valley)",
    modern_equivalent:
      "~108,900 sq ft (~2.5 acres) per one conversion table; Wikipedia instead gives 'approximately 1 hectare' for the same 50×60 Sana Lamjel definition — sources disagree on the precise absolute figure, so both are flagged here",
    conversion_formula:
      "50×60 Sana Lamjel = 1 Pari = 2 Lourak = 4 Sangam = 8 Loukhai = 16 Loushal = 32 Tong",
    meaning:
      "The largest traditional Manipuri land unit, defined directly from King Pakhangba's own body-measure (the Sana Lamjel) rather than from any external standard",
    historical_period:
      "Ningthouja/Meitei kingdom period (Nongda Lairen Pakhangba, traditionally dated 33 CE, through to the 1891 British takeover)",
    region_applicable: "Imphal Valley — the historic Meitei kingdom heartland",
    states: ["Manipur"],
    used_in: [
      "The largest traditional Manipuri land unit, defined directly from King Pakhangba's own body-measure (the Sana Lamjel) rather than from any external standard",
      "Land Measurement",
    ],
    references: [
      "https://en.wikipedia.org/wiki/Sana_lamjel",
      "https://en.wikipedia.org/wiki/Pari_(unit)",
    ],
    tags: [
      "manipur",
      "traditional-units",
      "land-measurement",
      "pari",
      "meitei",
      "area",
      "imphal-valley",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "manipur-land-7",
    slug: "point-land-manipur",
    name_english: "Point (modern statutory sub-unit)",
    name_sanskrit: "N/A (Anglicised Manipur-specific term)",
    local_names: ["পইন্ট"],
    name_hindi: "पॉइंट",
    category: "area",
    measurement_type: "Area",
    sector: "land-measurement",
    origin: "Pan-Manipur generally",
    modern_equivalent:
      "~435.6 sq ft (~40.47 sq m), equivalent to a Decimal elsewhere in India",
    conversion_formula: "100 Point = 1 Acre",
    meaning:
      "Modern statutory sub-unit used in Manipur government land records alongside the traditional Tong-through-Pari chain",
    historical_period:
      "British colonial princely-state period (Manipur, one of the last princely states annexed, from 1891) and post-1949 Indian administration",
    region_applicable: "Pan-Manipur generally",
    states: ["Manipur"],
    used_in: [
      "Modern statutory sub-unit used in Manipur government land records alongside the traditional Tong-through-Pari chain",
      "Land Measurement",
    ],
    references: [
      "https://kanglaonline.in/area-converter/",
      "https://ingkhol.com/tools/manipur-area-converter",
    ],
    tags: [
      "manipur",
      "traditional-units",
      "land-measurement",
      "point",
      "statutory",
      "area",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "manipur-land-8",
    slug: "acre-hectare-land-manipur",
    name_english: "Acre / Hectare",
    name_sanskrit: "एकर / हेक्टेयर",
    local_names: [],
    name_hindi: "एकड़ / हेक्टेयर",
    category: "area",
    measurement_type: "Area",
    sector: "land-measurement",
    origin: "Pan-Manipur generally",
    modern_equivalent: "43,560 sq ft (Acre); 10,000 sq m (Hectare)",
    conversion_formula: "100 Point = 1 Acre, 2.47 Acre ≈ 1 Hectare",
    meaning:
      "Modern statutory units used in government and industrial land records alongside the traditional Meitei chain",
    historical_period:
      "British colonial princely-state period (Manipur, one of the last princely states annexed, from 1891) and post-1949 Indian administration",
    region_applicable: "Pan-Manipur generally",
    states: ["Manipur"],
    used_in: [
      "Modern statutory units used in government and industrial land records alongside the traditional Meitei chain",
      "Land Measurement",
    ],
    references: ["https://en.wikipedia.org/wiki/Acre"],
    tags: [
      "manipur",
      "traditional-units",
      "land-measurement",
      "acre",
      "hectare",
      "statutory",
      "area",
    ],
    created_at: "2024-01-01",
  },

  // ─── 3. Livestock & Dairy (2 units) ─────────────────────────────────────────
  {
    id: "manipur-dairy-1",
    slug: "ser-seer-dairy-manipur",
    name_english: "Ser (Seer)",
    name_sanskrit: "सेर (Sēra)",
    local_names: [],
    name_hindi: "सेर",
    category: "volume",
    measurement_type: "Weight/Volume",
    sector: "livestock-dairy",
    origin: "Manipur (Imphal Valley)",
    modern_equivalent: "~0.93 kg / ~0.93 L",
    conversion_formula: "1/40 Mon",
    meaning:
      "Standard market measure for milk and ghee in the Meitei valley; no dairy-exclusive unit is separately documented for Manipur",
    historical_period:
      "British colonial princely-state period (Manipur, one of the last princely states annexed, from 1891) and post 1949 Indian administration",
    region_applicable: "Imphal Valley — the historic Meitei kingdom heartland",
    states: ["Manipur"],
    used_in: [
      "Standard market measure for milk and ghee in the Meitei valley; no dairy-exclusive unit is separately documented for Manipur",
      "Livestock & Dairy",
    ],
    references: [
      "https://grokipedia.com/page/Seer_(unit)",
      "https://en.wikipedia.org/wiki/Maund",
    ],
    tags: [
      "manipur",
      "traditional-units",
      "livestock-dairy",
      "ser",
      "seer",
      "dairy",
      "milk",
      "ghee",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "manipur-dairy-2",
    slug: "mithun-count-dairy-manipur",
    name_english: "Mithun-count (hill districts)",
    name_sanskrit: "N/A — value/wealth reckoning, not a weight or volume unit",
    local_names: [],
    name_hindi: "मिथुन-गणना",
    category: "other",
    measurement_type: "Count (wealth/value unit)",
    sector: "livestock-dairy",
    origin: "Manipur (Hill Districts)",
    modern_equivalent:
      "A household's status and wealth is reckoned by the number of Mithun owned",
    conversion_formula: "No fixed hierarchy",
    meaning:
      "Manipur's Naga and Kuki-Zo hill communities, like their counterparts in neighbouring Nagaland and Arunachal Pradesh, traditionally valued the semi-domesticated Mithun (Bos frontalis) as the pre-eminent measure of pastoral wealth and a medium for bride-price and feast-of-merit sacrifice",
    historical_period:
      "Customary/traditional practice of Manipur's Naga and Kuki-Zo hill communities, predating and continuing alongside Meitei valley administration",
    region_applicable:
      "Hill districts — Naga (Tangkhul, Mao, Poumai) and Kuki-Zo (Thadou, Zomi, Hmar) homelands",
    states: ["Manipur"],
    used_in: [
      "Manipur's Naga and Kuki-Zo hill communities, like their counterparts in neighbouring Nagaland and Arunachal Pradesh, traditionally valued the semi-domesticated Mithun (Bos frontalis) as the pre-eminent measure of pastoral wealth and a medium for bride-price and feast-of-merit sacrifice",
      "Livestock & Dairy",
    ],
    references: [
      "https://www.insidene.com/importance-of-the-mithun-in-arunachal-pradesh/",
    ],
    tags: [
      "manipur",
      "traditional-units",
      "livestock-dairy",
      "mithun",
      "hill-districts",
      "naga",
      "kuki-zo",
      "wealth-count",
    ],
    created_at: "2024-01-01",
  },

  // ─── 4. Household & Daily Life (3 units) ────────────────────────────────────
  {
    id: "manipur-hh-1",
    slug: "chutki-muthi-household-manipur",
    name_english: "Chutki / Muthi",
    name_sanskrit:
      "N/A (general vernacular, shared with the wider North Indian vocabulary via colonial-era context)",
    local_names: [],
    name_hindi: "चुटकी / मुट्ठी",
    category: "volume",
    measurement_type: "Volume (informal)",
    sector: "household",
    origin: "Manipur (Imphal Valley)",
    modern_equivalent: "Pinch to ~50–100 g fistful",
    conversion_formula: "Chutki < Muthi",
    meaning:
      "Everyday informal cooking-quantity gestures in Meitei valley households",
    historical_period:
      "British colonial princely-state period (Manipur, one of the last princely states annexed, from 1891) and post-1949 Indian administration",
    region_applicable: "Imphal Valley — the historic Meitei kingdom heartland",
    states: ["Manipur"],
    used_in: [
      "Everyday informal cooking-quantity gestures in Meitei valley households",
      "Household & Daily Life",
    ],
    references: ["https://en.wikipedia.org/wiki/Handful"],
    tags: [
      "manipur",
      "traditional-units",
      "household",
      "chutki",
      "muthi",
      "cooking",
      "informal",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "manipur-hh-2",
    slug: "chittak-chhatak-household-manipur",
    name_english: "Chittak (Chhatak)",
    name_sanskrit: "N/A (vernacular)",
    local_names: [],
    name_hindi: "छटाक",
    category: "weight",
    measurement_type: "Weight",
    sector: "household",
    origin: "Manipur (Imphal Valley)",
    modern_equivalent: "~58.3 g",
    conversion_formula: "1/16 Ser = 1 Chittak",
    meaning:
      "Everyday kitchen weighing of spices and flour, adopted through colonial-era trade contact",
    historical_period:
      "British colonial princely-state period (Manipur, one of the last princely states annexed, from 1891) and post-1949 Indian administration",
    region_applicable: "Imphal Valley — the historic Meitei kingdom heartland",
    states: ["Manipur"],
    used_in: [
      "Everyday kitchen weighing of spices and flour, adopted through colonial-era trade contact",
      "Household & Daily Life",
    ],
    references: [
      "https://grokipedia.com/page/Seer_(unit)",
      "https://en.wikipedia.org/wiki/Maund",
    ],
    tags: [
      "manipur",
      "traditional-units",
      "household",
      "chittak",
      "chhatak",
      "kitchen-weight",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "manipur-hh-3",
    slug: "bamboo-container-household-manipur",
    name_english: "(Bamboo container — hill households)",
    name_sanskrit: "N/A — vessel-based, no fixed named hierarchy documented",
    local_names: [],
    name_hindi: "बांस पात्र (जनोपचारिक)",
    category: "volume",
    measurement_type: "Volume (utility, informal)",
    sector: "household",
    origin: "Manipur (Hill Districts)",
    modern_equivalent:
      "Determined by the natural size of the bamboo internode used",
    conversion_formula: "No standardised hierarchy",
    meaning:
      "Hollowed bamboo sections are used across Naga and Kuki-Zo hill households to store and informally measure rice and rice-beer (zu)",
    historical_period:
      "Customary/traditional practice of Manipur's Naga and Kuki-Zo hill communities, predating and continuing alongside Meitei valley administration",
    region_applicable:
      "Hill districts — Naga (Tangkhul, Mao, Poumai) and Kuki-Zo (Thadou, Zomi, Hmar) homelands",
    states: ["Manipur"],
    used_in: [
      "Hollowed bamboo sections are used across Naga and Kuki-Zo hill households to store and informally measure rice and rice-beer (zu)",
      "Household & Daily Life",
    ],
    references: [
      "No standardised metrological reference documented for this practice",
    ],
    tags: [
      "manipur",
      "traditional-units",
      "household",
      "bamboo-container",
      "hill-households",
      "naga",
      "kuki-zo",
      "zu",
    ],
    created_at: "2024-01-01",
  },

  // ─── 5. Gold & Jewellery (3 units) ──────────────────────────────────────────
  {
    id: "manipur-gold-1",
    slug: "ratti-gold-manipur",
    name_english: "Ratti",
    name_sanskrit: "रत्ति (Ratti / Raktika)",
    local_names: [],
    name_hindi: "रत्ती",
    category: "weight",
    measurement_type: "Weight",
    sector: "gold-jewellery",
    origin: "Manipur (Imphal Valley)",
    modern_equivalent: "~0.1215 g",
    conversion_formula: "Base gold/gem unit",
    meaning:
      "Traditional small-ornament weighing by Imphal jewellers, in a kingdom whose own state anthem — \"Sana Leibak Manipur\", literally 'Manipur, Land of Gold' — names gold directly",
    historical_period:
      "Vedic–Classical Sanskrit period (c. 1000 BCE–500 CE), reaching Manipur through Vaishnavite influence from the 18th century onward",
    region_applicable: "Imphal Valley — the historic Meitei kingdom heartland",
    states: ["Manipur"],
    used_in: [
      "Traditional small-ornament weighing by Imphal jewellers, in a kingdom whose own state anthem — \"Sana Leibak Manipur\", literally 'Manipur, Land of Gold' — names gold directly",
      "Gold & Jewellery",
    ],
    references: ["https://en.wikipedia.org/wiki/Ratti_(unit)"],
    tags: [
      "manipur",
      "traditional-units",
      "gold-jewellery",
      "ratti",
      "gold",
      "jewellery",
      "imphal",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "manipur-gold-2",
    slug: "tola-gold-manipur",
    name_english: "Tola",
    name_sanskrit: "तोला (Tola)",
    local_names: [],
    name_hindi: "तोला",
    category: "weight",
    measurement_type: "Weight",
    sector: "gold-jewellery",
    origin: "Manipur (Imphal Valley)",
    modern_equivalent: "~11.66 g",
    conversion_formula: "12 Masha = 1 Tola",
    meaning:
      "Principal gold-trade weight in the Meitei valley's jewellery bazaars, including the historic Sana Keithel ('Golden Market') in Imphal",
    historical_period:
      "Vedic–Classical Sanskrit period (c. 1000 BCE–500 CE), reaching Manipur through Vaishnavite influence from the 18th century onward",
    region_applicable: "Imphal Valley — the historic Meitei kingdom heartland",
    states: ["Manipur"],
    used_in: [
      "Principal gold-trade weight in the Meitei valley's jewellery bazaars, including the historic Sana Keithel ('Golden Market') in Imphal",
      "Gold & Jewellery",
    ],
    references: ["https://en.wikipedia.org/wiki/Tola_(unit)"],
    tags: [
      "manipur",
      "traditional-units",
      "gold-jewellery",
      "tola",
      "gold",
      "sana-keithel",
      "imphal",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "manipur-gold-3",
    slug: "bead-mithun-wealth-reckoning-gold-manipur",
    name_english: "(Bead and Mithun-based wealth reckoning — hill districts)",
    name_sanskrit: "N/A — count/livestock-based, not a weight unit",
    local_names: [],
    name_hindi: "मनका/मिथुन धन (जनोपचारिक)",
    category: "other",
    measurement_type: "Count/Livestock unit (informal)",
    sector: "gold-jewellery",
    origin: "Manipur (Hill Districts)",
    modern_equivalent:
      "Valued by bead-count, craftsmanship or number of Mithun owned rather than by a gold-weight scale",
    conversion_formula: "No fixed hierarchy",
    meaning:
      "As in neighbouring Nagaland and Arunachal Pradesh, Manipur's Naga and Kuki-Zo hill communities traditionally reckoned high-value wealth through beads and livestock (Mithun) rather than by a gold-weight scale weighed by the valley's Tola scale",
    historical_period:
      "Customary/traditional practice of Manipur's Naga and Kuki-Zo hill communities, predating and continuing alongside Meitei valley administration",
    region_applicable:
      "Hill districts — Naga (Tangkhul, Mao, Poumai) and Kuki-Zo (Thadou, Zomi, Hmar) homelands",
    states: ["Manipur"],
    used_in: [
      "As in neighbouring Nagaland and Arunachal Pradesh, Manipur's Naga and Kuki-Zo hill communities traditionally reckoned high-value wealth through beads and livestock (Mithun) rather than by a gold-weight scale weighed by the valley's Tola scale",
      "Gold & Jewellery",
    ],
    references: [
      "https://www.insidene.com/importance-of-the-mithun-in-arunachal-pradesh/",
    ],
    tags: [
      "manipur",
      "traditional-units",
      "gold-jewellery",
      "beads",
      "mithun",
      "wealth",
      "hill-districts",
      "naga",
      "kuki-zo",
    ],
    created_at: "2024-01-01",
  },

  // ─── 6. Seed & Crop (Agriculture) (4 units) ─────────────────────────────────
  {
    id: "manipur-agri-1",
    slug: "ser-seer-agri-manipur",
    name_english: "Ser (Seer)",
    name_sanskrit: "सेर (Sēra)",
    local_names: [],
    name_hindi: "सेर",
    category: "weight",
    measurement_type: "Weight",
    sector: "agriculture",
    origin: "Manipur (Imphal Valley)",
    modern_equivalent: "~0.93 kg",
    conversion_formula: "16 Chittak = 1 Ser",
    meaning:
      "Standard measure for seed grain and harvested paddy in the wet-rice fields of the Imphal Valley",
    historical_period:
      "British colonial princely-state period (Manipur, one of the last princely states annexed, from 1891) and post-1949 Indian administration",
    region_applicable: "Imphal Valley — the historic Meitei kingdom heartland",
    states: ["Manipur"],
    used_in: [
      "Standard measure for seed grain and harvested paddy in the wet-rice fields of the Imphal Valley",
      "Seed & Crop (Agriculture)",
    ],
    references: [
      "https://grokipedia.com/page/Seer_(unit)",
      "https://en.wikipedia.org/wiki/Maund",
    ],
    tags: [
      "manipur",
      "traditional-units",
      "agriculture",
      "ser",
      "seer",
      "grain",
      "paddy",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "manipur-agri-2",
    slug: "mon-maund-agri-manipur",
    name_english: "Mon (Maund)",
    name_sanskrit: "মণ (Māna)",
    local_names: [],
    name_hindi: "मन",
    category: "weight",
    measurement_type: "Weight",
    sector: "agriculture",
    origin: "Manipur (Imphal Valley)",
    modern_equivalent: "~37.3 kg",
    conversion_formula: "40 Ser = 1 Mon",
    meaning: "Principal wholesale unit for paddy sale at Imphal Valley markets",
    historical_period:
      "British colonial princely-state period (Manipur, one of the last princely states annexed, from 1891) and post-1949 Indian administration",
    region_applicable: "Imphal Valley — the historic Meitei kingdom heartland",
    states: ["Manipur"],
    used_in: [
      "Principal wholesale unit for paddy sale at Imphal Valley markets",
      "Seed & Crop (Agriculture)",
    ],
    references: [
      "https://grokipedia.com/page/Seer_(unit)",
      "https://en.wikipedia.org/wiki/Maund",
    ],
    tags: [
      "manipur",
      "traditional-units",
      "agriculture",
      "mon",
      "maund",
      "wholesale",
      "paddy",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "manipur-agri-3",
    slug: "sangam-loukhai-agri-manipur",
    name_english: "Sangam / Loukhai (wet-rice field plots)",
    name_sanskrit: "N/A (Meitei vernacular revenue term)",
    local_names: ["সংগম / লৌখাই"],
    name_hindi: "संगम / लौखाई",
    category: "area",
    measurement_type: "Area",
    sector: "agriculture",
    origin: "Manipur (Loktak Lake)",
    modern_equivalent:
      "Sangam ~27,225 sq ft, Loukhai ~13,612.5 sq ft",
    conversion_formula: "2 Loukhai = 1 Sangam",
    meaning:
      "Field-size unit for reckoning sowing area and expected yield on the fertile wet-rice land around Loktak Lake",
    historical_period:
      "Ningthouja/Meitei kingdom period (Nongda Lairen Pakhangba, traditionally dated 33 CE, through to the 1891 British takeover)",
    region_applicable:
      "Loktak Lake and surrounding wetlands, Bishnupur district",
    states: ["Manipur"],
    used_in: [
      "Field-size unit for reckoning sowing area and expected yield on the fertile wet-rice land around Loktak Lake",
      "Seed & Crop (Agriculture)",
    ],
    references: [
      "https://kanglaonline.in/area-converter/",
      "https://ingkhol.com/tools/manipur-area-converter",
    ],
    tags: [
      "manipur",
      "traditional-units",
      "agriculture",
      "sangam",
      "loukhai",
      "wet-rice",
      "loktak-lake",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "manipur-agri-4",
    slug: "basket-load-jhum-agri-manipur",
    name_english: "(Basket-load Jhum reckoning — hill districts)",
    name_sanskrit:
      "N/A — vessel-based, no fixed named weight/volume unit documented",
    local_names: [],
    name_hindi: "टोकरी-भार (जनोपचारिक)",
    category: "volume",
    measurement_type: "Weight/Volume (informal)",
    sector: "agriculture",
    origin: "Manipur (Hill Districts)",
    modern_equivalent:
      "Determined by the size of the woven bamboo carrying-basket in use",
    conversion_formula: "No standardised hierarchy",
    meaning:
      "Jhum (shifting-cultivation) harvests of rice and millet in Manipur's hill districts were traditionally carried and quantified basket-by-basket, distinct from the Sangam/Loukhai-measured wet-rice fields of the valley",
    historical_period:
      "Customary/traditional practice of Manipur's Naga and Kuki-Zo hill communities, predating and continuing alongside Meitei valley administration",
    region_applicable:
      "Hill districts — Naga (Tangkhul, Mao, Poumai) and Kuki-Zo (Thadou, Zomi, Hmar) homelands",
    states: ["Manipur"],
    used_in: [
      "Jhum (shifting-cultivation) harvests of rice and millet in Manipur's hill districts were traditionally carried and quantified basket-by-basket, distinct from the Sangam/Loukhai-measured wet-rice fields of the valley",
      "Seed & Crop (Agriculture)",
    ],
    references: [
      "No standardised metrological reference documented for this practice",
    ],
    tags: [
      "manipur",
      "traditional-units",
      "agriculture",
      "jhum",
      "basket-load",
      "hill-districts",
      "naga",
      "kuki-zo",
    ],
    created_at: "2024-01-01",
  },

  // ─── 7. Currency & Money (5 units) ──────────────────────────────────────────
  {
    id: "manipur-curr-1",
    slug: "barter-economy-pre-coinage-currency-manipur",
    name_english: "(Barter economy — pre-coinage)",
    name_sanskrit: "N/A — no named unit; a practice, not a fixed unit",
    local_names: [],
    name_hindi: "वस्तु-विनिमय",
    category: "other",
    measurement_type: "Exchange system (non-monetary)",
    sector: "currency-money",
    origin: "Pan-Manipur generally",
    modern_equivalent: "Not applicable",
    conversion_formula: "No fixed hierarchy",
    meaning:
      "Documented as Manipur's original economic system, predating and coexisting with coinage for centuries",
    historical_period:
      "Ningthouja/Meitei kingdom period (Nongda Lairen Pakhangba, traditionally dated 33 CE, through to the 1891 British takeover)",
    region_applicable: "Pan-Manipur generally",
    states: ["Manipur"],
    used_in: [
      "Documented as Manipur's original economic system, predating and coexisting with coinage for centuries",
      "Currency & Money",
    ],
    references: [
      "https://www.granthaalayahpublication.org/Arts-Journal/ShodhKosh/article/download/3303/2971/19610",
    ],
    tags: [
      "manipur",
      "traditional-units",
      "currency-money",
      "barter",
      "exchange-system",
      "meitei",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "manipur-curr-2",
    slug: "meitei-bronze-coin-ura-konthouba-currency-manipur",
    name_english: "Meitei bronze coin (Ura Konthouba era)",
    name_sanskrit: "N/A (archaic Meitei script inscription)",
    local_names: [],
    name_hindi: "मैतेई कांस्य सिक्का",
    category: "currency",
    measurement_type: "Currency",
    sector: "currency-money",
    origin: "Manipur (Imphal Valley)",
    modern_equivalent:
      "Bronze coin, dated by surviving examples to 568–658 CE",
    conversion_formula: "Earliest firmly attested Meitei coinage",
    meaning:
      "Minted under the Ningthouja dynasty; the royal chronicle Cheitharol Kumbaba records that King Khagemba's later coin issue coincided with 'all round progress in the kingdom'",
    historical_period:
      "Ningthouja/Meitei kingdom period (Nongda Lairen Pakhangba, traditionally dated 33 CE, through to the 1891 British takeover)",
    region_applicable: "Imphal Valley — the historic Meitei kingdom heartland",
    states: ["Manipur"],
    used_in: [
      "Minted under the Ningthouja dynasty; the royal chronicle Cheitharol Kumbaba records that King Khagemba's later coin issue coincided with 'all round progress in the kingdom'",
      "Currency & Money",
    ],
    references: [
      "https://simple.wikipedia.org/wiki/Meitei_currency",
      "https://www.mintageworld.com/media/detail/11816-bell-metal-sel-of-manipur/",
    ],
    tags: [
      "manipur",
      "traditional-units",
      "currency-money",
      "bronze-coin",
      "ura-konthouba",
      "ningthouja",
      "meitei-script",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "manipur-curr-3",
    slug: "bell-metal-sel-currency-manipur",
    name_english: "Bell Metal Sel",
    name_sanskrit: "N/A (Meitei vernacular coin-name)",
    local_names: ["শেল"],
    name_hindi: "बेल मेटल सेल",
    category: "currency",
    measurement_type: "Currency",
    sector: "currency-money",
    origin: "Manipur (Imphal Valley)",
    modern_equivalent: "~1.3 g bell-metal (bronze-alloy) coin",
    conversion_formula:
      "Standard denomination of Khagemba's currency reform",
    meaning:
      "Distributed by the king himself at the Sana Keithel royal market as a public gesture of goodwill; women reportedly resisted an early royal plan to issue copper coins instead",
    historical_period:
      "Reign of King Khagemba (1597–1652 CE), who redeemed the Sana Lamjel and introduced the Bell Metal Sel",
    region_applicable: "Imphal Valley — the historic Meitei kingdom heartland",
    states: ["Manipur"],
    used_in: [
      "Distributed by the king himself at the Sana Keithel royal market as a public gesture of goodwill; women reportedly resisted an early royal plan to issue copper coins instead",
      "Currency & Money",
    ],
    references: [
      "https://simple.wikipedia.org/wiki/Meitei_currency",
      "https://www.mintageworld.com/media/detail/11816-bell-metal-sel-of-manipur/",
    ],
    tags: [
      "manipur",
      "traditional-units",
      "currency-money",
      "bell-metal-sel",
      "sel",
      "coinage",
      "khagemba",
      "imphal",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "manipur-curr-4",
    slug: "cheitharol-kumbaba-royal-chronicle-currency-manipur",
    name_english:
      "Cheitharol Kumbaba (royal chronicle) — a dating instrument, not a coin",
    name_sanskrit: "N/A — a chronicle, not a currency unit",
    local_names: ["চৈথারোল কুম্বাবা"],
    name_hindi: "चैथारोल कुम्बाबा",
    category: "other",
    measurement_type: "Calendar/Record (chronicling instrument)",
    sector: "currency-money",
    origin: "Manipur (Imphal Valley)",
    modern_equivalent:
      "A day-by-day royal chronicle maintained continuously since the reign of Pakhangba (traditionally from 33 CE)",
    conversion_formula:
      "Not applicable — a documentary record rather than a subdivided unit",
    meaning:
      "Manipur's own currency and land-unit history is known largely through this remarkable unbroken court chronicle, itself a form of historical 'measurement' — a continuous, dated administrative record with few parallels among India's regional kingdoms",
    historical_period:
      "Ningthouja/Meitei kingdom period (Nongda Lairen Pakhangba, traditionally dated 33 CE, through to the 1891 British takeover)",
    region_applicable: "Imphal Valley — the historic Meitei kingdom heartland",
    states: ["Manipur"],
    used_in: [
      "Manipur's own currency and land-unit history is known largely through this remarkable unbroken court chronicle, itself a form of historical 'measurement' — a continuous, dated administrative record with few parallels among India's regional kingdoms",
      "Currency & Money",
    ],
    references: [
      "https://www.granthaalayahpublication.org/Arts-Journal/ShodhKosh/article/download/3303/2971/19610",
    ],
    tags: [
      "manipur",
      "traditional-units",
      "currency-money",
      "cheitharol-kumbaba",
      "chronicle",
      "pakhangba",
      "meitei",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "manipur-curr-5",
    slug: "indian-rupee-currency-manipur",
    name_english: "Indian Rupee (post-1891/1949)",
    name_sanskrit: "N/A",
    local_names: [],
    name_hindi: "रुपया",
    category: "currency",
    measurement_type: "Currency",
    sector: "currency-money",
    origin: "Pan-Manipur generally",
    modern_equivalent: "Standard Indian Rupee",
    conversion_formula: "Superseded the Sel/bronze coin system",
    meaning:
      "Became Manipur's standard currency following British annexation in 1891 and the kingdom's 1949 merger with the Indian Union",
    historical_period:
      "British colonial princely-state period (Manipur, one of the last princely states annexed, from 1891) and post-1949 Indian administration",
    region_applicable: "Pan-Manipur generally",
    states: ["Manipur"],
    used_in: [
      "Became Manipur's standard currency following British annexation in 1891 and the kingdom's 1949 merger with the Indian Union",
      "Currency & Money",
    ],
    references: ["https://en.wikipedia.org/wiki/Manipur"],
    tags: [
      "manipur",
      "traditional-units",
      "currency-money",
      "indian-rupee",
      "british-period",
      "currency",
    ],
    created_at: "2024-01-01",
  },

  // ─── 8. Storage & Transportation (3 units) ───────────────────────────────────
  {
    id: "manipur-storage-1",
    slug: "ser-mon-storage-manipur",
    name_english: "Ser / Mon (Seer/Maund)",
    name_sanskrit: "सेर / मन",
    local_names: [],
    name_hindi: "सेर / मन",
    category: "weight",
    measurement_type: "Weight",
    sector: "storage-transport",
    origin: "Manipur (Imphal Valley)",
    modern_equivalent: "~0.93 kg Ser; 40 Ser = 1 Mon ≈ 37.3 kg",
    conversion_formula: "40 Ser = 1 Mon",
    meaning:
      "Standard granary and warehouse storage unit for paddy in the Imphal Valley",
    historical_period:
      "British colonial princely-state period (Manipur, one of the last princely states annexed, from 1891) and post-1949 Indian administration",
    region_applicable: "Imphal Valley — the historic Meitei kingdom heartland",
    states: ["Manipur"],
    used_in: [
      "Standard granary and warehouse storage unit for paddy in the Imphal Valley",
      "Storage & Transportation",
    ],
    references: [
      "https://grokipedia.com/page/Seer_(unit)",
      "https://en.wikipedia.org/wiki/Maund",
    ],
    tags: [
      "manipur",
      "traditional-units",
      "storage-transport",
      "ser",
      "mon",
      "seer",
      "maund",
      "granary",
      "warehouse",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "manipur-storage-2",
    slug: "phumdi-boat-load-storage-manipur",
    name_english: "(Phumdi/boat load reckoning — Loktak Lake)",
    name_sanskrit:
      "N/A — vessel/structure based, no fixed named unit documented",
    local_names: [],
    name_hindi: "फुम्दी/नौका भार (अनौपचारिक)",
    category: "volume",
    measurement_type: "Weight/Volume (informal, load based)",
    sector: "storage-transport",
    origin: "Manipur (Loktak Lake)",
    modern_equivalent:
      "Determined by individual boat or floating-hut (phumsang) capacity",
    conversion_formula: "No standardised hierarchy",
    meaning:
      "Loktak Lake — the largest freshwater lake in Northeast India, famous for its floating Phumdi islands of vegetation — has long supported a fishing economy in which catch and cargo were traditionally reckoned by boat-load rather than a fixed named weight unit",
    historical_period:
      "Ningthouja/Meitei kingdom period (Nongda Lairen Pakhangba, traditionally dated 33 CE, through to the 1891 British takeover)",
    region_applicable:
      "Loktak Lake and surrounding wetlands, Bishnupur district",
    states: ["Manipur"],
    used_in: [
      "Loktak Lake — the largest freshwater lake in Northeast India, famous for its floating Phumdi islands of vegetation — has long supported a fishing economy in which catch and cargo were traditionally reckoned by boat-load rather than a fixed named weight unit",
      "Storage & Transportation",
    ],
    references: ["https://en.wikipedia.org/wiki/Loktak_Lake"],
    tags: [
      "manipur",
      "traditional-units",
      "storage-transport",
      "phumdi",
      "boat-load",
      "loktak-lake",
      "phumsang",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "manipur-storage-3",
    slug: "porter-headload-storage-manipur",
    name_english: "(Porter/headload reckoning — hill districts)",
    name_sanskrit: "N/A — body-based, no fixed named unit documented",
    local_names: [],
    name_hindi: "सिर-भार (जनोपचारिक)",
    category: "weight",
    measurement_type: "Weight (informal, load-based)",
    sector: "storage-transport",
    origin: "Manipur (Hill Districts)",
    modern_equivalent:
      "One person's comfortable carrying load over hill-trail terrain",
    conversion_formula: "No standardised hierarchy",
    meaning:
      "In Manipur's hill districts, goods were traditionally moved between villages by human porterage, with loads reckoned informally, distinct from the valley's road- and lake-based transport",
    historical_period:
      "Customary/traditional practice of Manipur's Naga and Kuki-Zo hill communities, predating and continuing alongside Meitei valley administration",
    region_applicable:
      "Hill districts — Naga (Tangkhul, Mao, Poumai) and Kuki-Zo (Thadou, Zomi, Hmar) homelands",
    states: ["Manipur"],
    used_in: [
      "In Manipur's hill districts, goods were traditionally moved between villages by human porterage, with loads reckoned informally, distinct from the valley's road- and lake-based transport",
      "Storage & Transportation",
    ],
    references: [
      "No standardised metrological reference documented for this practice",
    ],
    tags: [
      "manipur",
      "traditional-units",
      "storage-transport",
      "porter",
      "headload",
      "hill-districts",
      "naga",
      "kuki-zo",
    ],
    created_at: "2024-01-01",
  },

  // ─── 9. Religious & Cultural (5 units) ───────────────────────────────────────
  {
    id: "manipur-relig-1",
    slug: "sajibu-nongma-panba-cheiraoba-relig-manipur",
    name_english:
      "Sajibu Nongma Panba (Cheiraoba) — lunar new year, not a subdivided unit",
    name_sanskrit: "N/A — a fixed calendar date, not a hierarchical unit",
    local_names: ["সজিবু নোংমা পান্বা"],
    name_hindi: "चेराओबा",
    category: "time",
    measurement_type: "Calendar (lunar new year marker)",
    sector: "religious-cultural",
    origin: "Manipur (Imphal Valley)",
    modern_equivalent:
      "The first lunar day of the month of Sajibu in the Meitei lunar calendar, generally falling in March, occasionally April",
    conversion_formula: "Not applicable — a single annual calendar marker",
    meaning:
      "The Meitei lunar new year, observed by followers of the indigenous Sanamahi faith with worship of the guardian deity Lainingthou Sanamahi, ritual house-cleaning, and the evening Thabal Chongba group dance",
    historical_period:
      "Ancient–Puranic/Sanamahi syncretic period; still ritually observed today",
    region_applicable: "Imphal Valley — the historic Meitei kingdom heartland",
    states: ["Manipur"],
    used_in: [
      "The Meitei lunar new year, observed by followers of the indigenous Sanamahi faith with worship of the guardian deity Lainingthou Sanamahi, ritual house-cleaning, and the evening Thabal Chongba group dance",
      "Religious & Cultural",
    ],
    references: [
      "https://en.wikipedia.org/wiki/Sajibu_Nongma_Panba",
      "https://en.wikipedia.org/wiki/Meitei_festivals",
    ],
    tags: [
      "manipur",
      "traditional-units",
      "religious-cultural",
      "sajibu-nongma-panba",
      "cheiraoba",
      "meitei-new-year",
      "sanamahi",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "manipur-relig-2",
    slug: "lai-haraoba-relig-manipur",
    name_english: "Lai Haraoba",
    name_sanskrit: "N/A — a festival name, not a subdivided time unit",
    local_names: ["লাই হারাওবা"],
    name_hindi: "लाई हराओबा",
    category: "time",
    measurement_type: "Calendar (ritual festival marker)",
    sector: "religious-cultural",
    origin: "Pan-Manipur generally",
    modern_equivalent:
      "Observed annually, typically between April and June, timing varying by locality and presiding deity",
    conversion_formula:
      "Not applicable — a ritual-cycle festival rather than a numeric time subdivision",
    meaning:
      "The principal ritual festival of Sanamahism, 'the merrymaking of the gods', involving days of ritual dance, music and re-enactment of Meitei creation mythology at village shrines dedicated to the Umang Lai (forest deities)",
    historical_period:
      "Ancient–Puranic/Sanamahi syncretic period; still ritually observed today",
    region_applicable: "Pan-Manipur generally",
    states: ["Manipur"],
    used_in: [
      "The principal ritual festival of Sanamahism, 'the merrymaking of the gods', involving days of ritual dance, music and re-enactment of Meitei creation mythology at village shrines dedicated to the Umang Lai (forest deities)",
      "Religious & Cultural",
    ],
    references: ["https://en.wikipedia.org/wiki/Lai_Haraoba"],
    tags: [
      "manipur",
      "traditional-units",
      "religious-cultural",
      "lai-haraoba",
      "sanamahism",
      "umang-lai",
      "meitei",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "manipur-relig-3",
    slug: "nadika-ghatika-muhurta-relig-manipur",
    name_english: "Nadika (Ghatika) / Muhurta (classical reference)",
    name_sanskrit: "नाडिका / मुहूर्त (Nādikā / Muhūrta)",
    local_names: [],
    name_hindi: "नाड़ी / मुहूर्त",
    category: "time",
    measurement_type: "Time",
    sector: "religious-cultural",
    origin: "Manipur (Imphal Valley)",
    modern_equivalent: "~24 minutes (Nadika); ~48 minutes (Muhurta)",
    conversion_formula: "2 Nadika = 1 Muhurta",
    meaning:
      "Used for fixing auspicious timings at Vaishnavite temples such as the Shri Govindajee Temple in Imphal, following Hindu ritual practice introduced from the 18th century",
    historical_period:
      "Vedic–Classical Sanskrit period (c. 1000 BCE–500 CE), reaching Manipur through Vaishnavite influence from the 18th century onward",
    region_applicable: "Imphal Valley — the historic Meitei kingdom heartland",
    states: ["Manipur"],
    used_in: [
      "Used for fixing auspicious timings at Vaishnavite temples such as the Shri Govindajee Temple in Imphal, following Hindu ritual practice introduced from the 18th century",
      "Religious & Cultural",
    ],
    references: ["https://en.wikipedia.org/wiki/Muhurta"],
    tags: [
      "manipur",
      "traditional-units",
      "religious-cultural",
      "nadika",
      "ghatika",
      "muhurta",
      "vaishnavite",
      "temple-time",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "manipur-relig-4",
    slug: "yojana-krosha-pilgrimage-distance-relig-manipur",
    name_english:
      "Yojana / Krosha (pilgrimage distance, classical reference)",
    name_sanskrit: "योजन / क्रोश (Yojana / Krośa)",
    local_names: [],
    name_hindi: "योजन / कोस",
    category: "length",
    measurement_type: "Distance",
    sector: "religious-cultural",
    origin: "Manipur (Imphal Valley)",
    modern_equivalent: "~11–14.5 km (Yojana); ~3.2 km (Krosha)",
    conversion_formula: "4 Krosha = 1 Yojana",
    meaning:
      "Puranic-scale distance unit used in describing pilgrimage geography around Vaishnavite shrines in the Imphal Valley",
    historical_period:
      "Vedic–Classical Sanskrit period (c. 1000 BCE–500 CE), reaching Manipur through Vaishnavite influence from the 18th century onward",
    region_applicable: "Imphal Valley — the historic Meitei kingdom heartland",
    states: ["Manipur"],
    used_in: [
      "Puranic-scale distance unit used in describing pilgrimage geography around Vaishnavite shrines in the Imphal Valley",
      "Religious & Cultural",
    ],
    references: ["https://en.wikipedia.org/wiki/Yojana"],
    tags: [
      "manipur",
      "traditional-units",
      "religious-cultural",
      "yojana",
      "krosha",
      "pilgrimage",
      "vaishnavite",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "manipur-relig-5",
    slug: "cheitharol-kumbaba-dating-convention-relig-manipur",
    name_english: "Cheitharol Kumbaba dating convention",
    name_sanskrit:
      "N/A — a continuous royal-chronicle record, not a subdivided unit",
    local_names: ["চৈথারোল কুম্বাবা"],
    name_hindi: "चैथारोल कुम्बाबा",
    category: "time",
    measurement_type: "Calendar/Record (chronicling instrument)",
    sector: "religious-cultural",
    origin: "Manipur (Imphal Valley)",
    modern_equivalent:
      "A continuous day-dated chronicle maintained since the traditional 33 CE founding of the Ningthouja dynasty",
    conversion_formula:
      "Not applicable — a documentary record rather than a subdivided time unit",
    meaning:
      "The single most important source for Manipur's own traditional chronology, recording kings' reigns, wars, coin-issues and natural events day by day — used by later historians to anchor Manipur's entire timeline, including the dating of the Sana Lamjel and the coinage entries in this workbook",
    historical_period:
      "Ningthouja/Meitei kingdom period (Nongda Lairen Pakhangba, traditionally dated 33 CE, through to the 1891 British takeover)",
    region_applicable: "Imphal Valley — the historic Meitei kingdom heartland",
    states: ["Manipur"],
    used_in: [
      "The single most important source for Manipur's own traditional chronology, recording kings' reigns, wars, coin-issues and natural events day by day — used by later historians to anchor Manipur's entire timeline, including the dating of the Sana Lamjel and the coinage entries in this workbook",
      "Religious & Cultural",
    ],
    references: [
      "https://www.granthaalayahpublication.org/Arts-Journal/ShodhKosh/article/download/3303/2971/19610",
    ],
    tags: [
      "manipur",
      "traditional-units",
      "religious-cultural",
      "cheitharol-kumbaba",
      "chronicle",
      "ningthouja",
      "meitei-chronology",
    ],
    created_at: "2024-01-01",
  },

  // ─── 10. Trade & Commerce (4 units) ─────────────────────────────────────────
  {
    id: "manipur-trade-1",
    slug: "barter-economy-pre-coinage-manipur",
    name_english: "(Barter economy — pre-coinage)",
    name_sanskrit: "N/A — no named unit; a practice, not a fixed unit",
    local_names: [],
    name_hindi: "वस्तु-विनिमय",
    category: "other",
    measurement_type: "Exchange system (non-monetary)",
    sector: "trade-commerce",
    origin: "Pan-Manipur generally",
    modern_equivalent: "Not applicable — reckoned good-for-good",
    conversion_formula: "No fixed hierarchy",
    meaning:
      "A 2023 academic study of Manipur's coinage system records that Manipuri society practiced barter to fulfill its needs before and alongside the introduction of coined money — all business was carried on by exchange",
    historical_period:
      "Ningthouja/Meitei kingdom period (Nongda Lairen Pakhangba, traditionally dated 33 CE, through to the 1891 British takeover)",
    region_applicable: "Pan-Manipur generally",
    states: ["Manipur"],
    used_in: [
      "A 2023 academic study of Manipur's coinage system records that Manipuri society practiced barter to fulfill its needs before and alongside the introduction of coined money — all business was carried on by exchange",
      "Trade & Commerce",
    ],
    references: [
      "https://www.granthaalayahpublication.org/Arts-Journal/ShodhKosh/article/download/3303/2971/19610",
    ],
    tags: [
      "manipur",
      "traditional-units",
      "trade-commerce",
      "barter",
      "exchange-system",
      "meitei",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "manipur-trade-2",
    slug: "bell-metal-sel-trade-manipur",
    name_english: "Bell Metal Sel",
    name_sanskrit: "N/A (Meitei vernacular coin-name)",
    local_names: ["শেল"],
    name_hindi: "बेल मेटल सेल",
    category: "currency",
    measurement_type: "Currency",
    sector: "trade-commerce",
    origin: "Manipur (Imphal Valley)",
    modern_equivalent: "~1.3 g, uniface bell metal (bronze alloy) coin",
    conversion_formula:
      "The standard small-denomination coin of Khagemba's monetary reform",
    meaning:
      "Introduced by King Khagemba (r. 1597–1652), used in Manipur's markets — most famously the Sana Keithel ('Golden Market') in Imphal, where the king himself would ceremonially throw coins to the public as a gesture of goodwill",
    historical_period:
      "Reign of King Khagemba (1597–1652 CE), who redeemed the Sana Lamjel and introduced the Bell Metal Sel",
    region_applicable: "Imphal Valley — the historic Meitei kingdom heartland",
    states: ["Manipur"],
    used_in: [
      "Introduced by King Khagemba (r. 1597–1652), used in Manipur's markets — most famously the Sana Keithel ('Golden Market') in Imphal, where the king himself would ceremonially throw coins to the public as a gesture of goodwill",
      "Trade & Commerce",
    ],
    references: [
      "https://simple.wikipedia.org/wiki/Meitei_currency",
      "https://www.mintageworld.com/media/detail/11816-bell-metal-sel-of-manipur/",
    ],
    tags: [
      "manipur",
      "traditional-units",
      "trade-commerce",
      "bell-metal-sel",
      "sel",
      "coinage",
      "khagemba",
      "imphal",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "manipur-trade-3",
    slug: "meitei-bronze-coin-ura-konthouba-manipur",
    name_english: "Meitei bronze coin (Ura Konthouba issue)",
    name_sanskrit: "N/A (archaic Meitei script inscription)",
    local_names: [],
    name_hindi: "मैतेई कांस्य सिक्का",
    category: "currency",
    measurement_type: "Currency",
    sector: "trade-commerce",
    origin: "Manipur (Imphal Valley)",
    modern_equivalent:
      "Bronze coin, inscribed in archaic Meitei script, earliest firmly dated pieces run 568–658 CE",
    conversion_formula: "Predates the later Bell Metal Sel system",
    meaning:
      "Traditionally credited to King Ura Konthouba (coronated 567 CE); some historians push the origin of Meitei coinage as far back as the legendary 1st century CE reign of Nongda Lairen Pakhangba, though firm evidence supports the 7th century",
    historical_period: "Ningthouja dynasty, 6th–7th century CE onward",
    region_applicable: "Imphal Valley — the historic Meitei kingdom heartland",
    states: ["Manipur"],
    used_in: [
      "Traditionally credited to King Ura Konthouba (coronated 567 CE); some historians push the origin of Meitei coinage as far back as the legendary 1st century CE reign of Nongda Lairen Pakhangba, though firm evidence supports the 7th century",
      "Trade & Commerce",
    ],
    references: [
      "https://simple.wikipedia.org/wiki/Meitei_currency",
      "https://www.mintageworld.com/media/detail/11816-bell-metal-sel-of-manipur/",
    ],
    tags: [
      "manipur",
      "traditional-units",
      "trade-commerce",
      "bronze-coin",
      "ura-konthouba",
      "ningthouja",
      "meitei-script",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "manipur-trade-4",
    slug: "ser-mon-trade-manipur",
    name_english: "Ser / Mon (Seer/Maund)",
    name_sanskrit: "सेर / मन",
    local_names: [],
    name_hindi: "सेर / मन",
    category: "weight",
    measurement_type: "Weight",
    sector: "trade-commerce",
    origin: "Pan-Manipur generally",
    modern_equivalent: "~0.93 kg Ser; 40 Ser = 1 Mon ≈ 37.3 kg",
    conversion_formula: "40 Ser = 1 Mon",
    meaning:
      "Standard bazaar weight for rice and other bulk goods, adopted through colonial-era trade contact with Cachar/Sylhet and the wider Bengal/Assam trading network",
    historical_period:
      "British colonial princely-state period (Manipur, one of the last princely states annexed, from 1891) and post-1949 Indian administration",
    region_applicable: "Pan-Manipur generally",
    states: ["Manipur"],
    used_in: [
      "Standard bazaar weight for rice and other bulk goods, adopted through colonial-era trade contact with Cachar/Sylhet and the wider Bengal/Assam trading network",
      "Trade & Commerce",
    ],
    references: [
      "https://grokipedia.com/page/Seer_(unit)",
      "https://en.wikipedia.org/wiki/Maund",
    ],
    tags: [
      "manipur",
      "traditional-units",
      "trade-commerce",
      "ser",
      "mon",
      "seer",
      "maund",
      "bazaar-weight",
    ],
    created_at: "2024-01-01",
  },

  // ─── 8. Textile & Handloom (4 units) ─────────────────────────────────────────
  {
    id: "manipur-textile-1",
    slug: "sana-lamjel-fathom-textile-manipur",
    name_english: "Sana Lamjel (fathom)",
    name_sanskrit: "N/A (Meitei royal-decree unit)",
    local_names: ["সানা লামজেল"],
    name_hindi: "साना लामजेल",
    category: "length",
    measurement_type: "Length",
    sector: "textile-handloom",
    origin: "Manipur (Imphal Valley)",
    modern_equivalent: "A fathom (outstretched-arm-span) plus 4 finger-widths",
    conversion_formula: "Base unit for the entire Manipuri length/area system",
    meaning:
      "The historic reference length for measuring out handloom cloth on the loom before cutting — cloth was traditionally cut to whole or half Sana Lamjel lengths rather than to a fixed metric figure",
    historical_period:
      "Ningthouja/Meitei kingdom period (Nongda Lairen Pakhangba, traditionally dated 33 CE, through to the 1891 British takeover)",
    region_applicable: "Imphal Valley — the historic Meitei kingdom heartland",
    states: ["Manipur"],
    used_in: [
      "The historic reference length for measuring out handloom cloth on the loom before cutting — cloth was traditionally cut to whole or half Sana Lamjel lengths rather than to a fixed metric figure",
      "Textile & Handloom",
    ],
    references: [
      "https://en.wikipedia.org/wiki/Sana_lamjel",
      "https://en.wikipedia.org/wiki/Pari_(unit)",
    ],
    tags: [
      "manipur",
      "traditional-units",
      "textile-handloom",
      "sana-lamjel",
      "loom-length",
      "handloom",
      "meitei",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "manipur-textile-2",
    slug: "moirang-phee-textile-manipur",
    name_english: "Moirang Phee",
    name_sanskrit:
      "N/A (Meitei textile: place name term — 'Phee' from Moirang principality)",
    local_names: ["মোইরাং ফী"],
    name_hindi: "मोइरांग फी",
    category: "other",
    measurement_type: "Garment (type unit, not a length measure)",
    sector: "textile-handloom",
    origin: "Manipur (Imphal Valley / Moirang)",
    modern_equivalent: "One woven length, individually sized to the wearer",
    conversion_formula:
      "Not a subdivided unit — reckoned as a finished textile piece",
    meaning:
      "A traditional Manipuri handloom textile associated with the historic Moirang principality, used for wraparound garments with distinctive woven-border (temple/mountain-motif) patterns",
    historical_period:
      "Ningthouja/Meitei kingdom period (Nongda Lairen Pakhangba, traditionally dated 33 CE, through to the 1891 British takeover)",
    region_applicable: "Imphal Valley — the historic Meitei kingdom heartland",
    states: ["Manipur"],
    used_in: [
      "A traditional Manipuri handloom textile associated with the historic Moirang principality, used for wraparound garments with distinctive woven-border (temple/mountain-motif) patterns",
      "Textile & Handloom",
    ],
    references: [
      "https://en.wikipedia.org/wiki/Moirang_Phee",
      "https://en.wikipedia.org/wiki/Manipuri_handloom",
    ],
    tags: [
      "manipur",
      "traditional-units",
      "textile-handloom",
      "moirang-phee",
      "gi-tag",
      "weaving",
      "handloom",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "manipur-textile-3",
    slug: "innaphi-phanek-textile-manipur",
    name_english: "Innaphi / Phanek (women's wraparound garments)",
    name_sanskrit: "N/A (Meitei garment terms)",
    local_names: ["ইন্নাফী / ফানেক"],
    name_hindi: "इन्नाफी / फानेक",
    category: "other",
    measurement_type: "Garment (type unit, not a length measure)",
    sector: "textile-handloom",
    origin: "Manipur (Imphal Valley)",
    modern_equivalent: "One woven piece, individually sized to the wearer",
    conversion_formula:
      "Not a subdivided unit — reckoned as a finished textile piece",
    meaning:
      "The Phanek (a striped wraparound skirt) and Innaphi (a shawl/wrap) are the everyday and ceremonial garments of Meitei women, woven on the loin loom without reference to a codified length-unit system",
    historical_period:
      "Ningthouja/Meitei kingdom period (Nongda Lairen Pakhangba, traditionally dated 33 CE, through to the 1891 British takeover)",
    region_applicable: "Imphal Valley — the historic Meitei kingdom heartland",
    states: ["Manipur"],
    used_in: [
      "The Phanek (a striped wraparound skirt) and Innaphi (a shawl/wrap) are the everyday and ceremonial garments of Meitei women, woven on the loin loom without reference to a codified length-unit system",
      "Textile & Handloom",
    ],
    references: [
      "https://en.wikipedia.org/wiki/Moirang_Phee",
      "https://en.wikipedia.org/wiki/Manipuri_handloom",
    ],
    tags: [
      "manipur",
      "traditional-units",
      "textile-handloom",
      "innaphi",
      "phanek",
      "loin-loom",
      "meitei-women",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "manipur-textile-4",
    slug: "tola-bullion-reference-textile-manipur",
    name_english: "Tola (bullion reference)",
    name_sanskrit: "तोला (Tola)",
    local_names: ["তোলা"],
    name_hindi: "तोला",
    category: "weight",
    measurement_type: "Weight",
    sector: "textile-handloom",
    origin: "Manipur (Imphal Valley)",
    modern_equivalent: "~11.66 g",
    conversion_formula: "12 Masha = 1 Tola",
    meaning:
      "Weighing gold and silver thread used in ceremonial textile embroidery for royal or high-status commissions",
    historical_period:
      "Vedic–Classical Sanskrit period (c. 1000 BCE–500 CE), reaching Manipur through Vaishnavite influence from the 18th century onward",
    region_applicable: "Imphal Valley — the historic Meitei kingdom heartland",
    states: ["Manipur"],
    used_in: [
      "Weighing gold and silver thread used in ceremonial textile embroidery for royal or high-status commissions",
      "Textile & Handloom",
    ],
    references: ["https://en.wikipedia.org/wiki/Tola_(unit)"],
    tags: [
      "manipur",
      "traditional-units",
      "textile-handloom",
      "tola",
      "bullion",
      "zari",
      "embroidery",
    ],
    created_at: "2024-01-01",
  },

  // ─── 9. Medicine (Ayurveda) (5 units) ───────────────────────────────────────
  {
    id: "manipur-med-1",
    slug: "ratti-medicine-manipur",
    name_english: "Ratti",
    name_sanskrit: "रत्ति / रक्तिका (Ratti / Raktika)",
    local_names: [],
    name_hindi: "रत्ती",
    category: "weight",
    measurement_type: "Weight",
    sector: "medicine",
    origin: "Manipur (Imphal Valley)",
    modern_equivalent: "~0.1215 g",
    conversion_formula: "Base / smallest unit",
    meaning:
      "Smallest dosage unit for herbo-mineral formulations, reaching Manipur's Meitei valley through Vaishnavite Hindu influence from the 18th century onward, alongside the pre-existing Sanamahi (indigenous) medical tradition",
    historical_period:
      "Vedic–Classical Sanskrit period (c. 1000 BCE–500 CE), reaching Manipur through Vaishnavite influence from the 18th century onward",
    region_applicable: "Imphal Valley — the historic Meitei kingdom heartland",
    states: ["Manipur"],
    used_in: [
      "Smallest dosage unit for herbo-mineral formulations, reaching Manipur's Meitei valley through Vaishnavite Hindu influence from the 18th century onward, alongside the pre-existing Sanamahi (indigenous) medical tradition",
      "Medicine (Ayurveda)",
    ],
    references: ["https://en.wikipedia.org/wiki/Ratti_(unit)"],
    tags: [
      "manipur",
      "traditional-units",
      "medicine",
      "ayurveda",
      "ratti",
      "dosage",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "manipur-med-2",
    slug: "masha-medicine-manipur",
    name_english: "Masha",
    name_sanskrit: "माष (Masa)",
    local_names: [],
    name_hindi: "माशा",
    category: "weight",
    measurement_type: "Weight",
    sector: "medicine",
    origin: "Manipur (Imphal Valley)",
    modern_equivalent: "~0.97 g",
    conversion_formula: "8 Ratti = 1 Masha",
    meaning: "Powder (churna) dosage in classical Ayurvedic prescription",
    historical_period:
      "Vedic–Classical Sanskrit period (c. 1000 BCE–500 CE), reaching Manipur through Vaishnavite influence from the 18th century onward",
    region_applicable: "Imphal Valley — the historic Meitei kingdom heartland",
    states: ["Manipur"],
    used_in: [
      "Powder (churna) dosage in classical Ayurvedic prescription",
      "Medicine (Ayurveda)",
    ],
    references: ["https://www.wisdomlib.org/concept/masha"],
    tags: [
      "manipur",
      "traditional-units",
      "medicine",
      "ayurveda",
      "masha",
      "churna",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "manipur-med-3",
    slug: "karsha-medicine-manipur",
    name_english: "Karsha",
    name_sanskrit: "कर्ष (Karsa)",
    local_names: [],
    name_hindi: "कर्ष",
    category: "weight",
    measurement_type: "Weight",
    sector: "medicine",
    origin: "Manipur (Imphal Valley)",
    modern_equivalent: "~12 g",
    conversion_formula: "12 Masha = 1 Karsha",
    meaning: "Weighing herbal powders and churnas",
    historical_period:
      "Vedic–Classical Sanskrit period (c. 1000 BCE–500 CE), reaching Manipur through Vaishnavite influence from the 18th century onward",
    region_applicable: "Imphal Valley — the historic Meitei kingdom heartland",
    states: ["Manipur"],
    used_in: [
      "Weighing herbal powders and churnas",
      "Medicine (Ayurveda)",
    ],
    references: ["https://www.wisdomlib.org/concept/karsha"],
    tags: [
      "manipur",
      "traditional-units",
      "medicine",
      "ayurveda",
      "karsha",
      "herbal",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "manipur-med-4",
    slug: "pala-medicine-manipur",
    name_english: "Pala",
    name_sanskrit: "पल (Pala)",
    local_names: [],
    name_hindi: "पल",
    category: "weight",
    measurement_type: "Weight",
    sector: "medicine",
    origin: "Manipur (Imphal Valley)",
    modern_equivalent: "~48 g",
    conversion_formula: "4 Karsha = 1 Pala",
    meaning:
      "Measuring bulk herbal ingredients for decoctions and medicated oils",
    historical_period:
      "Vedic–Classical Sanskrit period (c. 1000 BCE–500 CE), reaching Manipur through Vaishnavite influence from the 18th century onward",
    region_applicable: "Imphal Valley — the historic Meitei kingdom heartland",
    states: ["Manipur"],
    used_in: [
      "Measuring bulk herbal ingredients for decoctions and medicated oils",
      "Medicine (Ayurveda)",
    ],
    references: ["https://www.wisdomlib.org/concept/pala"],
    tags: [
      "manipur",
      "traditional-units",
      "medicine",
      "ayurveda",
      "pala",
      "decoction",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "manipur-med-5",
    slug: "hill-tribal-herbal-healing-medicine-manipur",
    name_english: "(Hill-tribal herbal healing — informal reckoning)",
    name_sanskrit: "N/A — no codified weight-dosage system documented",
    local_names: [],
    name_hindi: "जनजातीय औषधि (अनौपचारिक)",
    category: "volume",
    measurement_type: "Volume/Weight (informal)",
    sector: "medicine",
    origin: "Manipur (Hill Districts)",
    modern_equivalent: "Approximated by hand — no fixed weight scale",
    conversion_formula: "No standardised hierarchy",
    meaning:
      "Manipur's Naga and Kuki-Zo hill communities maintained their own herbal-healing knowledge through village healers, using informal handful/pinch dosing rather than the Sanskritic weight scale that reached the Meitei valley through Vaishnavism",
    historical_period:
      "Customary/traditional practice of Manipur's Naga and Kuki-Zo hill communities, predating and continuing alongside Meitei valley administration",
    region_applicable:
      "Hill districts — Naga (Tangkhul, Mao, Poumai) and Kuki-Zo (Thadou, Zomi, Hmar) homelands",
    states: ["Manipur"],
    used_in: [
      "Manipur's Naga and Kuki-Zo hill communities maintained their own herbal-healing knowledge through village healers, using informal handful/pinch dosing rather than the Sanskritic weight scale that reached the Meitei valley through Vaishnavism",
      "Medicine (Ayurveda)",
    ],
    references: [
      "No standardised metrological reference documented for this tradition",
    ],
    tags: [
      "manipur",
      "traditional-units",
      "medicine",
      "hill-tribal",
      "herbal",
      "naga",
      "kuki-zo",
    ],
    created_at: "2024-01-01",
  },

  // ─── 10. Construction & Architecture (3 units) ──────────────────────────────
  {
    id: "manipur-arch-1",
    slug: "sana-lamjel-fathom-architecture-manipur",
    name_english: "Sana Lamjel (fathom)",
    name_sanskrit: "N/A (Meitei royal-decree unit)",
    local_names: ["সানা লামজেল"],
    name_hindi: "साना लामजेल",
    category: "length",
    measurement_type: "Length",
    sector: "architecture",
    origin: "Manipur (Imphal Valley)",
    modern_equivalent: "A fathom (outstretched-arm-span) plus 4 finger-widths",
    conversion_formula:
      "Base unit for Manipur's entire traditional construction and land-survey system",
    meaning:
      "First fixed by King Nongda Lairen Pakhangba (traditionally 33 CE) as the span of his own raised right arm plus four finger-widths, and later redefined by King Khagemba (1597–1652) using his own outstretched arm span — one of the most literally 'body-defined' units of any Indian state's traditional system",
    historical_period:
      "Ningthouja/Meitei kingdom period (Nongda Lairen Pakhangba, traditionally dated 33 CE, through to the 1891 British takeover)",
    region_applicable: "Imphal Valley — the historic Meitei kingdom heartland",
    states: ["Manipur"],
    used_in: [
      "First fixed by King Nongda Lairen Pakhangba (traditionally 33 CE) as the span of his own raised right arm plus four finger-widths, and later redefined by King Khagemba (1597–1652) using his own outstretched arm span — one of the most literally 'body-defined' units of any Indian state's traditional system",
      "Construction & Architecture",
    ],
    references: [
      "https://en.wikipedia.org/wiki/Sana_lamjel",
      "https://en.wikipedia.org/wiki/Pari_(unit)",
    ],
    tags: [
      "manipur",
      "traditional-units",
      "architecture",
      "sana-lamjel",
      "construction",
      "land-survey",
      "meitei",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "manipur-arch-2",
    slug: "angula-hasta-architecture-manipur",
    name_english: "Angula / Hasta (classical reference)",
    name_sanskrit: "अङ्गुल / हस्त (Angula / Hasta)",
    local_names: [],
    name_hindi: "अंगुल / हाथ",
    category: "length",
    measurement_type: "Length",
    sector: "architecture",
    origin: "Manipur (Imphal Valley)",
    modern_equivalent: "~1.9 cm / ~45.7 cm",
    conversion_formula: "24 Angula = 1 Hasta",
    meaning:
      "Used alongside the indigenous Sana Lamjel system in construction influenced by Hindu Vaishnavite temple building conventions, such as the Shri Govindajee Temple in Imphal",
    historical_period:
      "Vedic–Classical Sanskrit period (c. 1000 BCE–500 CE), reaching Manipur through Vaishnavite influence from the 18th century onward",
    region_applicable: "Imphal Valley — the historic Meitei kingdom heartland",
    states: ["Manipur"],
    used_in: [
      "Used alongside the indigenous Sana Lamjel system in construction influenced by Hindu Vaishnavite temple building conventions, such as the Shri Govindajee Temple in Imphal",
      "Construction & Architecture",
    ],
    references: ["https://en.wikipedia.org/wiki/%E1%B9%85gula"],
    tags: [
      "manipur",
      "traditional-units",
      "architecture",
      "angula",
      "hasta",
      "temple-building",
      "vaishnavite",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "manipur-arch-3",
    slug: "bamboo-based-construction-hill-areas-manipur",
    name_english: "(Bamboo-based construction — hill areas)",
    name_sanskrit:
      "N/A — informal, material-based measurement, no fixed named unit documented",
    local_names: [],
    name_hindi: "बांस निर्माण (अनौपचारिक)",
    category: "length",
    measurement_type: "Length (informal)",
    sector: "architecture",
    origin: "Manipur (Hill Districts)",
    modern_equivalent:
      "Set by bamboo-pole length and body-reference, varying by builder",
    conversion_formula: "No standardised hierarchy",
    meaning:
      "Naga and Kuki-Zo hill-village houses, distinct from the Meitei valley's Sana Lamjel-governed layout, were traditionally built using informal bamboo- and body-based measurement",
    historical_period:
      "Customary/traditional practice of Manipur's Naga and Kuki-Zo hill communities, predating and continuing alongside Meitei valley administration",
    region_applicable:
      "Hill districts — Naga (Tangkhul, Mao, Poumai) and Kuki-Zo (Thadou, Zomi, Hmar) homelands",
    states: ["Manipur"],
    used_in: [
      "Naga and Kuki-Zo hill-village houses, distinct from the Meitei valley's Sana Lamjel-governed layout, were traditionally built using informal bamboo- and body-based measurement",
      "Construction & Architecture",
    ],
    references: [
      "No standardised metrological reference documented for this practice",
    ],
    tags: [
      "manipur",
      "traditional-units",
      "architecture",
      "bamboo",
      "hill-houses",
      "naga",
      "kuki-zo",
    ],
    created_at: "2024-01-01",
  },
];
