import { Measurement } from "@/types";

export const MP_MEASUREMENTS: Measurement[] = [
  // ─── 1. Seed & Crop (Agriculture) (10 units) ──────────────────────────────────
  {
    id: "mp-agri-1",
    slug: "ratti-agri-mp-1",
    name_english: "Ratti",
    name_hindi: "रत्ती",
    name_sanskrit: "रक्तिका (Raktikā)",
    local_names: ["रत्ती (Ratti)"],
    meaning: "Weighing seeds, medicinal herbs and spices. Smallest traditional weight unit.",
    category: "weight",
    measurement_type: "Seed Weight",
    sector: "agriculture",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈0.1215 g (121.5 mg)",
    conversion_formula: "Base Unit",
    historical_period: "Ancient–Present",
    region_applicable: "Entire Madhya Pradesh",
    used_in: ["Weighing seeds, medicinal herbs and spices"],
    references: ["Arthashastra; Charaka Samhita"],
    tags: ["madhya-pradesh", "traditional-units", "agriculture", "ratti", "weight"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-agri-2",
    slug: "masha-agri-mp-2",
    name_english: "Masha",
    name_hindi: "माशा",
    name_sanskrit: "माष",
    local_names: ["माशा (Masha)"],
    meaning: "Seeds, herbs, agricultural produce. Small agricultural weight.",
    category: "weight",
    measurement_type: "Seed Weight",
    sector: "agriculture",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈0.972 g",
    conversion_formula: "8 Ratti = 1 Masha",
    historical_period: "Ancient–Colonial",
    region_applicable: "Entire MP",
    used_in: ["Seeds, herbs, agricultural produce"],
    references: ["Arthashastra"],
    tags: ["madhya-pradesh", "traditional-units", "agriculture", "masha", "weight"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-agri-3",
    slug: "tola-agri-mp-3",
    name_english: "Tola",
    name_hindi: "तोला",
    name_sanskrit: "तुला",
    local_names: ["तोला (Tola)"],
    meaning: "Oilseeds, spices, valuable produce. Standard traditional weight.",
    category: "weight",
    measurement_type: "Weight",
    sector: "agriculture",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈11.66 g",
    conversion_formula: "12 Masha = 1 Tola",
    historical_period: "Mughal–Present",
    region_applicable: "Entire MP",
    used_in: ["Oilseeds, spices, valuable produce"],
    references: ["British India Standards"],
    tags: ["madhya-pradesh", "traditional-units", "agriculture", "tola", "weight"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-agri-4",
    slug: "chhatak-agri-mp-4",
    name_english: "Chhatak",
    name_hindi: "छटाक",
    local_names: ["छटाक (Chhatak)"],
    meaning: "Grain, pulses and seed measurement. Small grain measure.",
    category: "weight",
    measurement_type: "Grain Weight",
    sector: "agriculture",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈58.3 g",
    conversion_formula: "5 Tola = 1 Chhatak",
    historical_period: "Mughal–1958",
    region_applicable: "Entire MP",
    used_in: ["Grain, pulses and seed measurement"],
    references: ["Central Provinces Gazetteers"],
    tags: ["madhya-pradesh", "traditional-units", "agriculture", "chhatak", "weight"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-agri-5",
    slug: "pav-pao-agri-mp-5",
    name_english: "Pav (Pao)",
    name_hindi: "पाव",
    local_names: ["पाव (Pav)"],
    meaning: "Grain and pulses. Quarter Seer.",
    category: "weight",
    measurement_type: "Grain Weight",
    sector: "agriculture",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈233 g",
    conversion_formula: "4 Chhatak = 1 Pav",
    historical_period: "Mughal–1958",
    region_applicable: "Entire MP",
    used_in: ["Grain and pulses"],
    references: ["MP District Gazetteers"],
    tags: ["madhya-pradesh", "traditional-units", "agriculture", "pav-pao", "weight"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-agri-6",
    slug: "adha-seer-agri-mp-6",
    name_english: "Adha Seer",
    name_hindi: "आधा सेर",
    local_names: ["आधा सेर (Adha Seer)"],
    meaning: "Seeds and cereals. Half Seer.",
    category: "weight",
    measurement_type: "Grain Weight",
    sector: "agriculture",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈466 g",
    conversion_formula: "2 Pav = 1 Half Seer",
    historical_period: "Mughal–1958",
    region_applicable: "Entire MP",
    used_in: ["Seeds and cereals"],
    references: ["Revenue Settlement Manuals"],
    tags: ["madhya-pradesh", "traditional-units", "agriculture", "adha-seer", "weight"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-agri-7",
    slug: "seer-agri-mp-7",
    name_english: "Seer",
    name_hindi: "सेर",
    local_names: ["सेर (Seer)"],
    meaning: "Wheat, rice, pulses, oilseeds. Standard agricultural market unit.",
    category: "weight",
    measurement_type: "Grain Weight",
    sector: "agriculture",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈0.933 kg",
    conversion_formula: "2 Half Seer = 1 Seer (16 Chhatak)",
    historical_period: "Mughal–1958",
    region_applicable: "Entire MP",
    used_in: ["Wheat, rice, pulses, oilseeds"],
    references: ["Imperial Gazetteer of India"],
    tags: ["madhya-pradesh", "traditional-units", "agriculture", "seer", "weight"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-agri-8",
    slug: "pasri-agri-mp-8",
    name_english: "Pasri",
    name_hindi: "पसरी",
    local_names: ["पसरी (Pasri)"],
    meaning: "Grain storage and seed distribution. Intermediate grain measure.",
    category: "volume",
    measurement_type: "Grain Capacity",
    sector: "agriculture",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈4.66 kg (where 5 Seers were used)",
    conversion_formula: "Usually 5 Seers = 1 Pasri (Regional Variation)",
    historical_period: "Colonial",
    region_applicable: "Malwa, Bundelkhand",
    used_in: ["Grain storage and seed distribution"],
    references: ["District Gazetteers"],
    tags: ["madhya-pradesh", "traditional-units", "agriculture", "pasri", "volume"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-agri-9",
    slug: "maund-man-agri-mp-9",
    name_english: "Maund (Man)",
    name_hindi: "मन",
    name_sanskrit: "मान",
    local_names: ["मन (Maund / Man)"],
    meaning: "Harvest measurement and wholesale grain trade. Principal wholesale agricultural unit.",
    category: "weight",
    measurement_type: "Bulk Grain Weight",
    sector: "agriculture",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈37.324 kg",
    conversion_formula: "40 Seers = 1 Maund",
    historical_period: "Mughal–1958",
    region_applicable: "Entire MP",
    used_in: ["Harvest measurement and wholesale grain trade"],
    references: ["Government of India Historical Weights"],
    tags: ["madhya-pradesh", "traditional-units", "agriculture", "maund-man", "weight"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-agri-10",
    slug: "khandi-agri-mp-10",
    name_english: "Khandi",
    name_hindi: "खंडी",
    name_sanskrit: "खण्डी",
    local_names: ["खंडी (Khandi)"],
    meaning: "Large-scale grain storage. Bulk agricultural storage unit.",
    category: "volume",
    measurement_type: "Bulk Storage",
    sector: "agriculture",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈746 kg (where applicable)",
    conversion_formula: "≈20 Maunds (Regional)",
    historical_period: "Medieval–Colonial",
    region_applicable: "Malwa, Nimar",
    used_in: ["Large-scale grain storage"],
    references: ["Madhya Pradesh Gazetteers"],
    tags: ["madhya-pradesh", "traditional-units", "agriculture", "khandi", "volume"],
    created_at: "2024-01-01",
  },

  // ─── 2. Trade & Commerce (10 units) ──────────────────────────────────────────
  {
    id: "mp-trade-1",
    slug: "ratti-trade-mp-1",
    name_english: "Ratti",
    name_hindi: "रत्ती",
    name_sanskrit: "रक्तिका (Raktikā)",
    local_names: ["रत्ती (Ratti)"],
    meaning: "Gems, spices, medicines. Smallest commercial weight.",
    category: "weight",
    measurement_type: "Commercial Weight",
    sector: "trade-commerce",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈121.5 mg",
    conversion_formula: "Base Unit",
    historical_period: "Ancient–Present",
    region_applicable: "Entire MP",
    used_in: ["Gems, spices, medicines"],
    references: ["Arthashastra; Charaka Samhita"],
    tags: ["madhya-pradesh", "traditional-units", "trade-commerce", "ratti", "weight"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-trade-2",
    slug: "masha-trade-mp-2",
    name_english: "Masha",
    name_hindi: "माशा",
    name_sanskrit: "माष",
    local_names: ["माशा (Masha)"],
    meaning: "Herbs, perfumes, spices. Small market weight.",
    category: "weight",
    measurement_type: "Commercial Weight",
    sector: "trade-commerce",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈0.972 g",
    conversion_formula: "8 Ratti = 1 Masha",
    historical_period: "Ancient–Colonial",
    region_applicable: "Entire MP",
    used_in: ["Herbs, perfumes, spices"],
    references: ["Arthashastra"],
    tags: ["madhya-pradesh", "traditional-units", "trade-commerce", "masha", "weight"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-trade-3",
    slug: "tola-trade-mp-3",
    name_english: "Tola",
    name_hindi: "तोला",
    name_sanskrit: "तुला",
    local_names: ["तोला (Tola)"],
    meaning: "Gold, silver, spices. Standard commercial weight.",
    category: "weight",
    measurement_type: "Commercial Weight",
    sector: "trade-commerce",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈11.66 g",
    conversion_formula: "12 Masha = 1 Tola",
    historical_period: "Mughal–Present",
    region_applicable: "Entire MP",
    used_in: ["Gold, silver, spices"],
    references: ["British India Standards"],
    tags: ["madhya-pradesh", "traditional-units", "trade-commerce", "tola", "weight"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-trade-4",
    slug: "chhatak-trade-mp-4",
    name_english: "Chhatak",
    name_hindi: "छटाक",
    local_names: ["छटाक (Chhatak)"],
    meaning: "Grocery items. Retail weight.",
    category: "weight",
    measurement_type: "Market Weight",
    sector: "trade-commerce",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈58.3 g",
    conversion_formula: "5 Tola = 1 Chhatak",
    historical_period: "Mughal–1958",
    region_applicable: "Entire MP",
    used_in: ["Grocery items"],
    references: ["Central Provinces Gazetteers"],
    tags: ["madhya-pradesh", "traditional-units", "trade-commerce", "chhatak", "weight"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-trade-5",
    slug: "pav-pao-trade-mp-5",
    name_english: "Pav (Pao)",
    name_hindi: "पाव",
    local_names: ["पाव (Pav)"],
    meaning: "Flour, sugar, pulses. Quarter Seer.",
    category: "weight",
    measurement_type: "Market Weight",
    sector: "trade-commerce",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈233 g",
    conversion_formula: "4 Chhatak = 1 Pav",
    historical_period: "Mughal–1958",
    region_applicable: "Entire MP",
    used_in: ["Flour, sugar, pulses"],
    references: ["MP District Gazetteers"],
    tags: ["madhya-pradesh", "traditional-units", "trade-commerce", "pav-pao", "weight"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-trade-6",
    slug: "adha-seer-trade-mp-6",
    name_english: "Adha Seer",
    name_hindi: "आधा सेर",
    local_names: ["आधा सेर (Adha Seer)"],
    meaning: "Grain, jaggery, oil. Half Seer.",
    category: "weight",
    measurement_type: "Market Weight",
    sector: "trade-commerce",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈466 g",
    conversion_formula: "2 Pav = 1 Half Seer",
    historical_period: "Mughal–1958",
    region_applicable: "Entire MP",
    used_in: ["Grain, jaggery, oil"],
    references: ["Revenue Settlement Manuals"],
    tags: ["madhya-pradesh", "traditional-units", "trade-commerce", "adha-seer", "weight"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-trade-7",
    slug: "seer-trade-mp-7",
    name_english: "Seer",
    name_hindi: "सेर",
    local_names: ["सेर (Seer)"],
    meaning: "Grain, cotton, oil, jaggery. Standard market unit.",
    category: "weight",
    measurement_type: "Commercial Weight",
    sector: "trade-commerce",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈0.933 kg",
    conversion_formula: "2 Half Seer = 1 Seer",
    historical_period: "Mughal–1958",
    region_applicable: "Entire MP",
    used_in: ["Grain, cotton, oil, jaggery"],
    references: ["Imperial Gazetteer of India"],
    tags: ["madhya-pradesh", "traditional-units", "trade-commerce", "seer", "weight"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-trade-8",
    slug: "pasri-trade-mp-8",
    name_english: "Pasri",
    name_hindi: "पसरी",
    local_names: ["पसरी (Pasri)"],
    meaning: "Grain and cotton trade. Regional grain measure.",
    category: "volume",
    measurement_type: "Grain Capacity",
    sector: "trade-commerce",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈4.66 kg (where applicable)",
    conversion_formula: "Usually 5 Seers = 1 Pasri (Regional)",
    historical_period: "Colonial",
    region_applicable: "Malwa, Bundelkhand",
    used_in: ["Grain and cotton trade"],
    references: ["District Gazetteers"],
    tags: ["madhya-pradesh", "traditional-units", "trade-commerce", "pasri", "volume"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-trade-9",
    slug: "maund-man-trade-mp-9",
    name_english: "Maund (Man)",
    name_hindi: "मन",
    name_sanskrit: "मान",
    local_names: ["मन (Maund / Man)"],
    meaning: "Wholesale grain, cotton and salt. Principal wholesale unit.",
    category: "weight",
    measurement_type: "Wholesale Weight",
    sector: "trade-commerce",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈37.324 kg",
    conversion_formula: "40 Seers = 1 Maund",
    historical_period: "Mughal–1958",
    region_applicable: "Entire MP",
    used_in: ["Wholesale grain, cotton and salt"],
    references: ["Government of India Historical Standards"],
    tags: ["madhya-pradesh", "traditional-units", "trade-commerce", "maund-man", "weight"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-trade-10",
    slug: "khandi-trade-mp-10",
    name_english: "Khandi",
    name_hindi: "खंडी",
    name_sanskrit: "Khaṇḍī",
    local_names: ["खंडी (Khandi)"],
    meaning: "Bulk grain and cotton trade. Warehouse and transport unit.",
    category: "weight",
    measurement_type: "Bulk Commercial Weight",
    sector: "trade-commerce",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈746 kg (where applicable)",
    conversion_formula: "≈20 Maunds (Regional)",
    historical_period: "Medieval–Colonial",
    region_applicable: "Malwa, Nimar",
    used_in: ["Bulk grain and cotton trade"],
    references: ["Madhya Pradesh Gazetteers"],
    tags: ["madhya-pradesh", "traditional-units", "trade-commerce", "khandi", "weight"],
    created_at: "2024-01-01",
  },

  // ─── 3. Textile & Handloom (6 units) ─────────────────────────────────────────
  {
    id: "mp-tex-1",
    slug: "angul-tex-mp-1",
    name_english: "Angul",
    name_hindi: "अंगुल",
    name_sanskrit: "अङ्गुल",
    local_names: ["अंगुल (Angula)"],
    meaning: "Measuring thread, cloth borders. Finger-width measurement.",
    category: "length",
    measurement_type: "Length",
    sector: "textile-handloom",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈1.9 cm",
    conversion_formula: "Base Unit",
    historical_period: "Vedic–Present",
    region_applicable: "Entire MP",
    used_in: ["Measuring thread, cloth borders"],
    references: ["Arthashastra; Mānasāra"],
    tags: ["madhya-pradesh", "traditional-units", "textile-handloom", "angul", "length"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-tex-2",
    slug: "vitasti-tex-mp-2",
    name_english: "Vitasti",
    name_hindi: "वितस्ति",
    name_sanskrit: "वितस्ति",
    local_names: ["वितस्ति (Vitasti)"],
    meaning: "Cloth width, weaving. Span measurement.",
    category: "length",
    measurement_type: "Length",
    sector: "textile-handloom",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈22.8 cm",
    conversion_formula: "12 Angul = 1 Vitasti",
    historical_period: "Ancient–Medieval",
    region_applicable: "Entire MP",
    used_in: ["Cloth width, weaving"],
    references: ["Mānasāra"],
    tags: ["madhya-pradesh", "traditional-units", "textile-handloom", "vitasti", "length"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-tex-3",
    slug: "hasta-tex-mp-3",
    name_english: "Hasta",
    name_hindi: "हस्त",
    name_sanskrit: "हस्त",
    local_names: ["हस्त (Hasta)"],
    meaning: "Cloth measurement, weaving. Cubit measurement.",
    category: "length",
    measurement_type: "Length",
    sector: "textile-handloom",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈45.6 cm",
    conversion_formula: "2 Vitasti = 1 Hasta",
    historical_period: "Ancient–Colonial",
    region_applicable: "Entire MP",
    used_in: ["Cloth measurement, weaving"],
    references: ["Mayamata"],
    tags: ["madhya-pradesh", "traditional-units", "textile-handloom", "hasta", "length"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-tex-4",
    slug: "gaz-gaj-tex-mp-4",
    name_english: "Gaz (Gaj)",
    name_hindi: "गज़",
    local_names: ["गज़ (Gaz / Gaj)"],
    meaning: "Cloth trade, tailoring. Standard cloth measure.",
    category: "length",
    measurement_type: "Cloth Length",
    sector: "textile-handloom",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈0.9144 m",
    conversion_formula: "Regional standard",
    historical_period: "Mughal–Present",
    region_applicable: "Entire MP",
    used_in: ["Cloth trade, tailoring"],
    references: ["Imperial Gazetteer"],
    tags: ["madhya-pradesh", "traditional-units", "textile-handloom", "gaz-gaj", "length"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-tex-5",
    slug: "danda-tex-mp-5",
    name_english: "Danda",
    name_hindi: "दण्ड",
    name_sanskrit: "दण्ड",
    local_names: ["दण्ड (Danda)"],
    meaning: "Loom setting, workshop layout. Long measuring rod.",
    category: "length",
    measurement_type: "Length",
    sector: "textile-handloom",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈1.82 m",
    conversion_formula: "4 Hasta = 1 Danda",
    historical_period: "Ancient–Medieval",
    region_applicable: "Entire MP",
    used_in: ["Loom setting, workshop layout"],
    references: ["Arthashastra"],
    tags: ["madhya-pradesh", "traditional-units", "textile-handloom", "danda", "length"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-tex-6",
    slug: "rajju-tex-mp-6",
    name_english: "Rajju",
    name_hindi: "रज्जु",
    name_sanskrit: "रज्जु",
    local_names: ["रज्जु (Rajju)"],
    meaning: "Measuring long cloth rolls. Rope measuring unit.",
    category: "length",
    measurement_type: "Length",
    sector: "textile-handloom",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "Regionally Variable",
    conversion_formula: "Rope measure (variable)",
    historical_period: "Ancient–Colonial",
    region_applicable: "Malwa, Bundelkhand",
    used_in: ["Measuring long cloth rolls"],
    references: ["Traditional Survey Records"],
    tags: ["madhya-pradesh", "traditional-units", "textile-handloom", "rajju", "length"],
    created_at: "2024-01-01",
  },

  // ─── 4. Medicine (Ayurveda) (9 units) ─────────────────────────────────────────
  {
    id: "mp-med-1",
    slug: "ratti-med-mp-1",
    name_english: "Ratti",
    name_hindi: "रत्ती",
    name_sanskrit: "रक्तिका (Raktikā)",
    local_names: ["रत्ती (Ratti)"],
    meaning: "Herbs, mineral medicines. Smallest medicinal weight.",
    category: "weight",
    measurement_type: "Medicine Weight",
    sector: "medicine",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈121.5 mg",
    conversion_formula: "Base Unit",
    historical_period: "Ancient–Present",
    region_applicable: "Entire MP",
    used_in: ["Herbs, mineral medicines"],
    references: ["Charaka Samhita"],
    tags: ["madhya-pradesh", "traditional-units", "medicine", "ratti", "weight"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-med-2",
    slug: "masha-med-mp-2",
    name_english: "Masha",
    name_hindi: "माशा",
    name_sanskrit: "माष",
    local_names: ["माशा (Masha)"],
    meaning: "Herbal powders. Standard medicinal weight.",
    category: "weight",
    measurement_type: "Medicine Weight",
    sector: "medicine",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈0.972 g",
    conversion_formula: "8 Ratti = 1 Masha",
    historical_period: "Ancient–Present",
    region_applicable: "Entire MP",
    used_in: ["Herbal powders"],
    references: ["Sushruta Samhita"],
    tags: ["madhya-pradesh", "traditional-units", "medicine", "masha", "weight"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-med-3",
    slug: "karsha-med-mp-3",
    name_english: "Karsha",
    name_hindi: "कर्ष",
    name_sanskrit: "कर्ष",
    local_names: ["कर्ष (Karsha)"],
    meaning: "Churna, Kalka. Common medicinal dose.",
    category: "weight",
    measurement_type: "Medicine Weight",
    sector: "medicine",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈11.66 g",
    conversion_formula: "12 Masha = 1 Karsha",
    historical_period: "Ancient–Present",
    region_applicable: "Entire MP",
    used_in: ["Churna, Kalka"],
    references: ["Charaka Samhita"],
    tags: ["madhya-pradesh", "traditional-units", "medicine", "karsha", "weight"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-med-4",
    slug: "pala-med-mp-4",
    name_english: "Pala",
    name_hindi: "पल",
    name_sanskrit: "पल",
    local_names: ["पल (Pala)"],
    meaning: "Oils, decoctions. Standard pharmacy unit.",
    category: "weight",
    measurement_type: "Medicine Weight",
    sector: "medicine",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈46.6 g",
    conversion_formula: "4 Karsha = 1 Pala",
    historical_period: "Ancient–Present",
    region_applicable: "Entire MP",
    used_in: ["Oils, decoctions"],
    references: ["Ashtanga Hridaya"],
    tags: ["madhya-pradesh", "traditional-units", "medicine", "pala", "weight"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-med-5",
    slug: "prasruta-med-mp-5",
    name_english: "Prasruta",
    name_hindi: "प्रसृत",
    name_sanskrit: "प्रसृत",
    local_names: ["प्रसृत (Prasruta)"],
    meaning: "Medicated liquids. Liquid dosage.",
    category: "volume",
    measurement_type: "Liquid Measure",
    sector: "medicine",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈93 ml",
    conversion_formula: "2 Pala = 1 Prasruta",
    historical_period: "Ancient–Present",
    region_applicable: "Entire MP",
    used_in: ["Medicated liquids"],
    references: ["Charaka Samhita"],
    tags: ["madhya-pradesh", "traditional-units", "medicine", "prasruta", "volume"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-med-6",
    slug: "kudava-med-mp-6",
    name_english: "Kudava",
    name_hindi: "कुडव",
    name_sanskrit: "कुडव",
    local_names: ["कुडव (Kudava)"],
    meaning: "Oils, decoctions. Medium liquid measure.",
    category: "volume",
    measurement_type: "Liquid Measure",
    sector: "medicine",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈187 ml",
    conversion_formula: "2 Prasruta = 1 Kudava",
    historical_period: "Ancient–Present",
    region_applicable: "Entire MP",
    used_in: ["Oils, decoctions"],
    references: ["Sushruta Samhita"],
    tags: ["madhya-pradesh", "traditional-units", "medicine", "kudava", "volume"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-med-7",
    slug: "prastha-med-mp-7",
    name_english: "Prastha",
    name_hindi: "प्रस्थ",
    name_sanskrit: "प्रस्थ",
    local_names: ["प्रस्थ (Prastha)"],
    meaning: "Preparation of medicines. Large liquid measure.",
    category: "volume",
    measurement_type: "Volume",
    sector: "medicine",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈768 ml",
    conversion_formula: "4 Kudava = 1 Prastha",
    historical_period: "Ancient–Present",
    region_applicable: "Entire MP",
    used_in: ["Preparation of medicines"],
    references: ["Charaka Samhita"],
    tags: ["madhya-pradesh", "traditional-units", "medicine", "prastha", "volume"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-med-8",
    slug: "adhaka-med-mp-8",
    name_english: "Adhaka",
    name_hindi: "आढ़क",
    name_sanskrit: "आढक",
    local_names: ["आढ़क (Adhaka)"],
    meaning: "Pharmacy preparation. Bulk medicinal preparation.",
    category: "volume",
    measurement_type: "Volume",
    sector: "medicine",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈3.07 L",
    conversion_formula: "4 Prastha = 1 Adhaka",
    historical_period: "Ancient–Present",
    region_applicable: "Entire MP",
    used_in: ["Pharmacy preparation"],
    references: ["Ayurvedic Texts"],
    tags: ["madhya-pradesh", "traditional-units", "medicine", "adhaka", "volume"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-med-9",
    slug: "drona-med-mp-9",
    name_english: "Drona",
    name_hindi: "द्रोण",
    name_sanskrit: "द्रोण",
    local_names: ["द्रोण (Drona)"],
    meaning: "Bulk herbal preparation. Large storage measure.",
    category: "volume",
    measurement_type: "Volume",
    sector: "medicine",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈12.3 L",
    conversion_formula: "4 Adhaka = 1 Drona",
    historical_period: "Ancient–Present",
    region_applicable: "Entire MP",
    used_in: ["Bulk herbal preparation"],
    references: ["Charaka Samhita"],
    tags: ["madhya-pradesh", "traditional-units", "medicine", "drona", "volume"],
    created_at: "2024-01-01",
  },

  // ─── 5. Construction & Architecture (7 units) ────────────────────────────────
  {
    id: "mp-arch-1",
    slug: "yava-arch-mp-1",
    name_english: "Yava",
    name_hindi: "यव",
    name_sanskrit: "यव",
    local_names: ["यव (Yava)"],
    meaning: "Fine carving, ornaments. Smallest architectural unit.",
    category: "length",
    measurement_type: "Length",
    sector: "architecture",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈2.4 mm",
    conversion_formula: "Base Unit",
    historical_period: "Vedic–Medieval",
    region_applicable: "Entire MP",
    used_in: ["Fine carving, ornaments"],
    references: ["Mānasāra"],
    tags: ["madhya-pradesh", "traditional-units", "architecture", "yava", "length"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-arch-2",
    slug: "angula-arch-mp-2",
    name_english: "Angula",
    name_hindi: "अंगुल",
    name_sanskrit: "अङ्गुल",
    local_names: ["अंगुल (Angula)"],
    meaning: "Masonry, stone cutting. Finger-width measure.",
    category: "length",
    measurement_type: "Length",
    sector: "architecture",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈1.9 cm",
    conversion_formula: "8 Yava = 1 Angula",
    historical_period: "Ancient–Present",
    region_applicable: "Entire MP",
    used_in: ["Masonry, stone cutting"],
    references: ["Mānasāra; Mayamata"],
    tags: ["madhya-pradesh", "traditional-units", "architecture", "angula", "length"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-arch-3",
    slug: "vitasti-arch-mp-3",
    name_english: "Vitasti",
    name_hindi: "वितस्ति",
    name_sanskrit: "वितस्ति",
    local_names: ["वितस्ति (Vitasti)"],
    meaning: "Pillars, walls. Span measurement.",
    category: "length",
    measurement_type: "Length",
    sector: "architecture",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈22.8 cm",
    conversion_formula: "12 Angula = 1 Vitasti",
    historical_period: "Ancient–Medieval",
    region_applicable: "Entire MP",
    used_in: ["Pillars, walls"],
    references: ["Samarāṅgaṇa Sūtradhāra"],
    tags: ["madhya-pradesh", "traditional-units", "architecture", "vitasti", "length"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-arch-4",
    slug: "hasta-arch-mp-4",
    name_english: "Hasta",
    name_hindi: "हस्त",
    name_sanskrit: "हस्त",
    local_names: ["हस्त (Hasta)"],
    meaning: "Building dimensions. Cubit.",
    category: "length",
    measurement_type: "Length",
    sector: "architecture",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈45.6 cm",
    conversion_formula: "2 Vitasti = 1 Hasta (24 Angula)",
    historical_period: "Ancient–Present",
    region_applicable: "Entire MP",
    used_in: ["Building dimensions"],
    references: ["Mayamata"],
    tags: ["madhya-pradesh", "traditional-units", "architecture", "hasta", "length"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-arch-5",
    slug: "danda-arch-mp-5",
    name_english: "Danda",
    name_hindi: "दण्ड",
    name_sanskrit: "दण्ड",
    local_names: ["दण्ड (Danda)"],
    meaning: "House and road layout. Measuring rod.",
    category: "length",
    measurement_type: "Length",
    sector: "architecture",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈1.82 m",
    conversion_formula: "4 Hasta = 1 Danda",
    historical_period: "Ancient–Medieval",
    region_applicable: "Entire MP",
    used_in: ["House and road layout"],
    references: ["Arthashastra"],
    tags: ["madhya-pradesh", "traditional-units", "architecture", "danda", "length"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-arch-6",
    slug: "rajju-arch-mp-6",
    name_english: "Rajju",
    name_hindi: "रज्जु",
    name_sanskrit: "रज्जु",
    local_names: ["रज्जु (Rajju)"],
    meaning: "Land and building layout. Survey rope.",
    category: "length",
    measurement_type: "Length",
    sector: "architecture",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "Regionally Variable",
    conversion_formula: "Rope measure (variable)",
    historical_period: "Ancient–Colonial",
    region_applicable: "Malwa, Bundelkhand",
    used_in: ["Land and building layout"],
    references: ["Traditional Survey Manuals"],
    tags: ["madhya-pradesh", "traditional-units", "architecture", "rajju", "length"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-arch-7",
    slug: "gaj-gaz-arch-mp-7",
    name_english: "Gaj (Gaz)",
    name_hindi: "गज़",
    local_names: ["गज़ (Gaj / Gaz)"],
    meaning: "Construction and carpentry. Standard building measure.",
    category: "length",
    measurement_type: "Length",
    sector: "architecture",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈0.9144 m",
    conversion_formula: "Regional standard",
    historical_period: "Mughal–Present",
    region_applicable: "Entire MP",
    used_in: ["Construction and carpentry"],
    references: ["Imperial Gazetteer"],
    tags: ["madhya-pradesh", "traditional-units", "architecture", "gaj-gaz", "length"],
    created_at: "2024-01-01",
  },

  // ───────────────────────────────────────────────────────────────────────────
  // SECTOR: Transportation & Distance (8 units)
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "mp-trans-1",
    slug: "angula-mp-transportation",
    name_english: "Angula",
    name_hindi: "अंगुल",
    local_names: ["अंगुल", "Aṅgula"],
    name_sanskrit: "अङ्गुल",
    meaning: "Small engineering measurements. Finger-width unit.",
    category: "length",
    measurement_type: "Length",
    sector: "transportation-distance",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈1.9 cm",
    conversion_formula: "Base Unit",
    historical_period: "Vedic–Present",
    region_applicable: "Entire MP",
    used_in: ["Small engineering measurements"],
    references: ["Arthashastra"],
    tags: ["madhya-pradesh", "traditional-units", "transportation-distance", "angula", "length"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-trans-2",
    slug: "vitasti-mp-transportation",
    name_english: "Vitasti",
    name_hindi: "वितस्ति",
    local_names: ["वितस्ति", "Vitasti"],
    name_sanskrit: "वितस्ति",
    meaning: "Measuring carts, wooden parts. Span measure.",
    category: "length",
    measurement_type: "Length",
    sector: "transportation-distance",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈22.8 cm",
    conversion_formula: "12 Angula = 1 Vitasti",
    historical_period: "Ancient–Medieval",
    region_applicable: "Entire MP",
    used_in: ["Measuring carts, wooden parts"],
    references: ["Manusmriti"],
    tags: ["madhya-pradesh", "traditional-units", "transportation-distance", "vitasti", "length"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-trans-3",
    slug: "hasta-mp-transportation",
    name_english: "Hasta",
    name_hindi: "हस्त",
    local_names: ["हस्त", "Hasta"],
    name_sanskrit: "Hasta",
    meaning: "Vehicle construction. Cubit.",
    category: "length",
    measurement_type: "Length",
    sector: "transportation-distance",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈45.6 cm",
    conversion_formula: "2 Vitasti = 1 Hasta (24 Angula)",
    historical_period: "Ancient–Present",
    region_applicable: "Entire MP",
    used_in: ["Vehicle construction"],
    references: ["Mayamata"],
    tags: ["madhya-pradesh", "traditional-units", "transportation-distance", "hasta", "length"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-trans-4",
    slug: "danda-mp-transportation",
    name_english: "Danda",
    name_hindi: "दण्ड",
    local_names: ["दण्ड", "Daṇḍa"],
    name_sanskrit: "दण्ड",
    meaning: "Roads, bridges, layouts. Measuring rod.",
    category: "length",
    measurement_type: "Distance",
    sector: "transportation-distance",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈1.82 m",
    conversion_formula: "4 Hasta = 1 Danda",
    historical_period: "Ancient–Medieval",
    region_applicable: "Entire MP",
    used_in: ["Roads, bridges, layouts"],
    references: ["Arthashastra"],
    tags: ["madhya-pradesh", "traditional-units", "transportation-distance", "danda", "distance"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-trans-5",
    slug: "gaj-gaz-mp-transportation",
    name_english: "Gaj (Gaz)",
    name_hindi: "गज़",
    local_names: ["गज़", "Gaj (Gaz)"],
    meaning: "Measuring roads, timber, carts. Standard linear measure.",
    category: "length",
    measurement_type: "Length",
    sector: "transportation-distance",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈0.9144 m",
    conversion_formula: "Regional standard",
    historical_period: "Mughal–Present",
    region_applicable: "Entire MP",
    used_in: ["Measuring roads, timber, carts"],
    references: ["Imperial Gazetteer"],
    tags: ["madhya-pradesh", "traditional-units", "transportation-distance", "gaj-gaz", "length"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-trans-6",
    slug: "rajju-mp-transportation",
    name_english: "Rajju",
    name_hindi: "रज्जु",
    local_names: ["रज्जु", "Rajju"],
    name_sanskrit: "रज्जु",
    meaning: "Road and land surveying. Survey rope.",
    category: "length",
    measurement_type: "Survey Length",
    sector: "transportation-distance",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "Regionally Variable",
    conversion_formula: "Rope measure (variable)",
    historical_period: "Ancient–Colonial",
    region_applicable: "Malwa, Bundelkhand",
    used_in: ["Road and land surveying"],
    references: ["Survey Manuals"],
    tags: ["madhya-pradesh", "traditional-units", "transportation-distance", "rajju", "survey-length"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-trans-7",
    slug: "krosha-kos-mp-transportation",
    name_english: "Krosha (Kos)",
    name_hindi: "क्रोश / कोस",
    local_names: ["क्रोश / कोस", "Krosha (Kos)"],
    name_sanskrit: "क्रोश",
    meaning: "Road travel, milestones. Traditional road distance.",
    category: "length",
    measurement_type: "Distance",
    sector: "transportation-distance",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈3.2 km (regional variation 3–3.5 km)",
    conversion_formula: "1 Kos = 2000 Danda (traditional)",
    historical_period: "Ancient–British",
    region_applicable: "Entire MP",
    used_in: ["Road travel, milestones"],
    references: ["Arthashastra; Imperial Gazetteer"],
    tags: ["madhya-pradesh", "traditional-units", "transportation-distance", "krosha-kos", "distance"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-trans-8",
    slug: "yojana-mp-transportation",
    name_english: "Yojana",
    name_hindi: "योजन",
    local_names: ["योजन", "Yojana"],
    name_sanskrit: "योजन",
    meaning: "Long-distance travel and route planning. Largest traditional distance unit.",
    category: "length",
    measurement_type: "Long Distance",
    sector: "transportation-distance",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈12.8 km (approx.)",
    conversion_formula: "4 Kos = 1 Yojana",
    historical_period: "Ancient–Medieval",
    region_applicable: "Entire MP",
    used_in: ["Long-distance travel and route planning"],
    references: ["Surya Siddhanta; Arthashastra"],
    tags: ["madhya-pradesh", "traditional-units", "transportation-distance", "yojana", "distance"],
    created_at: "2024-01-01",
  },

  // ───────────────────────────────────────────────────────────────────────────
  // SECTOR: Livestock & Dairy (8 units)
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "mp-dairy-1",
    slug: "ratti-mp-dairy",
    name_english: "Ratti",
    name_hindi: "रत्ती",
    local_names: ["रत्ती", "Ratti"],
    name_sanskrit: "रक्तिका (Raktikā)",
    meaning: "Veterinary medicines. Smallest weight unit.",
    category: "weight",
    measurement_type: "Weight",
    sector: "livestock-dairy",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈121.5 mg",
    conversion_formula: "Base Unit",
    historical_period: "Ancient–Present",
    region_applicable: "Entire MP",
    used_in: ["Veterinary medicines"],
    references: ["Charaka Samhita"],
    tags: ["madhya-pradesh", "traditional-units", "livestock-dairy", "ratti", "weight"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-dairy-2",
    slug: "masha-mp-dairy",
    name_english: "Masha",
    name_hindi: "माशा",
    local_names: ["माशा", "Masha"],
    name_sanskrit: "माष",
    meaning: "Animal medicines. Small medicinal weight.",
    category: "weight",
    measurement_type: "Weight",
    sector: "livestock-dairy",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈0.972 g",
    conversion_formula: "8 Ratti = 1 Masha",
    historical_period: "Ancient–Present",
    region_applicable: "Entire MP",
    used_in: ["Animal medicines"],
    references: ["Sushruta Samhita"],
    tags: ["madhya-pradesh", "traditional-units", "livestock-dairy", "masha", "weight"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-dairy-3",
    slug: "tola-mp-dairy",
    name_english: "Tola",
    name_hindi: "तोला",
    local_names: ["तोला", "Tola"],
    name_sanskrit: "तुला",
    meaning: "Butter, medicinal preparations. Standard weight.",
    category: "weight",
    measurement_type: "Weight",
    sector: "livestock-dairy",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈11.66 g",
    conversion_formula: "12 Masha = 1 Tola",
    historical_period: "Mughal–Present",
    region_applicable: "Entire MP",
    used_in: ["Butter, medicinal preparations"],
    references: ["British India Standards"],
    tags: ["madhya-pradesh", "traditional-units", "livestock-dairy", "tola", "weight"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-dairy-4",
    slug: "chhatak-mp-dairy",
    name_english: "Chhatak",
    name_hindi: "छटाक",
    local_names: ["छटाक", "Chhatak"],
    meaning: "Butter, ghee. Small dairy measure.",
    category: "weight",
    measurement_type: "Weight",
    sector: "livestock-dairy",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈58.3 g",
    conversion_formula: "5 Tola = 1 Chhatak",
    historical_period: "Mughal–1958",
    region_applicable: "Entire MP",
    used_in: ["Butter, ghee"],
    references: ["Central Provinces Gazetteers"],
    tags: ["madhya-pradesh", "traditional-units", "livestock-dairy", "chhatak", "weight"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-dairy-5",
    slug: "pav-pao-mp-dairy",
    name_english: "Pav (Pao)",
    name_hindi: "पाव",
    local_names: ["पाव", "Pav"],
    meaning: "Milk and curd. Quarter Seer.",
    category: "volume",
    measurement_type: "Weight/Capacity",
    sector: "livestock-dairy",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈233 g / ≈250 ml (approx.)",
    conversion_formula: "4 Chhatak = 1 Pav",
    historical_period: "Mughal–1958",
    region_applicable: "Entire MP",
    used_in: ["Milk and curd"],
    references: ["MP District Gazetteers"],
    tags: ["madhya-pradesh", "traditional-units", "livestock-dairy", "pav-pao", "capacity"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-dairy-6",
    slug: "adha-seer-mp-dairy",
    name_english: "Adha Seer",
    name_hindi: "आधा सेर",
    local_names: ["आधा सेर", "Adha Seer"],
    meaning: "Milk, curd. Half Seer.",
    category: "volume",
    measurement_type: "Weight/Capacity",
    sector: "livestock-dairy",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈466 g / ≈500 ml (approx.)",
    conversion_formula: "2 Pav = 1 Half Seer",
    historical_period: "Mughal–1958",
    region_applicable: "Entire MP",
    used_in: ["Milk, curd"],
    references: ["Revenue Manuals"],
    tags: ["madhya-pradesh", "traditional-units", "livestock-dairy", "adha-seer", "capacity"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-dairy-7",
    slug: "seer-mp-dairy",
    name_english: "Seer",
    name_hindi: "सेर",
    local_names: ["सेर", "Seer"],
    meaning: "Milk, ghee, fodder. Standard dairy measure.",
    category: "volume",
    measurement_type: "Weight/Capacity",
    sector: "livestock-dairy",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈0.933 kg / ≈0.93 L",
    conversion_formula: "2 Half Seer = 1 Seer",
    historical_period: "Mughal–1958",
    region_applicable: "Entire MP",
    used_in: ["Milk, ghee, fodder"],
    references: ["Imperial Gazetteer"],
    tags: ["madhya-pradesh", "traditional-units", "livestock-dairy", "seer", "capacity"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-dairy-8",
    slug: "maund-man-mp-dairy",
    name_english: "Maund (Man)",
    name_hindi: "मन",
    local_names: ["मन", "Maund"],
    name_sanskrit: "मान",
    meaning: "Fodder, cattle feed. Bulk agricultural unit.",
    category: "weight",
    measurement_type: "Bulk Weight",
    sector: "livestock-dairy",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈37.324 kg",
    conversion_formula: "40 Seers = 1 Maund",
    historical_period: "Mughal–1958",
    region_applicable: "Entire MP",
    used_in: ["Fodder, cattle feed"],
    references: ["Government Historical Standards"],
    tags: ["madhya-pradesh", "traditional-units", "livestock-dairy", "maund-man", "weight"],
    created_at: "2024-01-01",
  },

  // ───────────────────────────────────────────────────────────────────────────
  // SECTOR: Household & Daily Life (8 units)
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "mp-hh-1",
    slug: "ratti-mp-household",
    name_english: "Ratti",
    name_hindi: "रत्ती",
    local_names: ["रत्ती", "Ratti"],
    name_sanskrit: "रक्तिका (Raktikā)",
    meaning: "Spices, medicines. Smallest household weight.",
    category: "weight",
    measurement_type: "Weight",
    sector: "household",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈121.5 mg",
    conversion_formula: "Base Unit",
    historical_period: "Ancient–Present",
    region_applicable: "Entire MP",
    used_in: ["Spices, medicines"],
    references: ["Charaka Samhita"],
    tags: ["madhya-pradesh", "traditional-units", "household", "ratti", "weight"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-hh-2",
    slug: "masha-mp-household",
    name_english: "Masha",
    name_hindi: "माशा",
    local_names: ["माशा", "Masha"],
    name_sanskrit: "माष",
    meaning: "Spices, herbal ingredients. Small kitchen weight.",
    category: "weight",
    measurement_type: "Weight",
    sector: "household",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈0.972 g",
    conversion_formula: "8 Ratti = 1 Masha",
    historical_period: "Ancient–Present",
    region_applicable: "Entire MP",
    used_in: ["Spices, herbal ingredients"],
    references: ["Sushruta Samhita"],
    tags: ["madhya-pradesh", "traditional-units", "household", "masha", "weight"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-hh-3",
    slug: "tola-mp-household",
    name_english: "Tola",
    name_hindi: "तोला",
    local_names: ["तोला", "Tola"],
    name_sanskrit: "तुला",
    meaning: "Ghee, spices, precious ingredients. Standard household weight.",
    category: "weight",
    measurement_type: "Weight",
    sector: "household",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈11.66 g",
    conversion_formula: "12 Masha = 1 Tola",
    historical_period: "Mughal–Present",
    region_applicable: "Entire MP",
    used_in: ["Ghee, spices, precious ingredients"],
    references: ["British India Standards"],
    tags: ["madhya-pradesh", "traditional-units", "household", "tola", "weight"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-hh-4",
    slug: "chhatak-mp-household",
    name_english: "Chhatak",
    name_hindi: "छटाक",
    local_names: ["छटाक", "Chhatak"],
    meaning: "Sugar, flour, lentils. Small domestic measure.",
    category: "weight",
    measurement_type: "Weight",
    sector: "household",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈58.3 g",
    conversion_formula: "5 Tola = 1 Chhatak",
    historical_period: "Mughal–1958",
    region_applicable: "Entire MP",
    used_in: ["Sugar, flour, lentils"],
    references: ["Central Provinces Gazetteers"],
    tags: ["madhya-pradesh", "traditional-units", "household", "chhatak", "weight"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-hh-5",
    slug: "pav-pao-mp-household",
    name_english: "Pav (Pao)",
    name_hindi: "पाव",
    local_names: ["पाव", "Pav"],
    meaning: "Rice, wheat flour, oil. Quarter Seer.",
    category: "weight",
    measurement_type: "Weight/Capacity",
    sector: "household",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈233 g",
    conversion_formula: "4 Chhatak = 1 Pav",
    historical_period: "Mughal–1958",
    region_applicable: "Entire MP",
    used_in: ["Rice, wheat flour, oil"],
    references: ["MP District Gazetteers"],
    tags: ["madhya-pradesh", "traditional-units", "household", "pav-pao", "capacity"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-hh-6",
    slug: "adha-seer-mp-household",
    name_english: "Adha Seer",
    name_hindi: "आधा सेर",
    local_names: ["आधा सेर", "Adha Seer"],
    meaning: "Cereals and pulses. Half Seer.",
    category: "weight",
    measurement_type: "Weight/Capacity",
    sector: "household",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈466 g",
    conversion_formula: "2 Pav = 1 Half Seer",
    historical_period: "Mughal–1958",
    region_applicable: "Entire MP",
    used_in: ["Cereals and pulses"],
    references: ["Revenue Settlement Manuals"],
    tags: ["madhya-pradesh", "traditional-units", "household", "adha-seer", "capacity"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-hh-7",
    slug: "seer-mp-household",
    name_english: "Seer",
    name_hindi: "सेर",
    local_names: ["सेर", "Seer"],
    meaning: "Rice, wheat, pulses, edible oil. Standard domestic measure.",
    category: "weight",
    measurement_type: "Weight/Capacity",
    sector: "household",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈0.933 kg / ≈0.93 L",
    conversion_formula: "2 Half Seer = 1 Seer",
    historical_period: "Mughal–1958",
    region_applicable: "Entire MP",
    used_in: ["Rice, wheat, pulses, edible oil"],
    references: ["Imperial Gazetteer of India"],
    tags: ["madhya-pradesh", "traditional-units", "household", "seer", "capacity"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-hh-8",
    slug: "maund-man-mp-household",
    name_english: "Maund (Man)",
    name_hindi: "मन",
    local_names: ["मन", "Maund"],
    name_sanskrit: "मान",
    meaning: "Household grain storage. Bulk storage unit.",
    category: "weight",
    measurement_type: "Bulk Weight",
    sector: "household",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈37.324 kg",
    conversion_formula: "40 Seers = 1 Maund",
    historical_period: "Mughal–1958",
    region_applicable: "Entire MP",
    used_in: ["Household grain storage"],
    references: ["Government of India Historical Standards"],
    tags: ["madhya-pradesh", "traditional-units", "household", "maund-man", "weight"],
    created_at: "2024-01-01",
  },

  // ───────────────────────────────────────────────────────────────────────────
  // SECTOR: Gold & Jewellery (7 units)
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "mp-gold-1",
    slug: "ratti-mp-gold",
    name_english: "Ratti",
    name_hindi: "रत्ती",
    local_names: ["रत्ती", "Ratti"],
    name_sanskrit: "रक्तिका (Raktikā)",
    meaning: "Diamonds, pearls, gemstones. Smallest jewellery weight.",
    category: "weight",
    measurement_type: "Precious Metal Weight",
    sector: "gold-jewellery",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈121.5 mg",
    conversion_formula: "Base Unit",
    historical_period: "Ancient–Present",
    region_applicable: "Entire MP",
    used_in: ["Diamonds, pearls, gemstones"],
    references: ["Arthashastra; Ratnaśāstra"],
    tags: ["madhya-pradesh", "traditional-units", "gold-jewellery", "ratti", "precious-metals"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-gold-2",
    slug: "masha-mp-gold",
    name_english: "Masha",
    name_hindi: "माशा",
    local_names: ["माशा", "Masha"],
    name_sanskrit: "माष",
    meaning: "Gold and silver ornaments. Small jewellery weight.",
    category: "weight",
    measurement_type: "Precious Metal Weight",
    sector: "gold-jewellery",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈0.972 g",
    conversion_formula: "8 Ratti = 1 Masha",
    historical_period: "Ancient–Present",
    region_applicable: "Entire MP",
    used_in: ["Gold and silver ornaments"],
    references: ["Sushruta Samhita"],
    tags: ["madhya-pradesh", "traditional-units", "gold-jewellery", "masha", "precious-metals"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-gold-3",
    slug: "suvarna-mp-gold",
    name_english: "Suvarna",
    name_hindi: "सुवर्ण",
    local_names: ["सुवर्ण", "Suvarna"],
    name_sanskrit: "सुवर्ण",
    meaning: "Gold coins and ornaments. Classical gold unit.",
    category: "weight",
    measurement_type: "Precious Metal Weight",
    sector: "gold-jewellery",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈15.55 g",
    conversion_formula: "16 Masha = 1 Suvarna",
    historical_period: "Ancient–Medieval",
    region_applicable: "Entire MP",
    used_in: ["Gold coins and ornaments"],
    references: ["Arthashastra"],
    tags: ["madhya-pradesh", "traditional-units", "gold-jewellery", "suvarna", "precious-metals"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-gold-4",
    slug: "tola-mp-gold",
    name_english: "Tola",
    name_hindi: "तोला",
    local_names: ["तोला", "Tola"],
    name_sanskrit: "तुला",
    meaning: "Gold and silver trade. Standard jewellers' unit.",
    category: "weight",
    measurement_type: "Precious Metal Weight",
    sector: "gold-jewellery",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈11.66 g",
    conversion_formula: "12 Masha = 1 Tola",
    historical_period: "Mughal–Present",
    region_applicable: "Entire MP",
    used_in: ["Gold and silver trade"],
    references: ["British India Standards"],
    tags: ["madhya-pradesh", "traditional-units", "gold-jewellery", "tola", "precious-metals"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-gold-5",
    slug: "chhatak-mp-gold",
    name_english: "Chhatak",
    name_hindi: "छटाक",
    local_names: ["छटाक", "Chhatak"],
    meaning: "Bulk silver and bullion. Medium bullion weight.",
    category: "weight",
    measurement_type: "Precious Metal Weight",
    sector: "gold-jewellery",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈58.3 g",
    conversion_formula: "5 Tola = 1 Chhatak",
    historical_period: "Mughal–Colonial",
    region_applicable: "Entire MP",
    used_in: ["Bulk silver and bullion"],
    references: ["Central Provinces Gazetteers"],
    tags: ["madhya-pradesh", "traditional-units", "gold-jewellery", "chhatak", "precious-metals"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-gold-6",
    slug: "seer-mp-gold",
    name_english: "Seer",
    name_hindi: "सेर",
    local_names: ["सेर", "Seer"],
    meaning: "Large bullion transactions. Wholesale bullion unit.",
    category: "weight",
    measurement_type: "Bullion Weight",
    sector: "gold-jewellery",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈0.933 kg",
    conversion_formula: "16 Chhatak = 1 Seer",
    historical_period: "Mughal–Colonial",
    region_applicable: "Entire MP",
    used_in: ["Large bullion transactions"],
    references: ["Imperial Gazetteer"],
    tags: ["madhya-pradesh", "traditional-units", "gold-jewellery", "seer", "bullion"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-gold-7",
    slug: "maund-man-mp-gold",
    name_english: "Maund (Man)",
    name_hindi: "मन",
    local_names: ["मन", "Maund"],
    name_sanskrit: "मान",
    meaning: "Treasury and state reserves. Largest traditional weight.",
    category: "weight",
    measurement_type: "Bulk Bullion Weight",
    sector: "gold-jewellery",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈37.324 kg",
    conversion_formula: "40 Seer = 1 Maund",
    historical_period: "Mughal–Colonial",
    region_applicable: "Entire MP",
    used_in: ["Treasury and state reserves"],
    references: ["Government Historical Standards"],
    tags: ["madhya-pradesh", "traditional-units", "gold-jewellery", "maund-man", "bulk-bullion"],
    created_at: "2024-01-01",
  },

  // ───────────────────────────────────────────────────────────────────────────
  // SECTOR: Currency & Money (6 units)
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "mp-curr-1",
    slug: "cowrie-mp-currency",
    name_english: "Cowrie",
    name_hindi: "कौड़ी",
    local_names: ["कौड़ी", "Cowrie"],
    name_sanskrit: "कपर्दिका (Kapardikā)",
    meaning: "Petty transactions. Smallest medium of exchange.",
    category: "currency",
    measurement_type: "Currency",
    sector: "currency-money",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "No fixed SI equivalent",
    conversion_formula: "Base unit (small-value currency)",
    historical_period: "Ancient–Medieval",
    region_applicable: "Entire MP",
    used_in: ["Petty transactions"],
    references: ["Arthashastra; Numismatic Studies"],
    tags: ["madhya-pradesh", "traditional-units", "currency-money", "cowrie", "currency"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-curr-2",
    slug: "dam-mp-currency",
    name_english: "Dam",
    name_hindi: "दाम",
    local_names: ["दाम", "Dām"],
    name_sanskrit: "द्रम / दाम",
    meaning: "Everyday market transactions. Copper coin.",
    category: "currency",
    measurement_type: "Currency",
    sector: "currency-money",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "Historical monetary unit",
    conversion_formula: "40 Dam = 1 Rupee (Mughal standard)",
    historical_period: "Mughal Period",
    region_applicable: "Entire MP",
    used_in: ["Everyday market transactions"],
    references: ["Ain-i-Akbari"],
    tags: ["madhya-pradesh", "traditional-units", "currency-money", "dam", "currency"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-curr-3",
    slug: "anna-mp-currency",
    name_english: "Anna",
    name_hindi: "आना",
    local_names: ["आना", "Ānā"],
    meaning: "Retail trade. Fractional rupee.",
    category: "currency",
    measurement_type: "Currency",
    sector: "currency-money",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "Historical monetary unit",
    conversion_formula: "16 Anna = 1 Rupee",
    historical_period: "British India",
    region_applicable: "Entire MP",
    used_in: ["Retail trade"],
    references: ["British Indian Coinage"],
    tags: ["madhya-pradesh", "traditional-units", "currency-money", "anna", "currency"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-curr-4",
    slug: "paisa-old-mp-currency",
    name_english: "Paisa (Old)",
    name_hindi: "पैसा",
    local_names: ["पैसा", "Paisa"],
    name_sanskrit: "पैस",
    meaning: "Daily purchases. Fractional currency.",
    category: "currency",
    measurement_type: "Currency",
    sector: "currency-money",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "Historical monetary unit",
    conversion_formula: "1 Anna = 4 Paisa (Old system)",
    historical_period: "British India",
    region_applicable: "Entire MP",
    used_in: ["Daily purchases"],
    references: ["Government Coinage Records"],
    tags: ["madhya-pradesh", "traditional-units", "currency-money", "paisa-old", "currency"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-curr-5",
    slug: "rupee-mp-currency",
    name_english: "Rupee",
    name_hindi: "रुपया",
    local_names: ["रुपया", "Rūpaya"],
    name_sanskrit: "रूप्य",
    meaning: "Trade, taxation, salaries. Standard monetary unit.",
    category: "currency",
    measurement_type: "Currency",
    sector: "currency-money",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "Historical silver coin",
    conversion_formula: "1 Rupee = 16 Anna = 64 Paisa = 192 Pie",
    historical_period: "Sher Shah Suri–Present",
    region_applicable: "Entire MP",
    used_in: ["Trade, taxation, salaries"],
    references: ["Arthashastra; Imperial Gazetteer"],
    tags: ["madhya-pradesh", "traditional-units", "currency-money", "rupee", "currency"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-curr-6",
    slug: "mohur-mp-currency",
    name_english: "Mohur",
    name_hindi: "मोहर",
    local_names: ["मोहर", "Mohur"],
    name_sanskrit: "सुवर्ण मुद्रा",
    meaning: "High-value trade. Gold currency.",
    category: "currency",
    measurement_type: "Currency",
    sector: "currency-money",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "Gold coin",
    conversion_formula: "Value varied with gold content",
    historical_period: "Mughal–British",
    region_applicable: "Entire MP",
    used_in: ["High-value trade"],
    references: ["Numismatic Society of India"],
    tags: ["madhya-pradesh", "traditional-units", "currency-money", "mohur", "currency"],
    created_at: "2024-01-01",
  },

  // ───────────────────────────────────────────────────────────────────────────
  // SECTOR: Storage & Transport (7 units)
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "mp-stor-1",
    slug: "chhatak-mp-storage",
    name_english: "Chhatak",
    name_hindi: "छटाक",
    local_names: ["छटाक", "Chhatak"],
    meaning: "Small storage unit",
    category: "weight",
    measurement_type: "Storage Weight",
    sector: "storage-transport",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈58.3 g",
    conversion_formula: "5 Tola = 1 Chhatak",
    historical_period: "Mughal–1958",
    region_applicable: "Entire MP",
    used_in: ["Small quantities of grain, spices"],
    references: ["Central Provinces Gazetteers"],
    tags: ["madhya-pradesh", "traditional-units", "storage-transport", "chhatak", "weight"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-stor-2",
    slug: "pav-pao-mp-storage",
    name_english: "Pav (Pao)",
    name_hindi: "पाव",
    local_names: ["पाव", "Pav"],
    meaning: "Quarter Seer",
    category: "weight",
    measurement_type: "Storage Weight",
    sector: "storage-transport",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈233 g",
    conversion_formula: "4 Chhatak = 1 Pav",
    historical_period: "Mughal–1958",
    region_applicable: "Entire MP",
    used_in: ["Household storage of grains"],
    references: ["MP District Gazetteers"],
    tags: ["madhya-pradesh", "traditional-units", "storage-transport", "pav-pao", "weight"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-stor-3",
    slug: "adha-seer-mp-storage",
    name_english: "Adha Seer",
    name_hindi: "आधा सेर",
    local_names: ["आधा सेर", "Adha Seer"],
    meaning: "Half Seer",
    category: "weight",
    measurement_type: "Storage Weight",
    sector: "storage-transport",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈466 g",
    conversion_formula: "2 Pav = 1 Half Seer",
    historical_period: "Mughal–1958",
    region_applicable: "Entire MP",
    used_in: ["Grain, pulses"],
    references: ["Revenue Settlement Manuals"],
    tags: ["madhya-pradesh", "traditional-units", "storage-transport", "adha-seer", "weight"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-stor-4",
    slug: "seer-mp-storage",
    name_english: "Seer",
    name_hindi: "सेर",
    local_names: ["सेर", "Seer"],
    meaning: "Standard storage unit",
    category: "weight",
    measurement_type: "Storage Weight",
    sector: "storage-transport",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈0.933 kg",
    conversion_formula: "2 Half Seer = 1 Seer",
    historical_period: "Mughal–1958",
    region_applicable: "Entire MP",
    used_in: ["Rice, wheat, pulses, oilseeds"],
    references: ["Imperial Gazetteer of India"],
    tags: ["madhya-pradesh", "traditional-units", "storage-transport", "seer", "weight"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-stor-5",
    slug: "pasri-mp-storage",
    name_english: "Pasri",
    name_hindi: "पसरी",
    local_names: ["पसरी", "Pasri"],
    meaning: "Intermediate storage unit",
    category: "volume",
    measurement_type: "Grain Capacity",
    sector: "storage-transport",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈4.66 kg (where applicable)",
    conversion_formula: "Usually 5 Seers = 1 Pasri (Regional Variation)",
    historical_period: "Colonial",
    region_applicable: "Malwa, Bundelkhand",
    used_in: ["Village grain storage"],
    references: ["District Gazetteers"],
    tags: ["madhya-pradesh", "traditional-units", "storage-transport", "pasri", "capacity"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-stor-6",
    slug: "maund-man-mp-storage",
    name_english: "Maund (Man)",
    name_hindi: "मन",
    local_names: ["मन", "Maund (Man)"],
    name_sanskrit: "मान",
    meaning: "Principal bulk storage unit",
    category: "weight",
    measurement_type: "Bulk Storage Weight",
    sector: "storage-transport",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈37.324 kg",
    conversion_formula: "40 Seers = 1 Maund",
    historical_period: "Mughal–1958",
    region_applicable: "Entire MP",
    used_in: ["Grain storage, transport by bullock carts"],
    references: ["Government Historical Standards"],
    tags: ["madhya-pradesh", "traditional-units", "storage-transport", "maund-man", "bulk-storage"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-stor-7",
    slug: "khandi-mp-storage",
    name_english: "Khandi",
    name_hindi: "खंडी",
    local_names: ["खंडी", "Khandi"],
    name_sanskrit: "खण्डी",
    meaning: "Largest traditional storage unit",
    category: "volume",
    measurement_type: "Bulk Capacity",
    sector: "storage-transport",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈746 kg (regional variation)",
    conversion_formula: "≈20 Maunds = 1 Khandi (Regional)",
    historical_period: "Medieval–Colonial",
    region_applicable: "Malwa, Nimar",
    used_in: ["Warehouse storage and long-distance transport"],
    references: ["Madhya Pradesh District Gazetteers"],
    tags: ["madhya-pradesh", "traditional-units", "storage-transport", "khandi", "bulk-capacity"],
    created_at: "2024-01-01",
  },

  // ───────────────────────────────────────────────────────────────────────────
  // SECTOR: Land Measurement (6 units)
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "mp-land-1",
    slug: "square-gaj-mp-land",
    name_english: "Square Gaj",
    name_hindi: "वर्ग गज़",
    local_names: ["वर्ग गज़", "Square Gaj"],
    name_sanskrit: "गज",
    meaning: "Smallest commonly used area unit",
    category: "area",
    measurement_type: "Land Area",
    sector: "land-measurement",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈0.8361 m²",
    conversion_formula: "Base Unit",
    historical_period: "Mughal–Present",
    region_applicable: "Entire MP",
    used_in: ["House plots and small land parcels"],
    references: ["Imperial Gazetteer of India"],
    tags: ["madhya-pradesh", "traditional-units", "land-measurement", "square-gaj", "area"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-land-2",
    slug: "biswansi-mp-land",
    name_english: "Biswansi",
    name_hindi: "बिसवांसी",
    local_names: ["बिसवांसी", "Biswansi"],
    meaning: "Small land subdivision",
    category: "area",
    measurement_type: "Land Area",
    sector: "land-measurement",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "Regionally Variable",
    conversion_formula: "20 Biswansi = 1 Biswa",
    historical_period: "Mughal–British",
    region_applicable: "Bundelkhand, Gwalior",
    used_in: ["Revenue subdivision"],
    references: ["Settlement Reports"],
    tags: ["madhya-pradesh", "traditional-units", "land-measurement", "biswansi", "area"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-land-3",
    slug: "biswa-mp-land",
    name_english: "Biswa",
    name_hindi: "बिस्वा",
    local_names: ["बिस्वा", "Biswa"],
    meaning: "Revenue land unit",
    category: "area",
    measurement_type: "Land Area",
    sector: "land-measurement",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "Regionally Variable",
    conversion_formula: "20 Biswa = 1 Bigha",
    historical_period: "Mughal–British",
    region_applicable: "Bundelkhand, Gwalior",
    used_in: ["Agricultural land records"],
    references: ["MP District Gazetteers"],
    tags: ["madhya-pradesh", "traditional-units", "land-measurement", "biswa", "area"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-land-4",
    slug: "bigha-mp-land",
    name_english: "Bigha",
    name_hindi: "बीघा",
    local_names: ["बीघा", "Bigha"],
    meaning: "Principal traditional land unit",
    category: "area",
    measurement_type: "Land Area",
    sector: "land-measurement",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "≈0.25–0.67 hectare (varied by district)",
    conversion_formula: "20 Biswa = 1 Bigha",
    historical_period: "Mughal–Present",
    region_applicable: "Entire MP",
    used_in: ["Agricultural fields"],
    references: ["Imperial Gazetteer; MP Gazetteers"],
    tags: ["madhya-pradesh", "traditional-units", "land-measurement", "bigha", "area"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-land-5",
    slug: "acre-mp-land",
    name_english: "Acre",
    name_hindi: "एकड़",
    local_names: ["एकड़", "Acre"],
    meaning: "British standard land unit",
    category: "area",
    measurement_type: "Land Area",
    sector: "land-measurement",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "4046.86 m²",
    conversion_formula: "1 Acre = 4840 sq yd",
    historical_period: "British–Present",
    region_applicable: "Entire MP",
    used_in: ["Revenue and settlement records"],
    references: ["British Revenue Records"],
    tags: ["madhya-pradesh", "traditional-units", "land-measurement", "acre", "area"],
    created_at: "2024-01-01",
  },
  {
    id: "mp-land-6",
    slug: "hectare-mp-land",
    name_english: "Hectare",
    name_hindi: "हेक्टेयर",
    local_names: ["हेक्टेयर", "Hectare"],
    meaning: "Official metric unit",
    category: "area",
    measurement_type: "Land Area",
    sector: "land-measurement",
    origin: "Madhya Pradesh",
    states: ["Madhya Pradesh"],
    modern_equivalent: "10,000 m²",
    conversion_formula: "1 Hectare = 2.471 Acres",
    historical_period: "1958–Present",
    region_applicable: "Entire MP",
    used_in: ["Modern land records"],
    references: ["Government of India"],
    tags: ["madhya-pradesh", "traditional-units", "land-measurement", "hectare", "area"],
    created_at: "2024-01-01",
  },
];
