import { Measurement } from "@/types";

export const MP_MEASUREMENTS: Measurement[] = [
  // Seed & Crop (Agriculture)
  {
    id: "mp-agri-1",
    slug: "mp-ratti-agri",
    name_english: "Ratti",
    name_hindi: "रत्ती",
    name_sanskrit: "Raktikā",
    local_names: ["रत्ती (Ratti)"],
    meaning: "Smallest traditional weight unit for seeds.",
    category: "weight",
    sector: "agriculture",
    modern_equivalent: "≈0.1215 g",
    conversion_formula: "Base Unit",
    states: ["Madhya Pradesh"],
    used_in: ["Weighing seeds, medicinal herbs and spices"],
    references: ["Arthashastra; Charaka Samhita"],
  },
  {
    id: "mp-agri-2",
    slug: "mp-masha-agri",
    name_english: "Masha",
    name_hindi: "माशा",
    name_sanskrit: "Māṣa",
    local_names: ["माशा (Masha)"],
    meaning: "Small agricultural weight.",
    category: "weight",
    sector: "agriculture",
    modern_equivalent: "≈0.972 g",
    conversion_formula: "8 Ratti = 1 Masha",
    states: ["Madhya Pradesh"],
    used_in: ["Seeds, herbs, agricultural produce"],
    references: ["Arthashastra"],
  },
  {
    id: "mp-agri-3",
    slug: "mp-tola-agri",
    name_english: "Tola",
    name_hindi: "तोला",
    name_sanskrit: "Tulā",
    local_names: ["तोला (Tola)"],
    meaning: "Standard traditional weight.",
    category: "weight",
    sector: "agriculture",
    modern_equivalent: "≈11.66 g",
    conversion_formula: "12 Masha = 1 Tola",
    states: ["Madhya Pradesh"],
    used_in: ["Oilseeds, spices, valuable produce"],
    references: ["British India Standards"],
  },

  // Trade & Commerce
  {
    id: "mp-trade-1",
    slug: "mp-chhatak-trade",
    name_english: "Chhatak",
    name_hindi: "छटाक",
    local_names: ["छटाक (Chhatak)"],
    meaning: "Retail weight.",
    category: "weight",
    sector: "trade-commerce",
    modern_equivalent: "≈58.3 g",
    conversion_formula: "5 Tola = 1 Chhatak",
    states: ["Madhya Pradesh"],
    used_in: ["Grocery items"],
    references: ["Central Provinces Gazetteers"],
  },
  {
    id: "mp-trade-2",
    slug: "mp-pav-trade",
    name_english: "Pav (Pao)",
    name_hindi: "पाव",
    local_names: ["पाव (Pav)"],
    meaning: "Quarter Seer.",
    category: "weight",
    sector: "trade-commerce",
    modern_equivalent: "≈233 g",
    conversion_formula: "4 Chhatak = 1 Pav",
    states: ["Madhya Pradesh"],
    used_in: ["Flour, sugar, pulses"],
    references: ["MP District Gazetteers"],
  },

  // Textile & Handloom
  {
    id: "mp-tex-1",
    slug: "mp-angul-tex",
    name_english: "Angul",
    name_hindi: "अंगुल",
    name_sanskrit: "Aṅgula",
    local_names: ["अंगुल (Angul)"],
    meaning: "Finger-width measurement.",
    category: "length",
    sector: "textile-handloom",
    modern_equivalent: "≈1.9 cm",
    conversion_formula: "Base Unit",
    states: ["Madhya Pradesh"],
    used_in: ["Measuring thread, cloth borders"],
    references: ["Arthashastra; Manasara"],
  },
  {
    id: "mp-tex-2",
    slug: "mp-gaz-tex",
    name_english: "Gaz (Gaj)",
    name_hindi: "गज़",
    local_names: ["गज़ (Gaz)"],
    meaning: "Standard cloth measure.",
    category: "length",
    sector: "textile-handloom",
    modern_equivalent: "≈0.9144 m",
    conversion_formula: "Regional standard",
    states: ["Madhya Pradesh"],
    used_in: ["Cloth trade, tailoring"],
    references: ["Imperial Gazetteer"],
  },

  // Medicine (Ayurveda)
  {
    id: "mp-med-1",
    slug: "mp-karsha-med",
    name_english: "Karsha",
    name_hindi: "कर्ष",
    name_sanskrit: "Karṣa",
    local_names: ["कर्ष (Karsha)"],
    meaning: "Common medicinal dose.",
    category: "weight",
    sector: "medicine",
    modern_equivalent: "≈11.66 g",
    conversion_formula: "12 Masha = 1 Karsha",
    states: ["Madhya Pradesh"],
    used_in: ["Churna, Kalka"],
    references: ["Charaka Samhita"],
  },
  {
    id: "mp-med-2",
    slug: "mp-pala-med",
    name_english: "Pala",
    name_hindi: "पल",
    name_sanskrit: "Pala",
    local_names: ["पल (Pala)"],
    meaning: "Standard pharmacy unit.",
    category: "weight",
    sector: "medicine",
    modern_equivalent: "≈46.6 g",
    conversion_formula: "4 Karsha = 1 Pala",
    states: ["Madhya Pradesh"],
    used_in: ["Oils, decoctions"],
    references: ["Ashtanga Hridaya"],
  },

  // Construction & Architecture
  {
    id: "mp-arch-1",
    slug: "mp-vitasti-arch",
    name_english: "Vitasti",
    name_hindi: "वितस्ति",
    name_sanskrit: "Vitasti",
    local_names: ["वितस्ति (Vitasti)"],
    meaning: "Span measurement.",
    category: "length",
    sector: "architecture",
    modern_equivalent: "≈22.8 cm",
    conversion_formula: "12 Angula = 1 Vitasti",
    states: ["Madhya Pradesh"],
    used_in: ["Pillars, walls"],
    references: ["Samarangana Sutradhara"],
  },
  {
    id: "mp-arch-2",
    slug: "mp-hasta-arch",
    name_english: "Hasta",
    name_hindi: "हस्त",
    name_sanskrit: "Hasta",
    local_names: ["हस्त (Hasta)"],
    meaning: "Cubit.",
    category: "length",
    sector: "architecture",
    modern_equivalent: "≈45.6 cm",
    conversion_formula: "2 Vitasti = 1 Hasta (24 Angula)",
    states: ["Madhya Pradesh"],
    used_in: ["Building dimensions"],
    references: ["Mayamata"],
  },

  // Transportation & Distance
  {
    id: "mp-trans-1",
    slug: "mp-danda-trans",
    name_english: "Danda",
    name_hindi: "दण्ड",
    name_sanskrit: "Daṇḍa",
    local_names: ["दण्ड (Danda)"],
    meaning: "Measuring rod used for roads and layouts.",
    category: "length",
    sector: "transportation-distance",
    modern_equivalent: "≈1.82 m",
    conversion_formula: "4 Hasta = 1 Danda",
    states: ["Madhya Pradesh"],
    used_in: ["Roads, bridges, layouts"],
    references: ["Arthashastra"],
  },
  {
    id: "mp-trans-2",
    slug: "mp-krosha-trans",
    name_english: "Krosha (Kos)",
    name_hindi: "क्रोश / कोस",
    name_sanskrit: "Krośa",
    local_names: ["कोस (Kos)"],
    meaning: "Traditional road distance.",
    category: "length",
    sector: "transportation-distance",
    modern_equivalent: "≈3.2 km",
    conversion_formula: "1 Kos = 2000 Danda",
    states: ["Madhya Pradesh"],
    used_in: ["Road travel, milestones"],
    references: ["Arthashastra; Imperial Gazetteer"],
  },
  {
    id: "mp-trans-3",
    slug: "mp-yojana-trans",
    name_english: "Yojana",
    name_hindi: "योजन",
    name_sanskrit: "Yojana",
    local_names: ["योजन (Yojana)"],
    meaning: "Largest traditional distance unit.",
    category: "length",
    sector: "transportation-distance",
    modern_equivalent: "≈12.8 km",
    conversion_formula: "4 Kos = 1 Yojana",
    states: ["Madhya Pradesh"],
    used_in: ["Long-distance travel"],
    references: ["Surya Siddhanta; Arthashastra"],
  },

  // Livestock & Dairy
  {
    id: "mp-dairy-1",
    slug: "mp-pav-dairy",
    name_english: "Pav (Pao)",
    name_hindi: "पाव",
    local_names: ["पाव (Pav)"],
    meaning: "Quarter Seer.",
    category: "volume",
    sector: "livestock-dairy",
    modern_equivalent: "≈233 g / ≈250 ml",
    conversion_formula: "4 Chhatak = 1 Pav",
    states: ["Madhya Pradesh"],
    used_in: ["Milk and curd"],
    references: ["Mughal-1958"],
  },
  {
    id: "mp-dairy-2",
    slug: "mp-seer-dairy",
    name_english: "Seer",
    name_hindi: "सेर",
    local_names: ["सेर (Seer)"],
    meaning: "Standard dairy measure.",
    category: "volume",
    sector: "livestock-dairy",
    modern_equivalent: "≈0.933 kg / ≈0.93 L",
    conversion_formula: "2 Half Seer = 1 Seer",
    states: ["Madhya Pradesh"],
    used_in: ["Milk, ghee, fodder"],
    references: ["Imperial Gazetteer"],
  },

  // Household & Daily Life
  {
    id: "mp-hh-1",
    slug: "mp-chhatak-hh",
    name_english: "Chhatak",
    name_hindi: "छटाक",
    local_names: ["छटाक (Chhatak)"],
    meaning: "Small domestic measure.",
    category: "weight",
    sector: "household",
    modern_equivalent: "≈58.3 g",
    conversion_formula: "5 Tola = 1 Chhatak",
    states: ["Madhya Pradesh"],
    used_in: ["Sugar, flour, lentils"],
    references: ["Central Provinces Gazetteers"],
  },
  {
    id: "mp-hh-2",
    slug: "mp-maund-hh",
    name_english: "Maund (Man)",
    name_hindi: "मन",
    local_names: ["मन (Man)"],
    meaning: "Bulk storage unit.",
    category: "weight",
    sector: "household",
    modern_equivalent: "≈37.324 kg",
    conversion_formula: "40 Seers = 1 Maund",
    states: ["Madhya Pradesh"],
    used_in: ["Household grain storage"],
    references: ["Mughal-1958"],
  },

  // Gold & Jewellery
  {
    id: "mp-gold-1",
    slug: "mp-suvarna-gold",
    name_english: "Suvarna",
    name_hindi: "सुवर्ण",
    name_sanskrit: "Suvarṇa",
    local_names: ["सुवर्ण (Suvarna)"],
    meaning: "Classical gold unit.",
    category: "weight",
    sector: "gold-jewellery",
    modern_equivalent: "≈15.55 g",
    conversion_formula: "16 Masha = 1 Suvarna",
    states: ["Madhya Pradesh"],
    used_in: ["Gold coins and ornaments"],
    references: ["Arthashastra"],
  },
  {
    id: "mp-gold-2",
    slug: "mp-tola-gold",
    name_english: "Tola",
    name_hindi: "तोला",
    name_sanskrit: "Tulā",
    local_names: ["तोला (Tola)"],
    meaning: "Standard jewellers' unit.",
    category: "weight",
    sector: "gold-jewellery",
    modern_equivalent: "≈11.66 g",
    conversion_formula: "12 Masha = 1 Tola",
    states: ["Madhya Pradesh"],
    used_in: ["Gold and silver trade"],
    references: ["British India Standards"],
  },

  // Currency & Money
  {
    id: "mp-cur-1",
    slug: "mp-cowrie-cur",
    name_english: "Cowrie",
    name_hindi: "कौड़ी",
    name_sanskrit: "Kapardikā",
    local_names: ["कौड़ी (Cowrie)"],
    meaning: "Smallest medium of exchange.",
    category: "currency",
    sector: "currency-money",
    modern_equivalent: "No fixed SI equivalent",
    conversion_formula: "Base unit",
    states: ["Madhya Pradesh"],
    used_in: ["Petty transactions"],
    references: ["Arthashastra; Numismatic Studies"],
  },
  {
    id: "mp-cur-2",
    slug: "mp-rupee-cur",
    name_english: "Rupee",
    name_hindi: "रुपया",
    name_sanskrit: "Rūpya",
    local_names: ["रुपया (Rupee)"],
    meaning: "Standard monetary unit.",
    category: "currency",
    sector: "currency-money",
    modern_equivalent: "Historical silver coin",
    conversion_formula: "16 Anna = 1 Rupee",
    states: ["Madhya Pradesh"],
    used_in: ["Trade, taxation, salaries"],
    references: ["Arthashastra; Imperial Gazetteer"],
  },
  {
    id: "mp-cur-3",
    slug: "mp-mohur-cur",
    name_english: "Mohur",
    name_hindi: "मोहर",
    name_sanskrit: "Suvarṇa Mudrā",
    local_names: ["मोहर (Mohur)"],
    meaning: "Gold currency.",
    category: "currency",
    sector: "currency-money",
    modern_equivalent: "Gold coin",
    conversion_formula: "Value varied with gold content",
    states: ["Madhya Pradesh"],
    used_in: ["High-value trade"],
    references: ["Numismatic Society of India"],
  },

  // Storage & Transportation
  {
    id: "mp-storage-1",
    slug: "mp-chhatak-storage",
    name_english: "Chhatak",
    name_hindi: "छटाक",
    local_names: ["छटाक (Chhatak)"],
    meaning: "Small storage unit.",
    category: "weight",
    sector: "storage-transport",
    modern_equivalent: "≈58.3 g",
    conversion_formula: "5 Tola = 1 Chhatak",
    states: ["Madhya Pradesh"],
    used_in: ["Small quantities of grain, spices"],
    references: ["Central Provinces Gazetteers"],
  },
  {
    id: "mp-storage-2",
    slug: "mp-khandi-storage",
    name_english: "Khandi",
    name_hindi: "खंडी",
    name_sanskrit: "Khaṇḍī",
    local_names: ["खंडी (Khandi)"],
    meaning: "Largest traditional storage unit.",
    category: "volume",
    sector: "storage-transport",
    modern_equivalent: "≈746 kg",
    conversion_formula: "≈20 Maunds = 1 Khandi (Regional)",
    states: ["Madhya Pradesh"],
    used_in: ["Warehouse storage and long-distance transport"],
    references: ["Madhya Pradesh District Gazetteers"],
  },

  // Land Measurement
  {
    id: "mp-land-1",
    slug: "mp-square-gaj",
    name_english: "Square Gaj",
    name_hindi: "वर्ग गज़",
    name_sanskrit: "Gaja",
    local_names: ["Square Gaj"],
    meaning: "Smallest commonly used area unit.",
    category: "area",
    sector: "land-measurement",
    modern_equivalent: "≈0.8361 m²",
    conversion_formula: "Base Unit",
    states: ["Madhya Pradesh"],
    used_in: ["House plots and small land parcels"],
    references: ["Imperial Gazetteer of India"],
  },
  {
    id: "mp-land-2",
    slug: "mp-bigha",
    name_english: "Bigha",
    name_hindi: "बीघा",
    local_names: ["बीघा (Bigha)"],
    meaning: "Principal traditional land unit.",
    category: "area",
    sector: "land-measurement",
    modern_equivalent: "≈0.25–0.67 hectare",
    conversion_formula: "20 Biswa = 1 Bigha",
    states: ["Madhya Pradesh"],
    used_in: ["Agricultural fields"],
    references: ["Imperial Gazetteer; MP Gazetteers"],
  },
  {
    id: "mp-land-3",
    slug: "mp-acre-land",
    name_english: "Acre",
    name_hindi: "एकड़",
    local_names: ["एकड़ (Acre)"],
    meaning: "British standard land unit.",
    category: "area",
    sector: "land-measurement",
    modern_equivalent: "4046.86 m²",
    conversion_formula: "1 Acre = 4840 sq yd",
    states: ["Madhya Pradesh"],
    used_in: ["Revenue and settlement records"],
    references: ["British Revenue Records"],
  },

  // ─── Seed & Crop (Agriculture) — Extended entries from Excel ─────────────────
  {
    id: "mp-agri-4",
    slug: "mp-chhatak-agri",
    name_english: "Chhatak",
    name_hindi: "छटाक",
    local_names: ["छटाक (Chhatak)"],
    meaning: "Small grain measure.",
    category: "weight",
    sector: "agriculture",
    modern_equivalent: "≈58.3 g",
    conversion_formula: "5 Tola = 1 Chhatak",
    states: ["Madhya Pradesh"],
    used_in: ["Grain, pulses and seed measurement"],
    references: ["Central Provinces Gazetteers"],
  },
  {
    id: "mp-agri-5",
    slug: "mp-pav-agri",
    name_english: "Pav (Pao)",
    name_hindi: "पाव",
    local_names: ["पाव (Pav)"],
    meaning: "Quarter Seer.",
    category: "weight",
    sector: "agriculture",
    modern_equivalent: "≈233 g",
    conversion_formula: "4 Chhatak = 1 Pav",
    states: ["Madhya Pradesh"],
    used_in: ["Grain and pulses"],
    references: ["MP District Gazetteers"],
  },
  {
    id: "mp-agri-6",
    slug: "mp-adha-seer-agri",
    name_english: "Adha Seer",
    name_hindi: "आधा सेर",
    local_names: ["आधा सेर (Adha Seer)"],
    meaning: "Half Seer.",
    category: "weight",
    sector: "agriculture",
    modern_equivalent: "≈466 g",
    conversion_formula: "2 Pav = 1 Half Seer",
    states: ["Madhya Pradesh"],
    used_in: ["Seeds and cereals"],
    references: ["Revenue Settlement Manuals"],
  },
  {
    id: "mp-agri-7",
    slug: "mp-seer-agri",
    name_english: "Seer",
    name_hindi: "सेर",
    local_names: ["सेर (Seer)"],
    meaning: "Standard agricultural market unit.",
    category: "weight",
    sector: "agriculture",
    modern_equivalent: "≈0.933 kg",
    conversion_formula: "2 Half Seer = 1 Seer (16 Chhatak)",
    states: ["Madhya Pradesh"],
    used_in: ["Wheat, rice, pulses, oilseeds"],
    references: ["Imperial Gazetteer of India"],
  },
  {
    id: "mp-agri-8",
    slug: "mp-pasri-agri",
    name_english: "Pasri",
    name_hindi: "पसरी",
    local_names: ["पसरी (Pasri)"],
    meaning: "Intermediate grain measure.",
    category: "weight",
    sector: "agriculture",
    modern_equivalent: "≈4.66 kg (where 5 Seers were used)",
    conversion_formula: "Usually 5 Seers = 1 Pasri (Regional Variation)",
    states: ["Madhya Pradesh"],
    used_in: ["Grain storage and seed distribution"],
    references: ["District Gazetteers"],
  },
  {
    id: "mp-agri-9",
    slug: "mp-maund-agri",
    name_english: "Maund (Man)",
    name_hindi: "मन",
    name_sanskrit: "Māna",
    local_names: ["मन (Man)"],
    meaning: "Principal wholesale agricultural unit.",
    category: "weight",
    sector: "agriculture",
    modern_equivalent: "≈37.324 kg",
    conversion_formula: "40 Seers = 1 Maund",
    states: ["Madhya Pradesh"],
    used_in: ["Harvest measurement and wholesale grain trade"],
    references: ["Government of India Historical Weights"],
  },
  {
    id: "mp-agri-10",
    slug: "mp-khandi-agri",
    name_english: "Khandi",
    name_hindi: "खंडी",
    name_sanskrit: "Khaṇḍī",
    local_names: ["खंडी (Khandi)"],
    meaning: "Bulk agricultural storage unit.",
    category: "volume",
    sector: "agriculture",
    modern_equivalent: "≈746 kg (where applicable)",
    conversion_formula: "≈20 Maunds (Regional)",
    states: ["Madhya Pradesh"],
    used_in: ["Large-scale grain storage"],
    references: ["Madhya Pradesh Gazetteers"],
  },

  // ─── Trade & Commerce — Extended entries from Excel ──────────────────────────
  {
    id: "mp-trade-3",
    slug: "mp-ratti-trade",
    name_english: "Ratti",
    name_hindi: "रत्ती",
    name_sanskrit: "Raktikā",
    local_names: ["रत्ती (Ratti)"],
    meaning: "Smallest commercial weight.",
    category: "weight",
    sector: "trade-commerce",
    modern_equivalent: "≈121.5 mg",
    conversion_formula: "Base Unit",
    states: ["Madhya Pradesh"],
    used_in: ["Gems, spices, medicines"],
    references: ["Arthashastra; Charaka Samhita"],
  },
  {
    id: "mp-trade-4",
    slug: "mp-masha-trade",
    name_english: "Masha",
    name_hindi: "माशा",
    name_sanskrit: "Māṣa",
    local_names: ["माशा (Masha)"],
    meaning: "Small market weight.",
    category: "weight",
    sector: "trade-commerce",
    modern_equivalent: "≈0.972 g",
    conversion_formula: "8 Ratti = 1 Masha",
    states: ["Madhya Pradesh"],
    used_in: ["Herbs, perfumes, spices"],
    references: ["Arthashastra"],
  },
  {
    id: "mp-trade-5",
    slug: "mp-tola-trade",
    name_english: "Tola",
    name_hindi: "तोला",
    name_sanskrit: "Tulā",
    local_names: ["तोला (Tola)"],
    meaning: "Standard commercial weight.",
    category: "weight",
    sector: "trade-commerce",
    modern_equivalent: "≈11.66 g",
    conversion_formula: "12 Masha = 1 Tola",
    states: ["Madhya Pradesh"],
    used_in: ["Gold, silver, spices"],
    references: ["British India Standards"],
  },
  {
    id: "mp-trade-6",
    slug: "mp-adha-seer-trade",
    name_english: "Adha Seer",
    name_hindi: "आधा सेर",
    local_names: ["आधा सेर (Adha Seer)"],
    meaning: "Half Seer.",
    category: "weight",
    sector: "trade-commerce",
    modern_equivalent: "≈466 g",
    conversion_formula: "2 Pav = 1 Half Seer",
    states: ["Madhya Pradesh"],
    used_in: ["Grain, jaggery, oil"],
    references: ["Revenue Settlement Manuals"],
  },
  {
    id: "mp-trade-7",
    slug: "mp-seer-trade",
    name_english: "Seer",
    name_hindi: "सेर",
    local_names: ["सेर (Seer)"],
    meaning: "Standard market unit.",
    category: "weight",
    sector: "trade-commerce",
    modern_equivalent: "≈0.933 kg",
    conversion_formula: "2 Half Seer = 1 Seer",
    states: ["Madhya Pradesh"],
    used_in: ["Grain, cotton, oil, jaggery"],
    references: ["Imperial Gazetteer of India"],
  },
  {
    id: "mp-trade-8",
    slug: "mp-pasri-trade",
    name_english: "Pasri",
    name_hindi: "पसरी",
    local_names: ["पसरी (Pasri)"],
    meaning: "Regional grain measure.",
    category: "weight",
    sector: "trade-commerce",
    modern_equivalent: "≈4.66 kg (where applicable)",
    conversion_formula: "Usually 5 Seers = 1 Pasri (Regional)",
    states: ["Madhya Pradesh"],
    used_in: ["Grain and cotton trade"],
    references: ["District Gazetteers"],
  },
  {
    id: "mp-trade-9",
    slug: "mp-maund-trade",
    name_english: "Maund (Man)",
    name_hindi: "मन",
    name_sanskrit: "Māna",
    local_names: ["मन (Man)"],
    meaning: "Principal wholesale unit.",
    category: "weight",
    sector: "trade-commerce",
    modern_equivalent: "≈37.324 kg",
    conversion_formula: "40 Seers = 1 Maund",
    states: ["Madhya Pradesh"],
    used_in: ["Wholesale grain, cotton and salt"],
    references: ["Government of India Historical Standards"],
  },
  {
    id: "mp-trade-10",
    slug: "mp-khandi-trade",
    name_english: "Khandi",
    name_hindi: "खंडी",
    name_sanskrit: "Khaṇḍī",
    local_names: ["खंडी (Khandi)"],
    meaning: "Warehouse and transport unit.",
    category: "volume",
    sector: "trade-commerce",
    modern_equivalent: "≈746 kg (where applicable)",
    conversion_formula: "≈20 Maunds (Regional)",
    states: ["Madhya Pradesh"],
    used_in: ["Bulk grain and cotton trade"],
    references: ["Madhya Pradesh Gazetteers"],
  },

  // ─── Textile & Handloom — Extended entries from Excel ────────────────────────
  {
    id: "mp-tex-3",
    slug: "mp-vitasti-tex",
    name_english: "Vitasti",
    name_hindi: "वितस्ति",
    name_sanskrit: "Vitasti",
    local_names: ["वितस्ति (Vitasti)"],
    meaning: "Span measurement.",
    category: "length",
    sector: "textile-handloom",
    modern_equivalent: "≈22.8 cm",
    conversion_formula: "12 Angul = 1 Vitasti",
    states: ["Madhya Pradesh"],
    used_in: ["Cloth width, weaving"],
    references: ["Mānasāra"],
  },
  {
    id: "mp-tex-4",
    slug: "mp-hasta-tex",
    name_english: "Hasta",
    name_hindi: "हस्त",
    name_sanskrit: "Hasta",
    local_names: ["हस्त (Hasta)"],
    meaning: "Cubit measurement.",
    category: "length",
    sector: "textile-handloom",
    modern_equivalent: "≈45.6 cm",
    conversion_formula: "2 Vitasti = 1 Hasta",
    states: ["Madhya Pradesh"],
    used_in: ["Cloth measurement, weaving"],
    references: ["Mayamata"],
  },
  {
    id: "mp-tex-5",
    slug: "mp-danda-tex",
    name_english: "Danda",
    name_hindi: "दण्ड",
    name_sanskrit: "Daṇḍa",
    local_names: ["दण्ड (Danda)"],
    meaning: "Long measuring rod.",
    category: "length",
    sector: "textile-handloom",
    modern_equivalent: "≈1.82 m",
    conversion_formula: "4 Hasta = 1 Danda",
    states: ["Madhya Pradesh"],
    used_in: ["Loom setting, workshop layout"],
    references: ["Arthashastra"],
  },
  {
    id: "mp-tex-6",
    slug: "mp-rajju-tex",
    name_english: "Rajju",
    name_hindi: "रज्जु",
    name_sanskrit: "Rajju",
    local_names: ["रज्जु (Rajju)"],
    meaning: "Rope measuring unit.",
    category: "length",
    sector: "textile-handloom",
    modern_equivalent: "Regionally Variable",
    conversion_formula: "Rope measure (variable)",
    states: ["Madhya Pradesh"],
    used_in: ["Measuring long cloth rolls"],
    references: ["Traditional Survey Records"],
  },

  // ─── Medicine (Ayurveda) — Extended entries from Excel ───────────────────────
  {
    id: "mp-med-3",
    slug: "mp-ratti-med",
    name_english: "Ratti",
    name_hindi: "रत्ती",
    name_sanskrit: "Raktikā",
    local_names: ["रत्ती (Ratti)"],
    meaning: "Smallest medicinal weight.",
    category: "weight",
    sector: "medicine",
    modern_equivalent: "≈121.5 mg",
    conversion_formula: "Base Unit",
    states: ["Madhya Pradesh"],
    used_in: ["Herbs, mineral medicines"],
    references: ["Charaka Samhita"],
  },
  {
    id: "mp-med-4",
    slug: "mp-masha-med",
    name_english: "Masha",
    name_hindi: "माशा",
    name_sanskrit: "Māṣa",
    local_names: ["माशा (Masha)"],
    meaning: "Standard medicinal weight.",
    category: "weight",
    sector: "medicine",
    modern_equivalent: "≈0.972 g",
    conversion_formula: "8 Ratti = 1 Masha",
    states: ["Madhya Pradesh"],
    used_in: ["Herbal powders"],
    references: ["Sushruta Samhita"],
  },
  {
    id: "mp-med-5",
    slug: "mp-prasruta-med",
    name_english: "Prasruta",
    name_hindi: "प्रसृत",
    name_sanskrit: "Prasṛta",
    local_names: ["प्रसृत (Prasruta)"],
    meaning: "Liquid dosage unit.",
    category: "volume",
    sector: "medicine",
    modern_equivalent: "≈93 ml",
    conversion_formula: "2 Pala = 1 Prasruta",
    states: ["Madhya Pradesh"],
    used_in: ["Medicated liquids"],
    references: ["Charaka Samhita"],
  },
  {
    id: "mp-med-6",
    slug: "mp-kudava-med",
    name_english: "Kudava",
    name_hindi: "कुडव",
    name_sanskrit: "Kuḍava",
    local_names: ["कुडव (Kudava)"],
    meaning: "Medium liquid measure.",
    category: "volume",
    sector: "medicine",
    modern_equivalent: "≈187 ml",
    conversion_formula: "2 Prasruta = 1 Kudava",
    states: ["Madhya Pradesh"],
    used_in: ["Oils, decoctions"],
    references: ["Sushruta Samhita"],
  },
  {
    id: "mp-med-7",
    slug: "mp-prastha-med",
    name_english: "Prastha",
    name_hindi: "प्रस्थ",
    name_sanskrit: "Prastha",
    local_names: ["प्रस्थ (Prastha)"],
    meaning: "Large liquid measure.",
    category: "volume",
    sector: "medicine",
    modern_equivalent: "≈768 ml",
    conversion_formula: "4 Kudava = 1 Prastha",
    states: ["Madhya Pradesh"],
    used_in: ["Preparation of medicines"],
    references: ["Charaka Samhita"],
  },
  {
    id: "mp-med-8",
    slug: "mp-adhaka-med",
    name_english: "Adhaka",
    name_hindi: "आढ़क",
    name_sanskrit: "Āḍhaka",
    local_names: ["आढ़क (Adhaka)"],
    meaning: "Bulk medicinal preparation measure.",
    category: "volume",
    sector: "medicine",
    modern_equivalent: "≈3.07 L",
    conversion_formula: "4 Prastha = 1 Adhaka",
    states: ["Madhya Pradesh"],
    used_in: ["Pharmacy preparation"],
    references: ["Ayurvedic Texts"],
  },
  {
    id: "mp-med-9",
    slug: "mp-drona-med",
    name_english: "Drona",
    name_hindi: "द्रोण",
    name_sanskrit: "Droṇa",
    local_names: ["द्रोण (Drona)"],
    meaning: "Large storage measure for bulk herbal preparation.",
    category: "volume",
    sector: "medicine",
    modern_equivalent: "≈12.3 L",
    conversion_formula: "4 Adhaka = 1 Drona",
    states: ["Madhya Pradesh"],
    used_in: ["Bulk herbal preparation"],
    references: ["Charaka Samhita"],
  },

  // ─── Construction & Architecture — Extended entries from Excel ───────────────
  {
    id: "mp-arch-3",
    slug: "mp-yava-arch",
    name_english: "Yava",
    name_hindi: "यव",
    name_sanskrit: "Yava",
    local_names: ["यव (Yava)"],
    meaning: "Smallest architectural unit.",
    category: "length",
    sector: "architecture",
    modern_equivalent: "≈2.4 mm",
    conversion_formula: "Base Unit",
    states: ["Madhya Pradesh"],
    used_in: ["Fine carving, ornaments"],
    references: ["Mānasāra"],
  },
  {
    id: "mp-arch-4",
    slug: "mp-angul-arch",
    name_english: "Angul",
    name_hindi: "अंगुल",
    name_sanskrit: "Aṅgula",
    local_names: ["अंगुल (Angul)"],
    meaning: "Finger-width measure.",
    category: "length",
    sector: "architecture",
    modern_equivalent: "≈1.9 cm",
    conversion_formula: "8 Yava = 1 Angula",
    states: ["Madhya Pradesh"],
    used_in: ["Masonry, stone cutting"],
    references: ["Mānasāra; Mayamata"],
  },
  {
    id: "mp-arch-5",
    slug: "mp-danda-arch",
    name_english: "Danda",
    name_hindi: "दण्ड",
    name_sanskrit: "Daṇḍa",
    local_names: ["दण्ड (Danda)"],
    meaning: "Measuring rod used in construction.",
    category: "length",
    sector: "architecture",
    modern_equivalent: "≈1.82 m",
    conversion_formula: "4 Hasta = 1 Danda",
    states: ["Madhya Pradesh"],
    used_in: ["House and road layout"],
    references: ["Arthashastra"],
  },
  {
    id: "mp-arch-6",
    slug: "mp-rajju-arch",
    name_english: "Rajju",
    name_hindi: "रज्जु",
    name_sanskrit: "Rajju",
    local_names: ["रज्जु (Rajju)"],
    meaning: "Survey rope.",
    category: "length",
    sector: "architecture",
    modern_equivalent: "Regionally Variable",
    conversion_formula: "Rope measure (variable)",
    states: ["Madhya Pradesh"],
    used_in: ["Land and building layout"],
    references: ["Traditional Survey Manuals"],
  },
  {
    id: "mp-arch-7",
    slug: "mp-gaj-arch",
    name_english: "Gaj (Gaz)",
    name_hindi: "गज़",
    local_names: ["गज़ (Gaj)"],
    meaning: "Standard building measure.",
    category: "length",
    sector: "architecture",
    modern_equivalent: "≈0.9144 m",
    conversion_formula: "Regional standard",
    states: ["Madhya Pradesh"],
    used_in: ["Construction and carpentry"],
    references: ["Imperial Gazetteer"],
  },

  // ─── Transportation & Distance — Extended entries from Excel ─────────────────
  {
    id: "mp-trans-4",
    slug: "mp-angul-trans",
    name_english: "Angul",
    name_hindi: "अंगुल",
    name_sanskrit: "Aṅgula",
    local_names: ["अंगुल (Angul)"],
    meaning: "Finger-width unit used in engineering.",
    category: "length",
    sector: "transportation-distance",
    modern_equivalent: "≈1.9 cm",
    conversion_formula: "Base Unit",
    states: ["Madhya Pradesh"],
    used_in: ["Small engineering measurements"],
    references: ["Arthashastra"],
  },
  {
    id: "mp-trans-5",
    slug: "mp-vitasti-trans",
    name_english: "Vitasti",
    name_hindi: "वितस्ति",
    name_sanskrit: "Vitasti",
    local_names: ["वितस्ति (Vitasti)"],
    meaning: "Span measure.",
    category: "length",
    sector: "transportation-distance",
    modern_equivalent: "≈22.8 cm",
    conversion_formula: "12 Angula = 1 Vitasti",
    states: ["Madhya Pradesh"],
    used_in: ["Measuring carts, wooden parts"],
    references: ["Manusmriti"],
  },
  {
    id: "mp-trans-6",
    slug: "mp-hasta-trans",
    name_english: "Hasta",
    name_hindi: "हस्त",
    name_sanskrit: "Hasta",
    local_names: ["हस्त (Hasta)"],
    meaning: "Cubit used in vehicle construction.",
    category: "length",
    sector: "transportation-distance",
    modern_equivalent: "≈45.6 cm",
    conversion_formula: "2 Vitasti = 1 Hasta (24 Angula)",
    states: ["Madhya Pradesh"],
    used_in: ["Vehicle construction"],
    references: ["Mayamata"],
  },
  {
    id: "mp-trans-7",
    slug: "mp-gaj-trans",
    name_english: "Gaj (Gaz)",
    name_hindi: "गज़",
    local_names: ["गज़ (Gaj)"],
    meaning: "Standard linear measure for roads and transport.",
    category: "length",
    sector: "transportation-distance",
    modern_equivalent: "≈0.9144 m",
    conversion_formula: "Regional standard",
    states: ["Madhya Pradesh"],
    used_in: ["Measuring roads, timber, carts"],
    references: ["Imperial Gazetteer"],
  },
  {
    id: "mp-trans-8",
    slug: "mp-rajju-trans",
    name_english: "Rajju",
    name_hindi: "रज्जु",
    name_sanskrit: "Rajju",
    local_names: ["रज्जु (Rajju)"],
    meaning: "Survey rope for road and land surveying.",
    category: "length",
    sector: "transportation-distance",
    modern_equivalent: "Regionally Variable",
    conversion_formula: "Rope measure (variable)",
    states: ["Madhya Pradesh"],
    used_in: ["Road and land surveying"],
    references: ["Survey Manuals"],
  },

  // ─── Livestock & Dairy — Extended entries from Excel ─────────────────────────
  {
    id: "mp-dairy-3",
    slug: "mp-ratti-dairy",
    name_english: "Ratti",
    name_hindi: "रत्ती",
    name_sanskrit: "Raktikā",
    local_names: ["रत्ती (Ratti)"],
    meaning: "Smallest weight unit for veterinary use.",
    category: "weight",
    sector: "livestock-dairy",
    modern_equivalent: "≈121.5 mg",
    conversion_formula: "Base Unit",
    states: ["Madhya Pradesh"],
    used_in: ["Veterinary medicines"],
    references: ["Charaka Samhita"],
  },
  {
    id: "mp-dairy-4",
    slug: "mp-masha-dairy",
    name_english: "Masha",
    name_hindi: "माशा",
    name_sanskrit: "Māṣa",
    local_names: ["माशा (Masha)"],
    meaning: "Small medicinal weight for animal care.",
    category: "weight",
    sector: "livestock-dairy",
    modern_equivalent: "≈0.972 g",
    conversion_formula: "8 Ratti = 1 Masha",
    states: ["Madhya Pradesh"],
    used_in: ["Animal medicines"],
    references: ["Sushruta Samhita"],
  },
  {
    id: "mp-dairy-5",
    slug: "mp-tola-dairy",
    name_english: "Tola",
    name_hindi: "तोला",
    name_sanskrit: "Tulā",
    local_names: ["तोला (Tola)"],
    meaning: "Standard weight for dairy products.",
    category: "weight",
    sector: "livestock-dairy",
    modern_equivalent: "≈11.66 g",
    conversion_formula: "12 Masha = 1 Tola",
    states: ["Madhya Pradesh"],
    used_in: ["Butter, medicinal preparations"],
    references: ["British India Standards"],
  },
  {
    id: "mp-dairy-6",
    slug: "mp-chhatak-dairy",
    name_english: "Chhatak",
    name_hindi: "छटाक",
    local_names: ["छटाक (Chhatak)"],
    meaning: "Small dairy measure.",
    category: "weight",
    sector: "livestock-dairy",
    modern_equivalent: "≈58.3 g",
    conversion_formula: "5 Tola = 1 Chhatak",
    states: ["Madhya Pradesh"],
    used_in: ["Butter, ghee"],
    references: ["Central Provinces Gazetteers"],
  },
  {
    id: "mp-dairy-7",
    slug: "mp-adha-seer-dairy",
    name_english: "Adha Seer",
    name_hindi: "आधा सेर",
    local_names: ["आधा सेर (Adha Seer)"],
    meaning: "Half Seer liquid measure.",
    category: "volume",
    sector: "livestock-dairy",
    modern_equivalent: "≈466 g / ≈500 ml (approx.)",
    conversion_formula: "2 Pav = 1 Half Seer",
    states: ["Madhya Pradesh"],
    used_in: ["Milk, curd"],
    references: ["Revenue Manuals"],
  },
  {
    id: "mp-dairy-8",
    slug: "mp-maund-dairy",
    name_english: "Maund (Man)",
    name_hindi: "मन",
    name_sanskrit: "Māna",
    local_names: ["मन (Man)"],
    meaning: "Bulk agricultural unit for fodder.",
    category: "weight",
    sector: "livestock-dairy",
    modern_equivalent: "≈37.324 kg",
    conversion_formula: "40 Seers = 1 Maund",
    states: ["Madhya Pradesh"],
    used_in: ["Fodder, cattle feed"],
    references: ["Government Historical Standards"],
  },

  // ─── Household & Daily Life — Extended entries from Excel ────────────────────
  {
    id: "mp-hh-3",
    slug: "mp-ratti-hh",
    name_english: "Ratti",
    name_hindi: "रत्ती",
    name_sanskrit: "Raktikā",
    local_names: ["रत्ती (Ratti)"],
    meaning: "Smallest household weight.",
    category: "weight",
    sector: "household",
    modern_equivalent: "≈121.5 mg",
    conversion_formula: "Base Unit",
    states: ["Madhya Pradesh"],
    used_in: ["Spices, medicines"],
    references: ["Charaka Samhita"],
  },
  {
    id: "mp-hh-4",
    slug: "mp-masha-hh",
    name_english: "Masha",
    name_hindi: "माशा",
    name_sanskrit: "Māṣa",
    local_names: ["माशा (Masha)"],
    meaning: "Small kitchen weight.",
    category: "weight",
    sector: "household",
    modern_equivalent: "≈0.972 g",
    conversion_formula: "8 Ratti = 1 Masha",
    states: ["Madhya Pradesh"],
    used_in: ["Spices, herbal ingredients"],
    references: ["Sushruta Samhita"],
  },
  {
    id: "mp-hh-5",
    slug: "mp-tola-hh",
    name_english: "Tola",
    name_hindi: "तोला",
    name_sanskrit: "Tulā",
    local_names: ["तोला (Tola)"],
    meaning: "Standard household weight.",
    category: "weight",
    sector: "household",
    modern_equivalent: "≈11.66 g",
    conversion_formula: "12 Masha = 1 Tola",
    states: ["Madhya Pradesh"],
    used_in: ["Ghee, spices, precious ingredients"],
    references: ["British India Standards"],
  },
  {
    id: "mp-hh-6",
    slug: "mp-pav-hh",
    name_english: "Pav (Pao)",
    name_hindi: "पाव",
    local_names: ["पाव (Pav)"],
    meaning: "Quarter Seer household measure.",
    category: "weight",
    sector: "household",
    modern_equivalent: "≈233 g",
    conversion_formula: "4 Chhatak = 1 Pav",
    states: ["Madhya Pradesh"],
    used_in: ["Rice, wheat flour, oil"],
    references: ["MP District Gazetteers"],
  },
  {
    id: "mp-hh-7",
    slug: "mp-adha-seer-hh",
    name_english: "Adha Seer",
    name_hindi: "आधा सेर",
    local_names: ["आधा सेर (Adha Seer)"],
    meaning: "Half Seer.",
    category: "weight",
    sector: "household",
    modern_equivalent: "≈466 g",
    conversion_formula: "2 Pav = 1 Half Seer",
    states: ["Madhya Pradesh"],
    used_in: ["Cereals and pulses"],
    references: ["Revenue Settlement Manuals"],
  },
  {
    id: "mp-hh-8",
    slug: "mp-seer-hh",
    name_english: "Seer",
    name_hindi: "सेर",
    local_names: ["सेर (Seer)"],
    meaning: "Standard domestic measure.",
    category: "weight",
    sector: "household",
    modern_equivalent: "≈0.933 kg / ≈0.93 L",
    conversion_formula: "2 Half Seer = 1 Seer",
    states: ["Madhya Pradesh"],
    used_in: ["Rice, wheat, pulses, edible oil"],
    references: ["Imperial Gazetteer of India"],
  },

  // ─── Gold & Jewellery — Extended entries from Excel ──────────────────────────
  {
    id: "mp-gold-3",
    slug: "mp-ratti-gold",
    name_english: "Ratti",
    name_hindi: "रत्ती",
    name_sanskrit: "Raktikā",
    local_names: ["रत्ती (Ratti)"],
    meaning: "Smallest jewellery weight.",
    category: "weight",
    sector: "gold-jewellery",
    modern_equivalent: "≈121.5 mg",
    conversion_formula: "Base Unit",
    states: ["Madhya Pradesh"],
    used_in: ["Diamonds, pearls, gemstones"],
    references: ["Arthashastra; Ratnaśāstra"],
  },
  {
    id: "mp-gold-4",
    slug: "mp-masha-gold",
    name_english: "Masha",
    name_hindi: "माशा",
    name_sanskrit: "Māṣa",
    local_names: ["माशा (Masha)"],
    meaning: "Small jewellery weight.",
    category: "weight",
    sector: "gold-jewellery",
    modern_equivalent: "≈0.972 g",
    conversion_formula: "8 Ratti = 1 Masha",
    states: ["Madhya Pradesh"],
    used_in: ["Gold and silver ornaments"],
    references: ["Sushruta Samhita"],
  },
  {
    id: "mp-gold-5",
    slug: "mp-chhatak-gold",
    name_english: "Chhatak",
    name_hindi: "छटाक",
    local_names: ["छटाक (Chhatak)"],
    meaning: "Medium bullion weight.",
    category: "weight",
    sector: "gold-jewellery",
    modern_equivalent: "≈58.3 g",
    conversion_formula: "5 Tola = 1 Chhatak",
    states: ["Madhya Pradesh"],
    used_in: ["Bulk silver and bullion"],
    references: ["Central Provinces Gazetteers"],
  },
  {
    id: "mp-gold-6",
    slug: "mp-seer-gold",
    name_english: "Seer",
    name_hindi: "सेर",
    local_names: ["सेर (Seer)"],
    meaning: "Wholesale bullion unit.",
    category: "weight",
    sector: "gold-jewellery",
    modern_equivalent: "≈0.933 kg",
    conversion_formula: "16 Chhatak = 1 Seer",
    states: ["Madhya Pradesh"],
    used_in: ["Large bullion transactions"],
    references: ["Imperial Gazetteer"],
  },
  {
    id: "mp-gold-7",
    slug: "mp-maund-gold",
    name_english: "Maund (Man)",
    name_hindi: "मन",
    name_sanskrit: "Māna",
    local_names: ["मन (Man)"],
    meaning: "Largest traditional weight for treasury reserves.",
    category: "weight",
    sector: "gold-jewellery",
    modern_equivalent: "≈37.324 kg",
    conversion_formula: "40 Seer = 1 Maund",
    states: ["Madhya Pradesh"],
    used_in: ["Treasury and state reserves"],
    references: ["Government Historical Standards"],
  },

  // ─── Currency & Money — Extended entries from Excel ──────────────────────────
  {
    id: "mp-cur-4",
    slug: "mp-dam-cur",
    name_english: "Dam",
    name_hindi: "दाम",
    name_sanskrit: "Dāma",
    local_names: ["दाम (Dam)"],
    meaning: "Copper coin of the Mughal period.",
    category: "currency",
    sector: "currency-money",
    modern_equivalent: "Historical monetary unit",
    conversion_formula: "40 Dam = 1 Rupee (Mughal standard)",
    states: ["Madhya Pradesh"],
    used_in: ["Everyday market transactions"],
    references: ["Ain-i-Akbari"],
  },
  {
    id: "mp-cur-5",
    slug: "mp-anna-cur",
    name_english: "Anna",
    name_hindi: "आना",
    local_names: ["आना (Anna)"],
    meaning: "Fractional rupee unit.",
    category: "currency",
    sector: "currency-money",
    modern_equivalent: "Historical monetary unit",
    conversion_formula: "16 Anna = 1 Rupee",
    states: ["Madhya Pradesh"],
    used_in: ["Retail trade"],
    references: ["British Indian Coinage"],
  },
  {
    id: "mp-cur-6",
    slug: "mp-paisa-old-cur",
    name_english: "Paisa (Old)",
    name_hindi: "पैसा",
    local_names: ["पैसा (Paisa)"],
    meaning: "Fractional currency unit.",
    category: "currency",
    sector: "currency-money",
    modern_equivalent: "Historical monetary unit",
    conversion_formula: "1 Anna = 4 Paisa (Old system)",
    states: ["Madhya Pradesh"],
    used_in: ["Daily purchases"],
    references: ["Government Coinage Records"],
  },

  // ─── Storage & Transportation — Extended entries from Excel ──────────────────
  {
    id: "mp-storage-3",
    slug: "mp-pav-storage",
    name_english: "Pav (Pao)",
    name_hindi: "पाव",
    local_names: ["पाव (Pav)"],
    meaning: "Quarter Seer storage measure.",
    category: "weight",
    sector: "storage-transport",
    modern_equivalent: "≈233 g",
    conversion_formula: "4 Chhatak = 1 Pav",
    states: ["Madhya Pradesh"],
    used_in: ["Household storage of grains"],
    references: ["MP District Gazetteers"],
  },
  {
    id: "mp-storage-4",
    slug: "mp-adha-seer-storage",
    name_english: "Adha Seer",
    name_hindi: "आधा सेर",
    local_names: ["आधा सेर (Adha Seer)"],
    meaning: "Half Seer.",
    category: "weight",
    sector: "storage-transport",
    modern_equivalent: "≈466 g",
    conversion_formula: "2 Pav = 1 Half Seer",
    states: ["Madhya Pradesh"],
    used_in: ["Grain, pulses"],
    references: ["Revenue Settlement Manuals"],
  },
  {
    id: "mp-storage-5",
    slug: "mp-seer-storage",
    name_english: "Seer",
    name_hindi: "सेर",
    local_names: ["सेर (Seer)"],
    meaning: "Standard storage unit.",
    category: "weight",
    sector: "storage-transport",
    modern_equivalent: "≈0.933 kg",
    conversion_formula: "2 Half Seer = 1 Seer",
    states: ["Madhya Pradesh"],
    used_in: ["Rice, wheat, pulses, oilseeds"],
    references: ["Imperial Gazetteer of India"],
  },
  {
    id: "mp-storage-6",
    slug: "mp-pasri-storage",
    name_english: "Pasri",
    name_hindi: "पसरी",
    local_names: ["पसरी (Pasri)"],
    meaning: "Intermediate storage unit.",
    category: "weight",
    sector: "storage-transport",
    modern_equivalent: "≈4.66 kg (where applicable)",
    conversion_formula: "Usually 5 Seers = 1 Pasri (Regional Variation)",
    states: ["Madhya Pradesh"],
    used_in: ["Village grain storage"],
    references: ["District Gazetteers"],
  },
  {
    id: "mp-storage-7",
    slug: "mp-maund-storage",
    name_english: "Maund (Man)",
    name_hindi: "मन",
    name_sanskrit: "Māna",
    local_names: ["मन (Man)"],
    meaning: "Principal bulk storage unit.",
    category: "weight",
    sector: "storage-transport",
    modern_equivalent: "≈37.324 kg",
    conversion_formula: "40 Seers = 1 Maund",
    states: ["Madhya Pradesh"],
    used_in: ["Grain storage, transport by bullock carts"],
    references: ["Government Historical Standards"],
  },

  // ─── Land Measurement — Extended entries from Excel ──────────────────────────
  {
    id: "mp-land-4",
    slug: "mp-biswansi-land",
    name_english: "Biswansi",
    name_hindi: "बिसवांसी",
    local_names: ["बिसवांसी (Biswansi)"],
    meaning: "Small land subdivision used in revenue records.",
    category: "area",
    sector: "land-measurement",
    modern_equivalent: "Regionally Variable",
    conversion_formula: "20 Biswansi = 1 Biswa",
    states: ["Madhya Pradesh"],
    used_in: ["Revenue subdivision"],
    references: ["Settlement Reports"],
  },
  {
    id: "mp-land-5",
    slug: "mp-biswa-land",
    name_english: "Biswa",
    name_hindi: "बिस्वा",
    local_names: ["बिस्वा (Biswa)"],
    meaning: "Revenue land unit.",
    category: "area",
    sector: "land-measurement",
    modern_equivalent: "Regionally Variable",
    conversion_formula: "20 Biswa = 1 Bigha",
    states: ["Madhya Pradesh"],
    used_in: ["Agricultural land records"],
    references: ["MP District Gazetteers"],
  },
  {
    id: "mp-land-6",
    slug: "mp-hectare-land",
    name_english: "Hectare",
    name_hindi: "हेक्टेयर",
    local_names: ["हेक्टेयर (Hectare)"],
    meaning: "Official metric land unit.",
    category: "area",
    sector: "land-measurement",
    modern_equivalent: "10,000 m²",
    conversion_formula: "1 Hectare = 2.471 Acres",
    states: ["Madhya Pradesh"],
    used_in: ["Modern land records"],
    references: ["Government of India"],
  }
];
