import { Measurement } from "@/types";

export const PUNJAB_MEASUREMENTS: Measurement[] = [
  // ─── 1. Transportation & Distance (3 units) ─────────────────────────────────
  {
    id: "punjab-trans-1",
    slug: "karam-distance-reference-punjab",
    name_english: "Karam (distance reference)",
    name_sanskrit: "N/A (vernacular survey term)",
    local_names: ["ਕਰਮ"],
    name_hindi: "करम",
    category: "length",
    measurement_type: "Length",
    sector: "transportation-distance",
    origin: "Pan-Punjab generally",
    modern_equivalent: "5.5 ft",
    conversion_formula: "Base unit for short-distance and road-width reckoning",
    meaning:
      "Used for measuring road and canal bank widths in Sikh and later British Punjab",
    historical_period:
      "Sikh Misl Confederacy period (from Banda Singh Bahadur's 1710 Gobindshahi coin) through the Sikh Empire of Maharaja Ranjit Singh (1799–1839) to British annexation in 1849",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Used for measuring road and canal bank widths in Sikh and later British Punjab",
      "Transportation & Distance",
    ],
    references: [
      "https://en.wikipedia.org/wiki/Measurement_of_land_in_Punjab",
    ],
    tags: [
      "punjab",
      "traditional-units",
      "transportation-distance",
      "karam",
      "distance",
      "sikh-empire",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-trans-2",
    slug: "kos-krosha-distance-punjab",
    name_english: "Kos (Krosha)",
    name_sanskrit: "क्रोश (Krośa)",
    local_names: ["ਕੋਹ"],
    name_hindi: "कोस",
    category: "length",
    measurement_type: "Distance",
    sector: "transportation-distance",
    origin: "Pan-Punjab generally",
    modern_equivalent: "~3.2 km",
    conversion_formula: "1 Kos = traditional travel sub-unit",
    meaning:
      "Everyday travel distance reckoning along the Grand Trunk Road, whose Punjab stretch (Lahore–Amritsar–Jalandhar–Ludhiana) was one of its most heavily used sections, first paved by Sher Shah Suri in the 16th century",
    historical_period:
      "Delhi Sultanate–Mughal period (13th–18th century CE), preceding Sikh rule",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Everyday travel distance reckoning along the Grand Trunk Road, whose Punjab stretch (Lahore–Amritsar–Jalandhar–Ludhiana) was one of its most heavily used sections, first paved by Sher Shah Suri in the 16th century",
      "Transportation & Distance",
    ],
    references: ["https://en.wikipedia.org/wiki/Grand_Trunk_Road"],
    tags: [
      "punjab",
      "traditional-units",
      "transportation-distance",
      "kos",
      "krosha",
      "grand-trunk-road",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-trans-3",
    slug: "yojana-distance-punjab",
    name_english: "Yojana",
    name_sanskrit: "योजन (Yojana)",
    local_names: ["ਯੋਜਨ"],
    name_hindi: "योजन",
    category: "length",
    measurement_type: "Distance",
    sector: "transportation-distance",
    origin: "Pan-Punjab generally",
    modern_equivalent: "~11–14.5 km",
    conversion_formula: "4 Krosha = 1 Yojana",
    meaning:
      "Puranic-scale distance unit used in pre-Sikh Hindu religious geography of the Punjab plains; Sikh tradition from the 15th century CE (Guru Nanak) onward",
    historical_period:
      "Ancient–Puranic period; Sikh tradition from the 15th century CE (Guru Nanak) onward",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Puranic-scale distance unit used in pre-Sikh Hindu religious geography of the Punjab plains; Sikh tradition from the 15th century CE (Guru Nanak) onward",
      "Transportation & Distance",
    ],
    references: ["https://en.wikipedia.org/wiki/Yojana"],
    tags: [
      "punjab",
      "traditional-units",
      "transportation-distance",
      "yojana",
      "distance",
      "puranic",
    ],
    created_at: "2024-01-01",
  },

  // ─── 2. Land Measurement (8 units) ──────────────────────────────────────────
  {
    id: "punjab-land-1",
    slug: "karam-land-punjab",
    name_english: "Karam",
    name_sanskrit: "N/A (vernacular survey term; called 'Gatha' or 'Kadam' elsewhere in North India)",
    local_names: ["ਕਰਮ"],
    name_hindi: "करम",
    category: "length",
    measurement_type: "Length",
    sector: "land-measurement",
    origin: "Pan-Punjab generally",
    modern_equivalent:
      "5.5 ft in the British-standardised (66-inch) system — but historically 57.157 in. in the Patiala/Malwa system, 57.5 in. in the Doaba (Jalandhar-Hoshiarpur) system, 60 in. in the Majha (Amritsar-Gurdaspur) system, and 54 in. in the former Kapurthala state",
    conversion_formula:
      "Base unit of the entire Punjab land-measurement chain; 9 sq Karam = 1 Sarsahi",
    meaning:
      "The foundational measuring-rod length for Punjab's whole land-survey system — and the single biggest reason the 'same' unit names (Marla, Kanal, Bigha) still mean different absolute areas from one Punjab district to another today",
    historical_period:
      "British colonial period (Punjab annexed 1849) through post-1947/1966 Indian administration; British canal-colony settlement era (late 19th–early 20th century) for the Murabba unit specifically",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "The foundational measuring-rod length for Punjab's whole land-survey system — and the single biggest reason the 'same' unit names (Marla, Kanal, Bigha) still mean different absolute areas from one Punjab district to another today",
      "Land Measurement",
    ],
    references: [
      "https://www.realtyconsultants.in/tools/area-calculator/punjab-land-measurement-chart",
      "https://landvaluetools.com/blog/punjab-haryna-land-measurement-guide/",
    ],
    tags: [
      "punjab",
      "traditional-units",
      "land-measurement",
      "karam",
      "survey-rod",
      "length",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-land-2",
    slug: "sarsahi-sq-karam-land-punjab",
    name_english: "Sarsahi (Sq Karam)",
    name_sanskrit: "N/A (vernacular revenue term)",
    local_names: ["ਸਰਸਾਹੀ"],
    name_hindi: "सरसाही",
    category: "area",
    measurement_type: "Area",
    sector: "land-measurement",
    origin: "Pan-Punjab generally",
    modern_equivalent:
      "30.25 sq ft (one Karam squared, in the standard 66-inch system)",
    conversion_formula: "1 Sarsahi = 1 sq Karam; 9 Sarsahi = 1 Marla",
    meaning:
      "Smallest standard unit in the modern Punjab land record chain, used for narrow residential plot margins",
    historical_period:
      "British colonial period (Punjab annexed 1849) through post-1947/1966 Indian administration; British canal-colony settlement era (late 19th–early 20th century) for the Murabba unit specifically",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Smallest standard unit in the modern Punjab land record chain, used for narrow residential plot margins",
      "Land Measurement",
    ],
    references: ["https://bhumicalculator.com/states/punjab/"],
    tags: [
      "punjab",
      "traditional-units",
      "land-measurement",
      "sarsahi",
      "area",
      "sq-karam",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-land-3",
    slug: "marla-land-punjab",
    name_english: "Marla",
    name_sanskrit: "N/A (vernacular revenue term)",
    local_names: ["ਮਰਲਾ"],
    name_hindi: "मरला",
    category: "area",
    measurement_type: "Area",
    sector: "land-measurement",
    origin: "Pan-Punjab generally",
    modern_equivalent:
      "272.25 sq ft (standard system); 225 sq ft in the Majha/Amritsar system; 206.61 sq ft in the Doaba system; 182.25 sq ft in the Kapurthala system",
    conversion_formula: "9 Sarsahi = 1 Marla; 20 Marla = 1 Kanal",
    meaning:
      "Punjab's single most commonly quoted land unit today — urban plots, farmhouses and even government scheme allotments are still sold and registered 'by the Marla'",
    historical_period:
      "British colonial period (Punjab annexed 1849) through post-1947/1966 Indian administration; British canal-colony settlement era (late 19th–early 20th century) for the Murabba unit specifically",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Punjab's single most commonly quoted land unit today — urban plots, farmhouses and even government scheme allotments are still sold and registered 'by the Marla'",
      "Land Measurement",
    ],
    references: [
      "https://www.realtyconsultants.in/tools/area-calculator/punjab-land-measurement-chart",
      "https://landvaluetools.com/blog/punjab-haryna-land-measurement-guide/",
    ],
    tags: [
      "punjab",
      "traditional-units",
      "land-measurement",
      "marla",
      "area",
      "residential-plots",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-land-4",
    slug: "biswa-land-punjab",
    name_english: "Biswa",
    name_sanskrit:
      "N/A (vernacular revenue term, shared in name — though not in exact size — with the UP/Bihar Biswa)",
    local_names: ["ਬਿਸਵਾ"],
    name_hindi: "बिस्वा",
    category: "area",
    measurement_type: "Area",
    sector: "land-measurement",
    origin: "Pan-Punjab generally",
    modern_equivalent: "1,000 sq ft (4 Marla, standard system)",
    conversion_formula: "4 Marla = 1 Biswa; 5 Biswa = 1 Kanal",
    meaning:
      "Intermediate rung used in some Punjab districts' land records alongside the more common Kanal-Marla reckoning",
    historical_period:
      "British colonial period (Punjab annexed 1849) through post-1947/1966 Indian administration; British canal-colony settlement era (late 19th–early 20th century) for the Murabba unit specifically",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Intermediate rung used in some Punjab districts' land records alongside the more common Kanal-Marla reckoning",
      "Land Measurement",
    ],
    references: [
      "https://en.wikipedia.org/wiki/Measurement_of_land_in_Punjab",
    ],
    tags: [
      "punjab",
      "traditional-units",
      "land-measurement",
      "biswa",
      "area",
      "land-records",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-land-5",
    slug: "kanal-land-punjab",
    name_english: "Kanal",
    name_sanskrit: "N/A (vernacular revenue term, Punjab/Haryana-specific)",
    local_names: ["ਕਨਾਲ"],
    name_hindi: "कनाल",
    category: "area",
    measurement_type: "Area",
    sector: "land-measurement",
    origin: "Mohali and urban Punjab generally (66 inch British standardised karam)",
    modern_equivalent:
      "5,445 sq ft (standard system) = 505.9 sq m; 4,500 sq ft under the 'small Marla' variant",
    conversion_formula: "20 Marla = 1 Kanal; 8 Kanal = 1 Killa",
    meaning:
      "The everyday unit for larger residential plots and farmhouse land, especially in and around Chandigarh, Mohali and other urban Punjab developments",
    historical_period:
      "British colonial period (Punjab annexed 1849) through post-1947/1966 Indian administration; British canal-colony settlement era (late 19th–early 20th century) for the Murabba unit specifically",
    region_applicable:
      "Mohali and urban Punjab generally (66 inch British standardised karam)",
    states: ["Punjab"],
    used_in: [
      "The everyday unit for larger residential plots and farmhouse land, especially in and around Chandigarh, Mohali and other urban Punjab developments",
      "Land Measurement",
    ],
    references: ["https://bhumicalculator.com/states/punjab/"],
    tags: [
      "punjab",
      "traditional-units",
      "land-measurement",
      "kanal",
      "area",
      "mohali",
      "chandigarh",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-land-6",
    slug: "bigha-punjab-land",
    name_english: "Bigha (Punjab)",
    name_sanskrit: "N/A (vernacular revenue term)",
    local_names: ["ਬੀਘਾ"],
    name_hindi: "बीघा",
    category: "area",
    measurement_type: "Area",
    sector: "land-measurement",
    origin: "Pan-Punjab generally",
    modern_equivalent:
      "21,780 sq ft (4 Kanal, standard system) — notably different from the Bihar Bigha (~27,220 sq ft) and Uttar Pradesh's district-variable Bigha",
    conversion_formula: "4 Kanal = 1 Bigha; 2 Bigha = 1 Killa",
    meaning:
      "Rural agricultural land unit, used alongside but generally less prominently than Kanal-Marla in Punjab proper",
    historical_period:
      "Delhi Sultanate–Mughal period (13th–18th century CE), preceding Sikh rule",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Rural agricultural land unit, used alongside but generally less prominently than Kanal-Marla in Punjab proper",
      "Land Measurement",
    ],
    references: [
      "https://en.wikipedia.org/wiki/Measurement_of_land_in_Punjab",
    ],
    tags: [
      "punjab",
      "traditional-units",
      "land-measurement",
      "bigha",
      "area",
      "mughal-period",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-land-7",
    slug: "killa-acre-land-punjab",
    name_english: "Killa (Acre)",
    name_sanskrit: "एकड (Ekara)",
    local_names: ["ਕਿੱਲਾ"],
    name_hindi: "किल्ला / एकड़",
    category: "area",
    measurement_type: "Area",
    sector: "land-measurement",
    origin: "Pan-Punjab generally",
    modern_equivalent:
      "43,560 sq ft (exactly equivalent to the statutory Acre)",
    conversion_formula: "8 Kanal = 1 Killa = 1 Acre",
    meaning:
      "The standard large-farm unit in Punjab's wheat- and rice-growing tracts — uniquely among Indian states, Punjabi 'Killa' and the British 'Acre' were made to coincide exactly, rather than approximate each other",
    historical_period:
      "British colonial period (Punjab annexed 1849) through post-1947/1966 Indian administration; British canal-colony settlement era (late 19th–early 20th century) for the Murabba unit specifically",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "The standard large-farm unit in Punjab's wheat- and rice-growing tracts — uniquely among Indian states, Punjabi 'Killa' and the British 'Acre' were made to coincide exactly, rather than approximate each other",
      "Land Measurement",
    ],
    references: [
      "https://en.wikipedia.org/wiki/Measurement_of_land_in_Punjab",
    ],
    tags: [
      "punjab",
      "traditional-units",
      "land-measurement",
      "killa",
      "acre",
      "area",
      "wheat-tracts",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-land-8",
    slug: "murabba-land-punjab",
    name_english: "Murabba",
    name_sanskrit:
      "N/A (Persian-Urdu term for 'square/rectangle', adopted into Punjabi land-revenue usage)",
    local_names: ["ਮੁਰੱਬਾ"],
    name_hindi: "मुरब्बा",
    category: "area",
    measurement_type: "Area",
    sector: "land-measurement",
    origin: "Pan-Punjab generally",
    modern_equivalent: "25 Killa = 25 Acres ≈ 10.117 hectares",
    conversion_formula: "25 Killa = 1 Murabba",
    meaning:
      "The standard large-block unit created by British canal-colony officials when they surveyed and distributed newly irrigated land in the Bar tracts of undivided Punjab (late 19th–early 20th century) into regular square block-grants to settler-cultivators",
    historical_period:
      "British colonial period (Punjab annexed 1849) through post-1947/1966 Indian administration; British canal-colony settlement era (late 19th–early 20th century) for the Murabba unit specifically",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "The standard large-block unit created by British canal-colony officials when they surveyed and distributed newly irrigated land in the Bar tracts of undivided Punjab (late 19th–early 20th century) into regular square block-grants to settler-cultivators",
      "Land Measurement",
    ],
    references: [
      "https://en.wikipedia.org/wiki/Measurement_of_land_in_Punjab",
    ],
    tags: [
      "punjab",
      "traditional-units",
      "land-measurement",
      "murabba",
      "canal-colony",
      "bar-tracts",
    ],
    created_at: "2024-01-01",
  },

  // ─── 3. Livestock & Dairy (2 units) ─────────────────────────────────────────
  {
    id: "punjab-dairy-1",
    slug: "ser-seer-dairy-punjab",
    name_english: "Ser (Seer)",
    name_sanskrit: "सेर (Sēra)",
    local_names: ["ਸੇਰ"],
    name_hindi: "सेर",
    category: "volume",
    measurement_type: "Weight/Volume",
    sector: "livestock-dairy",
    origin: "Pan-Punjab generally",
    modern_equivalent: "~0.93 kg / ~0.93 L",
    conversion_formula: "1/40 Mon",
    meaning:
      "Standard market measure for milk, ghee and lassi; Punjab's buffalo dairy economy — among the most productive in India — traded milk by this unit long before litre-based metric rule became standard",
    historical_period:
      "British colonial period (Punjab annexed 1849) through post-1947/1966 Indian administration; British canal-colony settlement era (late 19th–early 20th century) for the Murabba unit specifically",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Standard market measure for milk, ghee and lassi; Punjab's buffalo dairy economy — among the most productive in India — traded milk by this unit long before litre-based metric rule became standard",
      "Livestock & Dairy",
    ],
    references: [
      "https://grokipedia.com/page/Seer_(unit)",
      "https://en.wikipedia.org/wiki/Maund",
    ],
    tags: [
      "punjab",
      "traditional-units",
      "livestock-dairy",
      "ser",
      "seer",
      "milk",
      "ghee",
      "lassi",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-dairy-2",
    slug: "mon-maund-dairy-punjab",
    name_english: "Mon (Maund)",
    name_sanskrit: "मण (Māna)",
    local_names: ["ਮਣ"],
    name_hindi: "मन",
    category: "weight",
    measurement_type: "Weight",
    sector: "livestock-dairy",
    origin: "Pan-Punjab generally",
    modern_equivalent: "40 Ser ≈ 37.3 kg",
    conversion_formula: "40 Ser = 1 Mon",
    meaning:
      "Bulk trade of ghee, fodder (toriya/chari) and cattle-feed cake at rural weekly markets",
    historical_period:
      "British colonial period (Punjab annexed 1849) through post-1947/1966 Indian administration; British canal-colony settlement era (late 19th–early 20th century) for the Murabba unit specifically",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Bulk trade of ghee, fodder (toriya/chari) and cattle-feed cake at rural weekly markets",
      "Livestock & Dairy",
    ],
    references: [
      "https://grokipedia.com/page/Seer_(unit)",
      "https://en.wikipedia.org/wiki/Maund",
    ],
    tags: [
      "punjab",
      "traditional-units",
      "livestock-dairy",
      "mon",
      "maund",
      "cattle-feed",
      "bulk-ghee",
    ],
    created_at: "2024-01-01",
  },

  // ─── 4. Household & Daily Life (4 units) ─────────────────────────────────────
  {
    id: "punjab-hh-1",
    slug: "chutki-muthi-household-punjab",
    name_english: "Chutki / Muthi",
    name_sanskrit:
      "N/A (general vernacular, shared with the wider North Indian vocabulary)",
    local_names: ["ਚੁਟਕੀ / ਮੁੱਠੀ"],
    name_hindi: "चुटकी / मुट्ठी",
    category: "volume",
    measurement_type: "Volume (informal)",
    sector: "household",
    origin: "Pan-Punjab generally",
    modern_equivalent: "Pinch to ~50–100 g fistful",
    conversion_formula: "Chutki < Muthi",
    meaning:
      "Everyday informal cooking-quantity gestures in Punjabi kitchens",
    historical_period:
      "Vedic–Classical Sanskrit period (c. 1000 BCE–500 CE), continued through the medieval era",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Everyday informal cooking-quantity gestures in Punjabi kitchens",
      "Household & Daily Life",
    ],
    references: ["https://en.wikipedia.org/wiki/Handful"],
    tags: [
      "punjab",
      "traditional-units",
      "household",
      "chutki",
      "muthi",
      "kitchen",
      "cooking",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-hh-2",
    slug: "chittak-chhatank-household-punjab",
    name_english: "Chittak (Chhatank)",
    name_sanskrit: "N/A (vernacular)",
    local_names: ["ਛਟਾਂਕ"],
    name_hindi: "छटांक",
    category: "weight",
    measurement_type: "Weight",
    sector: "household",
    origin: "Pan-Punjab generally",
    modern_equivalent: "~58.3 g",
    conversion_formula: "1/16 Ser = 1 Chittak",
    meaning:
      "Everyday kitchen weighing of spices, atta (wheat flour) and sugar",
    historical_period:
      "British colonial period (Punjab annexed 1849) through post-1947/1966 Indian administration; British canal-colony settlement era (late 19th–early 20th century) for the Murabba unit specifically",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Everyday kitchen weighing of spices, atta (wheat flour) and sugar",
      "Household & Daily Life",
    ],
    references: [
      "https://grokipedia.com/page/Seer_(unit)",
      "https://en.wikipedia.org/wiki/Maund",
    ],
    tags: [
      "punjab",
      "traditional-units",
      "household",
      "chittak",
      "chhatank",
      "spices",
      "atta",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-hh-3",
    slug: "pav-pao-household-punjab",
    name_english: "Pav (Pao)",
    name_sanskrit: "N/A (vernacular)",
    local_names: ["ਪਾਓ"],
    name_hindi: "पाव",
    category: "weight",
    measurement_type: "Weight",
    sector: "household",
    origin: "Pan-Punjab generally",
    modern_equivalent: "~233 g",
    conversion_formula: "1/4 Ser = 1 Pav",
    meaning:
      "Common household purchase quantity of atta, sugar and ghee",
    historical_period:
      "British colonial period (Punjab annexed 1849) through post-1947/1966 Indian administration; British canal-colony settlement era (late 19th–early 20th century) for the Murabba unit specifically",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Common household purchase quantity of atta, sugar and ghee",
      "Household & Daily Life",
    ],
    references: [
      "https://grokipedia.com/page/Seer_(unit)",
      "https://en.wikipedia.org/wiki/Maund",
    ],
    tags: [
      "punjab",
      "traditional-units",
      "household",
      "pav",
      "pao",
      "atta",
      "ghee",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-hh-4",
    slug: "ser-seer-household-punjab",
    name_english: "Ser (Seer)",
    name_sanskrit: "सेर (Sēra)",
    local_names: ["ਸੇਰ"],
    name_hindi: "सेर",
    category: "weight",
    measurement_type: "Weight",
    sector: "household",
    origin: "Pan-Punjab generally",
    modern_equivalent: "~0.93 kg",
    conversion_formula: "16 Chittak = 1 Ser",
    meaning:
      "Standard everyday household purchase unit for grain, sugar and vegetables",
    historical_period:
      "British colonial period (Punjab annexed 1849) through post-1947/1966 Indian administration; British canal-colony settlement era (late 19th–early 20th century) for the Murabba unit specifically",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Standard everyday household purchase unit for grain, sugar and vegetables",
      "Household & Daily Life",
    ],
    references: [
      "https://grokipedia.com/page/Seer_(unit)",
      "https://en.wikipedia.org/wiki/Maund",
    ],
    tags: [
      "punjab",
      "traditional-units",
      "household",
      "ser",
      "seer",
      "grain",
      "vegetables",
    ],
    created_at: "2024-01-01",
  },

  // ─── 5. Gold & Jewellery (4 units) ──────────────────────────────────────────
  {
    id: "punjab-gold-1",
    slug: "ratti-gold-punjab",
    name_english: "Ratti",
    name_sanskrit: "रत्ति (Ratti / Raktikā)",
    local_names: ["ਰੱਤੀ"],
    name_hindi: "रत्ती",
    category: "weight",
    measurement_type: "Weight",
    sector: "gold-jewellery",
    origin: "Pan-Punjab generally",
    modern_equivalent: "~0.1215 g",
    conversion_formula: "Base gold/gem unit",
    meaning:
      "Traditional small-ornament weighing by Punjabi jewellers (sunar)",
    historical_period:
      "Vedic–Classical Sanskrit period (c. 1000 BCE–500 CE), continued through the medieval era",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Traditional small-ornament weighing by Punjabi jewellers (sunar)",
      "Gold & Jewellery",
    ],
    references: ["https://en.wikipedia.org/wiki/Ratti_(unit)"],
    tags: [
      "punjab",
      "traditional-units",
      "gold-jewellery",
      "ratti",
      "sunar",
      "gemstone",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-gold-2",
    slug: "masha-gold-punjab",
    name_english: "Masha",
    name_sanskrit: "माष (Māṣa)",
    local_names: ["ਮਾਸ਼ਾ"],
    name_hindi: "माशा",
    category: "weight",
    measurement_type: "Weight",
    sector: "gold-jewellery",
    origin: "Pan-Punjab generally",
    modern_equivalent: "~0.97 g",
    conversion_formula: "8 Ratti = 1 Masha",
    meaning: "Weighing gold dust and small ornament fragments",
    historical_period:
      "Vedic–Classical Sanskrit period (c. 1000 BCE–500 CE), continued through the medieval era",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Weighing gold dust and small ornament fragments",
      "Gold & Jewellery",
    ],
    references: ["https://www.wisdomlib.org/concept/masha"],
    tags: [
      "punjab",
      "traditional-units",
      "gold-jewellery",
      "masha",
      "gold-dust",
      "ornaments",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-gold-3",
    slug: "tola-gold-punjab",
    name_english: "Tola",
    name_sanskrit: "तोला (Tola)",
    local_names: ["ਤੋਲਾ"],
    name_hindi: "तोला",
    category: "weight",
    measurement_type: "Weight",
    sector: "gold-jewellery",
    origin: "Pan-Punjab generally",
    modern_equivalent: "~11.66 g",
    conversion_formula: "12 Masha = 1 Tola",
    meaning:
      "Principal gold trade weight in Punjab's jewellery bazaars, still the everyday spoken unit for gold quantity",
    historical_period:
      "Vedic–Classical Sanskrit period (c. 1000 BCE–500 CE), continued through the medieval era",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Principal gold trade weight in Punjab's jewellery bazaars, still the everyday spoken unit for gold quantity",
      "Gold & Jewellery",
    ],
    references: ["https://en.wikipedia.org/wiki/Tola_(unit)"],
    tags: [
      "punjab",
      "traditional-units",
      "gold-jewellery",
      "tola",
      "bazaars",
      "gold-bullion",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-gold-4",
    slug: "nanakshahi-rupee-bullion-reference-gold-punjab",
    name_english: "Nanakshahi Rupee (bullion reference)",
    name_sanskrit: "N/A (Sikh Empire term)",
    local_names: ["ਨਾਨਕਸ਼ਾਹੀ ਰੁਪਈਆ"],
    name_hindi: "नानकशाही रुपया",
    category: "currency",
    measurement_type: "Weight/Currency",
    sector: "gold-jewellery",
    origin:
      "Lahore–Amritsar axis — the Sikh Empire's political and mint centre",
    modern_equivalent: "~11–11.2 g silver",
    conversion_formula:
      "Historical bullion-value benchmark from the Sikh Empire's own coinage",
    meaning:
      "Used historically as a silver-weight and value reference in jewellery and dowry-gold transactions across the Sikh Empire",
    historical_period:
      "Sikh Misl Confederacy period (from Banda Singh Bahadur's 1710 Gobindshahi coin) through the Sikh Empire of Maharaja Ranjit Singh (1799–1839) to British annexation in 1849",
    region_applicable:
      "Lahore–Amritsar axis — the Sikh Empire's political and mint centre",
    states: ["Punjab"],
    used_in: [
      "Used historically as a silver-weight and value reference in jewellery and dowry-gold transactions across the Sikh Empire",
      "Gold & Jewellery",
    ],
    references: [
      "https://www.mintageworld.com/media/detail/12829-ranjit-singhs-nanakshahi-couplet-coin/",
      "https://en.numista.com/catalogue/sikh_empire-1.html",
    ],
    tags: [
      "punjab",
      "traditional-units",
      "gold-jewellery",
      "nanakshahi-rupee",
      "silver-weight",
      "sikh-empire",
      "dowry",
    ],
    created_at: "2024-01-01",
  },

  // ─── 6. Seed & Crop (Agriculture) (4 units) ─────────────────────────────────
  {
    id: "punjab-agri-1",
    slug: "chittak-chhatank-agriculture-punjab",
    name_english: "Chittak (Chhatank)",
    name_sanskrit: "N/A (vernacular)",
    local_names: ["ਛਟਾਂਕ"],
    name_hindi: "छटांक",
    category: "weight",
    measurement_type: "Weight",
    sector: "agriculture",
    origin: "Pan-Punjab generally",
    modern_equivalent: "~58.3 g",
    conversion_formula: "1/16 Ser = 1 Chittak",
    meaning:
      "Measuring small seed quantities of wheat and paddy before sowing",
    historical_period:
      "British colonial period (Punjab annexed 1849) through post-1947/1966 Indian administration; British canal-colony settlement era (late 19th–early 20th century) for the Murabba unit specifically",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Measuring small seed quantities of wheat and paddy before sowing",
      "Seed & Crop (Agriculture)",
    ],
    references: [
      "https://grokipedia.com/page/Seer_(unit)",
      "https://en.wikipedia.org/wiki/Maund",
    ],
    tags: [
      "punjab",
      "traditional-units",
      "agriculture",
      "chittak",
      "chhatank",
      "seed-weight",
      "sowing",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-agri-2",
    slug: "ser-seer-agriculture-punjab",
    name_english: "Ser (Seer)",
    name_sanskrit: "सेर (Sēra)",
    local_names: ["ਸੇਰ"],
    name_hindi: "सेर",
    category: "weight",
    measurement_type: "Weight",
    sector: "agriculture",
    origin: "Pan-Punjab generally",
    modern_equivalent: "~0.93 kg",
    conversion_formula: "16 Chittak = 1 Ser",
    meaning:
      "Standard measure for seed grain and harvested wheat/paddy at the village level",
    historical_period:
      "British colonial period (Punjab annexed 1849) through post-1947/1966 Indian administration; British canal-colony settlement era (late 19th–early 20th century) for the Murabba unit specifically",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Standard measure for seed grain and harvested wheat/paddy at the village level",
      "Seed & Crop (Agriculture)",
    ],
    references: [
      "https://grokipedia.com/page/Seer_(unit)",
      "https://en.wikipedia.org/wiki/Maund",
    ],
    tags: [
      "punjab",
      "traditional-units",
      "agriculture",
      "ser",
      "seer",
      "grain",
      "harvest",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-agri-3",
    slug: "mon-maund-agriculture-punjab",
    name_english: "Mon (Maund)",
    name_sanskrit: "मण (Māna)",
    local_names: ["ਮਣ"],
    name_hindi: "मन",
    category: "weight",
    measurement_type: "Weight",
    sector: "agriculture",
    origin: "Pan-Punjab generally",
    modern_equivalent: "~37.3 kg",
    conversion_formula: "40 Ser = 1 Mon",
    meaning:
      "Principal wholesale unit for wheat and paddy sale at Punjab's mandis, the physical and institutional backbone of India's post-1960s Green Revolution grain procurement",
    historical_period:
      "British colonial period (Punjab annexed 1849) through post-1947/1966 Indian administration; British canal-colony settlement era (late 19th–early 20th century) for the Murabba unit specifically",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Principal wholesale unit for wheat and paddy sale at Punjab's mandis, the physical and institutional backbone of India's post-1960s Green Revolution grain procurement",
      "Seed & Crop (Agriculture)",
    ],
    references: [
      "https://grokipedia.com/page/Seer_(unit)",
      "https://en.wikipedia.org/wiki/Maund",
    ],
    tags: [
      "punjab",
      "traditional-units",
      "agriculture",
      "mon",
      "maund",
      "mandi",
      "green-revolution",
      "wheat-procurement",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-agri-4",
    slug: "kanal-killa-murabba-field-size-reference-agriculture-punjab",
    name_english: "Kanal / Killa / Murabba (Field-size reference)",
    name_sanskrit: "N/A (vernacular revenue terms)",
    local_names: ["ਕਨਾਲ / ਕਿੱਲਾ / ਮੁਰੱਬਾ"],
    name_hindi: "कनाल / किल्ला / मुरब्बा",
    category: "area",
    measurement_type: "Area",
    sector: "agriculture",
    origin: "Pan-Punjab generally",
    modern_equivalent:
      "Kanal ~5,445 sq ft; Killa ~43,560 sq ft (1 Acre); Murabba ~25 Killa",
    conversion_formula: "8 Kanal = 1 Killa; 25 Killa = 1 Murabba",
    meaning:
      "Field-size units for reckoning sowing area and expected yield — the large, square Murabba block in particular reflects how British canal-colony engineers physically re-shaped Punjab's farmland into regular, irrigation-channel-fed grants",
    historical_period:
      "British colonial period (Punjab annexed 1849) through post-1947/1966 Indian administration; British canal-colony settlement era (late 19th–early 20th century) for the Murabba unit specifically",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Field-size units for reckoning sowing area and expected yield — the large, square Murabba block in particular reflects how British canal-colony engineers physically re-shaped Punjab's farmland into regular, irrigation-channel-fed grants",
      "Seed & Crop (Agriculture)",
    ],
    references: [
      "https://en.wikipedia.org/wiki/Measurement_of_land_in_Punjab",
    ],
    tags: [
      "punjab",
      "traditional-units",
      "agriculture",
      "kanal",
      "killa",
      "murabba",
      "sowing-area",
      "canal-colony",
    ],
    created_at: "2024-01-01",
  },

  // ─── 7. Currency & Money (5 units) ──────────────────────────────────────────
  {
    id: "punjab-curr-1",
    slug: "gobindshahi-coin-currency-punjab",
    name_english: "Gobindshahi coin",
    name_sanskrit: "N/A (Sikh coin-name honouring Guru Gobind Singh)",
    local_names: ["ਗੋਬਿੰਦਸ਼ਾਹੀ ਸਿੱਕਾ"],
    name_hindi: "गोबिंदशाही सिक्का",
    category: "currency",
    measurement_type: "Currency",
    sector: "currency-money",
    origin: "Pan-Punjab generally",
    modern_equivalent: "Silver coin, ~11 g",
    conversion_formula:
      "The founding issue of the entire later Sikh coinage tradition",
    meaning:
      "Struck in 1710 CE by Banda Singh Bahadur, the first political leader of the Sikhs, from his fort at Mukhlishgarh — the first sovereign Sikh coin, inscribed 'the coin struck in the two worlds, its bestower being the sword of Guru Nanak, the emperor Guru Gobind Singh, whose grace is true'",
    historical_period:
      "1710 CE, Banda Singh Bahadur's short-lived Sikh state",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Struck in 1710 CE by Banda Singh Bahadur, the first political leader of the Sikhs, from his fort at Mukhlishgarh — the first sovereign Sikh coin, inscribed 'the coin struck in the two worlds, its bestower being the sword of Guru Nanak, the emperor Guru Gobind Singh, whose grace is true'",
      "Currency & Money",
    ],
    references: [
      "https://www.sikhiwiki.org/index.php/Sikh_Coins",
      "https://www.livehistoryindia.com/story/living-culture/sikh-coins",
    ],
    tags: [
      "punjab",
      "traditional-units",
      "currency-money",
      "gobindshahi",
      "banda-singh-bahadur",
      "silver-coin",
      "sikh-state",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-curr-2",
    slug: "falus-dhela-taka-paisa-currency-punjab",
    name_english: "Falus / Dhela (Taka) / Paisa (copper denominations)",
    name_sanskrit: "N/A (Persian-vernacular copper-coin terms)",
    local_names: ["ਫਲੂਸ / ਧੇਲਾ / ਪੈਸਾ"],
    name_hindi: "फ़लूस / धेला / पैसा",
    category: "currency",
    measurement_type: "Currency",
    sector: "currency-money",
    origin:
      "Lahore–Amritsar axis — the Sikh Empire's political and mint centre",
    modern_equivalent:
      "Copper coins of varying small fractional value",
    conversion_formula:
      "Lower denominations below the silver Rupee",
    meaning:
      "The everyday small-change coinage of the Sikh Empire's markets, made of copper as against the Rupee's silver",
    historical_period:
      "Sikh Misl Confederacy period (from Banda Singh Bahadur's 1710 Gobindshahi coin) through the Sikh Empire of Maharaja Ranjit Singh (1799–1839) to British annexation in 1849",
    region_applicable:
      "Lahore–Amritsar axis — the Sikh Empire's political and mint centre",
    states: ["Punjab"],
    used_in: [
      "The everyday small-change coinage of the Sikh Empire's markets, made of copper as against the Rupee's silver",
      "Currency & Money",
    ],
    references: ["https://www.sikhiwiki.org/index.php/Sikh_Coins"],
    tags: [
      "punjab",
      "traditional-units",
      "currency-money",
      "falus",
      "dhela",
      "taka",
      "paisa",
      "copper-coins",
      "sikh-empire",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-curr-3",
    slug: "nanakshahi-rupee-currency-punjab",
    name_english: "Nanakshahi Rupee",
    name_sanskrit: "N/A (Sikh Empire term)",
    local_names: ["ਨਾਨਕਸ਼ਾਹੀ ਰੁਪਈਆ"],
    name_hindi: "नानकशाही रुपया",
    category: "currency",
    measurement_type: "Currency",
    sector: "currency-money",
    origin:
      "Lahore–Amritsar axis — the Sikh Empire's political and mint centre",
    modern_equivalent: "~11–11.2 g silver",
    conversion_formula: "Top denomination of the Sikh coin ladder",
    meaning:
      "Minted at Amritsar, Lahore, Multan, Kashmir and Peshawar under Maharaja Ranjit Singh — remarkably, neither Ranjit Singh nor his successors ever put their own names on the coinage, keeping the Guru Nanak/Guru Gobind Singh dedication throughout the Empire's history",
    historical_period:
      "Sikh Misl Confederacy period (from Banda Singh Bahadur's 1710 Gobindshahi coin) through the Sikh Empire of Maharaja Ranjit Singh (1799–1839) to British annexation in 1849",
    region_applicable:
      "Lahore–Amritsar axis — the Sikh Empire's political and mint centre",
    states: ["Punjab"],
    used_in: [
      "Minted at Amritsar, Lahore, Multan, Kashmir and Peshawar under Maharaja Ranjit Singh — remarkably, neither Ranjit Singh nor his successors ever put their own names on the coinage, keeping the Guru Nanak/Guru Gobind Singh dedication throughout the Empire's history",
      "Currency & Money",
    ],
    references: [
      "https://www.mintageworld.com/media/detail/12829-ranjit-singhs-nanakshahi-couplet-coin/",
      "https://en.numista.com/catalogue/sikh_empire-1.html",
    ],
    tags: [
      "punjab",
      "traditional-units",
      "currency-money",
      "nanakshahi-rupee",
      "silver-coin",
      "ranjit-singh",
      "amritsar",
      "sikh-empire",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-curr-4",
    slug: "dam-pre-sikh-mughal-layer-currency-punjab",
    name_english: "Dam (pre-Sikh Mughal layer)",
    name_sanskrit: "N/A (Persian-Mughal term)",
    local_names: ["ਦਾਮ"],
    name_hindi: "दाम",
    category: "currency",
    measurement_type: "Currency",
    sector: "currency-money",
    origin:
      "Lahore–Amritsar axis — the Sikh Empire's political and mint centre",
    modern_equivalent: "Copper coin, ~20.9 g under Akbar",
    conversion_formula: "40 Dam = 1 Rupee (Akbar's standardised rate)",
    meaning:
      "Base Mughal currency in Punjab before Sikh rule, minted at Lahore, one of the Mughal Empire's major provincial mints",
    historical_period:
      "Delhi Sultanate–Mughal period (13th–18th century CE), preceding Sikh rule",
    region_applicable:
      "Lahore–Amritsar axis — the Sikh Empire's political and mint centre",
    states: ["Punjab"],
    used_in: [
      "Base Mughal currency in Punjab before Sikh rule, minted at Lahore, one of the Mughal Empire's major provincial mints",
      "Currency & Money",
    ],
    references: [
      "https://en.wikipedia.org/wiki/Dam_(unit)",
      "https://www.mintageworld.com/blog/akbars-coinage/",
    ],
    tags: [
      "punjab",
      "traditional-units",
      "currency-money",
      "dam",
      "mughal-layer",
      "lahore-mint",
      "copper-coin",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-curr-5",
    slug: "british-indian-rupee-post-1849-currency-punjab",
    name_english: "British Indian Rupee (post-1849)",
    name_sanskrit: "N/A",
    local_names: ["ਰੁਪਈਆ"],
    name_hindi: "रुपया",
    category: "currency",
    measurement_type: "Currency",
    sector: "currency-money",
    origin: "Pan-Punjab generally",
    modern_equivalent: "~11.66 g silver, British India standard",
    conversion_formula:
      "Superseded the Nanakshahi Rupee after Punjab's 1849 annexation",
    meaning:
      "Introduced as Punjab passed under direct British East India Company rule following the Second Anglo-Sikh War",
    historical_period:
      "British colonial period (Punjab annexed 1849) through post-1947/1966 Indian administration; British canal-colony settlement era (late 19th–early 20th century) for the Murabba unit specifically",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Introduced as Punjab passed under direct British East India Company rule following the Second Anglo-Sikh War",
      "Currency & Money",
    ],
    references: ["https://en.wikipedia.org/wiki/Rupee"],
    tags: [
      "punjab",
      "traditional-units",
      "currency-money",
      "british-rupee",
      "colonial-period",
      "silver-rupee",
    ],
    created_at: "2024-01-01",
  },

  // ─── 8. Storage & Transportation (4 units) ───────────────────────────────────
  {
    id: "punjab-stor-1",
    slug: "ser-mon-seer-maund-storage-punjab",
    name_english: "Ser / Mon (Seer/Maund)",
    name_sanskrit: "सेर / मन",
    local_names: ["ਸੇਰ / ਮਣ"],
    name_hindi: "सेर / मन",
    category: "weight",
    measurement_type: "Weight",
    sector: "storage-transport",
    origin: "Pan-Punjab generally",
    modern_equivalent: "~0.93 kg Ser; 40 Ser = 1 Mon ≈ 37.3 kg",
    conversion_formula: "40 Ser = 1 Mon",
    meaning:
      "Standard granary and mandi warehouse storage unit for wheat and paddy",
    historical_period:
      "British colonial period (Punjab annexed 1849) through post-1947/1966 Indian administration; British canal-colony settlement era (late 19th–early 20th century) for the Murabba unit specifically",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Standard granary and mandi warehouse storage unit for wheat and paddy",
      "Storage & Transportation",
    ],
    references: [
      "https://grokipedia.com/page/Seer_(unit)",
      "https://en.wikipedia.org/wiki/Maund",
    ],
    tags: [
      "punjab",
      "traditional-units",
      "storage-transport",
      "ser",
      "mon",
      "seer",
      "maund",
      "granary",
      "warehouse",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-stor-2",
    slug: "bora-sack-storage-punjab",
    name_english: "Bora (sack)",
    name_sanskrit: "N/A (vernacular)",
    local_names: ["ਬੋਰਾ"],
    name_hindi: "बोरा",
    category: "weight",
    measurement_type: "Weight",
    sector: "storage-transport",
    origin: "Pan-Punjab generally",
    modern_equivalent: "~50–100 kg (sack dependent)",
    conversion_formula: "Standard sack unit; varies by commodity",
    meaning:
      "Grain sacking for storage and transport between farm, village kotha (granary room) and government procurement mandi",
    historical_period:
      "British colonial period (Punjab annexed 1849) through post-1947/1966 Indian administration; British canal-colony settlement era (late 19th–early 20th century) for the Murabba unit specifically",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Grain sacking for storage and transport between farm, village kotha (granary room) and government procurement mandi",
      "Storage & Transportation",
    ],
    references: ["https://en.wikipedia.org/wiki/Sack_(bag)"],
    tags: [
      "punjab",
      "traditional-units",
      "storage-transport",
      "bora",
      "sack",
      "grain-sacking",
      "mandi",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-stor-3",
    slug: "kotha-granary-room-storage-punjab",
    name_english: "Kotha (granary room)",
    name_sanskrit: "कोष्ठागार (Koṣṭhāgāra)",
    local_names: ["ਕੋਠਾ"],
    name_hindi: "कोठा",
    category: "volume",
    measurement_type: "Volume (utility)",
    sector: "storage-transport",
    origin: "Pan-Punjab generally",
    modern_equivalent: "Large variable capacity, several Maund of grain",
    conversion_formula:
      "Multiple Bora/Mound = 1 Kotha (variable by structure)",
    meaning:
      "The dedicated grain-storage room, often raised or brick-built, found on Punjabi farmhouses — larger and more substantial than the bamboo granaries of eastern India, reflecting Punjab's grain-surplus wheat economy",
    historical_period:
      "British colonial period (Punjab annexed 1849) through post-1947/1966 Indian administration; British canal-colony settlement era (late 19th–early 20th century) for the Murabba unit specifically",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "The dedicated grain-storage room, often raised or brick-built, found on Punjabi farmhouses — larger and more substantial than the bamboo granaries of eastern India, reflecting Punjab's grain-surplus wheat economy",
      "Storage & Transportation",
    ],
    references: ["https://en.wikipedia.org/wiki/Granary"],
    tags: [
      "punjab",
      "traditional-units",
      "storage-transport",
      "kotha",
      "granary-room",
      "brick-granary",
      "wheat-surplus",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-stor-4",
    slug: "kos-grand-trunk-road-reckoning-storage-punjab",
    name_english: "Kos (Grand Trunk Road reckoning)",
    name_sanskrit: "क्रोश (Krośa)",
    local_names: ["ਕੋਹ"],
    name_hindi: "कोस",
    category: "length",
    measurement_type: "Distance",
    sector: "storage-transport",
    origin: "Pan-Punjab generally",
    modern_equivalent: "~3.2 km",
    conversion_formula: "1 Kos = traditional travel sub-unit",
    meaning:
      "Distance-staging unit for caravan and cart transport of grain and goods along the Lahore-Amritsar-Jalandhar stretch of the Grand Trunk Road",
    historical_period:
      "Delhi Sultanate–Mughal period (13th–18th century CE), preceding Sikh rule",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Distance-staging unit for caravan and cart transport of grain and goods along the Lahore-Amritsar-Jalandhar stretch of the Grand Trunk Road",
      "Storage & Transportation",
    ],
    references: ["https://en.wikipedia.org/wiki/Grand_Trunk_Road"],
    tags: [
      "punjab",
      "traditional-units",
      "storage-transport",
      "kos",
      "grand-trunk-road",
      "cart-transport",
      "grain-staging",
    ],
    created_at: "2024-01-01",
  },

  // ─── 9. Religious & Cultural (5 units) ───────────────────────────────────────
  {
    id: "punjab-rel-1",
    slug: "nadika-ghatika-muhurta-religious-punjab",
    name_english: "Nadika (Ghatika) / Muhurta (classical reference)",
    name_sanskrit: "नाडिका / मुहूर्त (Nāḍikā / Muhūrta)",
    local_names: ["ਘੜੀ / ਮੁਹੂਰਤ"],
    name_hindi: "नाड़ी / मुहूर्त",
    category: "time",
    measurement_type: "Time",
    sector: "religious-cultural",
    origin: "Pan-Punjab generally",
    modern_equivalent: "~24 minutes (Nadika); ~48 minutes (Muhurta)",
    conversion_formula: "2 Nadika = 1 Muhurta",
    meaning:
      "Pre-Sikh Hindu ritual-timing units still referenced for some pre-Sikh-era temple and Hindu Punjabi household rituals",
    historical_period:
      "Vedic–Classical Sanskrit period (c. 1000 BCE–500 CE), continued through the medieval era",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Pre-Sikh Hindu ritual-timing units still referenced for some pre-Sikh-era temple and Hindu Punjabi household rituals",
      "Religious & Cultural",
    ],
    references: ["https://en.wikipedia.org/wiki/Muhurta"],
    tags: [
      "punjab",
      "traditional-units",
      "religious-cultural",
      "nadika",
      "ghatika",
      "muhurta",
      "ritual-timing",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-rel-2",
    slug: "nanakshahi-calendar-religious-punjab",
    name_english:
      "Nanakshahi calendar (Bikrami-to-solar reform) — a calendar system, not a subdivided unit",
    name_sanskrit: "N/A — a calendar reform, not a hierarchical unit",
    local_names: ["ਨਾਨਕਸ਼ਾਹੀ ਕੈਲੰਡਰ"],
    name_hindi: "नानकशाही कैलेंडर",
    category: "time",
    measurement_type: "Calendar (solar-year system)",
    sector: "religious-cultural",
    origin: "Pan-Punjab generally",
    modern_equivalent:
      "A tropical solar calendar with epoch year 1 = 1469 CE (Guru Nanak's birth), adopted by the SGPC in 2003 to replace the lunar Bikrami calendar for fixing Sikh Gurpurb (anniversary) dates",
    conversion_formula:
      "Not a subdivided unit — a standalone calendar reform, distinct from (and, confusingly, sharing its name with) the historical Nanakshahi silver Rupee coin",
    meaning:
      "Intended to fix major Sikh anniversaries — the birth of Guru Nanak, Baisakhi, and Guru Gobind Singh's founding of the Khalsa in 1699 — to the same solar date every year rather than a shifting lunar one; adoption has been debated and only partially implemented",
    historical_period:
      "Adopted 2003 CE by the Shiromani Gurdwara Parbandhak Committee (SGPC)",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Intended to fix major Sikh anniversaries — the birth of Guru Nanak, Baisakhi, and Guru Gobind Singh's founding of the Khalsa in 1699 — to the same solar date every year rather than a shifting lunar one; adoption has been debated and only partially implemented",
      "Religious & Cultural",
    ],
    references: [
      "https://en.wikipedia.org/wiki/Nanakshahi_calendar",
      "https://en.wikipedia.org/wiki/Vaisakhi",
    ],
    tags: [
      "punjab",
      "traditional-units",
      "religious-cultural",
      "nanakshahi-calendar",
      "sgpc",
      "solar-calendar",
      "gurpurb",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-rel-3",
    slug: "vaisakhi-baisakhi-religious-punjab",
    name_english:
      "Vaisakhi (Baisakhi) — a fixed solar-calendar festival date",
    name_sanskrit: "N/A — a fixed annual date, not a subdivided unit",
    local_names: ["ਵਿਸਾਖੀ"],
    name_hindi: "वैसाखी",
    category: "time",
    measurement_type: "Calendar (harvest/religious festival marker)",
    sector: "religious-cultural",
    origin: "Pan-Punjab generally",
    modern_equivalent:
      "Falls on 13 or 14 April each year, marking the solar new year in the Punjabi Bikrami calendar as well as the wheat harvest season",
    conversion_formula:
      "Not applicable — a single annual calendar marker",
    meaning:
      "Both Punjab's principal wheat harvest festival and the anniversary of Guru Gobind Singh's founding of the Khalsa Panth at Anandpur Sahib in 1699 — Phulkari dupattas are traditionally worn for the accompanying Gidda folk dance",
    historical_period:
      "Ancient–Puranic period; Sikh tradition from the 15th century CE (Guru Nanak) onward",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Both Punjab's principal wheat harvest festival and the anniversary of Guru Gobind Singh's founding of the Khalsa Panth at Anandpur Sahib in 1699 — Phulkari dupattas are traditionally worn for the accompanying Gidda folk dance",
      "Religious & Cultural",
    ],
    references: [
      "https://en.wikipedia.org/wiki/Nanakshahi_calendar",
      "https://en.wikipedia.org/wiki/Vaisakhi",
    ],
    tags: [
      "punjab",
      "traditional-units",
      "religious-cultural",
      "vaisakhi",
      "baisakhi",
      "wheat-harvest",
      "khalsa",
      "anandpur-sahib",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-rel-4",
    slug: "gurpurb-dates-religious-punjab",
    name_english: "Gurpurb dates (Guru anniversaries)",
    name_sanskrit:
      "N/A — fixed or lunar-calculated anniversary dates, not a subdivided numeric unit",
    local_names: ["ਗੁਰਪੁਰਬ"],
    name_hindi: "गुरपर्व",
    category: "time",
    measurement_type: "Calendar (religious anniversary marker)",
    sector: "religious-cultural",
    origin: "Pan-Punjab generally",
    modern_equivalent:
      "Historically dated by the lunar Bikrami calendar; the SGPC's 2003 Nanakshahi reform sought to fix them to solar dates instead",
    conversion_formula:
      "Not applicable — anniversary dates rather than a subdivided time unit",
    meaning:
      "The commemorations of the birth or martyrdom of the ten Sikh Gurus, observed at gurdwaras across Punjab with an Akhand Path (unbroken 48-hour reading of the Guru Granth Sahib) — itself a striking example of a ritual defined by continuous elapsed time rather than a subdivided unit",
    historical_period:
      "Ancient–Puranic period; Sikh tradition from the 15th century CE (Guru Nanak) onward",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "The commemorations of the birth or martyrdom of the ten Sikh Gurus, observed at gurdwaras across Punjab with an Akhand Path (unbroken 48-hour reading of the Guru Granth Sahib) — itself a striking example of a ritual defined by continuous elapsed time rather than a subdivided unit",
      "Religious & Cultural",
    ],
    references: [
      "https://en.wikipedia.org/wiki/Nanakshahi_calendar",
      "https://en.wikipedia.org/wiki/Vaisakhi",
    ],
    tags: [
      "punjab",
      "traditional-units",
      "religious-cultural",
      "gurpurb",
      "akhand-path",
      "guru-granth-sahib",
      "continuous-time",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-rel-5",
    slug: "kos-yojana-pilgrimage-distance-religious-punjab",
    name_english:
      "Kos / Yojana (pilgrimage distance, classical/general reference)",
    name_sanskrit: "क्रोश / योजन (Krośa / Yojana)",
    local_names: ["ਕੋਹ / ਯੋਜਨ"],
    name_hindi: "कोस / योजन",
    category: "length",
    measurement_type: "Distance",
    sector: "religious-cultural",
    origin: "Pan-Punjab generally",
    modern_equivalent: "~3.2 km (Kos); ~11–14.5 km (Yojana)",
    conversion_formula: "4 Krosha = 1 Yojana",
    meaning:
      "Pilgrimage-distance reckoning to the Harmandir Sahib (Golden Temple) at Amritsar and other Sikh and pre-Sikh Hindu sacred sites across Punjab",
    historical_period:
      "Ancient–Puranic period; Sikh tradition from the 15th century CE (Guru Nanak) onward",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Pilgrimage-distance reckoning to the Harmandir Sahib (Golden Temple) at Amritsar and other Sikh and pre-Sikh Hindu sacred sites across Punjab",
      "Religious & Cultural",
    ],
    references: ["https://en.wikipedia.org/wiki/Golden_Temple"],
    tags: [
      "punjab",
      "traditional-units",
      "religious-cultural",
      "kos",
      "yojana",
      "pilgrimage",
      "golden-temple",
      "amritsar",
    ],
    created_at: "2024-01-01",
  },

  // ─── 10. Trade & Commerce (5 units) ─────────────────────────────────────────
  {
    id: "punjab-trade-1",
    slug: "falus-trade-punjab",
    name_english: "Falus",
    name_sanskrit: "N/A (Persian-derived copper-coin term)",
    local_names: ["ਫਲੂਸ"],
    name_hindi: "फ़लूस",
    category: "currency",
    measurement_type: "Currency",
    sector: "trade-commerce",
    origin: "Lahore–Amritsar axis",
    modern_equivalent: "Copper coin, ~9.28 g",
    conversion_formula: "Smallest regular Sikh Empire coin denomination",
    meaning:
      "Petty bazaar transactions across the Sikh Empire's territories",
    historical_period:
      "Sikh Misl Confederacy period (from Banda Singh Bahadur's 1710 Gobindshahi coin) through the Sikh Empire of Maharaja Ranjit Singh (1799–1839) to British annexation in 1849",
    region_applicable:
      "Lahore–Amritsar axis — the Sikh Empire's political and mint centre",
    states: ["Punjab"],
    used_in: [
      "Petty bazaar transactions across the Sikh Empire's territories",
      "Trade & Commerce",
    ],
    references: [
      "https://www.sikhiwiki.org/index.php/Sikh_Coins",
      "https://www.livehistoryindia.com/story/living-culture/sikh-coins",
    ],
    tags: [
      "punjab",
      "traditional-units",
      "trade-commerce",
      "falus",
      "coinage",
      "sikh-empire",
      "amritsar",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-trade-2",
    slug: "dhela-taka-trade-punjab",
    name_english: "Dhela (Taka)",
    name_sanskrit: "N/A (vernacular copper coin term)",
    local_names: ["ਧੇਲਾ / ਟਕਾ"],
    name_hindi: "धेला / टका",
    category: "currency",
    measurement_type: "Currency",
    sector: "trade-commerce",
    origin: "Lahore–Amritsar axis",
    modern_equivalent: "Copper, fractional value below the Paisa",
    conversion_formula: "Sub-Paisa denomination",
    meaning:
      "Small daily-market transactions, made of copper like the Paisa",
    historical_period:
      "Sikh Misl Confederacy period (from Banda Singh Bahadur's 1710 Gobindshahi coin) through the Sikh Empire of Maharaja Ranjit Singh (1799–1839) to British annexation in 1849",
    region_applicable:
      "Lahore–Amritsar axis — the Sikh Empire's political and mint centre",
    states: ["Punjab"],
    used_in: [
      "Small daily-market transactions, made of copper like the Paisa",
      "Trade & Commerce",
    ],
    references: ["https://www.sikhiwiki.org/index.php/Sikh_Coins"],
    tags: [
      "punjab",
      "traditional-units",
      "trade-commerce",
      "dhela",
      "taka",
      "coinage",
      "sikh-empire",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-trade-3",
    slug: "paisa-trade-punjab",
    name_english: "Paisa",
    name_sanskrit: "N/A (vernacular copper coin term)",
    local_names: ["ਪੈਸਾ"],
    name_hindi: "पैसा",
    category: "currency",
    measurement_type: "Currency",
    sector: "trade-commerce",
    origin: "Lahore–Amritsar axis",
    modern_equivalent: "Copper coin",
    conversion_formula: "Lower denomination coin below the silver Rupee",
    meaning:
      "Everyday retail trade coin of the Sikh Empire; made of copper (while coins of lower denominations (dhela or falu and paisa) were made from copper)",
    historical_period:
      "Sikh Misl Confederacy period (from Banda Singh Bahadur's 1710 Gobindshahi coin) through the Sikh Empire of Maharaja Ranjit Singh (1799–1839) to British annexation in 1849",
    region_applicable:
      "Lahore–Amritsar axis — the Sikh Empire's political and mint centre",
    states: ["Punjab"],
    used_in: [
      "Everyday retail trade coin of the Sikh Empire; made of copper (while coins of lower denominations (dhela or falu and paisa) were made from copper)",
      "Trade & Commerce",
    ],
    references: ["https://www.sikhiwiki.org/index.php/Sikh_Coins"],
    tags: [
      "punjab",
      "traditional-units",
      "trade-commerce",
      "paisa",
      "copper-coin",
      "sikh-empire",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-trade-4",
    slug: "nanakshahi-rupee-trade-punjab",
    name_english: "Nanakshahi Rupee",
    name_sanskrit: "N/A (Sikh Empire term, honouring Guru Nanak)",
    local_names: ["ਨਾਨਕਸ਼ਾਹੀ ਰੁਪਈਆ"],
    name_hindi: "नानकशाही रुपया",
    category: "currency",
    measurement_type: "Currency",
    sector: "trade-commerce",
    origin: "Lahore–Amritsar axis",
    modern_equivalent: "~11–11.2 g silver",
    conversion_formula: "Standard high-value coin of the Sikh Empire's bazaar trade",
    meaning:
      "The principal trade coin, minted at Amritsar, Lahore, Multan, Kashmir (Srinagar) and Peshawar, bearing the Persian couplet crediting Guru Nanak and Guru Gobind Singh's sword for the Sikh state's authority, rather than any king's own name",
    historical_period:
      "Sikh Misl Confederacy period (from Banda Singh Bahadur's 1710 Gobindshahi coin) through the Sikh Empire of Maharaja Ranjit Singh (1799–1839) to British annexation in 1849",
    region_applicable:
      "Lahore–Amritsar axis — the Sikh Empire's political and mint centre",
    states: ["Punjab"],
    used_in: [
      "The principal trade coin, minted at Amritsar, Lahore, Multan, Kashmir (Srinagar) and Peshawar, bearing the Persian couplet crediting Guru Nanak and Guru Gobind Singh's sword for the Sikh state's authority, rather than any king's own name",
      "Trade & Commerce",
    ],
    references: [
      "https://www.mintageworld.com/media/detail/12829-ranjit-singhs-nanakshahi-couplet-coin/",
      "https://en.numista.com/catalogue/sikh_empire-1.html",
    ],
    tags: [
      "punjab",
      "traditional-units",
      "trade-commerce",
      "nanakshahi-rupee",
      "silver-coin",
      "ranjit-singh",
      "amritsar",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-trade-5",
    slug: "ser-mon-trade-punjab",
    name_english: "Ser / Mon (Seer/Maund)",
    name_sanskrit: "सेर / मन",
    local_names: ["ਸੇਰ / ਮਣ"],
    name_hindi: "सेर / मन",
    category: "weight",
    measurement_type: "Weight",
    sector: "trade-commerce",
    origin: "Pan-Punjab generally",
    modern_equivalent: "~0.93 kg Ser; 40 Ser = 1 Mon ≈ 37.3 kg",
    conversion_formula: "40 Ser = 1 Mon",
    meaning:
      "Standard bazaar weight for wheat, cotton and other bulk goods across Punjab's grain markets (mandis)",
    historical_period:
      "British colonial period (Punjab annexed 1849) through post-1947/1966 Indian administration; British canal-colony settlement era (late 19th–early 20th century) for the Murabba unit specifically",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Standard bazaar weight for wheat, cotton and other bulk goods across Punjab's grain markets (mandis)",
      "Trade & Commerce",
    ],
    references: [
      "https://grokipedia.com/page/Seer_(unit)",
      "https://en.wikipedia.org/wiki/Maund",
    ],
    tags: [
      "punjab",
      "traditional-units",
      "trade-commerce",
      "ser",
      "mon",
      "seer",
      "maund",
      "mandi",
    ],
    created_at: "2024-01-01",
  },

  // ─── 11. Textile & Handloom (4 units) ────────────────────────────────────────
  {
    id: "punjab-textile-1",
    slug: "named-phulkari-bagh-piece-textile-punjab",
    name_english:
      "(Named Phulkari/Bagh piece — garment-based reckoning)",
    name_sanskrit:
      "N/A — informal, garment-specific naming, no fixed length-unit hierarchy documented",
    local_names: ["ਫੁਲਕਾਰੀ / ਬਾਗ਼"],
    name_hindi: "फुलकारी / बाग़",
    category: "other",
    measurement_type: "Garment (type unit, not a length measure)",
    sector: "textile-handloom",
    origin: "Pan-Punjab generally",
    modern_equivalent:
      "One embroidered khaddar (hand-spun cotton) panel, individually sized to its purpose",
    conversion_formula:
      "No standardised hierarchy — reckoned by named piece and occasion, not by length",
    meaning:
      "Punjab's iconic embroidery tradition names its pieces by occasion and pattern rather than by a length unit: Bagh ('garden', fully covered), Chope (a double-sided shawl gifted by the maternal grandmother before a wedding), Vari-da-Bagh (gifted by the groom's family), Sainchi (storytelling motifs of village life, native to Bathinda/Faridkot), Thirma (white based, worn by older women), and Darshan Dwar (donated to gurdwaras on fulfilment of a wish)",
    historical_period: "Traditional/folk usage, continuing into the present day",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Punjab's iconic embroidery tradition names its pieces by occasion and pattern rather than by a length unit: Bagh ('garden', fully covered), Chope (a double-sided shawl gifted by the maternal grandmother before a wedding), Vari-da-Bagh (gifted by the groom's family), Sainchi (storytelling motifs of village life, native to Bathinda/Faridkot), Thirma (white based, worn by older women), and Darshan Dwar (donated to gurdwaras on fulfilment of a wish)",
      "Textile & Handloom",
    ],
    references: [
      "https://www.fibre2fashion.com/industry-article/10500/phulkari-embroidery-a-complete-guide-to-punjab-s-iconic-textile-art-history-types-styling",
      "https://www.memeraki.com/blogs/posts/phulkari-the-embroidery-tradition-from-punjab",
    ],
    tags: [
      "punjab",
      "traditional-units",
      "textile-handloom",
      "phulkari",
      "bagh",
      "khaddar",
      "embroidery",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-textile-2",
    slug: "karam-cloth-trade-textile-punjab",
    name_english: "Karam (cloth-trade reference)",
    name_sanskrit: "N/A (vernacular survey/trade term)",
    local_names: ["ਕਰਮ"],
    name_hindi: "करम",
    category: "length",
    measurement_type: "Length",
    sector: "textile-handloom",
    origin: "Pan-Punjab generally",
    modern_equivalent: "5.5 ft (1.8333 yard)",
    conversion_formula: "1 Karam = 5.5 ft",
    meaning:
      "Occasionally used as a rough length reference for coarse khaddar cloth before it was cut and embroidered",
    historical_period:
      "British colonial period (Punjab annexed 1849) through post-1947/1966 Indian administration; British canal-colony settlement era (late 19th–early 20th century) for the Murabba unit specifically",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Occasionally used as a rough length reference for coarse khaddar cloth before it was cut and embroidered",
      "Textile & Handloom",
    ],
    references: [
      "https://en.wikipedia.org/wiki/Measurement_of_land_in_Punjab",
    ],
    tags: [
      "punjab",
      "traditional-units",
      "textile-handloom",
      "karam",
      "khaddar",
      "cloth-trade",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-textile-3",
    slug: "gaz-textile-punjab",
    name_english: "Gaz",
    name_sanskrit: "गज (Gaja)",
    local_names: ["ਗਜ਼"],
    name_hindi: "गज",
    category: "length",
    measurement_type: "Length",
    sector: "textile-handloom",
    origin: "Pan-Punjab generally",
    modern_equivalent: "~0.83–0.91 m",
    conversion_formula: "16 Girah = 1 Gaz",
    meaning:
      "Standard cloth trade measure for cotton and silk fabric in Punjab's bazaars, alongside the coarser khaddar-based Phulkari tradition",
    historical_period:
      "Delhi Sultanate–Mughal period (13th–18th century CE), preceding Sikh rule",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Standard cloth trade measure for cotton and silk fabric in Punjab's bazaars, alongside the coarser khaddar-based Phulkari tradition",
      "Textile & Handloom",
    ],
    references: ["https://en.wikipedia.org/wiki/Guz"],
    tags: [
      "punjab",
      "traditional-units",
      "textile-handloom",
      "gaz",
      "girah",
      "cloth-measure",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-textile-4",
    slug: "tola-bullion-reference-textile-punjab",
    name_english: "Tola (bullion reference)",
    name_sanskrit: "तोला (Tola)",
    local_names: ["ਤੋਲਾ"],
    name_hindi: "तोला",
    category: "weight",
    measurement_type: "Weight",
    sector: "textile-handloom",
    origin: "Pan-Punjab generally",
    modern_equivalent: "~11.66 g",
    conversion_formula: "12 Masha = 1 Tola",
    meaning:
      "Weighing gold and silver (zari) thread used in high-value ceremonial embroidery commissions",
    historical_period:
      "Vedic–Classical Sanskrit period (c. 1000 BCE–500 CE), continued through the medieval era",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Weighing gold and silver (zari) thread used in high-value ceremonial embroidery commissions",
      "Textile & Handloom",
    ],
    references: ["https://en.wikipedia.org/wiki/Tola_(unit)"],
    tags: [
      "punjab",
      "traditional-units",
      "textile-handloom",
      "tola",
      "zari",
      "bullion",
      "embroidery",
    ],
    created_at: "2024-01-01",
  },

  // ─── 12. Medicine (Ayurveda) (5 units) ──────────────────────────────────────
  {
    id: "punjab-med-1",
    slug: "ratti-medicine-punjab",
    name_english: "Ratti",
    name_sanskrit: "रत्ति / रक्तिका (Ratti / Raktikā)",
    local_names: ["ਰੱਤੀ"],
    name_hindi: "रत्ती",
    category: "weight",
    measurement_type: "Weight",
    sector: "medicine",
    origin: "Pan-Punjab generally",
    modern_equivalent: "~0.1215 g",
    conversion_formula: "Base / smallest unit",
    meaning:
      "Smallest dosage unit for herbo-mineral formulations, used by both Ayurvedic Vaids and, reflecting Punjab's centuries of Mughal-era administration, Unani Hakims practising alongside them",
    historical_period:
      "Vedic–Classical Sanskrit period (c. 1000 BCE–500 CE), continued through the medieval era",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Smallest dosage unit for herbo-mineral formulations, used by both Ayurvedic Vaids and, reflecting Punjab's centuries of Mughal-era administration, Unani Hakims practising alongside them",
      "Medicine (Ayurveda)",
    ],
    references: ["https://en.wikipedia.org/wiki/Ratti_(unit)"],
    tags: [
      "punjab",
      "traditional-units",
      "medicine",
      "ayurveda",
      "unani",
      "ratti",
      "dosage",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-med-2",
    slug: "masha-medicine-punjab",
    name_english: "Masha",
    name_sanskrit: "माष (Māṣa)",
    local_names: ["ਮਾਸ਼ਾ"],
    name_hindi: "माशा",
    category: "weight",
    measurement_type: "Weight",
    sector: "medicine",
    origin: "Pan-Punjab generally",
    modern_equivalent: "~0.97 g",
    conversion_formula: "8 Ratti = 1 Masha",
    meaning: "Powder (churna) dosage in classical Ayurvedic prescription",
    historical_period:
      "Vedic–Classical Sanskrit period (c. 1000 BCE–500 CE), continued through the medieval era",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Powder (churna) dosage in classical Ayurvedic prescription",
      "Medicine (Ayurveda)",
    ],
    references: ["https://www.wisdomlib.org/concept/masha"],
    tags: [
      "punjab",
      "traditional-units",
      "medicine",
      "ayurveda",
      "masha",
      "churna",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-med-3",
    slug: "karsha-medicine-punjab",
    name_english: "Karsha",
    name_sanskrit: "कर्ष (Karṣa)",
    local_names: ["ਕਰਸ਼"],
    name_hindi: "कर्ष",
    category: "weight",
    measurement_type: "Weight",
    sector: "medicine",
    origin: "Pan-Punjab generally",
    modern_equivalent: "~12 g",
    conversion_formula: "12 Masha = 1 Karsha",
    meaning: "Weighing herbal powders and churnas",
    historical_period:
      "Vedic–Classical Sanskrit period (c. 1000 BCE–500 CE), continued through the medieval era",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Weighing herbal powders and churnas",
      "Medicine (Ayurveda)",
    ],
    references: ["https://www.wisdomlib.org/concept/karsha"],
    tags: [
      "punjab",
      "traditional-units",
      "medicine",
      "ayurveda",
      "karsha",
      "herbal",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-med-4",
    slug: "pala-medicine-punjab",
    name_english: "Pala",
    name_sanskrit: "पल (Pala)",
    local_names: ["ਪਲ"],
    name_hindi: "पल",
    category: "weight",
    measurement_type: "Weight",
    sector: "medicine",
    origin: "Pan-Punjab generally",
    modern_equivalent: "~48 g",
    conversion_formula: "4 Karsha = 1 Pala",
    meaning:
      "Measuring bulk herbal ingredients for decoctions and medicated oils",
    historical_period:
      "Vedic–Classical Sanskrit period (c. 1000 BCE–500 CE), continued through the medieval era",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Measuring bulk herbal ingredients for decoctions and medicated oils",
      "Medicine (Ayurveda)",
    ],
    references: ["https://www.wisdomlib.org/concept/pala"],
    tags: [
      "punjab",
      "traditional-units",
      "medicine",
      "ayurveda",
      "pala",
      "decoction",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-med-5",
    slug: "kudava-medicine-punjab",
    name_english: "Kudava",
    name_sanskrit: "कुडव (Kuḍava)",
    local_names: ["ਕੁੜਵ"],
    name_hindi: "कुड़व",
    category: "volume",
    measurement_type: "Volume",
    sector: "medicine",
    origin: "Pan-Punjab generally",
    modern_equivalent: "~192 ml",
    conversion_formula: "4 Kudava = 1 Prastha",
    meaning: "Measuring liquid decoctions and medicated oils",
    historical_period:
      "Vedic–Classical Sanskrit period (c. 1000 BCE–500 CE), continued through the medieval era",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Measuring liquid decoctions and medicated oils",
      "Medicine (Ayurveda)",
    ],
    references: ["https://www.wisdomlib.org/definition/kudava"],
    tags: [
      "punjab",
      "traditional-units",
      "medicine",
      "ayurveda",
      "kudava",
      "liquid-decoction",
    ],
    created_at: "2024-01-01",
  },

  // ─── 13. Construction & Architecture (3 units) ─────────────────────────────
  {
    id: "punjab-arch-1",
    slug: "angula-architecture-punjab",
    name_english: "Angula",
    name_sanskrit: "अङ्गुल (Aṅgula)",
    local_names: ["ਅੰਗੁਲ"],
    name_hindi: "अंगुल",
    category: "length",
    measurement_type: "Length",
    sector: "architecture",
    origin: "Pan-Punjab generally",
    modern_equivalent: "~1.9 cm",
    conversion_formula: "Base unit, 24 Angula = 1 Hasta",
    meaning:
      "Fine calibration of brick and stone dimensions in pre-Sikh, Mughal-period construction",
    historical_period:
      "Vedic–Classical Sanskrit period (c. 1000 BCE–500 CE), continued through the medieval era",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Fine calibration of brick and stone dimensions in pre-Sikh, Mughal-period construction",
      "Construction & Architecture",
    ],
    references: ["https://en.wikipedia.org/wiki/A%E1%B9%85gula"],
    tags: [
      "punjab",
      "traditional-units",
      "architecture",
      "angula",
      "hasta",
      "mughal-period",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-arch-2",
    slug: "karam-architecture-punjab",
    name_english: "Karam",
    name_sanskrit: "N/A (vernacular survey/construction term)",
    local_names: ["ਕਰਮ"],
    name_hindi: "करम",
    category: "length",
    measurement_type: "Length",
    sector: "architecture",
    origin: "Lahore–Amritsar axis",
    modern_equivalent:
      "5.5 ft (British-standardised value); regionally 54–66 inches depending on district (see Land Measurement)",
    conversion_formula:
      "1 Karam = 5.5 ft in the standardised system, base unit of the entire Punjab land and building survey chain",
    meaning:
      "The working measuring rod length for laying out havelis, city gates and fort walls, including the Sikh Empire's rebuilding and gilding of the Harmandir Sahib (Golden Temple) at Amritsar under Maharaja Ranjit Singh",
    historical_period:
      "Sikh Misl Confederacy period (from Banda Singh Bahadur's 1710 Gobindshahi coin) through the Sikh Empire of Maharaja Ranjit Singh (1799–1839) to British annexation in 1849",
    region_applicable:
      "Lahore–Amritsar axis — the Sikh Empire's political and mint centre",
    states: ["Punjab"],
    used_in: [
      "The working measuring rod length for laying out havelis, city gates and fort walls, including the Sikh Empire's rebuilding and gilding of the Harmandir Sahib (Golden Temple) at Amritsar under Maharaja Ranjit Singh",
      "Construction & Architecture",
    ],
    references: ["https://en.wikipedia.org/wiki/Golden_Temple"],
    tags: [
      "punjab",
      "traditional-units",
      "architecture",
      "karam",
      "golden-temple",
      "ranjit-singh",
      "amritsar",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "punjab-arch-3",
    slug: "marla-construction-reference-punjab",
    name_english: "Marla (construction reference)",
    name_sanskrit: "N/A (vernacular revenue term)",
    local_names: ["ਮਰਲਾ"],
    name_hindi: "मरला",
    category: "area",
    measurement_type: "Area",
    sector: "architecture",
    origin: "Pan-Punjab generally",
    modern_equivalent: "272.25 sq ft (9 Sarsahi)",
    conversion_formula: "9 Sarsahi = 1 Marla; 20 Marla = 1 Kanal",
    meaning:
      "Still the standard plot-size unit quoted for urban and rural house construction across Punjab today, more so than in almost any other Indian state",
    historical_period:
      "British colonial period (Punjab annexed 1849) through post-1947/1966 Indian administration; British canal-colony settlement era (late 19th–early 20th century) for the Murabba unit specifically",
    region_applicable: "Pan-Punjab generally",
    states: ["Punjab"],
    used_in: [
      "Still the standard plot-size unit quoted for urban and rural house construction across Punjab today, more so than in almost any other Indian state",
      "Construction & Architecture",
    ],
    references: [
      "https://en.wikipedia.org/wiki/Measurement_of_land_in_Punjab",
    ],
    tags: [
      "punjab",
      "traditional-units",
      "architecture",
      "marla",
      "sarsahi",
      "kanal",
      "plot-size",
    ],
    created_at: "2024-01-01",
  },
];
