import { Measurement } from "@/types";

export const RAJASTHAN_MEASUREMENTS: Measurement[] = [
  // Land Measurement
  {
    id: "rj-land-1",
    slug: "rj-biswa",
    name_english: "Biswa",
    name_hindi: "बिस्वा",
    local_names: ["बिस्वा (Biswa)"],
    meaning: "Traditional sub-unit of land area.",
    category: "area",
    sector: "land-measurement",
    modern_equivalent: "≈126.5 sq meters",
    conversion_formula: "20 Biswansi = 1 Biswa",
    states: ["Rajasthan"],
    used_in: ["Revenue records and agricultural plots"],
    references: ["Rajasthan Land Revenue Act"],
  },
  {
    id: "rj-land-2",
    slug: "rj-bigha",
    name_english: "Bigha (Kachha and Pucca)",
    name_hindi: "बीघा",
    local_names: ["बीघा (Bigha)"],
    meaning: "Standard agricultural land unit.",
    category: "area",
    sector: "land-measurement",
    modern_equivalent: "≈2530 sq meters (Pucca Bigha)",
    conversion_formula: "20 Biswa = 1 Bigha",
    states: ["Rajasthan"],
    used_in: ["Farming and land sales"],
    references: ["Rajasthan Tenancy Act"],
  },

  // Trade & Commerce
  {
    id: "rj-trade-1",
    slug: "rj-tola-trade",
    name_english: "Tola",
    name_hindi: "तोला",
    local_names: ["तोला (Tola)"],
    meaning: "Standard weight for precious items and spices.",
    category: "weight",
    sector: "trade-commerce",
    modern_equivalent: "≈11.66 g",
    conversion_formula: "12 Masha = 1 Tola",
    states: ["Rajasthan"],
    used_in: ["Jewellery, spice trading"],
    references: ["Marwari Trade Records"],
  },
  {
    id: "rj-trade-2",
    slug: "rj-seer-trade",
    name_english: "Seer",
    name_hindi: "सेर",
    local_names: ["सेर (Seer)"],
    meaning: "Common market weight.",
    category: "weight",
    sector: "trade-commerce",
    modern_equivalent: "≈0.933 kg",
    conversion_formula: "Base market unit",
    states: ["Rajasthan"],
    used_in: ["Grocery, wholesale"],
    references: ["Rajputana Gazetteers"],
  },
  {
    id: "rj-trade-3",
    slug: "rj-maund-trade",
    name_english: "Maund (Man)",
    name_hindi: "मन",
    local_names: ["मन (Man)"],
    meaning: "Bulk trading weight.",
    category: "weight",
    sector: "trade-commerce",
    modern_equivalent: "≈37.324 kg",
    conversion_formula: "40 Seer = 1 Maund",
    states: ["Rajasthan"],
    used_in: ["Grain mandis, cotton trade"],
    references: ["Rajputana Gazetteers"],
  },

  // Transportation & Distance
  {
    id: "rj-trans-1",
    slug: "rj-kos",
    name_english: "Kos (Krosha)",
    name_hindi: "कोस",
    local_names: ["कोस (Kos)"],
    meaning: "Distance between villages.",
    category: "length",
    sector: "transportation-distance",
    modern_equivalent: "≈3.2 km",
    conversion_formula: "Standard traditional distance",
    states: ["Rajasthan"],
    used_in: ["Travel and route planning in desert areas"],
    references: ["Mughal & Rajput records"],
  },

  // Textile & Handloom
  {
    id: "rj-tex-1",
    slug: "rj-hath-tex",
    name_english: "Hath",
    name_hindi: "हाथ",
    local_names: ["हाथ (Hath)"],
    meaning: "Cubit for measuring cloth.",
    category: "length",
    sector: "textile-handloom",
    modern_equivalent: "≈45.7 cm",
    conversion_formula: "1 Hath = 24 Angul",
    states: ["Rajasthan"],
    used_in: ["Handloom and textile markets"],
    references: ["Traditional weavers' records"],
  },
  {
    id: "rj-tex-2",
    slug: "rj-gaj-tex",
    name_english: "Gaj",
    name_hindi: "गज़",
    local_names: ["गज़ (Gaj)"],
    meaning: "Standard yard for cloth.",
    category: "length",
    sector: "textile-handloom",
    modern_equivalent: "≈0.9144 m",
    conversion_formula: "2 Hath = 1 Gaj",
    states: ["Rajasthan"],
    used_in: ["Tailoring and textile retail"],
    references: ["Market standards"],
  },

  // Currency & Money
  {
    id: "rj-cur-1",
    slug: "rj-taka-cur",
    name_english: "Taka",
    name_hindi: "टका",
    local_names: ["टका (Taka)"],
    meaning: "Historical copper coin.",
    category: "currency",
    sector: "currency-money",
    modern_equivalent: "Historical",
    conversion_formula: "Fractional currency",
    states: ["Rajasthan"],
    used_in: ["Everyday transactions in princely states"],
    references: ["Rajputana Numismatics"],
  },
  {
    id: "rj-cur-2",
    slug: "rj-rupiya-cur",
    name_english: "Rupiya",
    name_hindi: "रुपिया",
    local_names: ["रुपिया (Rupiya)"],
    meaning: "Silver standard coin.",
    category: "currency",
    sector: "currency-money",
    modern_equivalent: "Historical",
    conversion_formula: "16 Anna = 1 Rupiya",
    states: ["Rajasthan"],
    used_in: ["Trade, taxation"],
    references: ["State Treasury Records"],
  },

  // Additional Authentic Land Measurement
  {
    id: "rj-land-3",
    slug: "rj-pucca-bigha",
    name_english: "Pucca Bigha",
    name_hindi: "पक्का बीघा",
    local_names: ["पक्का बीघा (Pucca Bigha)"],
    meaning: "Standardized Bigha in some regions.",
    category: "area",
    sector: "land-measurement",
    modern_equivalent: "≈27,225 sq.ft",
    conversion_formula: "Fixed-value Bigha system",
    states: ["Rajasthan"],
    used_in: ["Official revenue calculations"],
    references: ["Revenue surveys"],
  },
  {
    id: "rj-land-4",
    slug: "rj-killa",
    name_english: "Killa",
    name_hindi: "किल्ला",
    local_names: ["किल्ला (Killa)"],
    meaning: "Large farm measure.",
    category: "area",
    sector: "land-measurement",
    modern_equivalent: "≈1 Acre",
    conversion_formula: "Approximately equal to Acre in some regions",
    states: ["Rajasthan"],
    used_in: ["Agricultural holdings"],
    references: ["Regional practices"],
  },

  // Additional Authentic Transportation & Distance
  {
    id: "rj-trans-2",
    slug: "rj-kathi",
    name_english: "Kathi",
    name_hindi: "काठी",
    local_names: ["काठी (Kathi)"],
    meaning: "Wooden measuring stick used in villages.",
    category: "length",
    sector: "transportation-distance",
    modern_equivalent: "≈1.5–2 m",
    conversion_formula: "Regional variation",
    states: ["Rajasthan"],
    used_in: ["Used by traditional land surveyors"],
    references: ["Local survey traditions"],
  },
  {
    id: "rj-trans-3",
    slug: "rj-gavyuti",
    name_english: "Gavyuti",
    name_hindi: "गव्यूति",
    name_sanskrit: "Gavyūti",
    local_names: ["गव्यूति (Gavyuti)"],
    meaning: "Distance associated with cattle movement.",
    category: "length",
    sector: "transportation-distance",
    modern_equivalent: "≈10–12 km (varies)",
    conversion_formula: "Related to distance of cattle calling range",
    states: ["Rajasthan"],
    used_in: ["Pastoral and geographical descriptions"],
    references: ["Vedic literature"],
  },
  {
    id: "rj-trans-4",
    slug: "rj-yojana-trans",
    name_english: "Yojana",
    name_hindi: "योजन",
    name_sanskrit: "Yojanā",
    local_names: ["योजन (Yojana)"],
    meaning: "Largest classical Indian distance unit.",
    category: "length",
    sector: "transportation-distance",
    modern_equivalent: "≈12–15 km (varies)",
    conversion_formula: "1 Yojana = 4 Kos",
    states: ["Rajasthan"],
    used_in: ["Long journeys and kingdom descriptions"],
    references: ["Classical Sanskrit texts"],
  },

  // Livestock & Dairy
  {
    id: "rj-dairy-1",
    slug: "rj-payli-dairy",
    name_english: "Paili / Payli",
    name_hindi: "पायली",
    local_names: ["पायली (Payli)"],
    meaning: "Traditional vessel measurement.",
    category: "volume",
    sector: "livestock-dairy",
    modern_equivalent: "≈1.5–2 litres (varies)",
    conversion_formula: "Vessel based measure",
    states: ["Rajasthan"],
    used_in: ["Milk, grains and household liquids"],
    references: ["Local practices"],
  },
  {
    id: "rj-dairy-2",
    slug: "rj-matka-dairy",
    name_english: "Matka / Ghada",
    name_hindi: "मटका / घड़ा",
    name_sanskrit: "Ghaṭa",
    local_names: ["मटका (Matka)"],
    meaning: "Earthen pot-based dairy storage unit.",
    category: "volume",
    sector: "livestock-dairy",
    modern_equivalent: ">5–15 litres (varies)",
    conversion_formula: "Large container measure",
    states: ["Rajasthan"],
    used_in: ["Storing and transporting milk and buttermilk"],
    references: ["Village dairy traditions"],
  },
  {
    id: "rj-dairy-3",
    slug: "rj-handi-dairy",
    name_english: "Handi",
    name_hindi: "हांडी",
    local_names: ["हांडी (Handi)"],
    meaning: "Large household dairy container.",
    category: "volume",
    sector: "livestock-dairy",
    modern_equivalent: "Regional variation",
    conversion_formula: "Large vessel measure",
    states: ["Rajasthan"],
    used_in: ["Bulk milk, curd and ghee storage"],
    references: ["Local traditions"],
  },

  // Gold & Jewellery
  {
    id: "rj-gold-1",
    slug: "rj-gunja-gold",
    name_english: "Gunja",
    name_hindi: "गुंजा",
    name_sanskrit: "Guñjā",
    local_names: ["गुंजा (Gunja)"],
    meaning: "Smallest traditional weight based on seed.",
    category: "weight",
    sector: "gold-jewellery",
    modern_equivalent: "≈0.12 g",
    conversion_formula: "1 Gunja ≈ 1 Ratti",
    states: ["Rajasthan"],
    used_in: ["Natural seed standard for weighing gold"],
    references: ["Ancient Indian weight traditions"],
  },
  {
    id: "rj-gold-2",
    slug: "rj-dharana-gold",
    name_english: "Dharana",
    name_hindi: "धरण",
    name_sanskrit: "Dharaṇa",
    local_names: ["धरण (Dharana)"],
    meaning: "Ancient precious metal weight unit.",
    category: "weight",
    sector: "gold-jewellery",
    modern_equivalent: "≈3–4 g (varies)",
    conversion_formula: "Related to Masha and Ratti system",
    states: ["Rajasthan"],
    used_in: ["Classical jewellery calculations"],
    references: ["Sanskrit measurement references"],
  },
  {
    id: "rj-gold-3",
    slug: "rj-kori-gold",
    name_english: "Kori",
    name_hindi: "कोरी",
    local_names: ["कोरी (Kori)"],
    meaning: "Traditional monetary weight reference.",
    category: "weight",
    sector: "gold-jewellery",
    modern_equivalent: "Varies",
    conversion_formula: "Regional coin-based weight system",
    states: ["Rajasthan"],
    used_in: ["Western Indian trade networks"],
    references: ["Trade history"],
  },
  {
    id: "rj-gold-4",
    slug: "rj-vori-gold",
    name_english: "Vori / Bhori",
    name_hindi: "वोरी / भोरी",
    local_names: ["भोरी (Bhori)"],
    meaning: "Regional name for Tola.",
    category: "weight",
    sector: "gold-jewellery",
    modern_equivalent: "≈11.66 g",
    conversion_formula: "Generally equal to Tola",
    states: ["Rajasthan"],
    used_in: ["Traditional jewellers"],
    references: ["Regional practices"],
  },

  // Seed & Crop (Agriculture)
  {
    id: "rj-agri-1",
    slug: "rj-ser-agri",
    name_english: "Seer / Ser",
    name_hindi: "सेर",
    local_names: ["सेर (Ser)"],
    meaning: "Standard grain weight for agricultural produce.",
    category: "weight",
    sector: "agriculture",
    modern_equivalent: "≈0.933 kg",
    conversion_formula: "Base unit for agricultural weight",
    states: ["Rajasthan"],
    used_in: ["Harvest yields, seed sowing"],
    references: ["Rajputana Agricultural Records"],
  },
  {
    id: "rj-agri-2",
    slug: "rj-maund-agri",
    name_english: "Maund (Man)",
    name_hindi: "मन",
    local_names: ["मन (Man)"],
    meaning: "Bulk crop weight.",
    category: "weight",
    sector: "agriculture",
    modern_equivalent: "≈37.324 kg",
    conversion_formula: "40 Seer = 1 Maund",
    states: ["Rajasthan"],
    used_in: ["Wholesale grain mandis"],
    references: ["Revenue records"],
  },

  // Medicine (Ayurveda)
  {
    id: "rj-med-1",
    slug: "rj-ratti-med",
    name_english: "Ratti",
    name_hindi: "रत्ती",
    name_sanskrit: "Raktikā",
    local_names: ["रत्ती (Ratti)"],
    meaning: "Smallest medicinal dose.",
    category: "weight",
    sector: "medicine",
    modern_equivalent: "≈121.5 mg",
    conversion_formula: "Base Unit",
    states: ["Rajasthan"],
    used_in: ["Ayurvedic powders, Bhasma"],
    references: ["Charaka Samhita"],
  },
  {
    id: "rj-med-2",
    slug: "rj-masha-med",
    name_english: "Masha",
    name_hindi: "माशा",
    name_sanskrit: "Māṣa",
    local_names: ["माशा (Masha)"],
    meaning: "Standard Ayurvedic weight.",
    category: "weight",
    sector: "medicine",
    modern_equivalent: "≈0.972 g",
    conversion_formula: "8 Ratti = 1 Masha",
    states: ["Rajasthan"],
    used_in: ["Herbal medicines"],
    references: ["Ayurvedic pharmacopoeia"],
  },

  // Construction & Architecture
  {
    id: "rj-arch-1",
    slug: "rj-gaj-arch",
    name_english: "Gaj",
    name_hindi: "गज़",
    name_sanskrit: "Gaja",
    local_names: ["गज़ (Gaj)"],
    meaning: "Yard used for building dimensions.",
    category: "length",
    sector: "architecture",
    modern_equivalent: "≈0.9144 m",
    conversion_formula: "Regional standard",
    states: ["Rajasthan"],
    used_in: ["Fort and haveli architecture"],
    references: ["Vastu Shilpa texts"],
  },
  {
    id: "rj-arch-2",
    slug: "rj-angul-arch",
    name_english: "Angul",
    name_hindi: "अंगुल",
    name_sanskrit: "Aṅgula",
    local_names: ["अंगुल (Angul)"],
    meaning: "Finger-width for fine carving.",
    category: "length",
    sector: "architecture",
    modern_equivalent: "≈1.9 cm",
    conversion_formula: "Base Unit",
    states: ["Rajasthan"],
    used_in: ["Stone carving, jharokha design"],
    references: ["Traditional stone masons"],
  },

  // Household & Daily Life
  {
    id: "rj-hh-1",
    slug: "rj-pao-hh",
    name_english: "Pao / Pav",
    name_hindi: "पाव",
    local_names: ["पाव (Pav)"],
    meaning: "Quarter seer for daily groceries.",
    category: "weight",
    sector: "household",
    modern_equivalent: "≈233 g",
    conversion_formula: "1/4 Seer = 1 Pav",
    states: ["Rajasthan"],
    used_in: ["Daily kitchen supplies"],
    references: ["Household oral traditions"],
  },
  {
    id: "rj-hh-2",
    slug: "rj-chhatak-hh",
    name_english: "Chhatak",
    name_hindi: "छटाक",
    local_names: ["छटाक (Chhatak)"],
    meaning: "Small household unit.",
    category: "weight",
    sector: "household",
    modern_equivalent: "≈58.3 g",
    conversion_formula: "1/16 Seer = 1 Chhatak",
    states: ["Rajasthan"],
    used_in: ["Spices, lentils"],
    references: ["Traditional kitchen practices"],
  },

  // Storage & Transportation
  {
    id: "rj-storage-1",
    slug: "rj-bori-storage",
    name_english: "Bori / Sack",
    name_hindi: "बोरी",
    local_names: ["बोरी (Bori)"],
    meaning: "Standard sack for storage.",
    category: "volume",
    sector: "storage-transport",
    modern_equivalent: "≈100 kg (varies)",
    conversion_formula: "Vessel based measure",
    states: ["Rajasthan"],
    used_in: ["Godowns and transportation"],
    references: ["Mandis and transport records"],
  },

  // Religious & Cultural
  {
    id: "rj-relig-1",
    slug: "rj-muhurta-relig",
    name_english: "Muhurta",
    name_hindi: "मुहूर्त",
    name_sanskrit: "Muhūrta",
    local_names: ["मुहूर्त (Muhurta)"],
    meaning: "Auspicious time unit.",
    category: "time",
    sector: "religious-cultural",
    modern_equivalent: "48 minutes",
    conversion_formula: "1 Muhurta = 2 Ghati",
    states: ["Rajasthan"],
    used_in: ["Panchang, temple rituals"],
    references: ["Jyotisha Shastra"],
  },
  {
    id: "rj-relig-2",
    slug: "rj-ghati-relig",
    name_english: "Ghati",
    name_hindi: "घटी",
    name_sanskrit: "Ghaṭī",
    local_names: ["घटी (Ghati)"],
    meaning: "Traditional unit of time.",
    category: "time",
    sector: "religious-cultural",
    modern_equivalent: "24 minutes",
    conversion_formula: "60 Ghati = 1 Day",
    states: ["Rajasthan"],
    used_in: ["Astrology, daily temple schedule"],
    references: ["Panchang calculations"],
  }
];
