import { Measurement } from "@/types";

export const TAMILNADU_MEASUREMENTS: Measurement[] = [
  // Land Measurement
  {
    id: "tn-land-1",
    slug: "tn-kani",
    name_english: "Kani",
    name_hindi: "காணி",
    local_names: ["காணி (Kani)"],
    meaning: "Traditional area measurement unit.",
    category: "area",
    sector: "land-measurement",
    modern_equivalent: "≈1.32 Acres",
    conversion_formula: "1 Kani = 100 Kuzhi",
    states: ["Tamil Nadu"],
    used_in: ["Agricultural land assessment"],
    references: ["Tamil Nadu Revenue Records"],
  },
  {
    id: "tn-land-2",
    slug: "tn-veli",
    name_english: "Veli",
    name_hindi: "வேலி",
    local_names: ["வேலி (Veli)"],
    meaning: "Large land area measurement.",
    category: "area",
    sector: "land-measurement",
    modern_equivalent: "≈6.6 Acres",
    conversion_formula: "1 Veli = 5 Kani",
    states: ["Tamil Nadu"],
    used_in: ["Large agricultural holdings"],
    references: ["Chola Inscriptions"],
  },
  {
    id: "tn-land-3",
    slug: "tn-kuzhi",
    name_english: "Kuzhi",
    name_hindi: "குழி",
    local_names: ["குழி (Kuzhi)"],
    meaning: "Small land area unit.",
    category: "area",
    sector: "land-measurement",
    modern_equivalent: "≈576 sq.ft",
    conversion_formula: "100 Kuzhi = 1 Kani",
    states: ["Tamil Nadu"],
    used_in: ["House plots, small fields"],
    references: ["Traditional surveying"],
  },

  // Trade & Commerce
  {
    id: "tn-trade-1",
    slug: "tn-palam",
    name_english: "Palam",
    name_hindi: "பலம்",
    local_names: ["பலம் (Palam)"],
    meaning: "Traditional weight measure.",
    category: "weight",
    sector: "trade-commerce",
    modern_equivalent: "≈35 g",
    conversion_formula: "Variable based on commodity",
    states: ["Tamil Nadu"],
    used_in: ["Grocery, hardware trade"],
    references: ["Tamil Markets"],
  },
  {
    id: "tn-trade-2",
    slug: "tn-viss",
    name_english: "Viss / Visam",
    name_hindi: "வீசம்",
    local_names: ["வீசம் (Visam)"],
    meaning: "Wholesale weight.",
    category: "weight",
    sector: "trade-commerce",
    modern_equivalent: "≈1.4 kg",
    conversion_formula: "1 Viss = 40 Palam",
    states: ["Tamil Nadu"],
    used_in: ["Vegetable and grocery wholesale"],
    references: ["Colonial trade records"],
  },

  // Transportation & Distance
  {
    id: "tn-trans-1",
    slug: "tn-kadham",
    name_english: "Kadham",
    name_hindi: "காதம்",
    local_names: ["காதம் (Kadham)"],
    meaning: "Traditional travel distance.",
    category: "length",
    sector: "transportation-distance",
    modern_equivalent: "≈16 km",
    conversion_formula: "4 Kaadham = 1 Yojana (Approx)",
    states: ["Tamil Nadu"],
    used_in: ["Journey distances"],
    references: ["Sangam literature"],
  },

  // Textile & Handloom
  {
    id: "tn-tex-1",
    slug: "tn-muzham",
    name_english: "Muzham",
    name_hindi: "முழம்",
    local_names: ["முழம் (Muzham)"],
    meaning: "Cubit (fingertip to elbow).",
    category: "length",
    sector: "textile-handloom",
    modern_equivalent: "≈45 cm",
    conversion_formula: "Base textile measure",
    states: ["Tamil Nadu"],
    used_in: ["Measuring silk sarees, jasmine flowers"],
    references: ["Kanchipuram weavers"],
  },

  // Currency & Money
  {
    id: "tn-cur-1",
    slug: "tn-kasu",
    name_english: "Kasu",
    name_hindi: "காசு",
    local_names: ["காசு (Kasu)"],
    meaning: "Small copper coin / generic money.",
    category: "currency",
    sector: "currency-money",
    modern_equivalent: "Historical",
    conversion_formula: "Smallest denomination",
    states: ["Tamil Nadu"],
    used_in: ["Daily transactions"],
    references: ["Chola and Pallava coins"],
  },
  {
    id: "tn-cur-2",
    slug: "tn-panam",
    name_english: "Panam",
    name_hindi: "பணம்",
    local_names: ["பணம் (Panam)"],
    meaning: "Standard gold or silver coin.",
    category: "currency",
    sector: "currency-money",
    modern_equivalent: "Historical",
    conversion_formula: "Standard currency",
    states: ["Tamil Nadu"],
    used_in: ["Major trade and taxation"],
    references: ["Madras Presidency"],
  },

  // Livestock & Dairy
  {
    id: "tn-dairy-1",
    slug: "tn-padi-dairy",
    name_english: "Padi",
    name_hindi: "படி",
    local_names: ["படி (Padi)"],
    meaning: "Standard volumetric measure.",
    category: "volume",
    sector: "livestock-dairy",
    modern_equivalent: "≈1.5 L",
    conversion_formula: "Base unit",
    states: ["Tamil Nadu"],
    used_in: ["Milk distribution"],
    references: ["Rural Tamil Nadu"],
  },

  // Gold & Jewellery
  {
    id: "tn-gold-1",
    slug: "tn-kalanju",
    name_english: "Kalanju",
    name_hindi: "கழஞ்சு",
    local_names: ["கழஞ்சு (Kalanju)"],
    meaning: "Ancient gold weight.",
    category: "weight",
    sector: "gold-jewellery",
    modern_equivalent: "≈4.5 to 5 g",
    conversion_formula: "Variable",
    states: ["Tamil Nadu"],
    used_in: ["Temple gold donations"],
    references: ["Thanjavur Temple Inscriptions"],
  },
  {
    id: "tn-gold-2",
    slug: "tn-manjadi",
    name_english: "Manjadi",
    name_hindi: "மஞ்சாடி",
    local_names: ["மஞ்சாடி (Manjadi)"],
    meaning: "Small seed-based weight.",
    category: "weight",
    sector: "gold-jewellery",
    modern_equivalent: "≈0.26 g",
    conversion_formula: "20 Manjadi = 1 Kalanju",
    states: ["Tamil Nadu"],
    used_in: ["Weighing precious stones"],
    references: ["Ancient jewellers"],
  },

  // Seed & Crop (Agriculture)
  {
    id: "tn-agri-1",
    slug: "tn-kalam",
    name_english: "Kalam",
    name_hindi: "கலம்",
    local_names: ["கலம் (Kalam)"],
    meaning: "Large volumetric grain measure.",
    category: "volume",
    sector: "agriculture",
    modern_equivalent: "≈36 L",
    conversion_formula: "1 Kalam = 12 Marakkal",
    states: ["Tamil Nadu"],
    used_in: ["Paddy harvest measurement"],
    references: ["Chola land grants"],
  },
  {
    id: "tn-agri-2",
    slug: "tn-kuruni",
    name_english: "Kuruni / Marakkal",
    name_hindi: "குறுணி",
    local_names: ["குறுணி (Kuruni)"],
    meaning: "Standard grain volume.",
    category: "volume",
    sector: "agriculture",
    modern_equivalent: "≈3 L",
    conversion_formula: "1 Kuruni = 2 Padakku",
    states: ["Tamil Nadu"],
    used_in: ["Village grain markets"],
    references: ["Tamil Literature"],
  },

  // Medicine (Ayurveda/Siddha)
  {
    id: "tn-med-1",
    slug: "tn-kundri",
    name_english: "Kundrimani",
    name_hindi: "குன்றிமணி",
    local_names: ["குன்றிமணி (Kundrimani)"],
    meaning: "Abrus precatorius seed weight.",
    category: "weight",
    sector: "medicine",
    modern_equivalent: "≈130 mg",
    conversion_formula: "Smallest medicinal base",
    states: ["Tamil Nadu"],
    used_in: ["Siddha medicine dosage"],
    references: ["Siddha texts"],
  },

  // Construction & Architecture
  {
    id: "tn-arch-1",
    slug: "tn-viral",
    name_english: "Viral",
    name_hindi: "விரல்",
    local_names: ["விரல் (Viral)"],
    meaning: "Finger width (Angula).",
    category: "length",
    sector: "architecture",
    modern_equivalent: "≈1.9 cm",
    conversion_formula: "Base unit for proportion",
    states: ["Tamil Nadu"],
    used_in: ["Dravidian temple architecture, Shilpa Shastras"],
    references: ["Mayamata, Manasara"],
  },

  // Household & Daily Life
  {
    id: "tn-hh-1",
    slug: "tn-uzhakku",
    name_english: "Uzhakku",
    name_hindi: "உழக்கு",
    local_names: ["உழக்கு (Uzhakku)"],
    meaning: "Small household volume.",
    category: "volume",
    sector: "household",
    modern_equivalent: "≈336 ml",
    conversion_formula: "4 Uzhakku = 1 Padi",
    states: ["Tamil Nadu"],
    used_in: ["Measuring daily rice for cooking"],
    references: ["Household kitchen traditions"],
  },
  {
    id: "tn-hh-2",
    slug: "tn-azhakku",
    name_english: "Azhakku",
    name_hindi: "ஆழாக்கு",
    local_names: ["ஆழாக்கு (Azhakku)"],
    meaning: "Very small volume measure.",
    category: "volume",
    sector: "household",
    modern_equivalent: "≈168 ml",
    conversion_formula: "2 Azhakku = 1 Uzhakku",
    states: ["Tamil Nadu"],
    used_in: ["Spices, dal measurement"],
    references: ["Traditional recipes"],
  },

  // Storage & Transportation
  {
    id: "tn-storage-1",
    slug: "tn-moodai",
    name_english: "Moodai / Mootai",
    name_hindi: "மூட்டை",
    local_names: ["மூட்டை (Mootai)"],
    meaning: "Standard sack or gunny bag.",
    category: "weight",
    sector: "storage-transport",
    modern_equivalent: "≈75 kg to 100 kg",
    conversion_formula: "Varies by grain",
    states: ["Tamil Nadu"],
    used_in: ["Transporting paddy and pulses"],
    references: ["Wholesale mandis"],
  },

  // Religious & Cultural
  {
    id: "tn-relig-1",
    slug: "tn-nazhigai",
    name_english: "Nazhigai",
    name_hindi: "நாழிகை",
    local_names: ["நாழிகை (Nazhigai)"],
    meaning: "Traditional time unit.",
    category: "time",
    sector: "religious-cultural",
    modern_equivalent: "24 minutes",
    conversion_formula: "60 Nazhigai = 1 Day",
    states: ["Tamil Nadu"],
    used_in: ["Astrology, temple timing"],
    references: ["Tamil Panchangam"],
  },
  {
    id: "tn-relig-2",
    slug: "tn-yamam",
    name_english: "Yamam",
    name_hindi: "யாமம்",
    local_names: ["யாமம் (Yamam)"],
    meaning: "Period of the day/night.",
    category: "time",
    sector: "religious-cultural",
    modern_equivalent: "3 hours",
    conversion_formula: "8 Yamam = 1 Day",
    states: ["Tamil Nadu"],
    used_in: ["Temple pooja schedules"],
    references: ["Agama Shastras"],
  }
];
