import { Measurement } from "@/types";

export const TRIPURA_MEASUREMENTS: Measurement[] = [
  // ─── 1. Transportation & Distance (3 units) ─────────────────────────────────
  {
    id: "tripura-trans-1",
    slug: "krosha-kos-transport-tripura",
    name_english: "Krosha (Kos)",
    name_sanskrit: "क्रोश (Krośa)",
    local_names: ["ক্রোশ"],
    name_hindi: "कोस",
    category: "length",
    measurement_type: "Distance",
    sector: "transportation-distance",
    origin: "Tripura",
    modern_equivalent: "~3.2 km",
    conversion_formula: "1 Krosha = traditional travel sub-unit",
    meaning:
      "Everyday travel-distance reckoning in plains Tripura and along routes to the Manikya court",
    historical_period:
      "Vedic–Classical Sanskrit period (c. 1000 BCE–500 CE), continued through the medieval era",
    region_applicable: "Agartala and the Manikya royal court (plains Tripura)",
    states: ["Tripura"],
    used_in: [
      "Everyday travel-distance reckoning in plains Tripura and along routes to the Manikya court",
      "Transportation & Distance",
    ],
    references: ["https://en.wikipedia.org/wiki/Kos_(unit)"],
    tags: ["tripura", "traditional-units", "transportation-distance", "distance", "krosha", "kos"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-trans-2",
    slug: "yojana-transport-tripura",
    name_english: "Yojana",
    name_sanskrit: "योजन (Yojana)",
    local_names: ["যোজন"],
    name_hindi: "योजन",
    category: "length",
    measurement_type: "Distance",
    sector: "transportation-distance",
    origin: "Tripura",
    modern_equivalent: "~11–14.5 km",
    conversion_formula: "4 Krosha = 1 Yojana",
    meaning:
      "Puranic-scale distance unit used in describing the sacred geography around Tripura Sundari Temple (Matabari) at Udaipur, one of the 51 Shakti Peeths",
    historical_period:
      "Ancient-Puranic/syncretic Hindu-tribal period; still ritually observed today",
    region_applicable: "Pan-Tripura generally",
    states: ["Tripura"],
    used_in: [
      "Puranic-scale distance unit describing sacred geography around Tripura Sundari Temple (Matabari)",
      "Transportation & Distance",
    ],
    references: ["https://en.wikipedia.org/wiki/Tripura_Sundari_Temple"],
    tags: ["tripura", "traditional-units", "transportation-distance", "distance", "yojana", "sacred-geography"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-trans-3",
    slug: "days-walk-hill-reckoning-transport-tripura",
    name_english: "(Day's-walk hill reckoning)",
    name_sanskrit:
      "N/A — informal, terrain-based measurement, no fixed named unit documented",
    local_names: [],
    name_hindi: "दिन भर की यात्रा (अनौपचारिक)",
    category: "length",
    measurement_type: "Distance (informal, time-based)",
    sector: "transportation-distance",
    origin: "Hill Tripura",
    modern_equivalent:
      "Distance expressed as the number of days' walk required through hill terrain",
    conversion_formula: "No standardised hierarchy",
    meaning:
      "In hill Tripura's forested terrain, travel between Jhumia villages was traditionally reckoned by days' walk, similar to the practice across the wider Northeast Indian hill tracts, rather than by a fixed-length unit",
    historical_period:
      "Customary/traditional practice of Tripura's 19 indigenous communities, predating and continuing alongside Manikya and Indian administration",
    region_applicable:
      "Hill Tripura — Jhum-cultivating tribal areas under TTAADC (Tripura Tribal Areas Autonomous District Council)",
    states: ["Tripura"],
    used_in: [
      "Travel between Jhumia villages in forested hill terrain reckoned by days of walk",
      "Transportation & Distance",
    ],
    references: [
      "No standardised metrological reference documented for this practice",
    ],
    tags: ["tripura", "traditional-units", "transportation-distance", "distance", "hill-reckoning", "tribal"],
    created_at: "2024-01-01",
  },

  // ─── 2. Land Measurement (7 units) ──────────────────────────────────────────
  {
    id: "tripura-land-1",
    slug: "dhur-land-tripura",
    name_english: "Dhur",
    name_sanskrit: "N/A (vernacular Tripura revenue term)",
    local_names: ["ধুর"],
    name_hindi: "धुर",
    category: "area",
    measurement_type: "Area",
    sector: "land-measurement",
    origin: "Tripura",
    modern_equivalent: "3.6 sq ft (~0.33 sq m)",
    conversion_formula: "20 Dhur = 1 Kranta",
    meaning:
      "Smallest unit in Tripura's own officially gazetted land-measurement chain, used for narrow homestead margins",
    historical_period:
      "British colonial/princely-state period (Tripura remained a semi-independent princely state under British paramountcy, 19th–20th century CE) and post-1949 Indian administration",
    region_applicable: "Pan-Tripura generally",
    states: ["Tripura"],
    used_in: [
      "Smallest unit in Tripura's own officially gazetted land-measurement chain, used for narrow homestead margins",
      "Land Measurement",
    ],
    references: [
      "https://upload.indiacode.nic.in/showfile?actid=AC_TR_87_1283_00001_00001_1593504604426&type=circular&filename=uom_land_trp.pdf",
    ],
    tags: ["tripura", "traditional-units", "land-measurement", "area", "dhur"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-land-2",
    slug: "kranta-land-tripura",
    name_english: "Kranta",
    name_sanskrit: "N/A (vernacular Tripura revenue term)",
    local_names: ["ক্রান্তা"],
    name_hindi: "क्रांत",
    category: "area",
    measurement_type: "Area",
    sector: "land-measurement",
    origin: "Tripura",
    modern_equivalent: "72 sq ft (~6.69 sq m)",
    conversion_formula: "20 Dhur = 1 Kranta; 3 Kranta = 1 Kara",
    meaning:
      "A distinctively Tripura-only rung of the chain, absent from the Bihar/Jharkhand/West Bengal/Assam land-unit ladders",
    historical_period:
      "British colonial/princely-state period (Tripura remained a semi-independent princely state under British paramountcy, 19th–20th century CE) and post-1949 Indian administration",
    region_applicable: "Pan-Tripura generally",
    states: ["Tripura"],
    used_in: [
      "A distinctively Tripura-only rung of the chain, absent from other states' land ladders",
      "Land Measurement",
    ],
    references: [
      "https://upload.indiacode.nic.in/showfile?actid=AC_TR_87_1283_00001_00001_1593504604426&type=circular&filename=uom_land_trp.pdf",
    ],
    tags: ["tripura", "traditional-units", "land-measurement", "area", "kranta"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-land-3",
    slug: "kara-land-tripura",
    name_english: "Kara",
    name_sanskrit: "N/A (vernacular Tripura revenue term)",
    local_names: ["কড়া"],
    name_hindi: "कड़ा",
    category: "area",
    measurement_type: "Area",
    sector: "land-measurement",
    origin: "Tripura",
    modern_equivalent: "216 sq ft (~20.07 sq m)",
    conversion_formula: "3 Kranta = 1 Kara; 4 Kara = 1 Ganda",
    meaning:
      "Also serves as the base sub-unit of the modern statutory Decimal in Tripura's official conversion tables (2 Kara = 1 Decimal)",
    historical_period:
      "British colonial/princely-state period (Tripura remained a semi-independent princely state under British paramountcy, 19th–20th century CE) and post-1949 Indian administration",
    region_applicable: "Pan-Tripura generally",
    states: ["Tripura"],
    used_in: [
      "Base sub-unit of modern statutory Decimal in Tripura's official conversion tables",
      "Land Measurement",
    ],
    references: [
      "https://upload.indiacode.nic.in/showfile?actid=AC_TR_87_1283_00001_00001_1593504604426&type=circular&filename=uom_land_trp.pdf",
    ],
    tags: ["tripura", "traditional-units", "land-measurement", "area", "kara"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-land-4",
    slug: "ganda-land-tripura",
    name_english: "Ganda",
    name_sanskrit: "N/A (vernacular Tripura revenue term)",
    local_names: ["গণ্ডা"],
    name_hindi: "गंडा",
    category: "area",
    measurement_type: "Area",
    sector: "land-measurement",
    origin: "Hill Tripura",
    modern_equivalent: "864 sq ft (~80.3 sq m)",
    conversion_formula: "4 Kara = 1 Ganda; 20 Ganda = 1 Kani",
    meaning:
      "Everyday unit for small tribal Jhum and homestead plots, used today for Tripura Tribal Areas Autonomous District Council (TTAADC) land-rights certification",
    historical_period:
      "British colonial/princely-state period (Tripura remained a semi-independent princely state under British paramountcy, 19th–20th century CE) and post-1949 Indian administration",
    region_applicable:
      "Hill Tripura — Jhum cultivating tribal areas under TTAADC (Tripura Tribal Areas Autonomous District Council)",
    states: ["Tripura"],
    used_in: [
      "Everyday unit for small tribal Jhum and homestead plots, used for TTAADC land-rights certification",
      "Land Measurement",
    ],
    references: [
      "https://manica.online/tripura-land-converter/",
      "https://www.bajajfinserv.in/land-measurement-in-tripura",
    ],
    tags: ["tripura", "traditional-units", "land-measurement", "area", "ganda", "ttaadc"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-land-5",
    slug: "kani-land-tripura",
    name_english: "Kani",
    name_sanskrit: "N/A (vernacular Tripura revenue term)",
    local_names: ["কানি"],
    name_hindi: "कानी",
    category: "area",
    measurement_type: "Area",
    sector: "land-measurement",
    origin: "Tripura",
    modern_equivalent:
      "17,280 sq ft (~1,605 sq m) per the official gazetted figure (some commercial converters round this to ~20,000 sq ft)",
    conversion_formula: "20 Ganda = 1 Kani; 16 Kani = 1 Drono",
    meaning:
      "Tripura's principal everyday land-holding unit, quoted in property transactions from village plots to industrial-estate allotments (e.g. at the Bodhjungnagar Industrial Estate)",
    historical_period:
      "British colonial/princely-state period (Tripura remained a semi-independent princely state under British paramountcy, 19th–20th century CE) and post-1949 Indian administration",
    region_applicable: "Pan-Tripura generally",
    states: ["Tripura"],
    used_in: [
      "Tripura's principal everyday land-holding unit quoted in property transactions and industrial allotments",
      "Land Measurement",
    ],
    references: [
      "https://upload.indiacode.nic.in/showfile?actid=AC_TR_87_1283_00001_00001_1593504604426&type=circular&filename=uom_land_trp.pdf",
    ],
    tags: ["tripura", "traditional-units", "land-measurement", "area", "kani"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-land-6",
    slug: "drono-land-tripura",
    name_english: "Drono",
    name_sanskrit: "द्रोण (Droṇa)",
    local_names: ["দ্রোণ"],
    name_hindi: "द्रोण",
    category: "area",
    measurement_type: "Area",
    sector: "land-measurement",
    origin: "Tripura",
    modern_equivalent: "276,480 sq ft (~25,687 sq m = 2.57 hectares)",
    conversion_formula: "16 Kani = 1 Drono",
    meaning:
      "The largest traditional Tripura land unit, its Sanskrit name recalling the same classical grain-measure root (Drona) that also survives in rural Bengali as 'dona' — reflecting Tripura's centuries of cultural exchange with neighbouring Bengal",
    historical_period:
      "British colonial/princely-state period (Tripura remained a semi-independent princely state under British paramountcy, 19th–20th century CE) and post-1949 Indian administration",
    region_applicable: "Pan-Tripura generally",
    states: ["Tripura"],
    used_in: [
      "The largest traditional Tripura land unit recalling classical grain-measure root",
      "Land Measurement",
    ],
    references: [
      "https://upload.indiacode.nic.in/showfile?actid=AC_TR_87_1283_00001_00001_1593504604426&type=circular&filename=uom_land_trp.pdf",
    ],
    tags: ["tripura", "traditional-units", "land-measurement", "area", "drono"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-land-7",
    slug: "acre-hectare-land-tripura",
    name_english: "Acre / Hectare",
    name_sanskrit: "एकड़ / हेक्टेयर",
    local_names: ["একর / হেক্টর"],
    name_hindi: "एकड़ / हेक्टेयर",
    category: "area",
    measurement_type: "Area",
    sector: "land-measurement",
    origin: "Tripura",
    modern_equivalent: "43,560 sq ft (Acre); 10,000 sq m (Hectare)",
    conversion_formula:
      "40 Are = 1 Acre (per Tripura's own official conversion table); 2.47 Acre = 1 Hectare",
    meaning:
      "Modern statutory units used in government and industrial land records alongside the traditional Dhur-Kranta-Kara-Ganda-Kani-Drono chain",
    historical_period:
      "British colonial/princely-state period (Tripura remained a semi-independent princely state under British paramountcy, 19th–20th century CE) and post-1949 Indian administration",
    region_applicable: "Pan-Tripura generally",
    states: ["Tripura"],
    used_in: [
      "Modern statutory units used in government and industrial land records alongside traditional chain",
      "Land Measurement",
    ],
    references: [
      "https://upload.indiacode.nic.in/showfile?actid=AC_TR_87_1283_00001_00001_1593504604426&type=circular&filename=uom_land_trp.pdf",
    ],
    tags: ["tripura", "traditional-units", "land-measurement", "area", "acre", "hectare"],
    created_at: "2024-01-01",
  },

  // ─── 3. Livestock & Dairy (2 units) ─────────────────────────────────────────
  {
    id: "tripura-dairy-1",
    slug: "ser-seer-dairy-tripura",
    name_english: "Ser (Seer)",
    name_sanskrit: "सेर (Sēra)",
    local_names: ["সের"],
    name_hindi: "सेर",
    category: "volume",
    measurement_type: "Weight/Volume",
    sector: "livestock-dairy",
    origin: "Tripura",
    modern_equivalent: "~0.93 kg / ~0.93 L",
    conversion_formula: "1/40 Mon",
    meaning:
      "Standard market measure for milk and ghee; no dairy-exclusive unit is separately documented for Tripura — the general Ser-Mon system, shared with Bengal, served this sector",
    historical_period:
      "British colonial/princely-state period (Tripura remained a semi-independent princely state under British paramountcy, 19th–20th century CE) and post-1949 Indian administration",
    region_applicable: "Pan-Tripura generally",
    states: ["Tripura"],
    used_in: [
      "Standard market measure for milk and ghee in plains Tripura",
      "Livestock & Dairy",
    ],
    references: [
      "https://grokipedia.com/page/Seer_(unit)",
      "https://en.wikipedia.org/wiki/Maund",
    ],
    tags: ["tripura", "traditional-units", "livestock-dairy", "milk", "ghee", "seer"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-dairy-2",
    slug: "mon-maund-dairy-tripura",
    name_english: "Mon (Maund)",
    name_sanskrit: "मन (Māna)",
    local_names: ["মণ"],
    name_hindi: "मन",
    category: "weight",
    measurement_type: "Weight",
    sector: "livestock-dairy",
    origin: "Tripura",
    modern_equivalent: "40 Ser ≈ 37.3 kg",
    conversion_formula: "40 Ser = 1 Mon",
    meaning: "Bulk trade of ghee and fodder at plains-Tripura weekly markets",
    historical_period:
      "British colonial/princely-state period (Tripura remained a semi-independent princely state under British paramountcy, 19th–20th century CE) and post-1949 Indian administration",
    region_applicable: "Pan-Tripura generally",
    states: ["Tripura"],
    used_in: [
      "Bulk trade of ghee and fodder at plains-Tripura weekly markets",
      "Livestock & Dairy",
    ],
    references: [
      "https://grokipedia.com/page/Seer_(unit)",
      "https://en.wikipedia.org/wiki/Maund",
    ],
    tags: ["tripura", "traditional-units", "livestock-dairy", "bulk", "fodder", "maund"],
    created_at: "2024-01-01",
  },

  // ─── 4. Household & Daily Life (3 units) ────────────────────────────────────
  {
    id: "tripura-hh-1",
    slug: "chutki-muthi-household-tripura",
    name_english: "Chutki / Muthi",
    name_sanskrit:
      "N/A (general vernacular, shared with the wider North Indian/Bengali vocabulary)",
    local_names: ["চিমটি / মুঠি"],
    name_hindi: "चुटकी / मुट्ठी",
    category: "volume",
    measurement_type: "Volume (informal)",
    sector: "household",
    origin: "Tripura",
    modern_equivalent: "Pinch to ~50–100 g fistful",
    conversion_formula: "Chutki < Muthi",
    meaning:
      "Everyday informal cooking-quantity gestures in plains Tripura and Bengali households",
    historical_period:
      "British colonial/princely-state period (Tripura remained a semi-independent princely state under British paramountcy, 19th–20th century CE) and post-1949 Indian administration",
    region_applicable: "Pan-Tripura generally",
    states: ["Tripura"],
    used_in: [
      "Everyday informal cooking-quantity gestures in plains Tripura and Bengali households",
      "Household & Daily Life",
    ],
    references: ["https://en.wikipedia.org/wiki/Handful"],
    tags: ["tripura", "traditional-units", "household", "cooking", "chutki", "muthi"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-hh-2",
    slug: "bamboo-container-volume-household-tripura",
    name_english: "(Bamboo container informal volume measure)",
    name_sanskrit: "N/A — vessel-based, no fixed named hierarchy documented",
    local_names: [],
    name_hindi: "बांस पात्र (अनौपचारिक)",
    category: "volume",
    measurement_type: "Volume (utility, informal)",
    sector: "household",
    origin: "Hill Tripura",
    modern_equivalent: "Determined by the natural size of the bamboo internode used",
    conversion_formula: "No standardised hierarchy",
    meaning:
      "Hollowed bamboo sections are used across hill Tripura tribal households to store and informally measure rice and traditional rice beer, echoing the same bamboo-based household utility practice found among neighbouring Northeast Indian hill communities",
    historical_period:
      "Customary/traditional practice of Tripura's 19 indigenous communities, predating and continuing alongside Manikya and Indian administration",
    region_applicable:
      "Hill Tripura — Jhum-cultivating tribal areas under TTAADC (Tripura Tribal Areas Autonomous District Council)",
    states: ["Tripura"],
    used_in: [
      "Hollowed bamboo sections used across hill tribal households to store and measure rice and rice beer",
      "Household & Daily Life",
    ],
    references: [
      "No standardised metrological reference documented for this practice",
    ],
    tags: ["tripura", "traditional-units", "household", "bamboo", "tribal"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-hh-3",
    slug: "chittak-chhatak-household-tripura",
    name_english: "Chittak (Chhatak)",
    name_sanskrit: "N/A (vernacular)",
    local_names: ["ছটাক"],
    name_hindi: "छटांक",
    category: "weight",
    measurement_type: "Weight",
    sector: "household",
    origin: "Tripura",
    modern_equivalent: "~58.3 g",
    conversion_formula: "1/16 Ser = 1 Chittak",
    meaning:
      "Everyday kitchen weighing of spices and flour in plains Tripura, Bengali-influenced households",
    historical_period:
      "British colonial/princely-state period (Tripura remained a semi-independent princely state under British paramountcy, 19th–20th century CE) and post-1949 Indian administration",
    region_applicable: "Agartala and the Manikya royal court (plains Tripura)",
    states: ["Tripura"],
    used_in: [
      "Everyday kitchen weighing of spices and flour in plains Tripura",
      "Household & Daily Life",
    ],
    references: [
      "https://grokipedia.com/page/Seer_(unit)",
      "https://en.wikipedia.org/wiki/Maund",
    ],
    tags: ["tripura", "traditional-units", "household", "kitchen", "chhatak"],
    created_at: "2024-01-01",
  },

  // ─── 5. Gold & Jewellery (4 units) ──────────────────────────────────────────
  {
    id: "tripura-gold-1",
    slug: "ratti-gold-tripura",
    name_english: "Ratti",
    name_sanskrit: "रत्ति (Ratti / Raktikā)",
    local_names: ["রত্তি"],
    name_hindi: "रत्ती",
    category: "weight",
    measurement_type: "Weight",
    sector: "gold-jewellery",
    origin: "Tripura",
    modern_equivalent: "~0.1215 g",
    conversion_formula: "Base gold/gem unit",
    meaning:
      "Traditional small-ornament weighing by Agartala jewellers (sonar) serving the Manikya court and plains population",
    historical_period:
      "Vedic–Classical Sanskrit period (c. 1000 BCE–500 CE), continued through the medieval era",
    region_applicable: "Agartala and the Manikya royal court (plains Tripura)",
    states: ["Tripura"],
    used_in: [
      "Traditional small-ornament weighing by Agartala jewellers (sonar)",
      "Gold & Jewellery",
    ],
    references: ["https://en.wikipedia.org/wiki/Ratti_(unit)"],
    tags: ["tripura", "traditional-units", "gold-jewellery", "gold", "ratti", "sonar"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-gold-2",
    slug: "tola-gold-tripura",
    name_english: "Tola",
    name_sanskrit: "तोला (Tolā)",
    local_names: ["তোলা"],
    name_hindi: "तोला",
    category: "weight",
    measurement_type: "Weight",
    sector: "gold-jewellery",
    origin: "Tripura",
    modern_equivalent: "~11.66 g",
    conversion_formula: "12 Masha = 1 Tola",
    meaning: "Principal gold trade weight in plains Tripura's jewellery bazaars",
    historical_period:
      "Vedic–Classical Sanskrit period (c. 1000 BCE–500 CE), continued through the medieval era",
    region_applicable: "Agartala and the Manikya royal court (plains Tripura)",
    states: ["Tripura"],
    used_in: [
      "Principal gold trade weight in plains Tripura's jewellery bazaars",
      "Gold & Jewellery",
    ],
    references: ["https://en.wikipedia.org/wiki/Tola_(unit)"],
    tags: ["tripura", "traditional-units", "gold-jewellery", "gold", "tola"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-gold-3",
    slug: "mohur-gold-tripura",
    name_english: "Mohur (bullion reference)",
    name_sanskrit: "मुद्रा (Mudrā)",
    local_names: ["মোহর"],
    name_hindi: "मोहर",
    category: "currency",
    measurement_type: "Weight/Currency",
    sector: "gold-jewellery",
    origin: "Tripura (Manikya Dynasty)",
    modern_equivalent: "~10.5–11.6 g gold",
    conversion_formula:
      "Manikya-era gold coin, also used as a bullion-weight reference",
    meaning:
      "Historical gold-value benchmark inherited from the Manikya dynasty's own coinage",
    historical_period:
      "Manikya dynasty period (Ratna Manikya, 1464 CE, to Bir Bikram Kishore Manikya, until 1949 CE merger with India)",
    region_applicable: "Agartala and the Manikya royal court (plains Tripura)",
    states: ["Tripura"],
    used_in: [
      "Historical gold-value benchmark inherited from Manikya dynasty coinage",
      "Gold & Jewellery",
    ],
    references: [
      "https://www.mintageworld.com/blog/coinage-of-tripura-kingdom/",
      "https://thetipra.in/the-introduction-of-coinage-system-by-king-ratna-manikya-in-tripura/",
    ],
    tags: ["tripura", "traditional-units", "gold-jewellery", "gold", "mohur", "bullion"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-gold-4",
    slug: "bead-silver-cane-ornament-gold-tripura",
    name_english:
      "(Bead, silver and bamboo/cane ornament — no weight-based hierarchy)",
    name_sanskrit: "N/A — count/craft-based, not a weight unit",
    local_names: [],
    name_hindi: "मनका-चांदी-बांस आभूषण (अनौपचारिक)",
    category: "count",
    measurement_type: "Count/Craft unit (informal)",
    sector: "gold-jewellery",
    origin: "Hill Tripura",
    modern_equivalent:
      "Valued by craftsmanship, material rarity and design rather than by a weight scale",
    conversion_formula: "No fixed hierarchy",
    meaning:
      "Tripura's tribal communities traditionally favoured jewellery of silver, bronze, copper, agate stone and glass beads — alongside intricately crafted bamboo and cane ornaments said to be unique to Tripura — rather than gold weighed by the Tola scale, which was primarily a plains/court practice",
    historical_period:
      "Customary/traditional practice of Tripura's 19 indigenous communities, predating and continuing alongside Manikya and Indian administration",
    region_applicable:
      "Hill Tripura — Jhum-cultivating tribal areas under TTAADC (Tripura Tribal Areas Autonomous District Council)",
    states: ["Tripura"],
    used_in: [
      "Tribal silver, bead, bronze and cane ornaments valued by craft rather than weight",
      "Gold & Jewellery",
    ],
    references: [
      "https://theindiantribal.com/2022/05/23/tripura-land-of-vibrant-colours-and-exquisite-jewellery-of-tribals/",
    ],
    tags: ["tripura", "traditional-units", "gold-jewellery", "tribal", "bead", "cane"],
    created_at: "2024-01-01",
  },

  // ─── 6. Seed & Crop (Agriculture) (4 units) ─────────────────────────────────
  {
    id: "tripura-agri-1",
    slug: "basket-load-jhum-agriculture-tripura",
    name_english: "(Basket-load Jhum reckoning)",
    name_sanskrit:
      "N/A — vessel-based, no fixed named weight/volume unit documented",
    local_names: [],
    name_hindi: "टोकरी-भार (अनौपचारिक)",
    category: "volume",
    measurement_type: "Weight/Volume (informal)",
    sector: "agriculture",
    origin: "Hill Tripura",
    modern_equivalent:
      "Determined by the size of the woven bamboo carrying-basket in use",
    conversion_formula: "No standardised hierarchy",
    meaning:
      "Jhum (shifting-cultivation) harvests of rice, cotton and vegetables — practised across hill Tripura, historically by an estimated 25,000-plus Jhumia families, mostly of the Reang tribe — were traditionally carried and quantified basket-by-basket rather than by a fixed named unit",
    historical_period:
      "Customary/traditional practice of Tripura's 19 indigenous communities, predating and continuing alongside Manikya and Indian administration",
    region_applicable:
      "Hill Tripura — Jhum-cultivating tribal areas under TTAADC (Tripura Tribal Areas Autonomous District Council)",
    states: ["Tripura"],
    used_in: [
      "Jhum harvests of rice, cotton and vegetables quantified basket-by-basket",
      "Seed & Crop (Agriculture)",
    ],
    references: [
      "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8362256/",
      "https://www.tripuraonline.in/guide/jhum-cultivation-in-tripura",
    ],
    tags: ["tripura", "traditional-units", "agriculture", "jhum", "basket-load", "reang"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-agri-2",
    slug: "ser-seer-agriculture-tripura",
    name_english: "Ser (Seer)",
    name_sanskrit: "सेर (Sēra)",
    local_names: ["সের"],
    name_hindi: "सेर",
    category: "weight",
    measurement_type: "Weight",
    sector: "agriculture",
    origin: "Tripura",
    modern_equivalent: "~0.93 kg",
    conversion_formula: "16 Chittak = 1 Ser",
    meaning:
      "Standard measure for seed grain and harvested paddy in plains, wet-cultivation Tripura",
    historical_period:
      "British colonial/princely-state period (Tripura remained a semi-independent princely state under British paramountcy, 19th–20th century CE) and post-1949 Indian administration",
    region_applicable: "Agartala and the Manikya royal court (plains Tripura)",
    states: ["Tripura"],
    used_in: [
      "Standard measure for seed grain and harvested paddy in plains wet-cultivation",
      "Seed & Crop (Agriculture)",
    ],
    references: [
      "https://grokipedia.com/page/Seer_(unit)",
      "https://en.wikipedia.org/wiki/Maund",
    ],
    tags: ["tripura", "traditional-units", "agriculture", "seed", "grain", "paddy", "seer"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-agri-3",
    slug: "mon-maund-agriculture-tripura",
    name_english: "Mon (Maund)",
    name_sanskrit: "मन (Māna)",
    local_names: ["মণ"],
    name_hindi: "मन",
    category: "weight",
    measurement_type: "Weight",
    sector: "agriculture",
    origin: "Tripura",
    modern_equivalent: "~37.3 kg",
    conversion_formula: "40 Ser = 1 Mon",
    meaning: "Principal wholesale unit for paddy sale at plains Tripura markets",
    historical_period:
      "British colonial/princely-state period (Tripura remained a semi-independent princely state under British paramountcy, 19th–20th century CE) and post-1949 Indian administration",
    region_applicable: "Agartala and the Manikya royal court (plains Tripura)",
    states: ["Tripura"],
    used_in: [
      "Principal wholesale unit for paddy sale at plains Tripura markets",
      "Seed & Crop (Agriculture)",
    ],
    references: [
      "https://grokipedia.com/page/Seer_(unit)",
      "https://en.wikipedia.org/wiki/Maund",
    ],
    tags: ["tripura", "traditional-units", "agriculture", "paddy", "wholesale", "maund"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-agri-4",
    slug: "kani-ganda-wet-land-agriculture-tripura",
    name_english: "Kani / Ganda (wet-land plots)",
    name_sanskrit: "N/A (vernacular Tripura revenue term)",
    local_names: ["কানি / গণ্ডা"],
    name_hindi: "कानी / गंडा",
    category: "area",
    measurement_type: "Area",
    sector: "agriculture",
    origin: "Tripura",
    modern_equivalent: "1 Kani = 17,280 sq ft; 1 Ganda = 864 sq ft",
    conversion_formula: "20 Ganda = 1 Kani",
    meaning:
      "Field-size unit for reckoning sowing area and expected yield on plains wet-rice land, as distinct from the informal basket-reckoned hill Jhum plots",
    historical_period:
      "British colonial/princely-state period (Tripura remained a semi-independent princely state under British paramountcy, 19th–20th century CE) and post-1949 Indian administration",
    region_applicable: "Pan-Tripura generally",
    states: ["Tripura"],
    used_in: [
      "Field-size unit for reckoning sowing area and expected yield on plains wet-rice land",
      "Seed & Crop (Agriculture)",
    ],
    references: [
      "https://upload.indiacode.nic.in/showfile?actid=AC_TR_87_1283_00001_00001_1593504604426&type=circular&filename=uom_land_trp.pdf",
    ],
    tags: ["tripura", "traditional-units", "agriculture", "area", "sowing", "kani", "ganda"],
    created_at: "2024-01-01",
  },

  // ─── 7. Trade & Commerce (4 units) ──────────────────────────────────────────
  {
    id: "tripura-trade-1",
    slug: "1-32-tanka-trade-tripura",
    name_english: "1/32 Tanka",
    name_sanskrit: "N/A (Manikya-era fractional denomination)",
    local_names: ["৩২ ভাগের ১ টঙ্কা"],
    name_hindi: "बत्तीसवां टंका",
    category: "currency",
    measurement_type: "Currency",
    sector: "trade-commerce",
    origin: "Tripura (Manikya Dynasty)",
    modern_equivalent: "~0.33 g silver",
    conversion_formula: "32 fractions = 1 Tanka",
    meaning:
      "Smallest regular fractional coin of the Manikya dynasty's silver currency, used for petty bazaar transactions in and around Agartala",
    historical_period:
      "Manikya dynasty period (Ratna Manikya, 1464 CE, to Bir Bikram Kishore Manikya, until 1949 CE merger with India)",
    region_applicable: "Agartala and the Manikya royal court (plains Tripura)",
    states: ["Tripura"],
    used_in: [
      "Smallest regular fractional coin of the Manikya dynasty's silver currency, used for petty bazaar transactions in and around Agartala",
      "Trade & Commerce",
    ],
    references: [
      "https://en.banglapedia.org/index.php/Tripura_Coinage",
      "https://en.numista.com/catalogue/tripura_princely-1.html",
    ],
    tags: ["tripura", "traditional-units", "trade-commerce", "currency", "manikya"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-trade-2",
    slug: "tanka-trade-tripura",
    name_english: "Tanka",
    name_sanskrit: "टङ्क (Ṭaṅka)",
    local_names: ["টঙ্কা"],
    name_hindi: "टंका",
    category: "currency",
    measurement_type: "Currency",
    sector: "trade-commerce",
    origin: "Tripura (Manikya Dynasty)",
    modern_equivalent:
      "~10–11.6 g silver, weight-standard matched to contemporary Bengal Sultanate coinage",
    conversion_formula: "32 fractions = 1 Tanka",
    meaning:
      "The principal coin of the Manikya kings, struck continuously for about 500 years — the longest unbroken series of any princely coinage in Northeast India — first issued in Saka 1386 (1464 CE) by Ratna Manikya, who had learned minting technology while in exile at the Bengal Sultanate court",
    historical_period:
      "Manikya dynasty period (Ratna Manikya, 1464 CE, to Bir Bikram Kishore Manikya, until 1949 CE merger with India)",
    region_applicable: "Agartala and the Manikya royal court (plains Tripura)",
    states: ["Tripura"],
    used_in: [
      "The principal coin of the Manikya kings, struck continuously for about 500 years",
      "Trade & Commerce",
    ],
    references: [
      "https://en.banglapedia.org/index.php/Tripura_Coinage",
      "https://en.numista.com/catalogue/tripura_princely-1.html",
    ],
    tags: ["tripura", "traditional-units", "trade-commerce", "currency", "manikya", "silver"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-trade-3",
    slug: "mohur-trade-tripura",
    name_english: "Mohur",
    name_sanskrit: "मुद्रा (Mudrā)",
    local_names: ["মোহর"],
    name_hindi: "मोहर",
    category: "currency",
    measurement_type: "Currency",
    sector: "trade-commerce",
    origin: "Tripura (Manikya Dynasty)",
    modern_equivalent: "~10.5–11.6 g gold",
    conversion_formula: "Gold-denomination counterpart to the silver Tanka",
    meaning:
      "High-value royal treasury and ceremonial gift coin, issued by later Manikya kings such as Ratnaganga Manikya and Krishna Kishora Manikya; gold coins were far rarer than silver, since the metal had to be imported",
    historical_period:
      "Manikya dynasty period (Ratna Manikya, 1464 CE, to Bir Bikram Kishore Manikya, until 1949 CE merger with India)",
    region_applicable: "Agartala and the Manikya royal court (plains Tripura)",
    states: ["Tripura"],
    used_in: [
      "High-value royal treasury and ceremonial gift coin",
      "Trade & Commerce",
    ],
    references: [
      "https://www.mintageworld.com/blog/coinage-of-tripura-kingdom/",
      "https://thetproject.in/the-introduction-of-coinage-system-by-king-ratna-manikya-in-tripura/",
    ],
    tags: ["tripura", "traditional-units", "trade-commerce", "currency", "gold", "manikya"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-trade-4",
    slug: "ser-mon-trade-tripura",
    name_english: "Ser / Mon (Seer/Maund)",
    name_sanskrit: "सेर / मन",
    local_names: ["সের / মণ"],
    name_hindi: "सेर / मन",
    category: "weight",
    measurement_type: "Weight",
    sector: "trade-commerce",
    origin: "Tripura",
    modern_equivalent: "~0.93 kg Ser; 40 Ser = 1 Mon ≈ 37.3 kg",
    conversion_formula: "40 Ser = 1 Mon",
    meaning:
      "Standard bazaar weight for rice, cotton and other bulk goods in plains Tripura, adopted from neighbouring Bengal through centuries of trade contact",
    historical_period:
      "British colonial/princely-state period (Tripura remained a semi-independent princely state under British paramountcy, 19th–20th century CE) and post-1949 Indian administration",
    region_applicable: "Pan-Tripura generally",
    states: ["Tripura"],
    used_in: [
      "Standard bazaar weight for rice, cotton and other bulk goods in plains Tripura",
      "Trade & Commerce",
    ],
    references: [
      "https://grokipedia.com/page/Seer_(unit)",
      "https://en.wikipedia.org/wiki/Maund",
    ],
    tags: ["tripura", "traditional-units", "trade-commerce", "weight", "seer", "maund"],
    created_at: "2024-01-01",
  },

  // ─── 8. Textile & Handloom (5 units) ────────────────────────────────────────
  {
    id: "tripura-textile-1",
    slug: "loin-loom-garment-reckoning-textile-tripura",
    name_english: "(Loin-loom, garment-based reckoning)",
    name_sanskrit:
      "N/A — informal, garment-specific measurement, no fixed named length-unit documented",
    local_names: [],
    name_hindi: "अनौपचारिक वस्त्र-मापन",
    category: "length",
    measurement_type: "Length (informal)",
    sector: "textile-handloom",
    origin: "Hill Tripura",
    modern_equivalent:
      "Set by the finished size of the specific garment being woven, not a codified unit",
    conversion_formula: "No standardised hierarchy",
    meaning:
      "Tripuri and other tribal women weave Risa, Rignai and Pachra directly to the wearer's body measurements on a backstrap/loin loom, without reference to a fixed named length unit like the Gaz or Hasta used in the plains state cloth trade",
    historical_period:
      "Customary/traditional practice of Tripura's 19 indigenous communities, predating and continuing alongside Manikya and Indian administration",
    region_applicable:
      "Hill Tripura — Jhum-cultivating tribal areas under TTAADC (Tripura Tribal Areas Autonomous District Council)",
    states: ["Tripura"],
    used_in: [
      "Tripuri and other tribal women weave Risa, Rignai and Pachra directly to the wearer's body measurements on a backstrap/loin loom",
      "Textile & Handloom",
    ],
    references: [
      "https://en.wikipedia.org/wiki/Tripura_Risa_Textile",
      "https://en.wikipedia.org/wiki/Rignai",
    ],
    tags: ["tripura", "traditional-units", "textile-handloom", "loin-loom", "tribal"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-textile-2",
    slug: "risa-textile-tripura",
    name_english: "Risa",
    name_sanskrit: "N/A (Kokborok/Tripuri garment term, now GI-tag protected)",
    local_names: ["রিসা"],
    name_hindi: "रिसा",
    category: "count",
    measurement_type: "Garment (count/type unit)",
    sector: "textile-handloom",
    origin: "Hill Tripura",
    modern_equivalent:
      "One woven piece — a small, richly embroidered stole/breast cloth",
    conversion_formula: "Worn wrapped twice around the torso as an upper garment",
    meaning:
      "Given to adolescent Tripuri girls around age 12–14 in the 'Risa Sormani' ceremony, and worn during Garia Puja and weddings; granted a Geographical Indication (GI) tag",
    historical_period:
      "Customary/traditional practice of Tripura's 19 indigenous communities, predating and continuing alongside Manikya and Indian administration",
    region_applicable:
      "Hill Tripura — Jhum-cultivating tribal areas under TTAADC (Tripura Tribal Areas Autonomous District Council)",
    states: ["Tripura"],
    used_in: [
      "Given to adolescent Tripuri girls around age 12–14 in the 'Risa Sormani' ceremony, and worn during Garia Puja and weddings",
      "Textile & Handloom",
    ],
    references: [
      "https://en.wikipedia.org/wiki/Tripura_Risa_Textile",
      "https://en.wikipedia.org/wiki/Rignai",
    ],
    tags: ["tripura", "traditional-units", "textile-handloom", "risa", "gi-tag", "tripuri"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-textile-3",
    slug: "rignai-textile-tripura",
    name_english: "Rignai (Rigwnai)",
    name_sanskrit: "N/A (Kokborok/Tripuri garment term, now GI-tag protected)",
    local_names: ["রিগনাই"],
    name_hindi: "रिग्नई",
    category: "count",
    measurement_type: "Garment (count/type unit)",
    sector: "textile-handloom",
    origin: "Hill Tripura",
    modern_equivalent:
      "One woven piece — a wrap-around lower garment, extending below the knee",
    conversion_formula:
      "Worn with the Risa as the standard two-piece Tripuri women's dress",
    meaning:
      "Named variants (e.g. 'Chamathwibar', for weddings and Garia Puja; 'Kachak taqnor' for daily wear) show the garment functioning as a coded 'unit' of occasion as much as of cloth",
    historical_period:
      "Customary/traditional practice of Tripura's 19 indigenous communities, predating and continuing alongside Manikya and Indian administration",
    region_applicable:
      "Hill Tripura — Jhum-cultivating tribal areas under TTAADC (Tripura Tribal Areas Autonomous District Council)",
    states: ["Tripura"],
    used_in: [
      "Standard wrap-around lower garment for Tripuri women",
      "Textile & Handloom",
    ],
    references: [
      "https://en.wikipedia.org/wiki/Tripura_Risa_Textile",
      "https://en.wikipedia.org/wiki/Rignai",
    ],
    tags: ["tripura", "traditional-units", "textile-handloom", "rignai", "gi-tag", "tripuri"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-textile-4",
    slug: "pachra-textile-tripura",
    name_english: "Pachra",
    name_sanskrit:
      "N/A (garment term, Reang-community usage, GI-tag protected as 'Rignai Pachra')",
    local_names: ["পাছরা"],
    name_hindi: "पछरा",
    category: "count",
    measurement_type: "Garment (count/type unit)",
    sector: "textile-handloom",
    origin: "Hill Tripura",
    modern_equivalent:
      "One woven piece, worn as the lower garment by Reang women",
    conversion_formula:
      "Equivalent role to the Rignai among the Reang community",
    meaning:
      "More intricately patterned than the Rignai, with colours symbolising status and occasion among the Reang (Bru) tribe",
    historical_period:
      "Customary/traditional practice of Tripura's 19 indigenous communities, predating and continuing alongside Manikya and Indian administration",
    region_applicable:
      "Hill Tripura — Jhum-cultivating tribal areas under TTAADC (Tripura Tribal Areas Autonomous District Council)",
    states: ["Tripura"],
    used_in: [
      "Lower garment worn by Reang (Bru) women with intricate symbolic patterning",
      "Textile & Handloom",
    ],
    references: [
      "https://en.wikipedia.org/wiki/Tripura_Risa_Textile",
      "https://en.wikipedia.org/wiki/Rignai",
    ],
    tags: ["tripura", "traditional-units", "textile-handloom", "pachra", "reang", "bru", "gi-tag"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-textile-5",
    slug: "tola-textile-tripura",
    name_english: "Tola (bullion reference)",
    name_sanskrit: "तोला (Tolā)",
    local_names: ["তোলা"],
    name_hindi: "तोला",
    category: "weight",
    measurement_type: "Weight",
    sector: "textile-handloom",
    origin: "Tripura",
    modern_equivalent: "~11.66 g",
    conversion_formula: "12 Masha = 1 Tola",
    meaning:
      "Weighing gold and silver thread used in ceremonial Risa embroidery for royal or high-status commissions",
    historical_period:
      "Vedic–Classical Sanskrit period (c. 1000 BCE–500 CE), continued through the medieval era",
    region_applicable: "Agartala and the Manikya royal court (plains Tripura)",
    states: ["Tripura"],
    used_in: [
      "Weighing gold and silver thread used in ceremonial Risa embroidery for royal or high-status commissions",
      "Textile & Handloom",
    ],
    references: ["https://en.wikipedia.org/wiki/Tola_(unit)"],
    tags: ["tripura", "traditional-units", "textile-handloom", "weight", "tola", "embroidery"],
    created_at: "2024-01-01",
  },

  // ─── 9. Medicine (Ayurveda) (5 units) ───────────────────────────────────────
  {
    id: "tripura-med-1",
    slug: "ratti-medicine-tripura",
    name_english: "Ratti",
    name_sanskrit: "रत्ति / रक्तिका (Ratti / Raktikā)",
    local_names: ["রত্তি"],
    name_hindi: "रत्ती",
    category: "weight",
    measurement_type: "Weight",
    sector: "medicine",
    origin: "Tripura",
    modern_equivalent: "~0.1215 g",
    conversion_formula: "Base / smallest unit",
    meaning:
      "Smallest dosage unit for herbo-mineral formulations, used by Ayurvedic Kobiraj physicians patronised at the Hindu Manikya court",
    historical_period:
      "Vedic–Classical Sanskrit period (c. 1000 BCE–500 CE), continued through the medieval era",
    region_applicable: "Agartala and the Manikya royal court (plains Tripura)",
    states: ["Tripura"],
    used_in: [
      "Smallest dosage unit for herbo-mineral formulations, used by Ayurvedic Kobiraj physicians patronised at the Hindu Manikya court",
      "Medicine (Ayurveda)",
    ],
    references: ["https://en.wikipedia.org/wiki/Ratti_(unit)"],
    tags: ["tripura", "traditional-units", "medicine", "weight", "ratti", "ayurveda"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-med-2",
    slug: "masha-medicine-tripura",
    name_english: "Masha",
    name_sanskrit: "माष (Māṣa)",
    local_names: ["মাষ"],
    name_hindi: "माशा",
    category: "weight",
    measurement_type: "Weight",
    sector: "medicine",
    origin: "Tripura",
    modern_equivalent: "~0.97 g",
    conversion_formula: "8 Ratti = 1 Masha",
    meaning: "Powder (churna) dosage in classical Ayurvedic prescription",
    historical_period:
      "Vedic–Classical Sanskrit period (c. 1000 BCE–500 CE), continued through the medieval era",
    region_applicable: "Agartala and the Manikya royal court (plains Tripura)",
    states: ["Tripura"],
    used_in: [
      "Powder (churna) dosage in classical Ayurvedic prescription",
      "Medicine (Ayurveda)",
    ],
    references: ["https://www.wisdomlib.org/concept/masha"],
    tags: ["tripura", "traditional-units", "medicine", "weight", "masha", "ayurveda"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-med-3",
    slug: "karsha-medicine-tripura",
    name_english: "Karsha",
    name_sanskrit: "कर्ष (Karṣa)",
    local_names: ["কর্ষ"],
    name_hindi: "कर्ष",
    category: "weight",
    measurement_type: "Weight",
    sector: "medicine",
    origin: "Tripura",
    modern_equivalent: "~12 g",
    conversion_formula: "12 Masha = 1 Karsha",
    meaning: "Weighing herbal powders and churnas",
    historical_period:
      "Vedic–Classical Sanskrit period (c. 1000 BCE–500 CE), continued through the medieval era",
    region_applicable: "Agartala and the Manikya royal court (plains Tripura)",
    states: ["Tripura"],
    used_in: ["Weighing herbal powders and churnas", "Medicine (Ayurveda)"],
    references: ["https://www.wisdomlib.org/concept/karsha"],
    tags: ["tripura", "traditional-units", "medicine", "weight", "karsha", "ayurveda"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-med-4",
    slug: "pala-medicine-tripura",
    name_english: "Pala",
    name_sanskrit: "पल (Pala)",
    local_names: ["পল"],
    name_hindi: "पल",
    category: "weight",
    measurement_type: "Weight",
    sector: "medicine",
    origin: "Tripura",
    modern_equivalent: "~48 g",
    conversion_formula: "4 Karsha = 1 Pala",
    meaning:
      "Measuring bulk herbal ingredients for decoctions and medicated oils",
    historical_period:
      "Vedic–Classical Sanskrit period (c. 1000 BCE–500 CE), continued through the medieval era",
    region_applicable: "Agartala and the Manikya royal court (plains Tripura)",
    states: ["Tripura"],
    used_in: [
      "Measuring bulk herbal ingredients for decoctions and medicated oils",
      "Medicine (Ayurveda)",
    ],
    references: ["https://www.wisdomlib.org/concept/pala"],
    tags: ["tripura", "traditional-units", "medicine", "weight", "pala", "ayurveda"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-med-5",
    slug: "tribal-herbal-healing-medicine-tripura",
    name_english: "(Tribal herbal healing — informal reckoning)",
    name_sanskrit:
      "N/A — no codified weight-dosage system documented for Tripura's indigenous tribal healing traditions",
    local_names: [],
    name_hindi: "जनजातीय औषधि (अनौपचारिक)",
    category: "other",
    measurement_type: "Volume/Weight (informal)",
    sector: "medicine",
    origin: "Hill Tripura",
    modern_equivalent: "Approximated by hand — no fixed weight scale",
    conversion_formula: "No standardised hierarchy",
    meaning:
      "Alongside the court-patronised Sanskritic Ayurveda described above, Tripura's 19 indigenous tribal communities maintained their own herbal-healing knowledge through village healers, using informal (handful/pinch) rather than codified weight-based dosing — the two traditions existed side by side rather than merging into one",
    historical_period:
      "Customary/traditional practice of Tripura's 19 indigenous communities, predating and continuing alongside Manikya and Indian administration",
    region_applicable:
      "Hill Tripura — Jhum-cultivating tribal areas under TTAADC (Tripura Tribal Areas Autonomous District Council)",
    states: ["Tripura"],
    used_in: [
      "Tribal herbal-healing knowledge through village healers using informal dosing",
      "Medicine (Ayurveda)",
    ],
    references: [
      "No standardised metrological reference documented for this practice",
    ],
    tags: ["tripura", "traditional-units", "medicine", "tribal", "informal"],
    created_at: "2024-01-01",
  },

  // ─── 10. Construction & Architecture (4 units) ──────────────────────────────
  {
    id: "tripura-arch-1",
    slug: "angula-architecture-tripura",
    name_english: "Angula",
    name_sanskrit: "अङ्गुल (Aṅgula)",
    local_names: ["আঙুলি"],
    name_hindi: "अंगुल",
    category: "length",
    measurement_type: "Length",
    sector: "architecture",
    origin: "Tripura",
    modern_equivalent: "~1.9 cm",
    conversion_formula: "Base unit; 24 Angula = 1 Hasta",
    meaning: "Fine calibration of brick and stone dimensions",
    historical_period:
      "Vedic–Classical Sanskrit period (c. 1000 BCE–500 CE), continued through the medieval era",
    region_applicable: "Agartala and the Manikya royal court (plains Tripura)",
    states: ["Tripura"],
    used_in: [
      "Fine calibration of brick and stone dimensions",
      "Construction & Architecture",
    ],
    references: ["https://en.wikipedia.org/wiki/A%E1%89%85gula"],
    tags: ["tripura", "traditional-units", "architecture", "length", "angula"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-arch-2",
    slug: "hasta-architecture-tripura",
    name_english: "Hasta",
    name_sanskrit: "हस्त (Hasta)",
    local_names: ["হাত"],
    name_hindi: "हाथ",
    category: "length",
    measurement_type: "Length",
    sector: "architecture",
    origin: "Tripura (Manikya Dynasty)",
    modern_equivalent: "~45.7 cm",
    conversion_formula: "24 Angula = 1 Hasta",
    meaning:
      "Wall heights and pillar spacing in Manikya royal construction, including Agartala's Ujjayanta Palace (built 1899–1901) and the lake-set Neermahal 'water palace' (completed 1930, blending Hindu and Islamic architectural styles)",
    historical_period:
      "Manikya dynasty period (Ratna Manikya, 1464 CE, to Bir Bikram Kishore Manikya, until 1949 CE merger with India)",
    region_applicable: "Agartala and the Manikya royal court (plains Tripura)",
    states: ["Tripura"],
    used_in: [
      "Wall heights and pillar spacing in Manikya royal construction (Ujjayanta Palace, Neermahal)",
      "Construction & Architecture",
    ],
    references: [
      "https://en.wikipedia.org/wiki/Neermahal",
      "https://en.wikipedia.org/wiki/Ujjayanta_Palace",
    ],
    tags: ["tripura", "traditional-units", "architecture", "length", "hasta", "palace"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-arch-3",
    slug: "danda-architecture-tripura",
    name_english: "Danda",
    name_sanskrit: "दण्ड (Daṇḍa)",
    local_names: ["দণ্ড"],
    name_hindi: "डंडा",
    category: "length",
    measurement_type: "Length",
    sector: "architecture",
    origin: "Tripura (Manikya Dynasty)",
    modern_equivalent: "~1.8–1.9 m",
    conversion_formula: "4 Hasta = 1 Danda",
    meaning:
      "Courtyard and moat width measurement around royal residences and the Neermahal's artificial Rudrasagar lake",
    historical_period:
      "Manikya dynasty period (Ratna Manikya, 1464 CE, to Bir Bikram Kishore Manikya, until 1949 CE merger with India)",
    region_applicable: "Agartala and the Manikya royal court (plains Tripura)",
    states: ["Tripura"],
    used_in: [
      "Courtyard and moat width measurement around royal residences and Rudrasagar lake",
      "Construction & Architecture",
    ],
    references: [
      "https://en.wikipedia.org/wiki/Neermahal",
      "https://en.wikipedia.org/wiki/Ujjayanta_Palace",
    ],
    tags: ["tripura", "traditional-units", "architecture", "length", "danda"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-arch-4",
    slug: "bamboo-pole-handspan-architecture-tripura",
    name_english: "(Bamboo-pole/handspan reckoning)",
    name_sanskrit:
      "N/A — informal, material-based measurement, no fixed named unit documented",
    local_names: [],
    name_hindi: "बांस-डंडा (अनौपचारिक)",
    category: "length",
    measurement_type: "Length (informal)",
    sector: "architecture",
    origin: "Hill Tripura",
    modern_equivalent:
      "Set by the bamboo pole or the builder's own body-reference, varying by use",
    conversion_formula: "No standardised hierarchy",
    meaning:
      "Away from the royal court, tribal stilt-house and Jhum-hut construction across hill Tripura used informal bamboo- and body-based measurement, not the Sanskritic Angula-Hasta-Danda canon reserved for palace and temple building",
    historical_period:
      "Customary/traditional practice of Tripura's 19 indigenous communities, predating and continuing alongside Manikya and Indian administration",
    region_applicable:
      "Hill Tripura — Jhum-cultivating tribal areas under TTAADC (Tripura Tribal Areas Autonomous District Council)",
    states: ["Tripura"],
    used_in: [
      "Tribal stilt-house and Jhum-hut construction across hill Tripura using informal bamboo and body reckoning",
      "Construction & Architecture",
    ],
    references: [
      "No standardised metrological reference documented for this practice",
    ],
    tags: ["tripura", "traditional-units", "architecture", "length", "bamboo", "tribal"],
    created_at: "2024-01-01",
  },

  // ─── 11. Currency & Money (5 units) ─────────────────────────────────────────
  {
    id: "tripura-currency-1",
    slug: "one-thirty-second-tanka-currency-tripura",
    name_english: "1/32 Tanka",
    name_sanskrit: "N/A (Manikya-era fractional denomination)",
    local_names: ["৩২ ভাগের ১ টাকা"],
    name_hindi: "बत्तीसवां टंका",
    category: "currency",
    measurement_type: "Currency",
    sector: "currency-money",
    origin: "Tripura (Manikya Dynasty)",
    modern_equivalent: "~0.33 g silver",
    conversion_formula: "32 fractions = 1 Tanka",
    meaning: "Smallest official Manikya coin fraction for petty transactions",
    historical_period:
      "Manikya dynasty period (Ratna Manikya, 1464 CE, to Bir Bikram Kishore Manikya, until 1949 CE merger with India)",
    region_applicable: "Agartala and the Manikya royal court (plains Tripura)",
    states: ["Tripura"],
    used_in: [
      "Smallest official Manikya coin fraction for petty transactions",
      "Currency & Money",
    ],
    references: [
      "https://en.banglapedia.org/index.php/Tripura_Coinage",
      "https://en.numista.com/catalogue/tripura_princely-1.html",
    ],
    tags: ["tripura", "traditional-units", "currency-money", "currency", "tanka", "silver"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-currency-2",
    slug: "tanka-currency-tripura",
    name_english: "Tanka",
    name_sanskrit: "टङ्क (Taṅka)",
    local_names: ["টাকা"],
    name_hindi: "टंका",
    category: "currency",
    measurement_type: "Currency",
    sector: "currency-money",
    origin: "Tripura (Manikya Dynasty)",
    modern_equivalent: "~10–11.6 g silver",
    conversion_formula: "32 fractions = 1 Tanka",
    meaning:
      "The Manikya dynasty's principal coin for roughly 500 unbroken years (1464 CE onward) — one of the longest continuous regional coinages in Indian numismatic history, and one of only a handful of Indian coin series to name the Queen alongside the King",
    historical_period:
      "Manikya dynasty period (Ratna Manikya, 1464 CE, to Bir Bikram Kishore Manikya, until 1949 CE merger with India)",
    region_applicable: "Agartala and the Manikya royal court (plains Tripura)",
    states: ["Tripura"],
    used_in: [
      "The Manikya dynasty's principal coin for roughly 500 unbroken years",
      "Currency & Money",
    ],
    references: [
      "https://en.banglapedia.org/index.php/Tripura_Coinage",
      "https://en.numista.com/catalogue/tripura_princely-1.html",
    ],
    tags: ["tripura", "traditional-units", "currency-money", "currency", "tanka", "manikya"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-currency-3",
    slug: "mohur-currency-tripura",
    name_english: "Mohur",
    name_sanskrit: "मुद्रा (Mudrā)",
    local_names: ["মোহর"],
    name_hindi: "मोहर",
    category: "currency",
    measurement_type: "Currency",
    sector: "currency-money",
    origin: "Tripura (Manikya Dynasty)",
    modern_equivalent: "~10.3–11.6 g gold",
    conversion_formula: "Gold counterpart to the silver Tanka",
    meaning:
      "High-value royal treasury and ceremonial coin issued periodically by later Manikya kings",
    historical_period:
      "Manikya dynasty period (Ratna Manikya, 1464 CE, to Bir Bikram Kishore Manikya, until 1949 CE merger with India)",
    region_applicable: "Agartala and the Manikya royal court (plains Tripura)",
    states: ["Tripura"],
    used_in: [
      "High-value royal treasury and ceremonial coin issued periodically by later Manikya kings",
      "Currency & Money",
    ],
    references: [
      "https://www.mintageworld.com/blog/coinage-of-tripura-kingdom/",
      "https://thetipra.in/the-introduction-of-coinage-system-by-king-ratna-manikya-in-tripura/",
    ],
    tags: ["tripura", "traditional-units", "currency-money", "currency", "mohur", "gold"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-currency-4",
    slug: "tripura-era-currency-tripura",
    name_english: "Tripura Era (TE) — regnal calendar, not a subdivided unit",
    name_sanskrit: "N/A — a standalone era count, not a hierarchical unit",
    local_names: ["ত্রিপুরাব্দ"],
    name_hindi: "त्रिपुराब्द",
    category: "time",
    measurement_type: "Calendar (regnal/era count)",
    sector: "currency-money",
    origin: "Tripura (Manikya Dynasty)",
    modern_equivalent:
      "A continuous regnal year count used to date Manikya coins and inscriptions (e.g. 'TE 1279' on a Vira Chandra Manikya gold mohur)",
    conversion_formula:
      "Not a hierarchical subdivision — a standalone era, distinct from the Saka era also used on the earliest Tripura coins",
    meaning:
      "The Manikya dynasty's own dating system, used on its coinage right up to the 20th century, alongside occasional use of the Saka era on earlier coins (Ratna Manikya's first issue was dated Saka 1386)",
    historical_period:
      "Manikya dynasty period (Ratna Manikya, 1464 CE, to Bir Bikram Kishore Manikya, until 1949 CE merger with India)",
    region_applicable: "Agartala and the Manikya royal court (plains Tripura)",
    states: ["Tripura"],
    used_in: [
      "The Manikya dynasty's own dating system, used on its coinage right up to the 20th century",
      "Currency & Money",
    ],
    references: [
      "https://www.mintageworld.com/blog/coinage-of-tripura-kingdom/",
      "https://thetipra.in/the-introduction-of-coinage-system-by-king-ratna-manikya-in-tripura/",
    ],
    tags: ["tripura", "traditional-units", "currency-money", "calendar", "era", "tripura-era", "manikya"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-currency-5",
    slug: "indian-rupee-currency-tripura",
    name_english: "Indian Rupee (post-1949)",
    name_sanskrit: "N/A",
    local_names: ["রুপি"],
    name_hindi: "रुपया",
    category: "currency",
    measurement_type: "Currency",
    sector: "currency-money",
    origin: "Tripura",
    modern_equivalent: "Standard Indian Rupee",
    conversion_formula: "Superseded the Manikya Tanka/Mohur system",
    meaning:
      "Became Tripura's standard currency following the princely state's 1949 merger with the Indian Union",
    historical_period:
      "British colonial/princely-state period (Tripura remained a semi-independent princely state under British paramountcy, 19th–20th century CE) and post-1949 Indian administration",
    region_applicable: "Pan-Tripura generally",
    states: ["Tripura"],
    used_in: [
      "Became Tripura's standard currency following the princely state's 1949 merger with the Indian Union",
      "Currency & Money",
    ],
    references: ["https://en.wikipedia.org/wiki/Tripura"],
    tags: ["tripura", "traditional-units", "currency-money", "currency", "rupee", "post-1949"],
    created_at: "2024-01-01",
  },

  // ─── 12. Storage & Transportation (4 units) ─────────────────────────────────
  {
    id: "tripura-storage-1",
    slug: "ser-seer-storage-tripura",
    name_english: "Ser (Seer)",
    name_sanskrit: "सेरी (Serā)",
    local_names: ["সের"],
    name_hindi: "सेर",
    category: "weight",
    measurement_type: "Weight",
    sector: "storage-transport",
    origin: "Tripura",
    modern_equivalent: "~0.93 kg",
    conversion_formula: "16 Chittak = 1 Ser",
    meaning: "Household and shop-level grain storage measurement in plains Tripura",
    historical_period:
      "British colonial/princely-state period (Tripura remained a semi-independent princely state under British paramountcy, 19th–20th century CE) and post-1949 Indian administration",
    region_applicable: "Agartala and the Manikya royal court (plains Tripura)",
    states: ["Tripura"],
    used_in: [
      "Household and shop-level grain storage measurement in plains Tripura",
      "Storage & Transportation",
    ],
    references: [
      "https://grokipedia.com/page/Seer_(unit)",
      "https://en.wikipedia.org/wiki/Maund",
    ],
    tags: ["tripura", "traditional-units", "storage-transport", "storage", "seer", "grain"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-storage-2",
    slug: "mon-maund-storage-tripura",
    name_english: "Mon (Maund)",
    name_sanskrit: "मान (Māna)",
    local_names: ["মণ"],
    name_hindi: "मन",
    category: "weight",
    measurement_type: "Weight",
    sector: "storage-transport",
    origin: "Tripura",
    modern_equivalent: "~37.3 kg",
    conversion_formula: "40 Ser = 1 Mon",
    meaning: "Standard granary and warehouse storage unit for paddy",
    historical_period:
      "British colonial/princely-state period (Tripura remained a semi-independent princely state under British paramountcy, 19th–20th century CE) and post-1949 Indian administration",
    region_applicable: "Agartala and the Manikya royal court (plains Tripura)",
    states: ["Tripura"],
    used_in: [
      "Standard granary and warehouse storage unit for paddy",
      "Storage & Transportation",
    ],
    references: [
      "https://grokipedia.com/page/Seer_(unit)",
      "https://en.wikipedia.org/wiki/Maund",
    ],
    tags: ["tripura", "traditional-units", "storage-transport", "storage", "maund", "granary"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-storage-3",
    slug: "bamboo-granary-storage-tripura",
    name_english: "(Bamboo granary — informal capacity)",
    name_sanskrit: "N/A — structure-based, no fixed named unit documented",
    local_names: ["—"],
    name_hindi: "बाँस का गोला (अनौपचारिक)",
    category: "volume",
    measurement_type: "Volume (utility, informal)",
    sector: "storage-transport",
    origin: "Hill Tripura",
    modern_equivalent:
      "Capacity set by the size of the individual household granary structure",
    conversion_formula: "No standardised hierarchy",
    meaning:
      "Raised bamboo-and-thatch granaries store Jhum harvests across hill Tripura tribal villages, with capacity reckoned informally rather than by a fixed named unit",
    historical_period:
      "Customary/traditional practice of Tripura's 19 indigenous communities, predating and continuing alongside Manikya and Indian administration",
    region_applicable:
      "Hill Tripura — Jhum-cultivating tribal areas under TTAADC (Tripura Tribal Areas Autonomous District Council)",
    states: ["Tripura"],
    used_in: [
      "Raised bamboo-and-thatch granaries store Jhum harvests across hill Tripura tribal villages, with capacity reckoned informally rather than by a fixed named unit",
      "Storage & Transportation",
    ],
    references: [
      "No standardised metrological reference documented for this practice",
    ],
    tags: ["tripura", "traditional-units", "storage-transport", "storage", "bamboo", "granary", "tribal"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-storage-4",
    slug: "porter-headload-storage-tripura",
    name_english: "(Porter/headload reckoning)",
    name_sanskrit: "N/A — body-based, no fixed named unit documented",
    local_names: ["—"],
    name_hindi: "माथा का बोझ (अनौपचारिक)",
    category: "weight",
    measurement_type: "Weight (informal, load-based)",
    sector: "storage-transport",
    origin: "Hill Tripura",
    modern_equivalent:
      "One person's comfortable carrying load over hill-trail terrain",
    conversion_formula: "No standardised hierarchy",
    meaning:
      "Given Tripura's hilly, forested interior, goods moved between Jhum villages and plains markets were traditionally carried by human porterage as much as by cart, with loads reckoned informally",
    historical_period:
      "Customary/traditional practice of Tripura's 19 indigenous communities, predating and continuing alongside Manikya and Indian administration",
    region_applicable:
      "Hill Tripura — Jhum-cultivating tribal areas under TTAADC (Tripura Tribal Areas Autonomous District Council)",
    states: ["Tripura"],
    used_in: [
      "Given Tripura's hilly, forested interior, goods moved between Jhum villages and plains markets were traditionally carried by human porterage as much as by cart, with loads reckoned informally",
      "Storage & Transportation",
    ],
    references: [
      "No standardised metrological reference documented for this practice",
    ],
    tags: ["tripura", "traditional-units", "storage-transport", "transport", "porter", "headload", "tribal"],
    created_at: "2024-01-01",
  },

  // ─── 13. Religious & Cultural Sectors (6 units) ──────────────────────────────
  {
    id: "tripura-relig-1",
    slug: "nadika-ghatika-religious-tripura",
    name_english: "Nadika (Ghatika)",
    name_sanskrit: "नाडिका / घटिका (Nāḍikā / Ghaṭikā)",
    local_names: ["নাড়িকা"],
    name_hindi: "नाड़ी / घड़ी",
    category: "time",
    measurement_type: "Time",
    sector: "religious-cultural",
    origin: "Tripura",
    modern_equivalent: "~24 minutes",
    conversion_formula: "15 Laghu = 1 Nadika",
    meaning:
      "Water-clock time unit used to fix auspicious ritual timings at the Manikya court and at the Tripura Sundari Temple (Matabari)",
    historical_period:
      "Ancient-Puranic/syncratic Hindu-tribal period; still ritually observed today",
    region_applicable: "Agartala and the Manikya royal court (plains Tripura)",
    states: ["Tripura"],
    used_in: [
      "Water-clock time unit used to fix auspicious ritual timings at the Manikya court and at the Tripura Sundari Temple (Matabari)",
      "Religious & Cultural",
    ],
    references: ["https://en.wikipedia.org/wiki/Muhurta"],
    tags: ["tripura", "traditional-units", "religious-cultural", "time", "nadika", "ghatika", "temple"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-relig-2",
    slug: "muhurta-religious-tripura",
    name_english: "Muhurta",
    name_sanskrit: "मुहूर्त (Muhūrta)",
    local_names: ["মুহূর্ত"],
    name_hindi: "मुहूर्त",
    category: "time",
    measurement_type: "Time",
    sector: "religious-cultural",
    origin: "Tripura",
    modern_equivalent: "~48 minutes",
    conversion_formula: "2 Nadika = 1 Muhurta; 30 Muhurta = 1 day-night",
    meaning:
      "Auspicious-timing unit for weddings and Griha Pravesh, and for major temple rituals",
    historical_period:
      "Ancient-Puranic/syncratic Hindu-tribal period; still ritually observed today",
    region_applicable: "Agartala and the Manikya royal court (plains Tripura)",
    states: ["Tripura"],
    used_in: [
      "Auspicious-timing unit for weddings and Griha Pravesh, and for major temple rituals",
      "Religious & Cultural",
    ],
    references: ["https://en.wikipedia.org/wiki/Muhurta"],
    tags: ["tripura", "traditional-units", "religious-cultural", "time", "muhurta", "ritual"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-relig-3",
    slug: "garia-puja-timing-religious-tripura",
    name_english: "Garia Puja timing (seventh day of Baisakh)",
    name_sanskrit: "N/A — a fixed festival date, not a subdivided numeric time unit",
    local_names: ["গরিয়া পূজা"],
    name_hindi: "गरिया पूजा",
    category: "time",
    measurement_type: "Calendar (festival marker)",
    sector: "religious-cultural",
    origin: "Hill Tripura",
    modern_equivalent:
      "Observed on the seventh day of the Bengali/Hindu month of Baisakh (April), following about a week of associated rites beginning near the end of Chaitra",
    conversion_formula:
      "Fixed annual date within the lunar-solar calendar shared with Bengal",
    meaning:
      "Tripura's major indigenous agricultural festival, dedicated to Lord Garia — the deity of livestock, wealth and prosperity — worshipped in the form of a bamboo pole, with the Garia dance as its centerpiece; reflects the deep tie between tribal ritual, agriculture and the Baisakh new farming year marker also seen (differently timed) in Assam's Bihu",
    historical_period:
      "Customary/traditional practice of Tripura's 19 indigenous communities, predating and continuing alongside Manikya and Indian administration",
    region_applicable:
      "Hill Tripura — Jhum-cultivating tribal areas under TTAADC (Tripura Tribal Areas Autonomous District Council)",
    states: ["Tripura"],
    used_in: [
      "Tripura's major indigenous agricultural festival, dedicated to Lord Garia — the deity of livestock, wealth and prosperity — worshipped in the form of a bamboo pole, with the Garia dance as its centerpiece; reflects the deep tie between tribal ritual, agriculture and the Baisakh new farming year marker also seen (differently timed) in Assam's Bihu",
      "Religious & Cultural",
    ],
    references: ["https://discoveryofbharat.com/festivals-of-tripura-11202315/"],
    tags: ["tripura", "traditional-units", "religious-cultural", "festival", "garia-puja", "tribal"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-relig-4",
    slug: "kharchi-puja-timing-religious-tripura",
    name_english: "Kharchi Puja timing (eighth day of Ashar's bright fortnight)",
    name_sanskrit: "N/A — a fixed lunar-fortnight festival date, not a subdivided numeric time unit",
    local_names: ["খার্চি পূজা"],
    name_hindi: "खर्ची पूजा",
    category: "time",
    measurement_type: "Calendar (festival marker)",
    sector: "religious-cultural",
    origin: "Tripura (Manikya Dynasty)",
    modern_equivalent:
      "Falls on the eighth day (Ashtami) of the Shukla Paksha (bright fortnight) of the Hindu month of Ashar (June/July), 15 days after Ambubachi",
    conversion_formula: "Fixed annual lunar-fortnight date",
    meaning:
      "The week long 'Festival of 14 Gods', worshipping the Chaturdasha Devata — the same fourteen ancestral deities whose stylised depiction (fourteen vertical lines within a garland) appears on Ratna Manikya's own coinage — at the Chaturdasha Devata Temple built by King Krishna Manikya in 1761 in Old Agartala; it blends indigenous earth-worship with Brahmanical Hindu ritual",
    historical_period:
      "Manikya dynasty period (Ratna Manikya, 1461 CE, to Bir Bikram Kishore Manikya, until 1949 CE merger with India)",
    region_applicable: "Agartala and the Manikya royal court (plains Tripura)",
    states: ["Tripura"],
    used_in: [
      "The week long 'Festival of 14 Gods', worshipping the Chaturdasha Devata — the same fourteen ancestral deities whose stylised depiction (fourteen vertical lines within a garland) appears on Ratna Manikya's own coinage — at the Chaturdasha Devata Temple built by King Krishna Manikya in 1761 in Old Agartala; it blends indigenous earth-worship with Brahmanical Hindu ritual",
      "Religious & Cultural",
    ],
    references: [
      "https://en.wikipedia.org/wiki/Kharchi_puja",
      "https://www.vskassam.org/festival-of-14-gods-seven-day-kharchi-puja-commences-in-tripura/",
    ],
    tags: ["tripura", "traditional-units", "religious-cultural", "festival", "kharchi-puja", "manikya"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-relig-5",
    slug: "yojana-religious-tripura",
    name_english: "Yojana",
    name_sanskrit: "योजन (Yojana)",
    local_names: ["যোজন"],
    name_hindi: "योजन",
    category: "length",
    measurement_type: "Distance",
    sector: "religious-cultural",
    origin: "Tripura",
    modern_equivalent: "~11–14.5 km",
    conversion_formula: "4 Krosha = 1 Yojana",
    meaning:
      "Puranic-scale distance unit describing the sacred geography around the Tripura Sundari Shakti Peeth at Udaipur",
    historical_period:
      "Ancient-Puranic/syncratic Hindu-tribal period; still ritually observed today",
    region_applicable: "Pan-Tripura generally",
    states: ["Tripura"],
    used_in: [
      "Puranic-scale distance unit describing the sacred geography around the Tripura Sundari Shakti Peeth at Udaipur",
      "Religious & Cultural",
    ],
    references: ["https://en.wikipedia.org/wiki/Tripura_Sundari_Temple"],
    tags: ["tripura", "traditional-units", "religious-cultural", "distance", "sacred-geography", "yojana"],
    created_at: "2024-01-01",
  },
  {
    id: "tripura-relig-6",
    slug: "kalasha-religious-tripura",
    name_english: "Kalasha (ritual vessel measure)",
    name_sanskrit: "कलश (Kalaśa)",
    local_names: ["কলস"],
    name_hindi: "कलश",
    category: "volume",
    measurement_type: "Volume (ritual utility)",
    sector: "religious-cultural",
    origin: "Tripura",
    modern_equivalent: "Vessel-based, informal (typically 1–5 L)",
    conversion_formula: "Informal ritual-vessel unit, no fixed metrological hierarchy",
    meaning:
      "Water vessel used in Kharchi Puja's ritual river-bathing of the fourteen deities, and in household puja generally",
    historical_period:
      "Ancient-Puranic/syncratic Hindu-tribal period; still ritually observed today",
    region_applicable: "Pan-Tripura generally",
    states: ["Tripura"],
    used_in: [
      "Water vessel used in Kharchi Puja's ritual river-bathing of the fourteen deities, and in household puja generally",
      "Religious & Cultural",
    ],
    references: [
      "Traditional ritual-utility unit — no standardised metrological reference available",
    ],
    tags: ["tripura", "traditional-units", "religious-cultural", "volume", "kalasha", "ritual"],
    created_at: "2024-01-01",
  },
];



